### ISSUE TITLE
Upgrade to 5.1.0.1 fails with KeyError: ('trans', 'change')

### ISSUE THREAD

**Issue by SkeLLLa** [WeblateOrg/weblate#10224]
### Describe the issue

U[grading weblate to version 5.1.0.1 failing with error:

```
Starting...
System check identified no issues (1 silenced).
Postgres 150004 is up
Starting database migration...
Operations to perform:
  Apply all migrations: accounts, admin, auth, authtoken, configuration, contenttypes, django_celery_beat, gitexport, glossary, sessions, social_django, trans, utils, vcs, weblate_auth
[2023-10-17 21:49:00,789: WARNING/98] Handled exception: KeyError: ('trans', 'change')
Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weblate/runner.py", line 19, in main
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 301, in handle
    pre_migrate_state = executor._create_project_state(with_applied_migrations=True)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 91, in _create_project_state
    migration.mutate_state(state, preserve=False)
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 91, in mutate_state
    operation.state_forwards(self.app_label, new_state)
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/fields.py", line 93, in state_forwards
    state.add_field(
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/state.py", line 248, in add_field
    self.models[model_key].fields[name] = field
    ~~~~~~~~~~~^^^^^^^^^^^
KeyError: ('trans', 'change')

```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Have weblate version `4.16.4-1` (maybe any other version affected as well), reproduces with clean DB. In my case it's installed from helm chart.
2. Upgrade weblate to ` 5.1.0.1` (helm chart 0.5.2)
3. See error when it tries to apply migrations.

Overriding image version in 0.5.2 chart to `5.0.2.2` fixes the issue, and error not reproduces.

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
Upgrade via 5.0.2 is required, see https://docs.weblate.org/en/latest/changes.html#weblate-5-1

**Comment by nijel** [comment]
But there is code which is supposed to handle this more user-friendly, what apparently doesn't work:

https://github.com/WeblateOrg/docker/blob/4f450e8b426a1ccd0ec819c8811095f5611e7fae/start#L193-L200
