### ISSUE TITLE
Upgrade from 5.0.1.1 to 5.1.0.1: KeyError: ('trans', 'change')

### ISSUE THREAD

**Issue by mosesdd** [WeblateOrg/weblate#10231]
### Describe the issue

```
Starting...
2023-10-18T14:19:15.451985074Z System check identified no issues (1 silenced).
Postgres 160000 is up
Starting database migration...
Operations to perform:
2023-10-18T14:19:32.384074604Z   Apply all migrations: accounts, addons, admin, auth, authtoken, checks, configuration, contenttypes, django_celery_beat, fonts, gitexport, glossary, lang, memory, screenshots, sessions, social_django, trans, utils, vcs, weblate_auth, wladmin
[2023-10-18 14:19:32,384: WARNING/99] Handled exception: KeyError: ('trans', 'change')
2023-10-18T14:19:32.385075282Z Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 8, in <module>
    sys.exit(main())
2023-10-18T14:19:32.385130337Z              ^^^^^^
2023-10-18T14:19:32.385163335Z   File "/usr/local/lib/python3.11/site-packages/weblate/runner.py", line 19, in main
    utility.execute()
2023-10-18T14:19:32.385228967Z   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
2023-10-18T14:19:32.385394897Z     self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
2023-10-18T14:19:32.385550292Z     self.execute(*args, **cmd_options)
2023-10-18T14:19:32.385619415Z   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
2023-10-18T14:19:32.385778529Z     output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-10-18T14:19:32.385830906Z   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
2023-10-18T14:19:32.385881071Z     res = handle_func(*args, **kwargs)
2023-10-18T14:19:32.385942555Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 301, in handle
2023-10-18T14:19:32.386092108Z     pre_migrate_state = executor._create_project_state(with_applied_migrations=True)
2023-10-18T14:19:32.386203666Z                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 91, in _create_project_state
2023-10-18T14:19:32.386320862Z     migration.mutate_state(state, preserve=False)
2023-10-18T14:19:32.386347570Z   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 91, in mutate_state
    operation.state_forwards(self.app_label, new_state)
2023-10-18T14:19:32.386456803Z   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/fields.py", line 93, in state_forwards
2023-10-18T14:19:32.386516518Z     state.add_field(
2023-10-18T14:19:32.386529710Z   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/state.py", line 248, in add_field
    self.models[model_key].fields[name] = field
2023-10-18T14:19:32.386690365Z     ~~~~~~~~~~~^^^^^^^^^^^
2023-10-18T14:19:32.386701886Z KeyError: ('trans', 'change')
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Upgrade from 5.0.1.1 to 5.1.0.1

### How do you run Weblate?

Docker container

**Comment by mosesdd** [comment]
https://docs.weblate.org/en/latest/changes.html#weblate-5-1

**Comment by nijel** [comment]
See also https://github.com/WeblateOrg/docker/issues/2024, 5.1.0.2 Docker image will fail with a reasonable error message.
