### ISSUE TITLE
"Database migration has failed" when upgrading from 5.0.1 to 5.1.1 with docker

### ISSUE THREAD

**Issue by marco-doerig** [WeblateOrg/weblate#10312]
### Describe the issue

The docker containers will not start after trying to upgrade from weblate 5.0.1 to 5.1.1 with docker on arm64.
The container is stuck in a boot loop while the migrations fail.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

docker compose pull
docker compose up -d

### Expected behavior

Smooth upgrade via docker pull since this is only a minor upgrade.

### Exception traceback

```pytb
weblate-weblate-1   | Starting...
weblate-weblate-1   | System check identified no issues (1 silenced).
weblate-weblate-1   | Postgres 140009 is up
weblate-weblate-1   | Starting database migration...
weblate-weblate-1   | Operations to perform:
weblate-weblate-1   |   Apply all migrations: accounts, addons, admin, auth, authtoken, checks, configuration, contenttypes, django_celery_beat, fonts, gitexport, glossary, lang, memory, screenshots, sessions, social_django, trans, utils, vcs, weblate_auth, wladmin
weblate-weblate-1   | [2023-10-31 21:36:05,495: WARNING/75] Handled exception: KeyError: ('trans', 'change')
weblate-weblate-1   | Traceback (most recent call last):
weblate-weblate-1   |   File "/usr/local/bin/weblate", line 8, in <module>
weblate-weblate-1   |     sys.exit(main())
weblate-weblate-1   |              ^^^^^^
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/weblate/runner.py", line 19, in main
weblate-weblate-1   |     utility.execute()
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
weblate-weblate-1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
weblate-weblate-1   |     self.execute(*args, **cmd_options)
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
weblate-weblate-1   |     output = self.handle(*args, **options)
weblate-weblate-1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
weblate-weblate-1   |     res = handle_func(*args, **kwargs)
weblate-weblate-1   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 301, in handle
weblate-weblate-1   |     pre_migrate_state = executor._create_project_state(with_applied_migrations=True)
weblate-weblate-1   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 91, in _create_project_state
weblate-weblate-1   |     migration.mutate_state(state, preserve=False)
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 91, in mutate_state
weblate-weblate-1   |     operation.state_forwards(self.app_label, new_state)
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/fields.py", line 93, in state_forwards
weblate-weblate-1   |     state.add_field(
weblate-weblate-1   |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/state.py", line 248, in add_field
weblate-weblate-1   |     self.models[model_key].fields[name] = field
weblate-weblate-1   |     ~~~~~~~~~~~^^^^^^^^^^^
weblate-weblate-1   | KeyError: ('trans', 'change')
weblate-weblate-1   |
weblate-weblate-1   |
weblate-weblate-1   | Database migration has failed. Please check the error message above.
weblate-weblate-1   | Note: Upgrading across major versions is not supported. In case you are upgrading
weblate-weblate-1   |       from an 4.x version, please upgrade to 5.0.2 first.
```

### How do you run Weblate?

Docker container

### Weblate versions

Fresh pulled repo to upgrade to (5.1.1):
`RepoDigests: weblate/weblate@sha256:9c5231556b09a75c365aab6a048e962eec1dc47459b52ef96ac510cc12357475`

**Comment by dxdx123** [comment]
![image](https://github.com/WeblateOrg/weblate/assets/14290268/4fe1eb0c-4c90-49f2-948a-69a45f4da4d7)

**Comment by marco-doerig** [comment]
I'm so sorry! Everything works fine following the release notes...
