### ISSUE TITLE
 weblate.auth.models.User.DoesNotExist: User matching query does not exist.

### ISSUE THREAD

**Issue by janisii** [WeblateOrg/weblate#10339]
### Describe the issue

Weblate was working fine until we got Internal Server Error with message: `"weblate.auth.models.User.DoesNotExist: User matching query does not exist."` and Kubernetes healthz checks started to fail which resulted in pod kill and when Kube cluster tried to start pod again, migrations failed - `Handled exception: IntegrityError: duplicate key value violates unique constraint "weblate_auth_user_email_aaabd769_uniq"` .

```
Starting... 
System check identified no issues (1 silenced). |
Postgres 140009 is up
Starting database migration... 
Operations to perform: 
Apply all migrations: accounts, addons, admin, auth, authtoken, checks, configuration, contenttypes, django_celery_beat, fonts, gitexport, glossary, lang, memory, metrics, screenshots, sessions, social_django, trans, utils, vcs, weblate_auth, wladmin 
Running migrations: 
No migrations to apply. 
[2023-11-02 18:39:37,165: WARNING/99] Handled exception: IntegrityError: duplicate key value violates unique constraint "weblate_auth_user_email_aaabd769_uniq" 
DETAIL:  Key (email)=(noreply@weblate.org) already exists. 
Traceback (most recent call last): 
File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 916, in get_or_create 
 return self.get(**kwargs), False 
 ^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
 raise self.model.DoesNotExist(
 weblate.auth.models.User.DoesNotExist: User matching query does not exist.
During handling of the above exception, another exception occurred:
Traceback (most recent call last): 
File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
return self.cursor.execute(sql, params) 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
 File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute 
raise ex.with_traceback(None) 
psycopg.errors.UniqueViolation: duplicate key value violates unique constraint "weblate_auth_user_email_aaabd769_uniq"    DETAIL:  Key (email)=(noreply@weblate.org) already exists.
```

Weblate is installed in Kube cluster 1.26.9 with HELM: https://artifacthub.io/packages/helm/weblate/weblate

Thanks!

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Cannot provide.

### Expected behavior

Not failing migrations.

### Exception traceback

```pytb
gunicorn stderr | [2023-11-02 11:00:32,321: ERROR/3066] Internal Server Error: /healthz/
gunicorn stderr | Traceback (most recent call last):
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
gunicorn stderr |     response = get_response(request)
gunicorn stderr |                ^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/accounts/middleware.py", line 45, in __call__
gunicorn stderr |     request.user = user = get_user(request)
gunicorn stderr |                           ^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/accounts/middleware.py", line 27, in get_user
gunicorn stderr |     user = get_anonymous()
gunicorn stderr |            ^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/auth/models.py", line 279, in get_anonymous
gunicorn stderr |     return User.objects.select_related("profile").get(
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
gunicorn stderr |     raise self.model.DoesNotExist(
gunicorn stderr | weblate.auth.models.User.DoesNotExist: User matching query does not exist.
```

### How do you run Weblate?

Docker container

### Weblate versions

```
weblate list_versions
 * Weblate: 5.1
 * Django: 4.2.6
 * siphashc: 2.3
 * translate-toolkit: 3.10.1
 * lxml: 4.9.3
 * Pillow: 10.1.0
 * nh3: 0.2.14
 * python-dateutil: 2.8.2
 * social-auth-core: 4.4.2
 * social-auth-app-django: 5.3.0
 * django-crispy-forms: 2.1
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.14.0
 * django-filter: 23.3
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.12.4
 * rapidfuzz: 3.4.0
 * openpyxl: 3.1.2
 * celery: 5.3.4
 * django-celery-beat: 2.5.0
 * kombu: 5.3.2
 * translation-finder: 2.15
 * weblate-language-data: 2023.5
 * html2text: 2020.1.16
 * pycairo: 1.25.0
 * PyGObject: 3.46.0
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.4.0
 * hiredis: 2.2.3
 * sentry-sdk: 1.31.0
 * Cython: 3.0.3
 * misaka: 2.1.1
 * GitPython: 3.1.37
 * borgbackup: 1.2.6
 * pyparsing: 3.1.1
 * ahocorasick_rs: 0.20.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.0
 * Python: 3.11.5
 * Git: 2.39.2
 * psycopg2: 2.9.9
 * phply: 1.2.6
 * ruamel.yaml: 0.17.35
 * tesserocr: 2.6.2
 * boto3: 1.28.63
 * zeep: 4.2.1
 * aeidon: 1.13
 * iniparse: 0.5
 * mysqlclient: 2.2.0
 * Mercurial: 6.5.2
 * git-svn: 2.39.2
 * git-review: 2.3.1
 * PostgreSQL server: 14.9
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.eu.mailgun.org
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://:xxx@redis-master.redis:6379/5, redis://:xxxx@redis-master.redis:6379/5, regular
 * Platform: Linux 5.4.0-148-generic (x86_64)
```

### Weblate deploy checks

```shell
weblate check --deploy
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.1/admin/backup.html
?: (weblate.I031) New Weblate version is available, please upgrade to 5.1.1.
        HINT: https://docs.weblate.org/en/weblate-5.1/admin/upgrade.html

System check identified 6 issues (1 silenced).
```

**Comment by nijel** [comment]
Maybe somebody renamed the `anonymous` user and didn't change the `ANONYMOUS_USER_NAME` setting?

**Comment by janisii** [comment]
> Maybe somebody renamed the `anonymous` user and didn't change the `ANONYMOUS_USER_NAME` setting?

Yes, `anonymous` user was renamed. Ty for solving the issue!
