### ISSUE TITLE
Demo Import fails with RecursionError since Weblate 5.1

### ISSUE THREAD

**Issue by michael-smt** [WeblateOrg/weblate#10443]
### Describe the issue

The [demo import](https://docs.weblate.org/en/latest/admin/management.html#weblate-admin-import_demo) no longer works locally since tag `weblate-5.1`. It crashes with a `RecursionError: maximum recursion depth exceeded in comparison`.

It works when checking out tag `weblate-5.0.2`. Newer `weblate-` tags and `main` does not work.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Setup according to [Running Weblate locally](https://docs.weblate.org/en/latest/contributing/start.html#running-weblate-locally) up to and including step 3
2. Run `dropdb weblate`
3. Run `createdb weblate`
4. Run `weblate migrate`
5. Run `weblate import_demo`

### Expected behavior

Import completes successfully.

### Exception traceback

```pytb
[2023-11-20 16:54:58,846: DEBUG/25491] demo/gettext/cs: updating stats for Czech
[2023-11-20 16:54:58,861: DEBUG/25491] demo/gettext/cs: updating stats for Czech
[2023-11-20 16:54:58,861: DEBUG/25491] demo/gettext/cs: updating stats for None
[2023-11-20 16:54:58,866: WARNING/25491] Handled exception: RecursionError: maximum recursion depth exceeded in comparison
Traceback (most recent call last):
  File "/weblate/.venv/bin/weblate", line 8, in <module>
    sys.exit(main())
  File "/weblate/weblate/runner.py", line 19, in main
    utility.execute()
  File "/weblate/.venv/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/weblate/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/weblate/weblate/utils/management/base.py", line 27, in execute
    return super().execute(*args, **options)
  File "/weblate/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/weblate/weblate/trans/management/commands/import_demo.py", line 30, in handle
    component = Component.objects.create(
  File "/weblate/.venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/weblate/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/weblate/weblate/trans/models/component.py", line 872, in save
    self.after_save(**args)
  File "/weblate/weblate/trans/models/component.py", line 3038, in after_save
    was_change = self.create_translations()
  File "/weblate/weblate/trans/models/component.py", line 2301, in create_translations
    return self._create_translations(
  File "/weblate/weblate/trans/models/component.py", line 2489, in _create_translations
    self.invalidate_cache()
  File "/weblate/weblate/trans/models/component.py", line 2536, in invalidate_cache
    transaction.on_commit(self._invalidate_triger)
  File "/weblate/.venv/lib/python3.10/site-packages/django/db/transaction.py", line 134, in on_commit
    get_connection(using).on_commit(func, robust)
  File "/weblate/.venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 760, in on_commit
    func()
  File "/weblate/weblate/trans/models/component.py", line 2528, in _invalidate_triger
    self.stats.update_language_stats()
  File "/weblate/weblate/utils/stats.py", line 885, in update_language_stats
    self.update_parents(extras)
  File "/weblate/weblate/utils/stats.py", line 286, in update_parents
    stat.update_stats()
  File "/weblate/weblate/utils/stats.py", line 303, in update_stats
    self.calculate_basic()
  File "/weblate/weblate/utils/stats.py", line 311, in calculate_basic
    self._calculate_basic()
  File "/weblate/weblate/utils/stats.py", line 1197, in _calculate_basic
    super()._calculate_basic()
  File "/weblate/weblate/utils/stats.py", line 779, in _calculate_basic
    stats_obj.calculate_basic()
  File "/weblate/weblate/utils/stats.py", line 311, in calculate_basic
    self._calculate_basic()
  File "/weblate/weblate/utils/stats.py", line 780, in _calculate_basic
    stats_obj.save()
  File "/weblate/weblate/utils/stats.py", line 409, in save
    transaction.on_commit(self.update_parents)
  File "/weblate/.venv/lib/python3.10/site-packages/django/db/transaction.py", line 134, in on_commit
    get_connection(using).on_commit(func, robust)
  File "/weblate/.venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 760, in on_commit
    func()
  File "/weblate/weblate/utils/stats.py", line 286, in update_parents
    stat.update_stats()
  File "/weblate/weblate/utils/stats.py", line 303, in update_stats
    self.calculate_basic()
  File "/weblate/weblate/utils/stats.py", line 311, in calculate_basic
    self._calculate_basic()
  File "/weblate/weblate/utils/stats.py", line 780, in _calculate_basic
    stats_obj.save()
  File "/weblate/weblate/utils/stats.py", line 409, in save
    transaction.on_commit(self.update_parents)
  File "/weblate/.venv/lib/python3.10/site-packages/django/db/transaction.py", line 134, in on_commit
    get_connection(using).on_commit(func, robust)
  File "/weblate/.venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 760, in on_commit
    func()
  File "/weblate/weblate/utils/stats.py", line 286, in update_parents
    stat.update_stats()
  File "/weblate/weblate/utils/stats.py", line 303, in update_stats
    self.calculate_basic()
  File "/weblate/weblate/utils/stats.py", line 311, in calculate_basic
    self._calculate_basic()
  File "/weblate/weblate/utils/stats.py", line 1220, in _calculate_basic
    super()._calculate_basic()
  File "/weblate/weblate/utils/stats.py", line 779, in _calculate_basic
    stats_obj.calculate_basic()
  File "/weblate/weblate/utils/stats.py", line 311, in calculate_basic
    self._calculate_basic()
  File "/weblate/weblate/utils/stats.py", line 1197, in _calculate_basic
    super()._calculate_basic()
  File "/weblate/weblate/utils/stats.py", line 779, in _calculate_basic
    stats_obj.calculate_basic()
  File "/weblate/weblate/utils/stats.py", line 311, in calculate_basic
    self._calculate_basic()
  File "/weblate/weblate/utils/stats.py", line 780, in _calculate_basic
    stats_obj.save()
  File "/weblate/weblate/utils/stats.py", line 409, in save
    transaction.on_commit(self.update_parents)
  File "/weblate/.venv/lib/python3.10/site-packages/django/db/transaction.py", line 134, in on_commit
    get_connection(using).on_commit(func, robust)
  File "/weblate/.venv/lib/python3.10/site-packages/django/db/backends/base/base.py", line 760, in on_commit
    func()
[...and so on...]
```

### How do you run Weblate?

Git checkout

### Additional context

`diff -u weblate/settings_example.py weblate/settings.py`
```diff
--- weblate/settings_example.py	2023-11-20 17:14:58.104949968 +0100
+++ weblate/settings.py	2023-11-20 17:45:27.521171052 +0100
@@ -10,7 +10,7 @@
 SITE_TITLE = "Weblate"

 # Site domain
-SITE_DOMAIN = ""
+SITE_DOMAIN = "localhost"

 # Whether site uses https
 ENABLE_HTTPS = False
@@ -34,7 +34,7 @@
         # Database name.
         "NAME": "weblate",
         # Database user.
-        "USER": "weblate",
+        "USER": os.getenv("USER"),
         # Name of role to alter to set parameters in PostgreSQL,
         # use in case role name is different than user used for authentication.
         # "ALTER_ROLE": "weblate",
@@ -65,8 +65,7 @@
 }

 # Data directory, you can use following for the development purposes:
-# os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
-DATA_DIR = "/home/weblate/data"
+DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")
 CACHE_DIR = f"{DATA_DIR}/cache"

 # Local time zone for this installation. Choices can be found here:
@@ -175,7 +174,7 @@

 # Make this unique, and don't share it with anybody.
 # You can generate it using weblate-generate-secret-key
-SECRET_KEY = ""
+SECRET_KEY = "some-random-value"

 TEMPLATES = [
     {
@@ -539,6 +534,9 @@
 CSRF_USE_SESSIONS = True
 # Customize CSRF failure view
 CSRF_FAILURE_VIEW = "weblate.trans.views.error.csrf_failure"
+CSRF_TRUSTED_ORIGINS = [
+    'http://localhost:8000',
+]
 SESSION_COOKIE_SECURE = ENABLE_HTTPS
 SESSION_COOKIE_HTTPONLY = True
 # SSL redirect
@@ -742,19 +740,7 @@
 # Configuration for caching
 CACHES = {
     "default": {
-        "BACKEND": "redis_lock.django_cache.RedisCache",
-        "LOCATION": "redis://127.0.0.1:6379/1",
-        # If redis is running on same host as Weblate, you might
-        # want to use unix sockets instead:
-        # "LOCATION": "unix:///var/run/redis/redis.sock?db=1",
-        "OPTIONS": {
-            "CLIENT_CLASS": "django_redis.client.DefaultClient",
-            # If you set password here, adjust CELERY_BROKER_URL as well
-            "PASSWORD": None,
-            "CONNECTION_POOL_KWARGS": {},
-        },
-        "KEY_PREFIX": "weblate",
-        "TIMEOUT": 3600,
+        "BACKEND": "django.core.cache.backends.dummy.DummyCache",
     },
     "avatar": {
         "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
@@ -765,7 +751,9 @@
 }

 # Store sessions in cache
-SESSION_ENGINE = "django.contrib.sessions.backends.cache"
+# SESSION_ENGINE = "django.contrib.sessions.backends.cache"
+# https://stackoverflow.com/a/54687159
+SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"
 # Store messages in session
 MESSAGE_STORAGE = "django.contrib.messages.storage.session.SessionStorage"

@@ -831,13 +819,13 @@
 ]

 # Celery worker configuration for testing
-# CELERY_TASK_ALWAYS_EAGER = True
-# CELERY_BROKER_URL = "memory://"
-# CELERY_TASK_EAGER_PROPAGATES = True
+CELERY_TASK_ALWAYS_EAGER = True
+CELERY_BROKER_URL = "memory://"
+CELERY_TASK_EAGER_PROPAGATES = True
 # Celery worker configuration for production
-CELERY_TASK_ALWAYS_EAGER = False
-CELERY_BROKER_URL = "redis://localhost:6379"
-CELERY_RESULT_BACKEND = CELERY_BROKER_URL
+#CELERY_TASK_ALWAYS_EAGER = False
+#CELERY_BROKER_URL = "redis://localhost:6379"
+#CELERY_RESULT_BACKEND = CELERY_BROKER_URL

 # Celery settings, it is not recommended to change these
 CELERY_WORKER_MAX_MEMORY_PER_CHILD = 200000
```

**Comment by nijel** [comment]
I've tested it locally, and it works just fine. Adding it to CI pipeline seems to work well also (https://github.com/WeblateOrg/weblate/pull/10465 adds it, most jobs are already past this step now).

Now reading your initial post again:

> "BACKEND": "django.core.cache.backends.dummy.DummyCache"

This won't work, Weblate needs a cache that persists data.
