### ISSUE TITLE
Component discovery addon fails to create a component inside a category

### ISSUE THREAD

**Issue by pleunv** [WeblateOrg/weblate#10458]
### Describe the issue

When attempting to setup the component discovery plugin on a component housed inside a category and pressing "Save" to confirm creation of the discovered components, nothing happens. Upon checking the log I see an `EncodeError: Object of type Category is not JSON serializable` being thrown so I suspect this might be interrupting the normal workflow.

I'm currently on 5.1.1 and unable to update to 5.2 until 5.2.1 lands, but I suspect that 5.2 wouldn't solve the issue. The only relevant fix I can see is https://github.com/WeblateOrg/weblate/issues/10295, which does not seem to change anything to the serialization.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

- Create a VCS component inside a category
- Configure a "Component discovery" addon on aforementioned component
  - Both "Clone" and "Remove inexistent" flags are enabled but I don't think this is relevant
- Press "Save" and confirm the matched components

### Expected behavior

The matched components should be created, but are not.

### Exception traceback

```pytb
[2023-11-22 09:50:26,828: INFO/404] myproject/next/emails: Creating component web
[2023-11-22 09:50:26,828: INFO/ForkPoolWorker-1] myproject/next/emails: Creating component web
[2023-11-22 09:50:26,835: ERROR/404] Failure while executing task: EncodeError: Object of type Category is not JSON serializable
[2023-11-22 09:50:26,835: ERROR/ForkPoolWorker-1] Failure while executing task: EncodeError: Object of type Category is not JSON serializable
[2023-11-22 09:50:26,835: ERROR/404] Failure while executing task: EncodeError: {'signal': <Signal: task_failure providing_args={'traceback', 'args', 'exception', 'einfo', 'kwargs', 'task_id'}>, 'sender': <@task: weblate.addons.tasks.postconfigure_addon of weblate at 0x7f085f590b10>, 'task_id': '9375834b-e615-4dff-9081-4272c1b6b474', 'args': [97], 'kwargs': {}, 'traceback': <traceback object at 0x7f084b43ac40>, 'einfo': <ExceptionInfo: ExceptionWithTraceback()>}
[2023-11-22 09:50:26,835: ERROR/ForkPoolWorker-1] Failure while executing task: EncodeError: {'signal': <Signal: task_failure providing_args={'traceback', 'args', 'exception', 'einfo', 'kwargs', 'task_id'}>, 'sender': <@task: weblate.addons.tasks.postconfigure_addon of weblate at 0x7f085f590b10>, 'task_id': '9375834b-e615-4dff-9081-4272c1b6b474', 'args': [97], 'kwargs': {}, 'traceback': <traceback object at 0x7f084b43ac40>, 'einfo': <ExceptionInfo: ExceptionWithTraceback()>}
[2023-11-22 09:50:26,835: ERROR/404] Failure while executing task
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/weblate/trans/discovery.py", line 306, in perform
    found = main.linked_childs.filter(filemask=match["mask"])[0]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 450, in __getitem__
    return qs._result_cache[0]
           ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/kombu/serialization.py", line 41, in _reraise_errors
    yield
  File "/usr/local/lib/python3.11/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
              ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/utils/json.py", line 57, in dumps
    return _dumps(s, cls=cls, **dict(default_kwargs, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/utils/json.py", line 45, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Category is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weblate/addons/tasks.py", line 126, in postconfigure_addon
    addon.addon.post_configure_run()
  File "/usr/local/lib/python3.11/site-packages/weblate/addons/base.py", line 145, in post_configure_run
    self.post_update(component, "", False)
  File "/usr/local/lib/python3.11/site-packages/weblate/addons/discovery.py", line 29, in post_update
    self.discovery.perform(
  File "/usr/local/lib/python3.11/site-packages/weblate/trans/discovery.py", line 314, in perform
    component = self.create_component(main, match, background)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weblate/trans/discovery.py", line 245, in create_component
    create_component.delay(**kwargs, in_task=True)
  File "/usr/local/lib/python3.11/site-packages/celery/app/task.py", line 444, in delay
    return self.apply_async(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/task.py", line 594, in apply_async
    return app.send_task(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 798, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/usr/local/lib/python3.11/site-packages/celery/app/amqp.py", line 517, in send_task_message
    ret = producer.publish(
          ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/messaging.py", line 175, in publish
    body, content_type, content_encoding = self._prepare(
                                           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/messaging.py", line 268, in _prepare
    body) = dumps(body, serializer=serializer)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/serialization.py", line 219, in dumps
    with _reraise_errors(EncodeError):
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/kombu/serialization.py", line 45, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/lib/python3.11/site-packages/kombu/exceptions.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.11/site-packages/kombu/serialization.py", line 41, in _reraise_errors
    yield
  File "/usr/local/lib/python3.11/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
              ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/utils/json.py", line 57, in dumps
    return _dumps(s, cls=cls, **dict(default_kwargs, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/utils/json.py", line 45, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
kombu.exceptions.EncodeError: Object of type Category is not JSON serializable
[2023-11-22 09:50:26,835: ERROR/ForkPoolWorker-1] Failure while executing task
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/weblate/trans/discovery.py", line 306, in perform
    found = main.linked_childs.filter(filemask=match["mask"])[0]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 450, in __getitem__
    return qs._result_cache[0]
           ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/kombu/serialization.py", line 41, in _reraise_errors
    yield
  File "/usr/local/lib/python3.11/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
              ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/utils/json.py", line 57, in dumps
    return _dumps(s, cls=cls, **dict(default_kwargs, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/utils/json.py", line 45, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Category is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weblate/addons/tasks.py", line 126, in postconfigure_addon
    addon.addon.post_configure_run()
  File "/usr/local/lib/python3.11/site-packages/weblate/addons/base.py", line 145, in post_configure_run
    self.post_update(component, "", False)
  File "/usr/local/lib/python3.11/site-packages/weblate/addons/discovery.py", line 29, in post_update
    self.discovery.perform(
  File "/usr/local/lib/python3.11/site-packages/weblate/trans/discovery.py", line 314, in perform
    component = self.create_component(main, match, background)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weblate/trans/discovery.py", line 245, in create_component
    create_component.delay(**kwargs, in_task=True)
  File "/usr/local/lib/python3.11/site-packages/celery/app/task.py", line 444, in delay
    return self.apply_async(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/task.py", line 594, in apply_async
    return app.send_task(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 798, in send_task
    amqp.send_task_message(P, name, message, **options)
  File "/usr/local/lib/python3.11/site-packages/celery/app/amqp.py", line 517, in send_task_message
    ret = producer.publish(
          ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/messaging.py", line 175, in publish
    body, content_type, content_encoding = self._prepare(
                                           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/messaging.py", line 268, in _prepare
    body) = dumps(body, serializer=serializer)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/serialization.py", line 219, in dumps
    with _reraise_errors(EncodeError):
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/kombu/serialization.py", line 45, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/lib/python3.11/site-packages/kombu/exceptions.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.11/site-packages/kombu/serialization.py", line 41, in _reraise_errors
    yield
  File "/usr/local/lib/python3.11/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
              ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/utils/json.py", line 57, in dumps
    return _dumps(s, cls=cls, **dict(default_kwargs, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/utils/json.py", line 45, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
kombu.exceptions.EncodeError: Object of type Category is not JSON serializable
```

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 5.1.1
 * Django: 4.2.7
 * siphashc: 2.3
 * translate-toolkit: 3.10.1
 * lxml: 4.9.3
 * Pillow: 10.1.0
 * nh3: 0.2.14
 * python-dateutil: 2.8.2
 * social-auth-core: 4.5.0
 * social-auth-app-django: 5.4.0
 * django-crispy-forms: 2.1
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.14.0
 * django-filter: 23.3
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.13.1
 * rapidfuzz: 3.4.0
 * openpyxl: 3.1.2
 * celery: 5.3.4
 * django-celery-beat: 2.5.0
 * kombu: 5.3.2
 * translation-finder: 2.15
 * weblate-language-data: 2023.5
 * html2text: 2020.1.16
 * pycairo: 1.25.1
 * PyGObject: 3.46.0
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.4.0
 * hiredis: 2.2.3
 * sentry-sdk: 1.34.0
 * Cython: 3.0.5
 * misaka: 2.1.1
 * GitPython: 3.1.40
 * borgbackup: 1.2.6
 * pyparsing: 3.1.1
 * ahocorasick_rs: 0.20.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * Python: 3.11.5
 * Git: 2.39.2
 * psycopg2: 2.9.9
 * phply: 1.2.6
 * ruamel.yaml: 0.18.5
 * tesserocr: 2.6.2
 * boto3: 1.28.77
 * zeep: 4.2.1
 * aeidon: 1.13
 * iniparse: 0.5
 * mysqlclient: 2.2.0
 * Mercurial: 6.5.2
 * git-svn: 2.39.2
 * git-review: 2.3.1
 * PostgreSQL server: 15.5
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.mandrillapp.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.15.0-1034-azure (x86_64)

**Comment by nijel** [comment]
This was already fixed for 5.2 by 643650d875072b119ebecc41960506a152e35082.
