### ISSUE TITLE
Machinetranslation WeblateSimilarTranslation and WeblateTranslation time out

### ISSUE THREAD

**Issue by pc-jedi** [WeblateOrg/weblate#1056]
### Steps to reproduce
1. Open Tab "Machine Translation" while 'weblate.trans.machine.weblatetm.WeblateSimilarTranslation' and 'weblate.trans.machine.weblatetm.WeblateTranslation' are activated.
### Expected behaviour

See similar translations.
### Actual behaviour

```
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/site-packages/weblate/trans/models/unit.py", line 68, in more_like_queue
    result = more_like(pk, source, top)
  File "/usr/local/lib/python3.5/site-packages/weblate/trans/search.py", line 304, in more_like
    index = get_source_index()
  File "/usr/local/lib/python3.5/site-packages/weblate/trans/search.py", line 122, in get_source_index
    exists = STORAGE.index_exists('source')
  File "/usr/local/lib/python3.5/site-packages/whoosh/filedb/filestore.py", line 189, in index_exists
    ix = self.open_index(indexname)
  File "/usr/local/lib/python3.5/site-packages/whoosh/filedb/filestore.py", line 176, in open_index
    return indexclass(self, schema=schema, indexname=indexname)
  File "/usr/local/lib/python3.5/site-packages/whoosh/index.py", line 421, in __init__
    TOC.read(self.storage, self.indexname, schema=self._schema)
  File "/usr/local/lib/python3.5/site-packages/whoosh/index.py", line 664, in read
    segments = stream.read_pickle()
  File "/usr/local/lib/python3.5/site-packages/whoosh/filedb/structfile.py", line 245, in read_pickle
    return load_pickle(self.file)
AttributeError: Can't get attribute 'W3Segment' on <module 'whoosh.codec.whoosh3' from '/usr/local/lib/python3.5/site-packages/whoosh/codec/whoosh3.py'>
ERROR Handled exception Exception: b'Request timed out.'
ERROR Failed to fetch translations from Weblate similarity
ERROR Last fetched URL: None, params: None
```
### Server configuration

```
 * Weblate 2.6-dev
 * Python 3.5.1
 * Django 1.9.5
 * six 1.10.0
 * python-social-auth 0.2.14
 * Translate Toolkit 1.14.0-rc1
 * Whoosh 2.7.4
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.5.2
 * lxml 3.6.0
 * django-crispy-forms 1.6.0
 * compressor 1.6
 * djangorestframework 3.3.3
 * pyuca N/A
 * pyLibravatar N/A
 * Database backends: django.db.backends.mysql
```
##

**Comment by nijel** [comment]
This is known issue with current fulltext engine we're using, see #800. It happens just for some strings.

**Comment by nijel** [comment]
Maybe it's caused by this: https://bitbucket.org/mchaput/whoosh/issues/461/whoosh-goes-into-infinite-loop

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
