### ISSUE TITLE
ProgrammingError in Bulk Edit

### ISSUE THREAD

**Issue by vanlinh2204** [WeblateOrg/weblate#10620]
### Describe the issue

When testing the bulk edit feature in Weblate version 5.1 by navigating to "My Component" -> "Tool" -> "Bulk Edit" -> filling out the form -> and clicking "Apply," I encountered a UI message:

```
Server Error
The server had serious problems serving your request. You might want to contact server admins in case the error persists.
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Navigating to "My Component" -> "Tool" -> "Bulk Edit" -> filling out the form -> and clicking "Apply,"
![image](https://github.com/WeblateOrg/weblate/assets/133736755/e991374b-d0d5-4d36-a938-4a1558a233f7)

### Expected behavior

The expected behavior is that the bulk edit feature should run smoothly, and the target string should change its state to "needs editing."

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/133736755/dfd5a3ed-6cd4-4a3d-bdb5-641351557323)

### Exception traceback

```pytb
gunicorn stderr | [2023-12-14 07:25:42,161: ERROR/463] Internal Server Error: /bulk-edit/ipension-translation-de/ipension-events/
gunicorn stderr | Traceback (most recent call last):
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
gunicorn stderr |     return self.cursor.execute(sql, params)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
gunicorn stderr |     raise ex.with_traceback(None)
gunicorn stderr | psycopg.errors.UndefinedTable: invalid reference to FROM-clause entry for table "trans_unit"
gunicorn stderr | LINE 1: ..." = U1."id") WHERE (U1."component_id" IN (13) AND "trans_uni...
gunicorn stderr |                                                              ^
gunicorn stderr | HINT:  Perhaps you meant to reference the table alias "u0".
gunicorn stderr | 
gunicorn stderr | The above exception was the direct cause of the following exception:
gunicorn stderr | 
gunicorn stderr | Traceback (most recent call last):
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
gunicorn stderr |     response = get_response(request)
gunicorn stderr |                ^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
gunicorn stderr |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
gunicorn stderr |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
gunicorn stderr |     return view_func(request, *args, **kwargs)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/http.py", line 43, in inner
gunicorn stderr |     return func(request, *args, **kwargs)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
gunicorn stderr |     response = view_func(request, *args, **kwargs)
gunicorn stderr |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/trans/views/search.py", line 206, in bulk_edit
gunicorn stderr |     updated = bulk_perform(
gunicorn stderr |               ^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/trans/bulk.py", line 42, in bulk_perform
gunicorn stderr |     for component in components:
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
gunicorn stderr |     self._fetch_all()
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
gunicorn stderr |     self._result_cache = list(self._iterable_class(self))
gunicorn stderr |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
gunicorn stderr |     results = compiler.execute_sql(
gunicorn stderr |               ^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
gunicorn stderr |     cursor.execute(sql, params)
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
gunicorn stderr |     return self._execute_with_wrappers(
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
gunicorn stderr |     return executor(sql, params, many, context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
gunicorn stderr |     with self.db.wrap_database_errors:
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
gunicorn stderr |     raise dj_exc_value.with_traceback(traceback) from exc_value
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
gunicorn stderr |     return self.cursor.execute(sql, params)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
gunicorn stderr |     raise ex.with_traceback(None)
gunicorn stderr | django.db.utils.ProgrammingError: invalid reference to FROM-clause entry for table "trans_unit"
gunicorn stderr | LINE 1: ..." = U1."id") WHERE (U1."component_id" IN (13) AND "trans_uni...
gunicorn stderr |                                                              ^
gunicorn stderr | HINT:  Perhaps you meant to reference the table alias "u0".
```

### How do you run Weblate?

Docker container

### Weblate versions

5.1

**Comment by nijel** [comment]
This merely looks like a bug in Django. Can you try upgrading the container to get a newer Django version?
