### ISSUE TITLE
Unable to create a user through the Django admin panel

### ISSUE THREAD

**Issue by nkrapivin** [WeblateOrg/weblate#10715]
### Describe the issue

Attempting to create a user through the Django panel results in a (very long) exception.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go to `https://weblateinstanceurlgoeshere/admin/accounts/profile/add/`
2. Set the interface language and translation languages
3. (Try to) Save
4. Observe the exception

### Expected behavior

A created user.

### Exception traceback

```pytb
Environment:


Request Method: POST
Request URL: https://redacted.example.com/weblate/admin/accounts/profile/add/

Django Version: 4.2.9
Python Version: 3.11.7
Installed Applications:
['weblate.addons',
 'weblate.auth',
 'weblate.checks',
 'weblate.formats',
 'weblate.glossary',
 'weblate.machinery',
 'weblate.trans',
 'weblate.lang',
 'weblate_language_data',
 'weblate.memory',
 'weblate.screenshots',
 'weblate.fonts',
 'weblate.accounts',
 'weblate.configuration',
 'weblate.utils',
 'weblate.vcs',
 'weblate.wladmin',
 'weblate.metrics',
 'weblate',
 'weblate.gitexport',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin.apps.SimpleAdminConfig',
 'django.contrib.admindocs',
 'django.contrib.sitemaps',
 'django.contrib.humanize',
 'social_django',
 'crispy_forms',
 'crispy_bootstrap3',
 'compressor',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters',
 'django_celery_beat',
 'corsheaders']
Installed Middleware:
['weblate.middleware.RedirectMiddleware',
 'weblate.middleware.ProxyMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'weblate.accounts.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'weblate.accounts.middleware.RequireLoginMiddleware',
 'weblate.api.middleware.ThrottlingMiddleware',
 'weblate.middleware.SecurityMiddleware',
 'weblate.wladmin.middleware.ManageMiddleware']



Traceback (most recent call last):
  File "/root/weblate-env/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The above exception (null value in column "user_id" violates not-null constraint
DETAIL:  Failing row contains (5, ru, 0, 0, null, f, t, f, null, 1, , , 0, 0, 0, 15, 0, , , , , , , , , , , t, , auto).) was the direct cause of the following exception:
  File "/root/weblate-env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1798, in _changeform_view
    self.save_model(request, new_object, form, not add)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/django/contrib/admin/options.py", line 1227, in save_model
    obj.save()
    ^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
    ^
  File "/root/weblate-env/lib/python3.11/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              
  File "/root/weblate-env/lib/python3.11/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              
  File "/root/weblate-env/lib/python3.11/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           
  File "/root/weblate-env/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           
  File "/root/weblate-env/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/weblate-env/lib/python3.11/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: IntegrityError at /weblate/admin/accounts/profile/add/
Exception Value: null value in column "user_id" violates not-null constraint
DETAIL:  Failing row contains (5, ru, 0, 0, null, f, t, f, null, 1, , , 0, 0, 0, 15, 0, , , , , , , , , , , t, , auto).
```

### How do you run Weblate?

PyPI module

### Weblate versions

 * Weblate: 5.3.1
 * Django: 4.2.9
 * siphashc: 2.3
 * translate-toolkit: 3.11.1
 * lxml: 4.9.4
 * Pillow: 10.1.0
 * nh3: 0.2.15
 * python-dateutil: 2.8.2
 * social-auth-core: 4.5.1
 * social-auth-app-django: 5.4.0
 * django-crispy-forms: 2.1
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.14.0
 * django-filter: 23.5
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.13.1
 * rapidfuzz: 3.5.2
 * openpyxl: 3.1.2
 * celery: 5.3.6
 * django-celery-beat: 2.5.0
 * kombu: 5.3.4
 * translation-finder: 2.16
 * weblate-language-data: 2023.9
 * html2text: 2020.1.16
 * pycairo: 1.25.1
 * PyGObject: 3.46.0
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.4.0
 * hiredis: 2.2.3
 * sentry-sdk: 1.39.1
 * Cython: 3.0.7
 * misaka: 2.1.1
 * GitPython: 3.1.40
 * borgbackup: 1.2.7
 * pyparsing: 3.1.1
 * ahocorasick_rs: 0.20.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * Python: 3.11.7
 * Git: 2.25.1
 * psycopg: 3.1.16
 * psycopg-binary: 3.1.16
 * phply: 1.2.6
 * ruamel.yaml: 0.18.5
 * tesserocr: 2.6.2
 * aeidon: 1.13
 * iniparse: 0.5
 * git-svn: 2.25.1
 * git-review: 1.27.0
 * PostgreSQL server: 12.17
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 5.19.16-sunxi64 (aarch64)

### Weblate deploy checks

```shell
SystemCheckError: System check identified some issues:

ERRORS:
?: (weblate.E011) E-mail addresses for site admins is misconfigured
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#production-admins

WARNINGS:
?: (security.W018) You should not have DEBUG set to True in deployment.
?: (weblate.W033.Mercurial) Failure in loading VCS module for Mercurial: [Errno 2] No such file or directory: 'hg'
        HINT: https://docs.weblate.org/en/weblate-5.3.1/vcs.html
?: (weblate.W039.AWSTranslation) Error importing module 'weblate.machinery.aws' in WEBLATE_MACHINERY: No module named 'boto3'
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/machine.html
?: (weblate.W039.AlibabaTranslation) Error importing module 'weblate.machinery.alibaba' in WEBLATE_MACHINERY: No module named 'aliyunsdkalimt'
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/machine.html
?: (weblate.W039.GoogleV3Translation) Error importing module 'weblate.machinery.googlev3' in WEBLATE_MACHINERY: No module named 'google'
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/machine.html
?: (weblate.W039.OpenAITranslation) Error importing module 'weblate.machinery.openai' in WEBLATE_MACHINERY: No module named 'openai'
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/machine.html

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-5.3.1/admin/backup.html

System check identified 9 issues (1 silenced).
```

### Additional context

The error about misconfigured emails is intentional.
I am not willing to set up a proper email server because this is running on a very poor single board computer which can barely handle Nginx + Gitea already.
User creation requires SMTP and IMAP to be functional, which is completely impossible in my case.
If there really is no way to run Weblate completely without a mail server (meaning, ONLY Python, Nginx and Postgre) then this is very unfortunate.

**Comment by nijel** [comment]
You are not creating a user, but a user profile, which cannot exist without a user. So it is merely a validation that is missing here.

**Comment by nijel** [comment]
Also, it is perfectly okay to run Weblate without SMTP, but you need to deal with authentication somehow. The default setup relies on e-mail to verify accounts and reset passwords. If you use external authentication such as LDAP or OAuth2, e-mails are not needed.
