### ISSUE TITLE
invalid literal for int() with base 10: 'This'

### ISSUE THREAD

**Issue by tcitworld** [WeblateOrg/weblate#10988]
### Describe the issue

Exception given systematically when exporting a translation

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

- Access the `/download/project/component/lang/?format=json-nested&q=state:%3Ctranslated` URL (crawlers do that a lot)

### Exception traceback

```pytb
Internal Server Error: /download/mobilizon/frontend/fa/

ValueError at /download/mobilizon/frontend/fa/
invalid literal for int() with base 10: 'This'

Request Method: GET
Request URL: https://weblate.framasoft.org/download/mobilizon/frontend/fa/?format=json-nested&q=state:%3Ctranslated
Django Version: 4.2.6
Python Executable: /usr/bin/uwsgi-core
Python Version: 3.11.2
Python Path: ['/', '/var/www/weblate/weblate-env/lib/python3.11/site-packages/git/ext/gitdb', '.', '', '/usr/lib/python311.zip', '/usr/lib/python3.11', '/usr/lib/python3.11/lib-dynload', '/var/www/weblate/weblate-env/lib/python3.11/site-packages']
Server time: Tue, 13 Feb 2024 07:14:19 +0000
Installed Applications:
['weblate.addons',
 'weblate.auth',
 'weblate.checks',
 'weblate.formats',
 'weblate.glossary',
 'weblate.machinery',
 'weblate.trans',
 'weblate.lang',
 'weblate_language_data',
 'weblate.memory',
 'weblate.screenshots',
 'weblate.fonts',
 'weblate.accounts',
 'weblate.configuration',
 'weblate.utils',
 'weblate.vcs',
 'weblate.wladmin',
 'weblate.metrics',
 'weblate',
 'weblate.gitexport',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin.apps.SimpleAdminConfig',
 'django.contrib.admindocs',
 'django.contrib.sitemaps',
 'django.contrib.humanize',
 'social_django',
 'crispy_forms',
 'crispy_bootstrap3',
 'compressor',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters',
 'django_celery_beat',
 'corsheaders']
Installed Middleware:
['weblate.middleware.RedirectMiddleware',
 'weblate.middleware.ProxyMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'weblate.accounts.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'weblate.accounts.middleware.RequireLoginMiddleware',
 'weblate.api.middleware.ThrottlingMiddleware',
 'weblate.middleware.SecurityMiddleware',
 'weblate.wladmin.middleware.ManageMiddleware']


Traceback (most recent call last):
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/weblate/trans/views/files.py", line 124, in download
    return download_translation_file(request, obj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/weblate/utils/views.py", line 466, in download_translation_file
    exporter.add_units(units)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/weblate/formats/exporters.py", line 110, in add_units
    self.add_unit(unit)
    ^^^^^^^^^^^^^^^^^^^
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/weblate/formats/exporters.py", line 124, in add_unit
    output = self.build_unit(unit)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/weblate/formats/exporters.py", line 426, in build_unit
    output.setid(unit.context)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/translate/storage/jsonl10n.py", line 111, in setid
    self.get_unitid()
    ^^^^^^^^^^^^^^^^^
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/translate/storage/base.py", line 977, in get_unitid
    self._unitid = self.IdClass.from_string(self._id)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/translate/storage/base.py", line 959, in from_string
    result.extend(
    ^
  File "/var/www/weblate/weblate-env/lib/python3.11/site-packages/translate/storage/base.py", line 960, in <genexpr>
    ("index", int(pos))
              ^^^^^^^^

Exception Type: ValueError at /download/mobilizon/frontend/fa/
Exception Value: invalid literal for int() with base 10: 'This'
Raised during: weblate.trans.views.files.download
Request information:
USER: Anonymous

GET:
format = 'json-nested'
q = 'state:<translated'

POST: No POST data

FILES: No FILES data

COOKIES: No cookie data

META:
CONTENT_LENGTH = ''
CONTENT_TYPE = ''
DOCUMENT_ROOT = '/var/www/weblate/data'
HTTPS = 'on'
HTTP_ACCEPT = '*/*'
HTTP_ACCEPT_ENCODING = 'deflate, gzip, br'
HTTP_HOST = 'weblate.framasoft.org'
HTTP_USER_AGENT = 'Mozilla/5.0 (compatible; AhrefsBot/7.0; +http://ahrefs.com/robot/)'
PATH_INFO = '/download/mobilizon/frontend/fa/'
QUERY_STRING = 'format=json-nested&q=state:<translated'
REMOTE_ADDR = '54.36.148.102'
REMOTE_PORT = '16391'
REQUEST_METHOD = 'GET'
REQUEST_SCHEME = 'https'
REQUEST_URI = '/download/mobilizon/frontend/fa/?format=json-nested&q=state:<translated'
SCRIPT_NAME = ''
SERVER_NAME = 'weblate.framasoft.org'
SERVER_PORT = '443'
SERVER_PROTOCOL = 'HTTP/2.0'
WEBLATE_LANGUAGE = ''
WEBLATE_USER = "'anonymous'"
```

### How do you run Weblate?

PyPI module

### Weblate versions

WEBLATE_VERSION:Cython = '3.0.4'
WEBLATE_VERSION:Django = '4.2.6'
WEBLATE_VERSION:Git = '2.39.2'
WEBLATE_VERSION:GitPython = '3.1.40'
WEBLATE_VERSION:Mercurial = '6.5.2'
WEBLATE_VERSION:Pillow = '10.1.0'
WEBLATE_VERSION:PostgreSQL server = '15.5'
WEBLATE_VERSION:PyGObject = '3.46.0'
WEBLATE_VERSION:Python = '3.11.2'
WEBLATE_VERSION:Weblate = '5.3.1'
WEBLATE_VERSION:aeidon = '1.13'
WEBLATE_VERSION:ahocorasick_rs = '0.20.0'
WEBLATE_VERSION:borgbackup = '1.2.6'
WEBLATE_VERSION:boto3 = '1.28.71'
WEBLATE_VERSION:celery = '5.3.5'
WEBLATE_VERSION:charset-normalizer = '3.3.1'
WEBLATE_VERSION:diff-match-patch = '20230430'
WEBLATE_VERSION:django-appconf = '1.0.5'
WEBLATE_VERSION:django-celery-beat = '2.5.0'
WEBLATE_VERSION:django-compressor = '4.4'
WEBLATE_VERSION:django-crispy-forms = '2.1'
WEBLATE_VERSION:django-filter = '23.3'
WEBLATE_VERSION:django-redis = '5.4.0'
WEBLATE_VERSION:djangorestframework = '3.14.0'
WEBLATE_VERSION:filelock = '3.12.4'
WEBLATE_VERSION:git-review = '2.3.1'
WEBLATE_VERSION:git-svn = '2.39.2'
WEBLATE_VERSION:hiredis = '2.2.3'
WEBLATE_VERSION:html2text = '2020.1.16'
WEBLATE_VERSION:iniparse = '0.5'
WEBLATE_VERSION:kombu = '5.3.4'
WEBLATE_VERSION:lxml = '4.9.3'
WEBLATE_VERSION:misaka = '2.1.1'
WEBLATE_VERSION:nh3 = '0.2.14'
WEBLATE_VERSION:oauthlib = '3.2.2'
WEBLATE_VERSION:openpyxl = '3.1.2'
WEBLATE_VERSION:phply = '1.2.6'
WEBLATE_VERSION:psycopg = '3.1.12'
WEBLATE_VERSION:psycopg-binary = '3.1.12'
WEBLATE_VERSION:pycairo = '1.25.1'
WEBLATE_VERSION:pyparsing = '3.1.1'
WEBLATE_VERSION:python-dateutil = '2.8.2'
WEBLATE_VERSION:python-redis-lock = '4.0.0'
WEBLATE_VERSION:rapidfuzz = '********************'
WEBLATE_VERSION:requests = '2.31.0'
WEBLATE_VERSION:ruamel.yaml = '0.18.2'
WEBLATE_VERSION:sentry-sdk = '1.31.0'
WEBLATE_VERSION:siphashc = '2.3'
WEBLATE_VERSION:social-auth-app-django = '5.4.0'
WEBLATE_VERSION:social-auth-core = '4.4.2'
WEBLATE_VERSION:tesserocr = '2.6.2'
WEBLATE_VERSION:translate-toolkit = '3.11.1'
WEBLATE_VERSION:translation-finder = '2.15'
WEBLATE_VERSION:user-agents = '2.2.0'
WEBLATE_VERSION:weblate-language-data = '2023.5'
WEBLATE_VERSION:zeep = '4.2.1'

**Comment by nijel** [comment]
This should be already fixed by https://github.com/translate/translate/commit/2a9c3253a9e013d34ccf1a07984730f9cfff25f4

**Comment by tcitworld** [comment]
Thanks, I that's what I suspected.
