### ISSUE TITLE
Performance page (and `weblate check --deploy`) fail after upgrade to 5.4

### ISSUE THREAD

**Issue by BhaaLseN** [WeblateOrg/weblate#11029]
### Describe the issue

I just upgraded from 4.18.2 to 5.0.2 to 5.4, only to be greeted with an error message when running `weblate check --deploy` at the end. The website is up and running, and appears to be working just fine. The only thing that doesn't work is the Performance page; both of which show alerts such as "a new version is available, please update".

At the time of writing, 5.4 is the most recent one, so I don't know if this magically fixes itself once 5.4.1/5.5/whichever the next version is comes out; but from the traceback I _think_ this is related to a cache file somewhere on disk that I cannot locate (nor is cleared by any of the commands listed in the upgrade instructions.)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Install an older version of Weblate (I'm going out on a limb and say: 5.0.2, because thats what I stopped at to upgrade further from 4.18.2)
2. Make sure that `weblate check --deploy` and the Performance page work. They should indicate that Weblate 5.4 is available already.
3. Upgrade to 5.4 using the [Generic upgrade instructions](https://docs.weblate.org/en/latest/admin/upgrade.html)

### Expected behavior

Both `weblate check --deploy` and the Performance page working correctly, showing warnings/alerts as necessary.

### Exception traceback

```pytb
weblate@weblate:~/weblate$ weblate check --deploy
Traceback (most recent call last):
  File "/home/weblate/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django
_redis/client/default.py", line 445, in decode
    value = int(value)
            ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: b'\x80\x04\x95\xae&\x00\x00\
x00\x00\x00\x00]\x94(\x8c\x14weblate.utils.checks\x94\x8c\x07Release\x94\x93\x94
\x8c\x035.4\x94\x8c\x08datetime\x94\x8c\x08datetime\x94\x93\x94C\n\x07\xe8\x02\x
0f\r+#\x01W\

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/weblate/.pyenv/versions/3.11.3/bin/weblate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/weblate/weblate/weblate/runner.py", line 19, in main
    utility.execute()
  File "/home/weblate/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django
/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/weblate/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django
/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/weblate/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django
/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django
/core/management/commands/check.py", line 76, in handle
    self.check(
  File "/home/weblate/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django
/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/weblate/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django
/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate/weblate/utils/apps.py", line 373, in check_version
    latest = get_latest_version()
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate/weblate/utils/version.py", line 101, in get_latest
_version
    return get_version_info()[0]
           ^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate/weblate/utils/version.py", line 93, in get_version
_info
    result = cache.get(CACHE_KEY)
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django
_redis/cache.py", line 92, in get
    value = self._get(key, default, version, client)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django_redis/cache.py", line 29, in _decorator
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django_redis/cache.py", line 99, in _get
    return self.client.get(key, default=default, version=version, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django_redis/client/default.py", line 265, in get
    return self.decode(value)
           ^^^^^^^^^^^^^^^^^^
  File "/home/weblate/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django_redis/client/default.py", line 452, in decode
    value = self._serializer.loads(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/.pyenv/versions/3.11.3/lib/python3.11/site-packages/django_redis/serializers/pickle.py", line 32, in loads
    return pickle.loads(value)
           ^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'Release' on <module 'weblate.utils.checks' from '/home/weblate/weblate/weblate/utils/checks.py'>
```

### How do you run Weblate?

Git checkout

### Weblate versions

```
weblate@weblate:~/weblate$ weblate list_versions
 * Weblate: weblate-5.4-1-gd425c87191
 * Django: 4.2.10
 * siphashc: 2.4.1
 * translate-toolkit: 3.12.2
 * lxml: 5.1.0
 * pillow: 10.2.0
 * nh3: 0.2.15
 * python-dateutil: 2.8.2
 * social-auth-core: 4.5.3
 * social-auth-app-django: 5.4.0
 * django-crispy-forms: 2.1
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.14.0
 * django-filter: 23.5
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.13.1
 * rapidfuzz: 3.6.1
 * openpyxl: 3.1.2
 * celery: 5.3.6
 * django-celery-beat: 2.5.0
 * kombu: 5.3.5
 * translation-finder: 2.16
 * weblate-language-data: 2024.3
 * html2text: 2020.1.16
 * pycairo: 1.26.0
 * PyGObject: 3.46.0
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.4.0
 * hiredis: 2.3.2
 * sentry-sdk: 1.40.4
 * Cython: 3.0.8
 * misaka: 2.1.1
 * GitPython: 3.1.42
 * borgbackup: 1.2.7
 * pyparsing: 3.1.1
 * ahocorasick_rs: 0.22.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * Python: 3.11.3
 * Git: 2.39.2
 * psycopg: 3.1.9
 * psycopg-binary: 3.1.9
 * phply: 1.2.6
 * ruamel.yaml: 0.18.6
 * tesserocr: 2.6.2
 * boto3: 1.34.43
 * aeidon: 1.13
 * iniparse: 0.5
 * Mercurial: 6.6.3
 * git-review: 2.3.1
 * PostgreSQL server: 15.6
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache
 * Email setup: django.core.mail.backends.dummy.EmailBackend:
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 6.1.0-10-amd64 (x86_64)
```

Don't worry about this extra commit in the beginning, this is the tag `weblate-5.4` plus a commit with my local `settings.py` file that's on a dedicated branch (I rebase that one of the most recent tag every time I update, then diff against `settings_example.py` and amend the commit with the most recent state.)

### Weblate deploy checks

```shell
I'm afraid thats the problem; `weblate check --deploy` currently does not work.
```

**Comment by nijel** [comment]
This happens because we've moved some classes and the cached ones can no longer be loaded. The good news is that this is cached only for 24 hours, so it should be now expired and will load the version information again using the new class.

**Comment by BhaaLseN** [comment]
> This happens because we've moved some classes and the cached ones can no longer be loaded. The good news is that this is cached only for 24 hours, so it should be now expired and will load the version information again using the new class.

Yup, that's exactly what seems to have happened. Both work fine today. Thanks 👍
