### ISSUE TITLE
Error with the Addons after upgrading from 5.3.1 to 5.4.1

### ISSUE THREAD

**Issue by phandja** [WeblateOrg/weblate#11076]
### Describe the issue

Currently, we're encountering errors while attempting to access our customized Addons. Our server runs as a Docker Image. The issue is happening since we did upgrade to version 5.4.1. However, when we reverted to version 5.3.1, the problem ceased to occur. 
Any idea about the cause of this situation, or it is a known bug on the Docker version 5.4.1.

![weblate](https://github.com/WeblateOrg/weblate/assets/12895500/d8b6f8e3-131f-4f84-8f88-34ac02ecbc25)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Weblate Main page
2. Dashboard
3. Pick any Project
4. Pick any Component
5. Manage
6. Addon (Extensions in French version)

### Expected behavior

Server Error

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/12895500/a3b2fe76-0cfa-4f77-9f7f-97037f648943)

### How do you run Weblate?

weblate.org service

**Comment by nijel** [comment]
Can you please include logs from the container? Without that, the issue is useless.

> Currently, we're encountering errors while attempting to access our customized Addons. 

The add-ons interface evolves, and it has changed in the 5.4. release, so you need to adjust your customized add-ons.

> weblate.org service

Apparently not.

**Comment by phandja** [comment]
Here is some log (seems like the script import is the problem):

root@xxxxxx:/var/lib/weblate-docker# docker logs --tail 100 --follow --timestamps 852ff15f97b8
2024-02-22T19:20:54.959822071Z nginx stdout | 10.225.203.20 - - [22/Feb/2024:19:20:54 +0000] "GET /admin HTTP/1.1" 301 5 "-" "-"
2024-02-22T19:21:18.648307164Z nginx stdout | 10.225.203.21 - - [22/Feb/2024:19:21:18 +0000] "GET /admin HTTP/1.1" 301 162 "-" "-"
2024-02-22T19:21:18.662684191Z nginx stdout | 10.225.203.21 - - [22/Feb/2024:19:21:18 +0000] "GET /admin HTTP/1.1" 301 5 "-" "-"
2024-02-22T19:21:24.920276954Z nginx stdout | 10.225.203.20 - - [22/Feb/2024:19:21:24 +0000] "GET /admin HTTP/1.1" 301 162 "-" "-"
2024-02-22T19:21:24.934524478Z nginx stdout | 10.225.203.20 - - [22/Feb/2024:19:21:24 +0000] "GET /admin HTTP/1.1" 301 5 "-" "-"
2024-02-22T19:21:43.518513590Z celery-celery stderr | [2024-02-22 19:21:43,517: INFO/MainProcess] Task weblate.utils.tasks.heartbeat[a944f3db-ce71-4633-84c0-adb0922ba919] received
2024-02-22T19:21:48.653529153Z nginx stdout | 10.225.203.21 - - [22/Feb/2024:19:21:48 +0000] "GET /admin HTTP/1.1" 301 162 "-" "-"
2024-02-22T19:21:48.666850263Z nginx stdout | 10.225.203.21 - - [22/Feb/2024:19:21:48 +0000] "GET /admin HTTP/1.1" 301 5 "-" "-"
2024-02-22T19:21:54.927199769Z nginx stdout | 10.225.203.20 - - [22/Feb/2024:19:21:54 +0000] "GET /admin HTTP/1.1" 301 162 "-" "-"
2024-02-22T19:21:54.940758083Z nginx stdout | 10.225.203.20 - - [22/Feb/2024:19:21:54 +0000] "GET /admin HTTP/1.1" 301 5 "-" "-"
2024-02-22T19:22:18.637026699Z nginx stdout | 10.225.203.21 - - [22/Feb/2024:19:22:18 +0000] "GET /admin HTTP/1.1" 301 162 "-" "-"
2024-02-22T19:22:18.651565028Z nginx stdout | 10.225.203.21 - - [22/Feb/2024:19:22:18 +0000] "GET /admin HTTP/1.1" 301 5 "-" "-"
2024-02-22T19:22:24.929448711Z nginx stdout | 10.225.203.20 - - [22/Feb/2024:19:22:24 +0000] "GET /admin HTTP/1.1" 301 162 "-" "-"
2024-02-22T19:22:24.949366025Z nginx stdout | 10.225.203.20 - - [22/Feb/2024:19:22:24 +0000] "GET /admin HTTP/1.1" 301 5 "-" "-"
2024-02-22T19:22:43.519767222Z celery-celery stderr | [2024-02-22 19:22:43,517: INFO/MainProcess] Task weblate.utils.tasks.heartbeat[64918b55-99ef-4e0a-8b15-80ab727b207c] received
2024-02-22T19:22:48.636308694Z nginx stdout | 10.225.203.21 - - [22/Feb/2024:19:22:48 +0000] "GET /admin HTTP/1.1" 301 162 "-" "-"
2024-02-22T19:22:48.651036726Z nginx stdout | 10.225.203.21 - - [22/Feb/2024:19:22:48 +0000] "GET /admin HTTP/1.1" 301 5 "-" "-"
2024-02-22T19:22:54.933160475Z nginx stdout | 10.225.203.20 - - [22/Feb/2024:19:22:54 +0000] "GET /admin HTTP/1.1" 301 162 "-" "-"
2024-02-22T19:22:54.957468058Z nginx stdout | 10.225.203.20 - - [22/Feb/2024:19:22:54 +0000] "GET /admin HTTP/1.1" 301 5 "-" "-"
2024-02-22T19:23:18.656389916Z nginx stdout | 10.225.203.21 - - [22/Feb/2024:19:23:18 +0000] "GET /admin HTTP/1.1" 301 162 "-" "-"
2024-02-22T19:23:18.669971430Z nginx stdout | 10.225.203.21 - - [22/Feb/2024:19:23:18 +0000] "GET /admin HTTP/1.1" 301 5 "-" "-"
2024-02-22T19:23:24.936307931Z nginx stdout | 10.225.203.20 - - [22/Feb/2024:19:23:24 +0000] "GET /admin HTTP/1.1" 301 162 "-" "-"
2024-02-22T19:23:24.949460438Z nginx stdout | 10.225.203.20 - - [22/Feb/2024:19:23:24 +0000] "GET /admin HTTP/1.1" 301 5 "-" "-"
2024-02-22T19:23:43.521188656Z celery-celery stderr | [2024-02-22 19:23:43,519: INFO/MainProcess] Task weblate.utils.tasks.heartbeat[806de9cb-ace3-41b3-b252-73d9e0352b6a] received
2024-02-22T19:23:48.633943668Z nginx stdout | 10.225.203.21 - - [22/Feb/2024:19:23:48 +0000] "GET /admin HTTP/1.1" 301 162 "-" "-"
2024-02-22T19:23:48.653027969Z nginx stdout | 10.225.203.21 - - [22/Feb/2024:19:23:48 +0000] "GET /admin HTTP/1.1" 301 5 "-" "-"
2024-02-22T19:23:54.929868435Z nginx stdout | 10.225.203.20 - - [22/Feb/2024:19:23:54 +0000] "GET /admin HTTP/1.1" 301 162 "-" "-"
2024-02-22T19:23:54.944612068Z nginx stdout | 10.225.203.20 - - [22/Feb/2024:19:23:54 +0000] "GET /admin HTTP/1.1" 301 5 "-" "-"
2024-02-22T19:24:09.708839754Z gunicorn stderr | [2024-02-22 19:24:09,585: ERROR/1031] Internal Server Error: /addons/cumulus/wk-can-app-pot-translation-320200/
2024-02-22T19:24:09.708876454Z gunicorn stderr | Traceback (most recent call last):
2024-02-22T19:24:09.708884054Z gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/utils/classloader.py", line 21, in load_class
2024-02-22T19:24:09.708891154Z gunicorn stderr |     mod = import_module(module)
2024-02-22T19:24:09.708897155Z gunicorn stderr |           ^^^^^^^^^^^^^^^^^^^^^
2024-02-22T19:24:09.708902955Z gunicorn stderr |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
2024-02-22T19:24:09.708909155Z gunicorn stderr |     return _bootstrap._gcd_import(name[level:], package, level)
2024-02-22T19:24:09.708915155Z gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22T19:24:09.708921555Z gunicorn stderr |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2024-02-22T19:24:09.708928555Z gunicorn stderr |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2024-02-22T19:24:09.708935155Z gunicorn stderr |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
2024-02-22T19:24:09.708942355Z gunicorn stderr |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
2024-02-22T19:24:09.708948955Z gunicorn stderr |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
2024-02-22T19:24:09.708955255Z gunicorn stderr |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2024-02-22T19:24:09.708962156Z gunicorn stderr |   File "/app/data/python/customize/addons/msgmerge.py", line 25, in <module>
2024-02-22T19:24:09.708968656Z gunicorn stderr |     from weblate.addons.events import EVENT_POST_UPDATE
2024-02-22T19:24:09.708974856Z gunicorn stderr | ImportError: cannot import name 'EVENT_POST_UPDATE' from 'weblate.addons.events' (/usr/local/lib/python3.12/site-packages/weblate/addons/events.py)
2024-02-22T19:24:09.708994756Z gunicorn stderr |
2024-02-22T19:24:09.709001356Z gunicorn stderr | The above exception was the direct cause of the following exception:
2024-02-22T19:24:09.709007756Z gunicorn stderr |
2024-02-22T19:24:09.709013756Z gunicorn stderr | Traceback (most recent call last):
2024-02-22T19:24:09.709020056Z gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
2024-02-22T19:24:09.709026557Z gunicorn stderr |     response = get_response(request)
2024-02-22T19:24:09.709032557Z gunicorn stderr |                ^^^^^^^^^^^^^^^^^^^^^
2024-02-22T19:24:09.709040757Z gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
2024-02-22T19:24:09.709047857Z gunicorn stderr |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2024-02-22T19:24:09.709054557Z gunicorn stderr |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22T19:24:09.709061357Z gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
2024-02-22T19:24:09.709068057Z gunicorn stderr |     return self.dispatch(request, *args, **kwargs)
2024-02-22T19:24:09.709074557Z gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22T19:24:09.709081057Z gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
2024-02-22T19:24:09.709088058Z gunicorn stderr |     return handler(request, *args, **kwargs)
2024-02-22T19:24:09.709094458Z gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22T19:24:09.709101258Z gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/django/views/generic/list.py", line 174, in get
2024-02-22T19:24:09.709108258Z gunicorn stderr |     context = self.get_context_data()
2024-02-22T19:24:09.709114458Z gunicorn stderr |               ^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22T19:24:09.709120958Z gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/addons/views.py", line 40, in get_context_data
2024-02-22T19:24:09.709127758Z gunicorn stderr |     installed = {x.addon.name for x in result["object_list"]}
2024-02-22T19:24:09.709134458Z gunicorn stderr |                  ^^^^^^^
2024-02-22T19:24:09.709140758Z gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/django/utils/functional.py", line 57, in __get__
2024-02-22T19:24:09.709147858Z gunicorn stderr |     res = instance.__dict__[self.name] = self.func(instance)
2024-02-22T19:24:09.709154459Z gunicorn stderr |                                          ^^^^^^^^^^^^^^^^^^^
2024-02-22T19:24:09.709160959Z gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/addons/models.py", line 122, in addon
2024-02-22T19:24:09.709168059Z gunicorn stderr |     return self.addon_class(self)
2024-02-22T19:24:09.709180659Z gunicorn stderr |            ^^^^^^^^^^^^^^^^
2024-02-22T19:24:09.709187559Z gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/django/utils/functional.py", line 57, in __get__
2024-02-22T19:24:09.709194459Z gunicorn stderr |     res = instance.__dict__[self.name] = self.func(instance)
2024-02-22T19:24:09.709201059Z gunicorn stderr |                                          ^^^^^^^^^^^^^^^^^^^
2024-02-22T19:24:09.709208759Z gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/addons/models.py", line 118, in addon_class
2024-02-22T19:24:09.709215960Z gunicorn stderr |     return ADDONS[self.name]
2024-02-22T19:24:09.709222560Z gunicorn stderr |            ~~~~~~^^^^^^^^^^^
2024-02-22T19:24:09.709229060Z gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/utils/classloader.py", line 73, in __getitem__
2024-02-22T19:24:09.709236060Z gunicorn stderr |     return self.data.__getitem__(key)
2024-02-22T19:24:09.709241960Z gunicorn stderr |            ^^^^^^^^^
2024-02-22T19:24:09.709248360Z gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/django/utils/functional.py", line 57, in __get__
2024-02-22T19:24:09.709255160Z gunicorn stderr |     res = instance.__dict__[self.name] = self.func(instance)
2024-02-22T19:24:09.709261760Z gunicorn stderr |                                          ^^^^^^^^^^^^^^^^^^^
2024-02-22T19:24:09.709268360Z gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/utils/classloader.py", line 70, in data
2024-02-22T19:24:09.709274660Z gunicorn stderr |     return self.load_data()
2024-02-22T19:24:09.709281461Z gunicorn stderr |            ^^^^^^^^^^^^^^^^
2024-02-22T19:24:09.709287061Z gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/utils/classloader.py", line 57, in load_data
2024-02-22T19:24:09.709293561Z gunicorn stderr |     obj = load_class(path, self.name)
2024-02-22T19:24:09.709299161Z gunicorn stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22T19:24:09.709304961Z gunicorn stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/utils/classloader.py", line 23, in load_class
2024-02-22T19:24:09.709310761Z gunicorn stderr |     raise ImproperlyConfigured(
2024-02-22T19:24:09.709316361Z gunicorn stderr | django.core.exceptions.ImproperlyConfigured: Error importing module 'customize.addons.msgmerge' in WEBLATE_ADDONS: cannot import name 'EVENT_POST_UPDATE' from 'weblate.addons.events' (/usr/local/lib/python3.12/site-packages/weblate/addons/events.py)
2024-02-22T19:24:09.760282365Z nginx stdout | 10.118.59.211 - - [22/Feb/2024:19:24:09 +0000] "GET /addons/cumulus/wk-can-app-pot-translation-320200/ HTTP/1.1" 500 16426 "https://weblate.wolterskluwer.ca/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
2024-02-22T19:24:18.645996065Z nginx stdout | 10.225.203.21 - - [22/Feb/2024:19:24:18 +0000] "GET /admin HTTP/1.1" 301 162 "-" "-"
2024-02-22T19:24:18.659749481Z nginx stdout | 10.225.203.21 - - [22/Feb/2024:19:24:18 +0000] "GET /admin HTTP/1.1" 301 5 "-" "-"
2024-02-22T19:24:24.928439719Z nginx stdout | 10.225.203.20 - - [22/Feb/2024:19:24:24 +0000] "GET /admin HTTP/1.1" 301 162 "-" "-"
2024-02-22T19:24:24.942231137Z nginx stdout | 10.225.203.20 - - [22/Feb/2024:19:24:24 +0000] "GET /admin HTTP/1.1" 301 5 "-" "-"
2024-02-22T19:24:43.521330971Z celery-celery stderr | [2024-02-22 19:24:43,520: INFO/MainProcess] Task weblate.utils.tasks.heartbeat[abe61cc5-497b-463d-866f-2f9fc0829062] received
2024-02-22T19:24:48.636791926Z nginx stdout | 10.225.203.21 - - [22/Feb/2024:19:24:48 +0000] "GET /admin HTTP/1.1" 301 162 "-" "-"
2024-02-22T19:24:48.652283070Z nginx stdout | 10.225.203.21 - - [22/Feb/2024:19:24:48 +0000] "GET /admin HTTP/1.1" 301 5 "-" "-"
^C

**Comment by nijel** [comment]
You need to adjust your add-on code to match the current API. Also, why are you using custom msgmerge add-on when there is one built-in?

**Comment by phandja** [comment]
Thank you for responding, @nijel . This code is essentially a legacy code. We'll make the necessary adjustments.
