### ISSUE TITLE
Issue Report: KeyError during execution of perform_commit task

### ISSUE THREAD

**Issue by vanlinh2204** [WeblateOrg/weblate#11231]
### Describe the issue

When executing the perform_commit task in Weblate version 5.4.1, an error occurs resulting in a KeyError. This issue appears to stem from character checking in an Excel file, as indicated in the provided logs.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Execute the perform_commit task in Weblate version 5.4.1.
2. Observe the logs for any errors.

### Expected behavior

The perform_commit task should execute without errors, ensuring successful commit operations.

### Exception traceback

```pytb
celery-celery stderr | [2024-03-19 04:50:42,734: ERROR/ForkPoolWorker-6] Failure while executing task: KeyError: {'signal': <Signal: task_failure providing_args={'traceback', 'exception', 'einfo', 'args', 'kwargs', 'task_id'}>, 'sender': <@task: weblate.trans.tasks.perform_commit of weblate at 0x7f53932eb200>, 'task_id': '0523b69d-ae64-41fa-834d-d3c917bf5d35', 'args': [211, 'commit_pending', None], 'kwargs': {}, 'traceback': <traceback object at 0x7f537df2b280>, 'einfo': <ExceptionInfo: ExceptionWithTraceback()>}
celery-celery stderr | [2024-03-19 04:50:42,734: ERROR/911] Failure while executing task
celery-celery stderr | Traceback (most recent call last):
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 477, in trace_task
celery-celery stderr |     R = retval = fun(*args, **kwargs)
celery-celery stderr |                  ^^^^^^^^^^^^^^^^^^^^
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 760, in __protected_call__
celery-celery stderr |     return self.run(*args, **kwargs)
celery-celery stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/celery/app/autoretry.py", line 38, in run
celery-celery stderr |     return task._orig_run(*args, **kwargs)
celery-celery stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/tasks.py", line 107, in perform_commit
celery-celery stderr |     component.commit_pending(*args)
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/models/component.py", line 194, in on_link_wrapper
celery-celery stderr |     return getattr(linked, func.__name__)(*args, **kwargs)
celery-celery stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/models/component.py", line 195, in on_link_wrapper
celery-celery stderr |     return func(self, *args, **kwargs)
celery-celery stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/models/component.py", line 1957, in commit_pending
celery-celery stderr |     translation._commit_pending(reason, user)
celery-celery stderr |   File "/usr/local/lib/python3.12/contextlib.py", line 81, in inner
celery-celery stderr |     return func(*args, **kwds)
celery-celery stderr |            ^^^^^^^^^^^^^^^^^^^
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/models/translation.py", line 611, in _commit_pending
celery-celery stderr |     self.update_units(units, store, author_name, author.id)
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/models/translation.py", line 807, in update_units
celery-celery stderr |     store.save()
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/formats/ttkit.py", line 334, in save
celery-celery stderr |     self.save_atomic(self.storefile, self.save_content)
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/formats/base.py", line 434, in save_atomic
celery-celery stderr |     callback(temp)
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/formats/external.py", line 63, in save_content
celery-celery stderr |     ILLEGAL_CHARACTERS_RE.sub("", data[field]),
celery-celery stderr |                                   ~~~~^^^^^^^
celery-celery stderr | KeyError: ''
celery-celery stderr | [2024-03-19 04:50:42,734: ERROR/ForkPoolWorker-6] Failure while executing task
celery-celery stderr | Traceback (most recent call last):
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 477, in trace_task
celery-celery stderr |     R = retval = fun(*args, **kwargs)
celery-celery stderr |                  ^^^^^^^^^^^^^^^^^^^^
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 760, in __protected_call__
celery-celery stderr |     return self.run(*args, **kwargs)
celery-celery stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/celery/app/autoretry.py", line 38, in run
celery-celery stderr |     return task._orig_run(*args, **kwargs)
celery-celery stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/tasks.py", line 107, in perform_commit
celery-celery stderr |     component.commit_pending(*args)
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/models/component.py", line 194, in on_link_wrapper
celery-celery stderr |     return getattr(linked, func.__name__)(*args, **kwargs)
celery-celery stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/models/component.py", line 195, in on_link_wrapper
celery-celery stderr |     return func(self, *args, **kwargs)
celery-celery stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/models/component.py", line 1957, in commit_pending
celery-celery stderr |     translation._commit_pending(reason, user)
celery-celery stderr |   File "/usr/local/lib/python3.12/contextlib.py", line 81, in inner
celery-celery stderr |     return func(*args, **kwds)
celery-celery stderr |            ^^^^^^^^^^^^^^^^^^^
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/models/translation.py", line 611, in _commit_pending
celery-celery stderr |     self.update_units(units, store, author_name, author.id)
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/trans/models/translation.py", line 807, in update_units
celery-celery stderr |     store.save()
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/formats/ttkit.py", line 334, in save
celery-celery stderr |     self.save_atomic(self.storefile, self.save_content)
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/formats/base.py", line 434, in save_atomic
celery-celery stderr |     callback(temp)
celery-celery stderr |   File "/usr/local/lib/python3.12/site-packages/weblate/formats/external.py", line 63, in save_content
celery-celery stderr |     ILLEGAL_CHARACTERS_RE.sub("", data[field]),
celery-celery stderr |                                   ~~~~^^^^^^^
celery-celery stderr | KeyError: ''
```

### How do you run Weblate?

Docker container

### Weblate versions

Weblate Version: 5.4.1

### Additional context

- This issue seems to be related to character checking in Excel files.
- Any additional observations or insights regarding the issue.

**Comment by nijel** [comment]
Can you share your Excel file? You can strip the content, just header row and few lines to show how the content looks like.

**Comment by vanlinh2204** [comment]
Hello @nijel

Due to company policy reasons, I'm unable to provide the actual file. However, even with a temporary file, the issue I mentioned earlier still persists.

[de.xlsx](https://github.com/WeblateOrg/weblate/files/14647686/de.xlsx)
[fr.xlsx](https://github.com/WeblateOrg/weblate/files/14647687/fr.xlsx)
