### ISSUE TITLE
ERROR Failure while executing task: WeblateLockTimeoutError

### ISSUE THREAD

**Issue by dxdx123** [WeblateOrg/weblate#11278]
### Describe the issue

When I use automatic translation, automatic translation has been unable to be executed, even if I restart weblate, or even delete and rebuild the weblate container. 
Please check if this is a bug. 

From the log I saw the following error:
ERROR Failure while executing task: WeblateLockTimeoutError: {'signal': <Signal: task_failure providing_args={'kwargs', 'args', 'task_id', 'traceback', 'einfo', 'exception'}>, 'sender': <@task: weblate.trans.tasks.auto_translate of weblate at 0x7fc598de57d0>, 'task_id': '44a5f2fc-813a-4bbc-af24-62e1d8e6fd18', 'args': [6, 1566, 'fuzzy', 'nottranslated', 'mt', None, ['gpt-translate'], 90], 'kwargs': {'is_form_edit': True}, 'traceback': <traceback object at 0x7fc5832b2380>, 'einfo': <ExceptionInfo: ExceptionWithTraceback()>}
2024-03-26 17:49:59,536 ERROR Failure while executing task
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 306, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/_compat.py", line 115, in reraise
    raise value
  File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/celery.py", line 301, in _inner
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/autoretry.py", line 60, in run
    ret = task.retry(exc=exc, **retry_kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/task.py", line 736, in retry
    raise_with_context(exc)
  File "/usr/local/lib/python3.11/site-packages/celery/app/autoretry.py", line 38, in run
    return task._orig_run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weblate/trans/tasks.py", line 444, in auto_translate
    with translation.component.lock, override(user.profile.language if user else "en"):
  File "/usr/local/lib/python3.11/site-packages/weblate/utils/lock.py", line 86, in __enter__
    self._enter_implementation()
  File "/usr/local/lib/python3.11/site-packages/weblate/utils/lock.py", line 70, in _enter_redis
    raise WeblateLockTimeoutError(
weblate.utils.lock.WeblateLockTimeoutError: Lock on component-update-lock-213 could not be acquired in 20s

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Automatic Translation

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/14290268/566e95f1-5dcb-4ab7-b13f-4a96a5b94366)

### How do you run Weblate?

Docker container

### Weblate versions

5.3.1

**Comment by nijel** [comment]
The stale locks persist in redis (AFAIR for one hour), so rebuilding the container will not remove stale locks.
