### ISSUE TITLE
Exception upon clicking on the 'Add User' button

### ISSUE THREAD

**Issue by iamshoXy** [WeblateOrg/weblate#11580]
### Describe the issue

I'm receiving an error when trying to add a user through the admin dashboard.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go to the Django admin interface
2. Navigate to the users tab
3. Click on 'Add user'

### Expected behavior

The add user view should be shown

### Exception traceback

```pytb
gunicorn stderr | [2024-05-06 12:18:07,638: ERROR/443] Internal Server Error: /admin/weblate_auth/user/add/
gunicorn stderr | Traceback (most recent call last):
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/contrib/auth/password_validation.py", line 29, in get_password_validators
gunicorn stderr |     klass = import_string(validator["NAME"])
gunicorn stderr |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 30, in import_string
gunicorn stderr |     return cached_import(module_path, class_name)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/utils/module_loading.py", line 15, in cached_import
gunicorn stderr |     module = import_module(module_path)
gunicorn stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
gunicorn stderr |     return _bootstrap._gcd_import(name[level:], package, level)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
gunicorn stderr |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
gunicorn stderr |   File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
gunicorn stderr | ModuleNotFoundError: No module named 'zxcvbn_password'
gunicorn stderr |
gunicorn stderr | During handling of the above exception, another exception occurred:
gunicorn stderr |
gunicorn stderr | Traceback (most recent call last):
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
gunicorn stderr |     response = get_response(request)
gunicorn stderr |                ^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
gunicorn stderr |     response = response.render()
gunicorn stderr |                ^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
gunicorn stderr |     return old_render(self)
gunicorn stderr |            ^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
gunicorn stderr |     self.content = self.rendered_content
gunicorn stderr |                    ^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
gunicorn stderr |     return real_rendered_content.fget(self)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
gunicorn stderr |     return template.render(context, self._request)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
gunicorn stderr |     return self.template.render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
gunicorn stderr |     return self._render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
gunicorn stderr |     return self.nodelist.render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
gunicorn stderr |     return SafeString("".join([node.render_annotated(context) for node in self]))
gunicorn stderr |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
gunicorn stderr |     return self.render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
gunicorn stderr |     return compiled_parent._render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
gunicorn stderr |     return self.nodelist.render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
gunicorn stderr |     return SafeString("".join([node.render_annotated(context) for node in self]))
gunicorn stderr |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
gunicorn stderr |     return self.render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
gunicorn stderr |     return compiled_parent._render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
gunicorn stderr |     return self.nodelist.render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
gunicorn stderr |     return SafeString("".join([node.render_annotated(context) for node in self]))
gunicorn stderr |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
gunicorn stderr |     return self.render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
gunicorn stderr |     return compiled_parent._render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
gunicorn stderr |     return self.nodelist.render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
gunicorn stderr |     return SafeString("".join([node.render_annotated(context) for node in self]))
gunicorn stderr |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
gunicorn stderr |     return self.render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
gunicorn stderr |     return compiled_parent._render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
gunicorn stderr |     return self.nodelist.render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
gunicorn stderr |     return SafeString("".join([node.render_annotated(context) for node in self]))
gunicorn stderr |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
gunicorn stderr |     return self.render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
gunicorn stderr |     result = block.nodelist.render(context)
gunicorn stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
gunicorn stderr |     return SafeString("".join([node.render_annotated(context) for node in self]))
gunicorn stderr |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
gunicorn stderr |     return self.render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
gunicorn stderr |     result = block.nodelist.render(context)
gunicorn stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
gunicorn stderr |     return SafeString("".join([node.render_annotated(context) for node in self]))
gunicorn stderr |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
gunicorn stderr |     return self.render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
gunicorn stderr |     nodelist.append(node.render_annotated(context))
gunicorn stderr |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
gunicorn stderr |     return self.render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 210, in render
gunicorn stderr |     return template.render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 173, in render
gunicorn stderr |     return self._render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
gunicorn stderr |     return self.nodelist.render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
gunicorn stderr |     return SafeString("".join([node.render_annotated(context) for node in self]))
gunicorn stderr |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
gunicorn stderr |     return self.render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 242, in render
gunicorn stderr |     nodelist.append(node.render_annotated(context))
gunicorn stderr |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
gunicorn stderr |     return self.render(context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/template/defaulttags.py", line 197, in render
gunicorn stderr |     values = list(values)
gunicorn stderr |              ^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/contrib/admin/helpers.py", line 153, in __iter__
gunicorn stderr |     yield AdminField(self.form, field, is_first=(i == 0))
gunicorn stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/contrib/admin/helpers.py", line 167, in __init__
gunicorn stderr |     self.field = form[field]  # A django.forms.BoundField instance
gunicorn stderr |                  ~~~~^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/forms/forms.py", line 185, in __getitem__
gunicorn stderr |     self._bound_fields_cache[name] = field.get_bound_field(self, name)
gunicorn stderr |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/forms/fields.py", line 254, in get_bound_field
gunicorn stderr |     return BoundField(form, self, field_name)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/forms/boundfield.py", line 27, in __init__
gunicorn stderr |     self.help_text = field.help_text or ""
gunicorn stderr |                      ^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/utils/functional.py", line 187, in __wrapper__
gunicorn stderr |     result = func(*self._args, **self._kw)
gunicorn stderr |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/contrib/auth/password_validation.py", line 89, in _password_validators_help_text_html
gunicorn stderr |     help_texts = password_validators_help_texts(password_validators)
gunicorn stderr |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/contrib/auth/password_validation.py", line 78, in password_validators_help_texts
gunicorn stderr |     password_validators = get_default_password_validators()
gunicorn stderr |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/contrib/auth/password_validation.py", line 22, in get_default_password_validators
gunicorn stderr |     return get_password_validators(settings.AUTH_PASSWORD_VALIDATORS)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/contrib/auth/password_validation.py", line 35, in get_password_validators
gunicorn stderr |     raise ImproperlyConfigured(msg % validator["NAME"])
gunicorn stderr | django.core.exceptions.ImproperlyConfigured: The module in NAME could not be imported: zxcvbn_password.ZXCVBNValidator. Check your AUTH_PASSWORD_VALIDATORS setting.
```
```


### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 5.5.4-dev
 * Django: 5.0.4
 * siphashc: 2.4.1
 * translate-toolkit: 3.13.0
 * lxml: 5.2.1
 * pillow: 10.3.0
 * nh3: 0.2.17
 * python-dateutil: 2.9.0.post0
 * social-auth-core: 4.5.4
 * social-auth-app-django: 5.4.1
 * django-crispy-forms: 2.1
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.15.1
 * django-filter: 24.2
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.14.0
 * rapidfuzz: 3.9.0
 * openpyxl: 3.1.2
 * celery: 5.4.0
 * django-celery-beat: 2.6.0
 * kombu: 5.3.7
 * translation-finder: 2.16
 * weblate-language-data: 2024.5
 * html2text: 2024.2.26
 * pycairo: 1.26.0
 * PyGObject: 3.48.2
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.4.0
 * hiredis: 2.3.2
 * sentry-sdk: 1.45.0
 * Cython: 3.0.10
 * misaka: 2.1.1
 * GitPython: 3.1.43
 * borgbackup: 1.2.8
 * pyparsing: 3.1.2
 * ahocorasick_rs: 0.22.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.3.2
 * Python: 3.12.3
 * Git: 2.39.2
 * psycopg: 3.1.18
 * psycopg-binary: 3.1.18
 * phply: 1.2.6
 * ruamel.yaml: 0.18.6
 * tesserocr: 2.7.0
 * boto3: 1.34.98
 * zeep: 4.2.1
 * aeidon: 1.14.1
 * iniparse: 0.5
 * Mercurial: 6.7.2
 * git-svn: 2.39.2
 * git-review: 2.4.0
 * PostgreSQL server: 16.2
 * Database backends: django.db.backends.postgresql
 * PostgreSQL implementation: psycopg3 (binary)
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.gmail.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 6.1.0-18-amd64 (x86_64)

### Weblate deploy checks

```shell
?: (weblate.E003) Cannot send e-mail ((535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials s2-20020a5d4242000000b003472489d26fsm10536409wrr.19 - gsmtp')), please check EMAIL_* settings.
        HINT: https://docs.weblate.org/en/latest/admin/install.html#out-mail
?: (weblate.E027) The path /app/data/python/customize/static is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/latest/admin/install.html#file-permissions
?: (weblate.E027) The path /app/data/python/customize/static/favicon.ico is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/latest/admin/install.html#file-permissions
?: (weblate.E027) The path /app/data/python/customize/static/icons is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/latest/admin/install.html#file-permissions
?: (weblate.E027) The path /app/data/python/customize/static/icons/weblate.svg is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/latest/admin/install.html#file-permissions
?: (weblate.E027) The path /app/data/python/customize/static/logo-16.png is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/latest/admin/install.html#file-permissions
?: (weblate.E027) The path /app/data/python/customize/static/logo-32.png is owned by a different user, check your DATA_DIR settings.
        HINT: https://docs.weblate.org/en/latest/admin/install.html#file-permissions
```

**Comment by iamshoXy** [comment]
I just realized that I haven't installed the extras. My bad!
