### ISSUE TITLE
Missing changed in resource bundle file 

### ISSUE THREAD

**Issue by dngduy132** [WeblateOrg/weblate#11597]
### Describe the issue

Hello,
The problem occurred when I changed several lines in the resource bundle file; after merging to git, the new value was not synchronized into Weblate. I've also tried to rescan the repo, but I receive a server error like the one uploaded in the screenshot.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1. Go to manage 
2. Choose repository maintenance 
3. Click on Rescan

### Expected behavior

All of the change in resource bundle files synced and updated into Weblate 

### Screenshots

Server error: 
![2024-04-29_08-11](https://github.com/WeblateOrg/weblate/assets/92735527/9e70722f-cadf-446e-b6ac-553faf9bab0e)

Current value in resource bundle file: 
![image](https://github.com/WeblateOrg/weblate/assets/92735527/5d7b727d-5b62-4bc3-907d-94bd31b02fac)

Actual value in Weblate
![image](https://github.com/WeblateOrg/weblate/assets/92735527/f7c6d2fd-acca-492b-913d-6b55a5ed2727)

### Exception traceback

```pytb
gunicorn stderr | Traceback (most recent call last):
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
gunicorn stderr |     return self.cursor.execute(sql, params)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
gunicorn stderr |     raise ex.with_traceback(None)
gunicorn stderr | psycopg.errors.InternalError_: unexpected data beyond EOF in block 1720 of relation base/16384/16594
gunicorn stderr | HINT:  This has been seen to occur with buggy kernels; consider updating your system.
gunicorn stderr | 
gunicorn stderr | The above exception was the direct cause of the following exception:
gunicorn stderr | 
gunicorn stderr | Traceback (most recent call last):
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
gunicorn stderr |     response = get_response(request)
gunicorn stderr |                ^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
gunicorn stderr |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
gunicorn stderr |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
gunicorn stderr |     return view_func(request, *args, **kwargs)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/views/decorators/http.py", line 43, in inner
gunicorn stderr |     return func(request, *args, **kwargs)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/weblate/trans/views/git.py", line 124, in file_scan
gunicorn stderr |     return execute_locked(
gunicorn stderr |            ^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/weblate/trans/views/git.py", line 21, in execute_locked
gunicorn stderr |     result = call(*args, **kwargs)
gunicorn stderr |              ^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/weblate/trans/models/component.py", line 194, in on_link_wrapper
gunicorn stderr |     return getattr(linked, func.__name__)(*args, **kwargs)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/weblate/trans/models/component.py", line 195, in on_link_wrapper
gunicorn stderr |     return func(self, *args, **kwargs)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/usr/local/lib/python3.12/contextlib.py", line 81, in inner
gunicorn stderr |     return func(*args, **kwds)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/weblate/trans/models/component.py", line 1882, in do_file_scan
gunicorn stderr |     return self.create_translations(request=request)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/weblate/trans/models/component.py", line 2309, in create_translations
gunicorn stderr |     return self._create_translations(
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/weblate/trans/models/component.py", line 2483, in _create_translations
gunicorn stderr |     was_change |= component.create_translations(
gunicorn stderr |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/weblate/trans/models/component.py", line 2309, in create_translations
gunicorn stderr |     return self._create_translations(
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/weblate/trans/models/component.py", line 2428, in _create_translations
gunicorn stderr |     translation = Translation.objects.check_sync(
gunicorn stderr |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/weblate/trans/models/translation.py", line 84, in check_sync
gunicorn stderr |     translation.check_sync(force, request=request, change=change)
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/weblate/trans/models/translation.py", line 479, in check_sync
gunicorn stderr |     self.store_update_changes()
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/weblate/trans/models/translation.py", line 491, in store_update_changes
gunicorn stderr |     Change.objects.bulk_create(self.update_changes, batch_size=500)
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
gunicorn stderr |     return getattr(self.get_queryset(), name)(*args, **kwargs)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/weblate/trans/models/change.py", line 173, in bulk_create
gunicorn stderr |     changes = super().bulk_create(*args, **kwargs)
gunicorn stderr |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/db/models/query.py", line 803, in bulk_create
gunicorn stderr |     returned_columns = self._batched_insert(
gunicorn stderr |                        ^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1831, in _batched_insert
gunicorn stderr |     self._insert(
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1805, in _insert
gunicorn stderr |     return query.get_compiler(using=using).execute_sql(returning_fields)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
gunicorn stderr |     cursor.execute(sql, params)
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
gunicorn stderr |     return self._execute_with_wrappers(
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
gunicorn stderr |     return executor(sql, params, many, context)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
gunicorn stderr |     with self.db.wrap_database_errors:
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
gunicorn stderr |     raise dj_exc_value.with_traceback(traceback) from exc_value
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
gunicorn stderr |     return self.cursor.execute(sql, params)
gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gunicorn stderr |   File "/app/venv/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute
gunicorn stderr |     raise ex.with_traceback(None)
gunicorn stderr | django.db.utils.InternalError: unexpected data beyond EOF in block 1720 of relation base/16384/16594
gunicorn stderr | HINT:  This has been seen to occur with buggy kernels; consider updating your system.
```

### How do you run Weblate?

Docker container

### Weblate versions

5.4.3

**Comment by nijel** [comment]
This is a PostgreSQL error. Either your database files got corrupted or it is the kernel bug as described in the error message.

**Comment by dngduy132** [comment]
> This is a PostgreSQL error. Either your database files got corrupted or it is the kernel bug as described in the error message.

Thank @nijel for the information; I will recheck the database. But do you know why the new value didn't sync to Weblate? Currently, all of my updates aren't being applied to Weblate, and I'm unsure how to fix this.

**Comment by nijel** [comment]
If the parsing fails due to the database error, it can not update the database.
