### ISSUE TITLE
Properly report errors in background updates

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1233]
I got a report that Weblate online editor and po files inside https://l10n.opensuse.org/projects/skelcd-opensuse/master/ don't match the repository.

And indeed, there is an inconsistency. But Weblate reports that everything is OK:

The local repository is up to date.

Last remote commit: 7dfe5fb
Repository details

On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean

Everything is reported OK.

Even, for example https://l10n.opensuse.org/projects/skelcd-opensuse/master/cs/ Download pot file returns correct file, that:
license.cs.po: 8 translated messages, 1 fuzzy translation, 1 untranslated message.
But Weblate says:
10 strings  100% translated
## Steps to reproduce
1. Unknown conditions
2. Repository maintenance -> Reset
3. Go to https://l10n.opensuse.org/projects/skelcd-opensuse/master/cs/, download file, check the file online
### Actual behaviour

Inconsistencies
### Expected behaviour

Consistent behavior
### Server configuration
- Weblate 2.6
- Python 2.7.9
- Django 1.8.4
- six 1.9.0
- python-social-auth 0.2.7
- Translate Toolkit 1.14.0-rc1
- Whoosh 2.7.0
- Git 1.8.5.6
- Pillow (PIL) 1.1.7
- dateutil 2.4.2
- lxml 3.2.3
- django-crispy-forms 1.5.2
- compressor 1.5
- djangorestframework 3.3.3
- pytz 2013.9
- pyuca N/A
- Database backends: django.db.backends.mysql
##

**Comment by nijel** [comment]
Does the inconsistencies stay even if you run ```./manage.py loadpo skelcd-opensuse/master```?

**Comment by stanislav-brabec** [comment]
It fails:

INFO skelcd-opensuse/master: checking license/license.ar.po (ar) [1/17]
INFO skelcd-opensuse/master: checking license/license.cs.po (cs) [2/17]
INFO skelcd-opensuse/master/cs: processing license/license.cs.po, revision has changed
INFO sending notification new_string on skelcd-openSUSE/master - Czech to @@mail removed@@
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/usr/share/weblate/weblate/trans/management/commands/loadpo.py", line 42, in handle
    subproject.create_translations(options['force'], langs)
  File "/usr/share/weblate/weblate/trans/models/subproject.py", line 1002, in create_translations
    self, lang, code, path, force, request=request
  File "/usr/share/weblate/weblate/trans/models/translation.py", line 70, in check_sync
    translation.check_sync(force, request=request)
  File "/usr/share/weblate/weblate/trans/models/translation.py", line 529, in check_sync
    notify_new_string(self)
  File "/usr/share/weblate/weblate/accounts/models.py", line 177, in notify_new_string
    send_mails(mails)
  File "/usr/share/weblate/weblate/accounts/models.py", line 62, in send_mails
    [mail for mail in mails if mail is not None]
  File "/usr/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
    new_conn_created = self.open()
  File "/usr/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 58, in open
    self.connection = connection_class(self.host, self.port, **connection_params)
  File "/usr/lib64/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib64/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib64/python2.7/smtplib.py", line 291, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 111] Connection refused

**Comment by stanislav-brabec** [comment]
Note:
It looks like a stuck postfix on the server. postfix restart fixes the problem.

**Comment by nijel** [comment]
Okay, now I understand what went wrong - the background update from hooks as silently failed without anybody noticing. This is really something what should be addressed as such errors should be caught.

What might help is using some error collection service such as [Sentry](https://sentry.io/) or [Rollbar](https://rollbar.com/). Weblate has built in support for Rollbar, see https://docs.weblate.org/en/latest/admin/install.html#collecting-error-reports

PS: Implementation of background sending of mails would help in this case as well, see #492.

**Comment by burner1024** [comment]
+1 on hooks. At least a basic email notification would be nice when they fail.
Also, ideally manage.py should return non-zero exit code when any action fails, as per POSIX convention.

**Comment by nijel** [comment]
In case manage.py does not return with error on failure, please open separate issue for that, thanks!

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
