### ISSUE TITLE
Error during template rendering

### ISSUE THREAD

**Issue by antonin-kozak** [WeblateOrg/weblate#12472]
### Describe the issue

Hi, after changing a component settings, the component page rendering is broken giving me error:
```

Error during template rendering

Environment:


Request Method: GET
Request URL: http://***/projects/backend/develop/core/

Django Version: 5.0.8
Python Version: 3.11.2
Installed Applications:
['weblate.addons',
 'weblate.auth',
 'weblate.checks',
 'weblate.formats',
 'weblate.glossary',
 'weblate.machinery',
 'weblate.trans',
 'weblate.lang',
 'weblate_language_data',
 'weblate.memory',
 'weblate.screenshots',
 'weblate.fonts',
 'weblate.accounts',
 'weblate.configuration',
 'weblate.utils',
 'weblate.vcs',
 'weblate.wladmin',
 'weblate.metrics',
 'weblate',
 'weblate.gitexport',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin.apps.SimpleAdminConfig',
 'django.contrib.admindocs',
 'django.contrib.sitemaps',
 'django.contrib.humanize',
 'social_django',
 'crispy_forms',
 'crispy_bootstrap3',
 'compressor',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters',
 'django_celery_beat',
 'corsheaders']
Installed Middleware:
['weblate.middleware.RedirectMiddleware',
 'weblate.middleware.ProxyMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'weblate.accounts.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'weblate.accounts.middleware.RequireLoginMiddleware',
 'weblate.api.middleware.ThrottlingMiddleware',
 'weblate.middleware.SecurityMiddleware',
 'weblate.wladmin.middleware.ManageMiddleware']


Template error:
In template /home/weblate/weblate-env/lib/python3.11/site-packages/weblate/templates/component.html, error at line 132
   UnsupportedConfiguration.__init__() missing 2 required positional arguments: 'vcs' and 'file_format'
   122 : 
   123 : {% include "snippets/list-objects.html" with objects=translations name_source="language" label=_("Language") is_glossary=object.is_glossary add_link="translation" %}
   124 : 
   125 : </div>
   126 : 
   127 : <div class="tab-pane" id="alerts">
   128 : {% if user.is_authenticated %}
   129 : {% for alert in alerts %}
   130 : <div class="panel panel-default">
   131 : <div class="panel-heading">
   132 :    {% if alert.obj.doc_page %} 
   133 :     {% documentation_icon alert.obj.doc_page alert.obj.doc_anchor right=True %}
   134 :   {% endif %}
   135 :   {{ alert }}
   136 :   {% if alert.dismissed %}
   137 :     <span class="badge">{% trans "dismissed" %}</span>
   138 :   {% endif %}
   139 : </div>
   140 : <div class="panel-body">{% render_alert alert %}</div>
   141 : <form action="{% url "dismiss-alert" path=object.get_url_path %}" method="post">
   142 : <div class="panel-footer">


Traceback (most recent call last):
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/base.py", line 875, in _resolve_lookup
    current = current[bit]
              ^^^^^^^^^^^^

During handling of the above exception ('Alert' object is not subscriptable), another exception occurred:
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/weblate/trans/views/basic.py", line 213, in show
    return show_component(request, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/weblate/trans/views/basic.py", line 548, in show_component
    return render(
           
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/weblate/trans/util.py", line 247, in render
    return django.shortcuts.render(
           
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/defaulttags.py", line 319, in render
    match = condition.eval(context)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/defaulttags.py", line 885, in eval
    return self.value.resolve(context, ignore_failures=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/base.py", line 710, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/django/utils/functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/weblate/weblate-env/lib/python3.11/site-packages/weblate/trans/models/alert.py", line 91, in obj
    return ALERTS[self.name](self, **self.details)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: TypeError at /projects/backend/develop/core/
Exception Value: UnsupportedConfiguration.__init__() missing 2 required positional arguments: 'vcs' and 'file_format'

```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

1) Having a component with Github pull requests
2) Changing component setting of `Merge style`
3) Go to back to component detail

### How do you run Weblate?

Other

**Comment by nijel** [comment]
Your component uses a file format or version control that is no longer supported in your Weblate. And there is bug in handling that alert.

**Comment by gierschv** [comment]
Got the same bug this morning, opening directly the settings URL and just saving the component without changing the settings fixed this broken alert.

**Comment by antonin-kozak** [comment]
@nijel Thank you for the quick response and the fix.
However, we have tried to apply your fix into our instance, but it doesn't help.

(I don't know Python, but it surprises me that the fix is in the static function when the error message suggests me the problem is in calling the __init__ constructor.)

**Comment by nijel** [comment]
The fix fixes how the alert is triggered, thus will fix the rendering then. But if the falsely triggered alert is already there, the crash will still happen.

Review version control and file format settings, most likely there is an option which is no longer available.
