### ISSUE TITLE
setter for user `DUMMY_FIELDS` not available for django `get_or_create()`

### ISSUE THREAD

**Issue by JanMalte** [WeblateOrg/weblate#12700]
### Describe the issue

The setter method used for the `DUMMY_FIELDS` for `first_name` and `last_name` in the `weblate.auth.models.User` is not working with the `django` internal `get_or_create()` `defaults` parameter.

A `FieldError` exception is raised if one of those fields is provides as `defaults`.

```
FieldError at /accounts/login/

Invalid field name(s) for model User: 'first_name', 'last_name'.
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

This can be reproduced in a simple django python shell (`python src/manage.py shell`):

```python
from django.contrib.auth import get_user_model
User = get_user_model()
User.objects.get_or_create(username='test', defaults={'first_name': 'Test'})
```

### Expected behavior

A user is created and the `full_name` is set to `Test`

### Exception traceback

```pytb
Traceback (most recent call last):
  File "/Users/maltegerth/.local/share/poetry/virtualenvs/moll-translate-QA9TMEcw-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 916, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "/Users/maltegerth/.local/share/poetry/virtualenvs/moll-translate-QA9TMEcw-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
weblate.auth.models.User.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/maltegerth/.local/share/poetry/virtualenvs/moll-translate-QA9TMEcw-py3.11/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maltegerth/.local/share/poetry/virtualenvs/moll-translate-QA9TMEcw-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 918, in get_or_create
    params = self._extract_model_params(defaults, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maltegerth/.local/share/poetry/virtualenvs/moll-translate-QA9TMEcw-py3.11/lib/python3.11/site-packages/django/db/models/query.py", line 999, in _extract_model_params
    raise exceptions.FieldError(
django.core.exceptions.FieldError: Invalid field name(s) for model User: 'first_name'.
```

### How do you run Weblate?

Other

### Weblate versions

 * Weblate: 5.4.3
 * Django: 4.2.16

**Comment by nijel** [comment]
This is currently supported only for LDAP which passes attributes via `extra_data`. Adding support for other authentication backends is certainly possible.

**Comment by JezFirth** [comment]
Currently having a look at this

**Comment by Fjtg** [comment]
having a look
