### ISSUE TITLE
Migrating 2.2. to latest (2.10): relation "django_content_type" already exists

### ISSUE THREAD

**Issue by romanr** [WeblateOrg/weblate#1300]
### Actual behaviour
```
./manage.py migrate
System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.
Operations to perform:
  Apply all migrations: accounts, admin, auth, authtoken, contenttypes, lang, sessions, sites, social_auth, trans
Running migrations:
  Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/models.py", line 96, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 295, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 112, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "django_content_type" already exists
```

### Server configuration
```
./manage.py list_versions
System check identified some issues:

WARNINGS:
?: (1_8.W001) The standalone TEMPLATE_* settings were deprecated in Django 1.8 and the TEMPLATES dictionary takes precedence. You must put the values of the following settings into your default TEMPLATES dict: TEMPLATE_DEBUG.
 * Weblate weblate-2.10-29-g482e794
 * Python 2.7.3
 * Django 1.10.4
 * six 1.10.0
 * python-social-auth 0.2.21
 * Translate Toolkit 2.0.0b7
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 1.9.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.7.0
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.3
 * pytz 2014.10
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.10
 * Mercurial 3.2.2
 * Database backends: django.db.backends.postgresql_psycopg
```

How can I fix this situation? Thank you!

**Comment by nijel** [comment]
Adjust `settings.py` to match `settings_example.py` shipped with Weblate. As you're skipping quite a lot of versions (and upgrading Django as well), there will be many changes.

**Comment by nijel** [comment]
Also you're probably upgrading from Django older than 1.7, this is covered in [our documentation](https://docs.weblate.org/en/latest/admin/upgrade.html#django-17).

**Comment by romanr** [comment]
Thank you for the answer.

There is no `examples/migrate-south`. No `examples` in old version 2.2 either.

Also what does it mean "you can do this using virtualenv" - Should I downgrade to Django 1.6 first to do any of mentioned?

**Comment by romanr** [comment]
Used virtualenv and found the migrate-south in version 2.2.
running `examples/migrate-south` results in: `Unknown command: 'migrate'`

```
(django1.6)/weblate > examples/migrate-south --settings weblate.settings
New python executable in /tmp/tmp.0cltfohKaa/bin/python
Installing setuptools, pip...done.
Downloading/unpacking Django>=1.6,<1.7
  Downloading Django-1.6.11-py2.py3-none-any.whl (6.7MB): 6.7MB downloaded
Installing collected packages: Django
  Found existing installation: Django 1.10.4
    Not uninstalling Django at /usr/local/lib/python2.7/dist-packages, outside environment /tmp/tmp.0cltfohKaa
Successfully installed Django
Cleaning up...
Requirement already satisfied (use --upgrade to upgrade): south in /usr/local/lib/python2.7/dist-packages
Cleaning up...
Unknown command: 'migrate'
Type 'django-admin.py help' for usage.
```

**Comment by nijel** [comment]
Can you temporary remove system installed Django? It seems that the upgrade script does not properly handle this situation.

And yes, the upgrade script was present till 2.2 as newer Weblate versions are not compatible with old Django which is needed for the migration (I've documented this in f9b330d2a4357b9f61d6569b78a97ec8fa6267de).

**Comment by romanr** [comment]
Removed system python, getting exactly same output. `Unknown command: 'migrate'`

Django version is 1.6.11:

```
$ python
Python 2.7.3 (default, Jun 21 2016, 18:38:19)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import django
>>> django.get_version()
'1.6.11'
>>>
```

I am starting to think maybe I will be better installing with new database from scratch.

**Comment by nijel** [comment]
Are you using settings from 2.2 as well for the migration? It did have additional logic for that, see https://github.com/WeblateOrg/weblate/commit/e47adb71603e65355ca5aa7f21afcd76889f8856#diff-2b41b1c1bb3be7733aa2ed75c4a8e053

Unfortunately the migration from South to Django native migration was quite painful, but there was no other way forward.

**Comment by romanr** [comment]
Thank you for answers. This is a great software. I will do the clean install.
