### ISSUE TITLE
Migration to split social

### ISSUE THREAD

**Issue by dorantor** [WeblateOrg/weblate#1307]
### Steps to reproduce
1. New minimal Debian 8.6
2. Most dependencies installed via upgraded(because of `requests`) pip
3. Current versions:
```
$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
Babel (1.3)
beautifulsoup4 (4.3.2)
chardet (2.3.0)
defusedxml (0.4.1)
diff-match-patch (20121119)
Django (1.10.4)
django-appconf (1.0.2)
django-compressor (2.1)
django-crispy-forms (1.6.1)
djangorestframework (3.5.3)
future (0.16.0)
iniparse (0.4)
lxml (3.4.0)
mercurial (3.1.2)
oauthlib (2.0.1)
Pillow (3.4.2)
pip (9.0.1)
psycopg2 (2.5.4)
pycryptodomex (3.4.3)
pyenchant (1.6.6)
pyinotify (0.9.4)
pyjwkest (1.3.2)
PyJWT (1.4.2)
python-dateutil (2.2)
python-Levenshtein (0.11.2)
python-openid (2.2.5)
python-social-auth (0.3.1)
pytz (2012rc0)
rcssmin (1.0.6)
requests (2.12.4)
requests-oauthlib (0.7.0)
rjsmin (1.0.12)
setuptools (5.5.1)
simplejson (3.6.5)
six (1.10.0)
social-auth-app-django (0.1.0)
social-auth-core (0.1.0)
translate-toolkit (2.0.0b7)
uTidylib (0.2)
vobject (0.8.1rc0)
Whoosh (2.7.4)
```
4. Got weblate using `git clone https://github.com/WeblateOrg/weblate.git`

### Actual behaviour
```
$ ./manage.py check
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/check.py", line 68, in handle
    fail_level=getattr(checks, options['fail_level']),
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/weblate/weblate/weblate/urls.py", line 34, in <module>
    import weblate.accounts.views
  File "/home/weblate/weblate/weblate/accounts/views.py", line 45, in <module>
    from social.apps.django_app.utils import BACKENDS
  File "/usr/local/lib/python2.7/dist-packages/social/apps/django_app/utils.py", line 1, in <module>
    from social_django.utils import load_strategy, load_backend, psa, setting, BackendWrapper, strategy
ImportError: cannot import name strategy
```

### Expected behaviour
```
$ ./manage.py check
System check identified no issues (0 silenced).
```

### Server configuration
```
$ ./manage.py list_versions
 * Weblate weblate-2.10-73-g81be89e
 * Python 2.7.9
 * Django 1.10.4
 * six 1.10.0
 * python-social-auth 0.3.1
 * Translate Toolkit 2.0.0b7
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.2
 * lxml 3.4.0
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.3
 * pytz 2012c
 * Mercurial 3.1.2
 * Database backends: django.db.backends.postgresql_psycopg2
```

### Fix
Please pay attention to PSA version: 0.3.1. Library is being refactored and introduced some "breaking" [changes](https://github.com/omab/python-social-auth/blob/master/MIGRATING_TO_SOCIAL.md#django)
I'm trying to make it run for a second day already, so I manually did required fixes(no tests and examples, sorry):
```
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Changes not staged for commit:

	modified:   weblate/accounts/auth.py
	modified:   weblate/accounts/models.py
	modified:   weblate/accounts/pipeline.py
	modified:   weblate/accounts/views.py
```
And full list of changes:
```
$ git diff --patch
diff --git a/weblate/accounts/auth.py b/weblate/accounts/auth.py
index 06fd6b6..d9ff635 100644
--- a/weblate/accounts/auth.py
+++ b/weblate/accounts/auth.py
@@ -28,15 +28,15 @@ from django.dispatch.dispatcher import receiver
 from django.utils.translation import ugettext as _
 from django.contrib.auth.backends import ModelBackend
 
-import social.backends.email
-from social.exceptions import AuthMissingParameter
+import social_core.backends.email
+from social_core.exceptions import AuthMissingParameter
 
 from weblate.appsettings import ANONYMOUS_USER_NAME
 from weblate.trans import messages
 from weblate.utils.errors import report_error
 
 
-class EmailAuth(social.backends.email.EmailAuth):
+class EmailAuth(social_core.backends.email.EmailAuth):
     """Social auth handler to better report errors."""
     def auth_complete(self, *args, **kwargs):
         try:
diff --git a/weblate/accounts/models.py b/weblate/accounts/models.py
index c578b31..9b83bab 100644
--- a/weblate/accounts/models.py
+++ b/weblate/accounts/models.py
@@ -40,7 +40,7 @@ from django.utils.translation import LANGUAGE_SESSION_KEY
 
 from rest_framework.authtoken.models import Token
 
-from social.apps.django_app.default.models import UserSocialAuth
+from social_django.models import UserSocialAuth
 
 from weblate.lang.models import Language
 from weblate.trans import messages
diff --git a/weblate/accounts/pipeline.py b/weblate/accounts/pipeline.py
index ad0b2df..113a0f1 100644
--- a/weblate/accounts/pipeline.py
+++ b/weblate/accounts/pipeline.py
@@ -29,8 +29,8 @@ from django.utils.translation import ugettext as _
 
 from six.moves.urllib.request import Request, urlopen
 
-from social.pipeline.partial import partial
-from social.exceptions import (
+from social_core.pipeline.partial import partial
+from social_core.exceptions import (
     AuthException, AuthMissingParameter, AuthAlreadyAssociated
 )
 
diff --git a/weblate/accounts/views.py b/weblate/accounts/views.py
index 31ce248..ab1c3dd 100644
--- a/weblate/accounts/views.py
+++ b/weblate/accounts/views.py
@@ -41,9 +41,9 @@ from rest_framework.authtoken.models import Token
 
 from six.moves.urllib.parse import urlencode
 
-from social.backends.utils import load_backends
-from social.apps.django_app.utils import BACKENDS
-from social.apps.django_app.views import complete
+from social_core.backends.utils import load_backends
+from social_django.utils import BACKENDS
+from social_django.views import complete
 
 from weblate.accounts.forms import (
     RegistrationForm, PasswordForm, PasswordChangeForm, EmailForm, ResetForm,
```

Nothing special, as you can see. With this changes I managed to get expected result.

Sorry for a long "post", just wanted to provide all info that might be useful :)

**Comment by dorantor** [comment]
And migrations still failing, even with my fixes:
```
$ ./manage.py migrate
Operations to perform:
  Apply all migrations: accounts, admin, auth, authtoken, contenttypes, lang, sessions, sites, social_django, trans
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying authtoken.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying lang.0001_initial... OK
  Applying trans.0001_initial... OK
  Applying trans.0002_auto_20141021_1347... OK
  Applying trans.0003_auto_20141021_1348... OK
  Applying trans.0004_auto_20141021_1550... OK
  Applying trans.0005_auto_20141021_1550... OK
  Applying trans.0006_auto_20141021_1609... OK
  Applying trans.0007_auto_20141022_1159... OK
  Applying trans.0008_auto_20141104_1200... OK
  Applying trans.0009_auto_20141110_1501... OK
  Applying trans.0010_source_check_flags... OK
  Applying trans.0011_auto_20141114_1008... OK
  Applying trans.0012_translation_have_comment... OK
  Applying trans.0013_auto_20141124_1036... OK
  Applying trans.0014_auto_20141202_1101... OK
  Applying trans.0015_auto_20141203_1345... OK
  Applying trans.0016_auto_20141208_1029... OK
  Applying trans.0017_auto_20150108_1424... OK
  Applying trans.0018_auto_20150213_1447... OK
  Applying trans.0019_auto_20150220_1354... OK
  Applying trans.0020_auto_20150220_1356... OK
  Applying trans.0021_auto_20150306_1605... OK
  Applying trans.0022_auto_20150309_0932... OK
  Applying trans.0023_project_owner... OK
  Applying trans.0024_subproject_edit_template... OK
  Applying trans.0025_subproject_post_update_script... OK
  Applying trans.0026_auto_20150401_1029... OK
  Applying trans.0027_auto_20150401_1030... OK
  Applying trans.0028_auto_20150402_1430... OK
  Applying trans.0029_auto_20150415_1318... OK
  Applying trans.0030_change_subproject... OK
  Applying trans.0031_auto_20150415_1339... OK
  Applying trans.0032_subproject_agreement... OK
  Applying trans.0033_auto_20150618_1138... OK
  Applying trans.0034_auto_20150618_1140... OK
  Applying trans.0035_auto_20150630_1208... OK
  Applying trans.0036_auto_20150709_1005... OK
  Applying trans.0037_auto_20150810_1348... OK
  Applying trans.0038_auto_20150810_1354... OK
  Applying trans.0039_remove_project_owner... OK
  Applying trans.0040_auto_20150818_1643... OK
  Applying trans.0041_auto_20150819_1457... OK
  Applying trans.0042_auto_20150910_0854... OK
  Applying trans.0043_auto_20150910_0909... OK
  Applying trans.0044_auto_20150916_0952... OK
  Applying trans.0045_auto_20150916_1007... OK
  Applying trans.0046_auto_20151111_1456... OK
  Applying lang.0002_auto_20150630_1208... OK
  Applying trans.0047_project_source_language... OK
  Applying trans.0048_auto_20151120_1306... OK
  Applying trans.0049_auto_20151222_0949... OK
  Applying trans.0050_auto_20151222_1006... OK
  Applying trans.0051_auto_20151222_1059... OK
  Applying trans.0052_install_group_acl... OK
  Applying trans.0053_auto_20160202_1145... OK
  Applying trans.0054_auto_20160202_1219... OK
  Applying trans.0055_auto_20160202_1221... OK
  Applying trans.0056_auto_20160202_1224... OK
  Applying trans.0057_indexupdate_language_code... OK
  Applying trans.0058_componentlist... OK
  Applying social_django.0001_initial... OK
  Applying accounts.0001_initial...Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/models.py", line 96, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 246, in create_model
    definition, extra_params = self.column_sql(model, field)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 136, in column_sql
    db_params = field.db_parameters(connection=self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 940, in db_parameters
    return {"type": self.db_type(connection), "check": self.db_check(connection)}
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 937, in db_type
    return self.target_field.rel_db_type(connection=connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 855, in target_field
    return self.foreign_related_fields[0]
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 595, in foreign_related_fields
    return tuple(rhs_field for lhs_field, rhs_field in self.related_fields if rhs_field)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 582, in related_fields
    self._related_fields = self.resolve_related_fields()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/related.py", line 567, in resolve_related_fields
    raise ValueError('Related model %r cannot be resolved' % self.remote_field.model)
ValueError: Related model u'default.UserSocialAuth' cannot be resolved
```

**Comment by dorantor** [comment]
Added one more fix to `weblate/accounts/migrations/0001_initial.py` that helped to run migration:
```
# App label has been changed in python-social-auth 0.2.20
if 'social_auth' in apps.app_configs:
    SOCIAL_AUTH = 'social_auth'
elif 'social_django' in apps.app_configs:
    SOCIAL_AUTH = 'social_django'
else:
    SOCIAL_AUTH = 'default'
```
But I'm sure it's ugly, because with 0.2.21 current version of Django cannot work anyway(at least not in my hands).

**Comment by dorantor** [comment]
Not fully related, but in order to run `./manage.py compilemessages --settings=weblate.settings_test` I had to add `social_django` to list of INSTALLED_APPS in  `weblate/settings_test.py` and delete all(?) 
```
#| msgctxt "No known user"
```
strings from `weblate/locale/*/LC_MESSAGES/django.po` files. And `rm -rf weblate/locale/he/`, because it's broken beyond my ability to fix it.

**Comment by nijel** [comment]
The po files are already fixed in master.

The easiest fix for social auth is to use version older than 0.3.0, I've adjusted requirements to match that in a31bf3bac09487d550fd07b4fd24c531eb028d20. Proper fix to make Weblate work with newer version will follow later.

**Comment by nijel** [comment]
Actually there are more changes going on in the (former) python-social-auth: https://github.com/omab/python-social-auth/blob/master/MIGRATING_TO_SOCIAL.md

**Comment by dorantor** [comment]
@nijel, that's what I did in order to run Weblate. I had to do few more fixes(full PATCH):
https://gist.github.com/dorantor/aeb26ab0f8d8d394cdc04ff22f1dd9df

Also I had problems with pre 0.3.0 version. As far as I remember, it was not working with new version of Django. So I had to update it to most recent version. So I would recommend to test it with new Django and old psa. And changes required to make it work with new psa seems trivial to me ;)

Anyway, it's finally working for me and I'm going to freeze my installation :)) I hope that my comments will be useful for project.

**Comment by nijel** [comment]
Some old 0.2 indeed will not work with current Django, but recent ones do work just fine.

Thanks for the patch, if you can turn it into pull request, it can be probably merged (+ changing the requirements to 0.3 and add social_django).

**Comment by dorantor** [comment]
It will take some time, but I think I can do it. I'm concerned that I will not be able to do a proper testing, because I'm not very familiar with Django. The only thing I can say here is that "it works for me".

**Comment by nijel** [comment]
The good indication is that testsuite passes :-). It doesn't not cover everything, but it does the most usual scenarios. See https://docs.weblate.org/en/latest/contributing.html#testsuite for docs.

**Comment by nijel** [comment]
This is being fixed in the `next` branch, I'm still not sure if this will be part of 2.11, which will be released next week or not as this is quite invasive change quite late in the release cycle.

**Comment by nijel** [comment]
Also there is migration issue in current social auth: https://github.com/python-social-auth/social-app-django/issues/16

**Comment by nijel** [comment]
Okay, the `next` branch should work just fine with new social modules. I will merge it to `master` once the migration issue is fixed and released in social-app-django, so that we can depend on fixed version.
