### ISSUE TITLE
Can't import component from VCS - context must be a dict rather than DiscoveryResult

### ISSUE THREAD

**Issue by dpaleino** [WeblateOrg/weblate#13118]
### Describe the issue

Trying to import any component from VCS, yields a TypeError in Django, specifically:
`context must be a dict rather than DiscoveryResult`.

I tried with two different repositories (Android AOSP and Firefox-L10N), and it first scans the repository, then fails with this error.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar filed issues in this repository.

### Steps to reproduce the behavior

Created a project, trying to add a component from VCS.

Tried using:
- component name: browser/branding/official/brand.ftl
- URL slug: browserbrandingofficialbrand-ftl
- repository URL: https://github.com/mozilla-l10n/firefox-l10n.git
- repository branch: main

### Screenshots

![immagine](https://github.com/user-attachments/assets/18be6b1e-2a06-408e-8e0e-1d0bb8c25259)

### Exception traceback

```pytb
Traceback (most recent call last):
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/weblate/trans/views/create.py", line 383, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 182, in post
    return super().post(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 151, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/weblate/trans/views/create.py", line 308, in form_valid
    return self.get(self.request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 178, in get
    return super().get(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 142, in get
    return self.render_to_response(self.get_context_data())
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/weblate/trans/views/create.py", line 331, in get_context_data
    kwargs = super().get_context_data(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 72, in get_context_data
    kwargs["form"] = self.get_form()
                     ^^^^^^^^^^^^^^^
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/weblate/trans/views/create.py", line 312, in get_form
    form = super().get_form(form_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/django/views/generic/edit.py", line 37, in get_form
    return form_class(**self.get_form_kwargs())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/weblate/trans/forms.py", line 1972, in __init__
    (i, self.render_choice(value)) for i, value in enumerate(self.discovered)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/weblate/trans/forms.py", line 1958, in render_choice
    return render_to_string("trans/discover-choice.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 103, in render
    context = make_context(
              
  File "/home/cademia/weblate/venv/lib/python3.12/site-packages/django/template/context.py", line 288, in make_context
    raise TypeError(
    ^

Exception Type: TypeError at /create/component/vcs/
Exception Value: context must be a dict rather than DiscoveryResult.
```

### How do you run Weblate?

PyPI module

### Weblate versions

 * Weblate: 5.8.3
 * Django: 5.1.3
 * siphashc: 2.5
 * translate-toolkit: 3.14.1
 * lxml: 5.3.0
 * pillow: 11.0.0
 * nh3: 0.2.18
 * python-dateutil: 2.9.0.post0
 * social-auth-core: 4.5.4
 * social-auth-app-django: 5.4.2
 * django-crispy-forms: 2.3
 * oauthlib: 3.2.2
 * django-compressor: 4.5.1
 * djangorestframework: 3.15.2
 * django-filter: 24.3
 * django-appconf: 1.0.6
 * user-agents: 2.2.0
 * filelock: 3.16.1
 * RapidFuzz: 3.10.1
 * openpyxl: 3.1.5
 * celery: 5.4.0
 * django-celery-beat: 2.7.0
 * kombu: 5.4.2
 * translation-finder: 2.18
 * weblate-language-data: 2024.14
 * html2text: 2024.2.26
 * pycairo: 1.27.0
 * PyGObject: 3.50.0
 * diff-match-patch: 20241021
 * requests: 2.32.3
 * django-redis: 5.4.0
 * hiredis: 3.0.0
 * sentry-sdk: 2.18.0
 * Cython: 3.0.11
 * mistletoe: 1.4.0
 * GitPython: 3.1.43
 * borgbackup: 1.4.0
 * pyparsing: 3.2.0
 * ahocorasick_rs: 0.22.1
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.4.0
 * cyrtranslit: 1.1.1
 * drf-spectacular: 0.27.2
 * Python: 3.12.7
 * Git: 2.43.0
 * phply: 1.2.6
 * ruamel.yaml: 0.18.6
 * tesserocr: 2.7.1
 * aeidon: 1.15
 * iniparse: 0.5
 * mysqlclient: 2.2.6
 * google-cloud-translate: 3.18.0
 * MariaDB sever: 11.4.3
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 6.6.8-amd64 (x86_64)

### Weblate deploy checks

```shell
www-data@pitre:/home/cademia/weblate$ weblate check --deploy
System check identified some issues:

WARNINGS:
?: (security.W018) You should not have DEBUG set to True in deployment.
?: (weblate.W039.AlibabaTranslation) Error importing module 'weblate.machinery.alibaba' in WEBLATE_MACHINERY: No module named 'aliyunsdkalimt'
	HINT: https://docs.weblate.org/en/weblate-5.8.3/admin/machine.html

INFOS:
?: (weblate.E006) Weblate performs best with PostgreSQL, consider migrating to it.
	HINT: https://docs.weblate.org/en/weblate-5.8.3/admin/install.html#production-database
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-5.8.3/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-5.8.3/admin/backup.html
?: (weblate.I031) New Weblate version is available, please upgrade to 5.8.4.
	HINT: https://docs.weblate.org/en/weblate-5.8.3/admin/upgrade.html

System check identified 6 issues (11 silenced).
```

**Comment by nijel** [comment]
Upgrade Weblate or downgrade translation-finder. There was unintended API change in the library.

**Comment by nijel** [comment]
This was fixed in 952ea09ac620da49a5bd4b4bdf7a16820ebc89e8.
