### ISSUE TITLE
Openshift installation fails because of outdated git

### ISSUE THREAD

**Issue by AngryLoki** [WeblateOrg/weblate#1311]
Running installation via rhc fails after d0f82f7a713fa834315201f1063d8d17093a4020 with following traceback:

```
python ~/app-root/runtime/repo//openshift/manage.py migrate --noinput
*** Git <https://git-scm.com/> is too old! ***
Installed version 1.8.2.1, required 1.8.5
Traceback (most recent call last):
  File "/var/lib/openshift/586eb34089f5cfc12200013a//app-root/runtime/repo//openshift/manage.py", line 33, in <module>
    execute_from_command_line(sys.argv)
  File "/var/lib/openshift/586eb34089f5cfc12200013a/python/virtenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/var/lib/openshift/586eb34089f5cfc12200013a/python/virtenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/var/lib/openshift/586eb34089f5cfc12200013a/python/virtenv/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/var/lib/openshift/586eb34089f5cfc12200013a/python/virtenv/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/var/lib/openshift/586eb34089f5cfc12200013a/python/virtenv/lib/python2.7/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/opt/rh/python27/root/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/lib/openshift/586eb34089f5cfc12200013a/app-root/runtime/repo/weblate/__init__.py", line 104, in <module>
    check_requirements()
  File "/var/lib/openshift/586eb34089f5cfc12200013a/app-root/runtime/repo/weblate/requirements.py", line 306, in check_requirements
    'Some of required modules are missing or too old! '
Exception: Some of required modules are missing or too old! Check above output for details.
```

**Comment by nijel** [comment]
The requirement has been raised here: https://github.com/WeblateOrg/weblate/issues/1299#issuecomment-270357904

Not sure if it's really necessary or it was bug affecting just that version...
