### ISSUE TITLE
HEAD does not point to a branch

### ISSUE THREAD

**Issue by AlexMost** [WeblateOrg/weblate#1325]
### Steps to reproduce
1. Create project (uaprom), and component (uaprom-backend) (disable auto lock)
2. Two translators were adding translations to the same component (but to different units)
3. Go to component url /projects/uaprom/uaprom-backend/uk/

### Actual behaviour
Must show component translation

### Expected behaviour
Throws django error while visiting url /projects/uaprom/uaprom-backend/uk/ 
```
RepositoryException at /projects/uaprom/uaprom-backend/uk/
fatal: HEAD does not point to a branch (128)
Request Method:	GET
Request URL:	http://weblate.dev-cluster.uaprom/projects/uaprom/uaprom-backend/uk/
Django Version:	1.10.5
Exception Type:	RepositoryException
Exception Value:	
fatal: HEAD does not point to a branch (128)
Exception Location:	/usr/lib/python3.5/site-packages/weblate/trans/vcs.py in _popen, line 188
Python Executable:	/usr/bin/python3
Python Version:	3.5.2
Python Path:	
['',
 '/app/config',
 '/usr/lib/python35.zip',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-linux',
 '/usr/lib/python3.5/lib-dynload',
 '/usr/lib/python3.5/site-packages']
Server time:	Ср, 18 Янв 2017 16:47:36 +0000
```
local vars:
```
args	
['git', 'log', '-n', '1', '--format=format:%H', '@{upstream}']
cls	
<class 'weblate.trans.vcs.GitRepository'>
cwd	
'/app/config/../data/vcs/uaprom/uaprom-backend'
err	
False
output	
b''
output_err	
b'fatal: HEAD does not point to a branch\n'
process	
<subprocess.Popen object at 0x7fce1c1a6518>
retcode	
128
```

### Server configuration
```
 * Weblate 2.10
 * Python 3.5.2
 * Django 1.10.5
 * six 1.10.0
 * python-social-auth 0.2.21
 * Translate Toolkit 2.0.0rc1
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.11.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.7.2
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.3
 * pytz 2016.10
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.0.1
 * Database backends: django.db.backends.postgresql_psycopg2
```

**Comment by nijel** [comment]
Are you able to replicate this? I'd be really curious to have testcase for this as there seems to be occasionally something wrong with the Git repo and even though there were numerous fixes, it still seems to happen.

See for example https://github.com/WeblateOrg/weblate/issues/1266 or https://github.com/WeblateOrg/weblate/issues/1299

BTW: What webserver do you use? It might be also related to way how Weblate is executed as I've never seen this on Hosted Weblate, which I'd say is big enough to see such corner cases :-).

**Comment by AlexMost** [comment]
I'm using werkzeug server

```python
from werkzeug.serving import BaseWSGIServer

def run_app(options):
    django.setup()
    app = WSGIHandler()

    wsgi = BaseWSGIServer(
        host=options.host,
        port=options.port,
        fd=options.fd if options.fd else None,
        app=app,
    )
```

Still doesn't work for me. Don't see any solution except 2 options:
1. Execute `git checkout master` inside component repository.
2. Delete component and create the new one.

But still it's really strange behavior, looking forward for some help.

**Comment by AlexMost** [comment]
```git checkout master``` helped to solve the problem. Also I was running weblate on 4 workers, reduced this number to 1. Seems like it's ok now.

**Comment by nijel** [comment]
The workers were separate processes or threads?

**Comment by AlexMost** [comment]
separate processes

**Comment by AlexMost** [comment]
still having this issue even with a single worker. For now there is only one way to fix it is to ssh to the server and execute `git checkout master` inside the components repository. Would be great to have an ability to fix this trouble without ssh. Maybe some cli command for wlc or some button 'Checkout' in the UI ?

**Comment by nijel** [comment]
I'd prefer to fix this rather than provide workaround in the UI. The checkout should have happened in the setup. It has to be something version dependent as I was not able to reproduce it on any system I have at hand.

Once you have this messed up repository, what is output of `git branch` there?

Also does it happen only on new projects or even during the translating?

**Comment by AlexMost** [comment]
have not checked `git branch`. If this problem will occur again will check it. This happens during translating. Agree, that it's better to fix that thing.

**Comment by nijel** [comment]
Also it would be great if you could apply 	2cb0035, enable logging of vcs commands (just comment out section added to the sample configuration) and post here vcs commands executed prior to failure.

**Comment by AlexMost** [comment]
Was using wlc cli to update translations, and have met this trouble again. No one was translating at that time, maybe hooks caused some kind of lock.

Here is `git branch` output:
```
$ git branch
* (detached from 86813e7)
  master
```

Here is the log from the server:
```
192.168.21.100 - - [30/Jan/2017 16:17:28] "POST /hooks/gitlab/ HTTP/1.1" 200 -
192.168.21.100 - - [30/Jan/2017 16:17:30] "POST /hooks/gitlab/ HTTP/1.1" 200 -
192.168.21.100 - - [30/Jan/2017 16:17:36] "POST /hooks/gitlab/ HTTP/1.1" 200 -
192.168.21.100 - - [30/Jan/2017 16:17:36] "GET /api/components/uaprom-vas/vas-frontend/ HTTP/1.1" 200 -
Exception in thread Thread-52:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/weblate/trans/models/subproject.py", line 705, in do_update
    self.commit_pending(request, skip_push=True)
  File "/usr/lib/python3.5/site-packages/weblate/trans/models/subproject.py", line 866, in commit_pending
    translation.commit_pending(request, skip_push=True)
  File "/usr/lib/python3.5/site-packages/weblate/trans/models/translation.py", line 673, in commit_pending
    request, last, self.last_change, True, True, skip_push
  File "/usr/lib/python3.5/site-packages/weblate/trans/models/translation.py", line 787, in git_commit
    self.__git_commit(author, timestamp, sync)
  File "/usr/lib/python3.5/site-packages/weblate/trans/models/translation.py", line 734, in __git_commit
    msg, author, timestamp, files
  File "/usr/lib/python3.5/site-packages/weblate/trans/vcs.py", line 598, in commit
    self.execute(['add', '--force', '--'] + files)
  File "/usr/lib/python3.5/site-packages/weblate/trans/vcs.py", line 200, in execute
    self.last_output = self._popen(args, self.path)
  File "/usr/lib/python3.5/site-packages/weblate/trans/vcs.py", line 188, in _popen
    output.decode('utf-8')
weblate.trans.vcs.RepositoryException: fatal: Unable to create '/app/data/vcs/uaprom/uaprom-frontend/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue. (128)

Exception in thread Thread-44:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/weblate/trans/models/subproject.py", line 705, in do_update
    self.commit_pending(request, skip_push=True)
  File "/usr/lib/python3.5/site-packages/weblate/trans/models/subproject.py", line 866, in commit_pending
    translation.commit_pending(request, skip_push=True)
  File "/usr/lib/python3.5/site-packages/weblate/trans/models/translation.py", line 673, in commit_pending
    request, last, self.last_change, True, True, skip_push
  File "/usr/lib/python3.5/site-packages/weblate/trans/models/translation.py", line 787, in git_commit
    self.__git_commit(author, timestamp, sync)
  File "/usr/lib/python3.5/site-packages/weblate/trans/models/translation.py", line 734, in __git_commit
    msg, author, timestamp, files
  File "/usr/lib/python3.5/site-packages/weblate/trans/vcs.py", line 598, in commit
    self.execute(['add', '--force', '--'] + files)
  File "/usr/lib/python3.5/site-packages/weblate/trans/vcs.py", line 200, in execute
    self.last_output = self._popen(args, self.path)
  File "/usr/lib/python3.5/site-packages/weblate/trans/vcs.py", line 188, in _popen
    output.decode('utf-8')
weblate.trans.vcs.RepositoryException: fatal: Unable to create '/app/data/vcs/uaprom/uaprom-frontend/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue. (128)

Exception in thread Thread-56:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/weblate/trans/filelock.py", line 100, in acquire
    self.try_lock(self.handle)
  File "/usr/lib/python3.5/site-packages/weblate/trans/filelock.py", line 173, in try_lock
    fcntl.flock(handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/weblate/trans/models/subproject.py", line 688, in do_update
    if not self.update_remote_branch():
  File "/usr/lib/python3.5/site-packages/weblate/trans/models/subproject.py", line 638, in update_remote_branch
    with self.repository.lock():
  File "/usr/lib/python3.5/site-packages/weblate/trans/filelock.py", line 148, in __enter__
    self.acquire()
  File "/usr/lib/python3.5/site-packages/weblate/trans/filelock.py", line 107, in acquire
    raise FileLockException("Timeout occured.")
weblate.trans.filelock.FileLockException: Timeout occured.

Exception in thread Thread-49:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/weblate/trans/filelock.py", line 100, in acquire
    self.try_lock(self.handle)
  File "/usr/lib/python3.5/site-packages/weblate/trans/filelock.py", line 173, in try_lock
    fcntl.flock(handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/weblate/trans/models/subproject.py", line 688, in do_update
    if not self.update_remote_branch():
  File "/usr/lib/python3.5/site-packages/weblate/trans/models/subproject.py", line 638, in update_remote_branch
    with self.repository.lock():
  File "/usr/lib/python3.5/site-packages/weblate/trans/filelock.py", line 148, in __enter__
    self.acquire()
  File "/usr/lib/python3.5/site-packages/weblate/trans/filelock.py", line 107, in acquire
    raise FileLockException("Timeout occured.")
weblate.trans.filelock.FileLockException: Timeout occured.

Exception in thread Thread-51:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/weblate/trans/filelock.py", line 100, in acquire
    self.try_lock(self.handle)
  File "/usr/lib/python3.5/site-packages/weblate/trans/filelock.py", line 173, in try_lock
    fcntl.flock(handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/weblate/trans/models/subproject.py", line 688, in do_update
    if not self.update_remote_branch():
  File "/usr/lib/python3.5/site-packages/weblate/trans/models/subproject.py", line 638, in update_remote_branch
    with self.repository.lock():
  File "/usr/lib/python3.5/site-packages/weblate/trans/filelock.py", line 148, in __enter__
    self.acquire()
  File "/usr/lib/python3.5/site-packages/weblate/trans/filelock.py", line 107, in acquire
    raise FileLockException("Timeout occured.")
weblate.trans.filelock.FileLockException: Timeout occured.

Internal Server Error: /api/components/uaprom-vas/vas-frontend/repository/
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/weblate/trans/filelock.py", line 100, in acquire
    self.try_lock(self.handle)
  File "/usr/lib/python3.5/site-packages/weblate/trans/filelock.py", line 173, in try_lock
    fcntl.flock(handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/rest_framework/viewsets.py", line 83, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/rest_framework/views.py", line 477, in dispatch
    response = self.handle_exception(exc)
  File "/usr/lib/python3.5/site-packages/rest_framework/views.py", line 437, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/lib/python3.5/site-packages/rest_framework/views.py", line 474, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/weblate/api/views.py", line 164, in repository
    serializer.validated_data['operation']
  File "/usr/lib/python3.5/site-packages/weblate/api/views.py", line 141, in repository_operation
    return getattr(obj, method)(request)
  File "/usr/lib/python3.5/site-packages/weblate/trans/models/subproject.py", line 688, in do_update
    if not self.update_remote_branch():
  File "/usr/lib/python3.5/site-packages/weblate/trans/models/subproject.py", line 638, in update_remote_branch
    with self.repository.lock():
  File "/usr/lib/python3.5/site-packages/weblate/trans/filelock.py", line 148, in __enter__
    self.acquire()
  File "/usr/lib/python3.5/site-packages/weblate/trans/filelock.py", line 107, in acquire
    raise FileLockException("Timeout occured.")
weblate.trans.filelock.FileLockException: Timeout occured.
192.168.21.100 - - [30/Jan/2017 16:18:08] "POST /api/components/uaprom-vas/vas-frontend/repository/ HTTP/1.1" 500 -
Exception in thread Thread-55:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/weblate/trans/models/subproject.py", line 922, in update_branch
    method()
  File "/usr/lib/python3.5/site-packages/weblate/trans/vcs.py", line 486, in rebase
    self.execute(['rebase', 'origin/{0}'.format(self.branch)])
  File "/usr/lib/python3.5/site-packages/weblate/trans/vcs.py", line 200, in execute
    self.last_output = self._popen(args, self.path)
  File "/usr/lib/python3.5/site-packages/weblate/trans/vcs.py", line 188, in _popen
    output.decode('utf-8')
weblate.trans.vcs.RepositoryException: fatal: Unable to create '/app/data/vcs/uaprom-vas/vas-backend/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
could not detach HEAD (1)
```

**Comment by AlexMost** [comment]
Maybe the problem is that `wlc pull` and update hook was executed at the same time and caused some raise condition? I think I can remove update hook, because now I have both: update hook and update script in CI.
192.168.21.100 - - [30/Jan/2017 16:17:36] "POST /hooks/gitlab/ HTTP/1.1" 200 -
192.168.21.100 - - [30/Jan/2017 16:17:36] "GET /api/components/uaprom-vas/vas-frontend/ HTTP/1.1" 200 -

**Comment by nijel** [comment]
Concurrency should not matter as there is locking in Weblate *and* Git which each should IMHO prevent this. But obviously it seems to matter, so at least Weblate locking is not working as expected. On what filesystem are the repositories stored?

**Comment by AlexMost** [comment]
Wow, hope those fixes will solve the issue, will be waiting for update! I am using ext4 on the server.

**Comment by nijel** [comment]
I think I've found the problematic place, at least it could cause some strange results when two updates are run concurrently. However I still have no clue how it could end up with detached head, there is clearly something strange in git version you are using.

**Comment by AlexMost** [comment]
thanks, will check your updates when they will be available.

**Comment by nijel** [comment]
2.11 will be out later today :-)
