### ISSUE TITLE
Long file names for components

### ISSUE THREAD

**Issue by Insoleet** [WeblateOrg/weblate#1337]
### Steps to reproduce
1. Import the RTM in weblate using the following command : 
```
./manage.py import_project relative-theory-money https://github.com/vtexier/theorie-relative-de-la-monnaie dev "source/locale/**/LC_MESSAGES/*.po"
```
2. See error

### Actual behaviour
```
weblate@vps272066:~/weblate$ ./manage.py import_project relative-theory-money https://github.com/vtexier/theorie-relative-de-la-monnaie dev "source/locale/**/LC_MESSAGES/*.po"
INFO Cloning git repository...
INFO Updating working copy in git repository...
INFO Found 26 matching files
INFO Found 1 subprojects
INFO Creating component en_US as main one
INFO relative-theory-money/en_us: updating repository
INFO relative-theory-money/en_us: update took 0.53 seconds:
INFO relative-theory-money/en_us: merge remote into repo
INFO relative-theory-money/en_us: skipping language introduction-de-la-version-1.0 [source/locale/en_US/LC_MESSAGES/introduction-de-la-version-1.0.po]
INFO relative-theory-money/en_us: skipping language introduction-de-la-version-2.718 [source/locale/en_US/LC_MESSAGES/introduction-de-la-version-2.718.po]
INFO relative-theory-money/en_us: skipping language conseils-de-lecture-version-2.718 [source/locale/en_US/LC_MESSAGES/conseils-de-lecture-version-2.718.po]
INFO relative-theory-money/en_us: skipping language preface-de-la-version-1.0-par-Yoland-Bresson [source/locale/en_US/LC_MESSAGES/preface-de-la-version-1.0-par-Yoland-Bresson.po]
INFO relative-theory-money/en_us: checking source/locale/en_US/LC_MESSAGES/appendice-1.po (appendice-1) [1/22]
INFO relative-theory-money/en_us/appendice_: processing source/locale/en_US/LC_MESSAGES/appendice-1.po, revision has changed
INFO relative-theory-money/en_us: checking source/locale/en_US/LC_MESSAGES/appendice-2.po (appendice-2) [2/22]
ERROR relative-theory-money/en_us: duplicate language found: appendice_
INFO relative-theory-money/en_us: checking source/locale/en_US/LC_MESSAGES/autres-fondements-du-dividende-universel.po (autres-fondements-du-dividende-universel) [3/22]
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/opt/weblate/weblate/weblate/trans/management/commands/import_project.py", line 314, in handle
    matches, sharedrepo = self.import_initial(project, repo, branch)
  File "/opt/weblate/weblate/weblate/trans/management/commands/import_project.py", line 418, in import_initial
    **self.get_project_attribs()
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/db/models/query.py", line 399, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/weblate/weblate/weblate/trans/models/subproject.py", line 1403, in save
    self.create_translations()
  File "/opt/weblate/weblate/weblate/trans/models/subproject.py", line 1034, in create_translations
    self, lang, code, path, force, request=request
  File "/opt/weblate/weblate/weblate/trans/models/translation.py", line 71, in check_sync
    'language_code': code,
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/db/models/query.py", line 475, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/db/models/query.py", line 505, in _create_object_from_params
    obj = self.create(**params)
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/db/models/query.py", line 399, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/db/models/base.py", line 796, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/db/models/base.py", line 824, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/db/models/base.py", line 908, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/db/models/base.py", line 947, in _do_insert
    using=using, raw=raw)
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/db/models/query.py", line 1045, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    cursor.execute(sql, params)
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/weblate/.local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.DataError: value too long for type character varying(20)
```

### Expected behaviour
All the files should be imported succefully.

### Server configuration
```
weblate@vps272066:~/weblate$ ./manage.py list_versions
 * Weblate weblate-2.10.1
 * Python 2.7.9
 * Django 1.10.5
 * six 1.10.0
 * python-social-auth 0.2.21
 * Translate Toolkit 2.0.0rc2
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.7.2
 * django-crispy-forms 1.6.1
 * compressor 2.1
 * djangorestframework 3.5.3
 * PyYAML 3.11
 * Mercurial 3.1.2
 * hub 2.2.3
 * Database backends: django.db.backends.postgresql_psycopg2
```

**Comment by nijel** [comment]
The problem is that you've mixed component name and language in the mask, it should be rather - `source/locale/*/LC_MESSAGES/**.po` in this case. However it should indeed fail more gracefully.
