### ISSUE TITLE
AttributeError: 'RegexURLPattern' object has no attribute '_callback'

### ISSUE THREAD

**Issue by christophemassin** [WeblateOrg/weblate#1364]
### Steps to reproduce
1.Install weblate. Database is not on the same server. 
2.try to configure it ./manage.py migrate
3.fail with following message

### Actual behaviour
`
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/management/base.py", line 342, in execute
    self.check()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/weblate/weblate/urls.py", line 53, in <module>
    import weblate.api.urls
  File "/home/ubuntu/weblate/weblate/api/urls.py", line 65, in <module>
    include(router.urls)
  File "/usr/lib/python2.7/dist-packages/rest_framework/routers.py", line 79, in urls
    self._urls = self.get_urls()
  File "/usr/lib/python2.7/dist-packages/rest_framework/routers.py", line 321, in get_urls
    urls = format_suffix_patterns(urls)
  File "/usr/lib/python2.7/dist-packages/rest_framework/urlpatterns.py", line 64, in format_suffix_patterns
    return apply_suffix_patterns(urlpatterns, suffix_pattern, suffix_required)
  File "/usr/lib/python2.7/dist-packages/rest_framework/urlpatterns.py", line 27, in apply_suffix_patterns
    view = urlpattern._callback or urlpattern._callback_str
AttributeError: 'RegexURLPattern' object has no attribute '_callback'
`

### Expected behaviour
Configuration should start

### Server configuration
```
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/management/base.py", line 342, in execute
    self.check()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/weblate/weblate/urls.py", line 53, in <module>
    import weblate.api.urls
  File "/home/ubuntu/weblate/weblate/api/urls.py", line 65, in <module>
    include(router.urls)
  File "/usr/lib/python2.7/dist-packages/rest_framework/routers.py", line 79, in urls
    self._urls = self.get_urls()
  File "/usr/lib/python2.7/dist-packages/rest_framework/routers.py", line 321, in get_urls
    urls = format_suffix_patterns(urls)
  File "/usr/lib/python2.7/dist-packages/rest_framework/urlpatterns.py", line 64, in format_suffix_patterns
    return apply_suffix_patterns(urlpatterns, suffix_pattern, suffix_required)
  File "/usr/lib/python2.7/dist-packages/rest_framework/urlpatterns.py", line 27, in apply_suffix_patterns
    view = urlpattern._callback or urlpattern._callback_str
AttributeError: 'RegexURLPattern' object has no attribute '_callback'
```

**Comment by christophemassin** [comment]
Solved 
- Git pull 
- Update some library that where then notify as too old

**Comment by christophemassin** [comment]
I ve scratch the instance, reconfigure everything, but i still got this : 

`
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 353, in execute
    self.check()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/ubuntu/weblate/weblate/urls.py", line 53, in <module>
    import weblate.api.urls
  File "/home/ubuntu/weblate/weblate/api/urls.py", line 65, in <module>
    include(router.urls)
  File "/usr/lib/python2.7/dist-packages/rest_framework/routers.py", line 79, in urls
    self._urls = self.get_urls()
  File "/usr/lib/python2.7/dist-packages/rest_framework/routers.py", line 321, in get_urls
    urls = format_suffix_patterns(urls)
  File "/usr/lib/python2.7/dist-packages/rest_framework/urlpatterns.py", line 64, in format_suffix_patterns
    return apply_suffix_patterns(urlpatterns, suffix_pattern, suffix_required)
  File "/usr/lib/python2.7/dist-packages/rest_framework/urlpatterns.py", line 27, in apply_suffix_patterns
    view = urlpattern._callback or urlpattern._callback_str
AttributeError: 'RegexURLPattern' object has no attribute '_callback'
`

**Comment by christophemassin** [comment]
Some drop from pip freeze

Babel==1.3
beautifulsoup4==4.4.1
blinker==1.3
chardet==2.3.0
cryptography==1.2.3
csscompressor==0.9.4
defusedxml==0.4.1
diff-match-patch==20121119
Django==1.10
django-appconf==1.0.1
django-compressor==2.0
django-crispy-forms==1.6.0
django-filter==0.11.0
django-guardian==1.4.1
djangorestframework==3.3.2
enum34==1.1.2
html5lib==0.999
idna==2.0
iniparse==0.4
ipaddress==1.0.16
lxml==3.5.0
Markdown==2.6.6
mercurial==3.7.3
mysqlclient==1.3.7
ndg-httpsclient==0.4.0
oauthlib==2.0.1
Pillow==3.1.2
pyasn1==0.1.9
pydns==2.3.6
pyenchant==1.6.6
Pygments==2.1
PyJWT==1.4.2
pyLibravatar==1.7
PyMySQL==0.7.2
pyOpenSSL==0.15.1
python-dateutil==2.4.2
python-Levenshtein==0.12.0
python-openid==2.2.5
pytz==2014.10
PyYAML==3.11
rcssmin==1.0.6
requests==2.13.0
requests-oauthlib==0.7.0
rjsmin==1.0.12
simplejson==3.8.1
siphashc==0.7
six==1.10.0
social-auth-app-django==1.1.0
social-auth-core==1.2.0
sqlparse==0.1.18
translate-toolkit==2.0.0
urllib3==1.13.1
uTidylib==0.2
vobject==0.8.1rc0
Whoosh==2.7.0

**Comment by nijel** [comment]
Update django-rest-framework to version compatible with Django 1.10 (according to http://stackoverflow.com/q/34611268/225718 at least version 3.4.0).
