### ISSUE TITLE
Fresh installation: Table '`weblate`.`django_content_type`' already exists

### ISSUE THREAD

**Issue by marcinkunert** [WeblateOrg/weblate#1373]
### Steps to reproduce
1. Download weblate sources from master branch
2. Install all requirements by following the guidelines
3. Copy the example config, set the database credentials
4. Run ./manage.py migrate

### Actual behaviour

Startup fails with message:

```
Operations to perform:
  Apply all migrations: accounts, admin, auth, authtoken, contenttypes, lang, screenshots, sessions, sites, social_django, trans
Running migrations:
  Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/models.py", line 96, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 295, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 112, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1050, "Table '`weblate`.`django_content_type`' already exists")
```

### Expected behaviour
No errors

### Server configuration
 `./manage.py list_versions` result:

```
 * Weblate weblate-2.11-305-g586b021
 * Python 2.7.9
 * Django 1.10.5
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.7.3
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.4
 * pytz 2012c
 * pyLibravatar N/A
 * PyYAML 3.11
 * Mercurial 3.1.2
 * Database backends: django.db.backends.mysql
```

The database schema `weblate` exists and has no tables.

**Comment by nijel** [comment]
Was the database really empty before doing this?

**Comment by marcinkunert** [comment]
@nijel I'm 100% sure. I've even tried to drop the schema and created a new one.

**Comment by nijel** [comment]
Strange, this really should not happen. This could happen when migrating from older Django versions (see http://stackoverflow.com/q/29760817/225718), but not on fresh installs.

Can you please try start with empty schema again, run migrations verbosely (`./manage.py migrate -v 3`) and paste here it's output?

**Comment by marcinkunert** [comment]
I've dropped the schema, recreated a new one, pulled the current master, executed migration and got a new error. It looks a lot better. There are at least a few tables created.

`./manage.py migrate -v 3`


```
System check identified some issues:

WARNINGS:
?: (mysql.W002) MySQL Strict Mode is not set for database connection 'default'
        HINT: MySQL's Strict Mode fixes many data integrity problems in MySQL, such as data truncation upon insertion, by escalating warnings into errors. It is strongly recommended you activate it. See: https://docs.djangoproject.com/en/1.10/ref/databases/#mysql-sql-mode
Operations to perform:
  Apply all migrations: accounts, admin, auth, authtoken, contenttypes, lang, screenshots, sessions, sites, social_django, trans
Running pre-migrate handlers for application auth
Running pre-migrate handlers for application contenttypes
Running pre-migrate handlers for application sessions
Running pre-migrate handlers for application sites
Running pre-migrate handlers for application admin
Running pre-migrate handlers for application social_django
Running pre-migrate handlers for application crispy_forms
Running pre-migrate handlers for application compressor
Running pre-migrate handlers for application rest_framework
Running pre-migrate handlers for application authtoken
Running pre-migrate handlers for application trans
Running pre-migrate handlers for application langgi
Running pre-migrate handlers for application screenshots
Running pre-migrate handlers for application accounts
Running pre-migrate handlers for application utils
Running pre-migrate handlers for application weblate
Running migrations:
  Applying contenttypes.0001_initial... OK (0.054s)
  Applying contenttypes.0002_remove_content_type_name... OK (0.071s)
  Applying auth.0001_initial... OK (0.318s)
  Applying auth.0002_alter_permission_name_max_length... OK (0.043s)
  Applying auth.0003_alter_user_email_max_length... OK (0.045s)
  Applying auth.0004_alter_user_username_opts... OK (0.023s)
  Applying auth.0005_alter_user_last_login_null... OK (0.044s)
  Applying auth.0006_require_contenttypes_0002... OK (0.007s)
  Applying auth.0007_alter_validators_add_error_messages... OK (0.027s)
  Applying auth.0008_alter_user_username_max_length... OK (0.040s)
  Applying authtoken.0001_initial... OK (0.064s)
  Applying lang.0001_initial... OK (0.022s)
  Applying trans.0001_squashed_0018_auto_20150213_1447...Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/models.py", line 96, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 295, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 112, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.ProgrammingError: (1146, "Table 'weblate.trans_whiteboardmessage' doesn't exist")
```

**Comment by nijel** [comment]
Can you please try that with strict mode enabled as the warning says? There might be some error before which is silently ignored by the server due to this. I've added example for this in 1763e958ca4f4a1a781129d6eb24e6480f03cd2b.

**Comment by marcinkunert** [comment]
Unfortunately that didn't change anything.

`./manage.py migrate -v 3`

```
Operations to perform:
  Apply all migrations: accounts, admin, auth, authtoken, contenttypes, lang, screenshots, sessions, sites, social_django, trans
Running pre-migrate handlers for application auth
Running pre-migrate handlers for application contenttypes
Running pre-migrate handlers for application sessions
Running pre-migrate handlers for application sites
Running pre-migrate handlers for application admin
Running pre-migrate handlers for application social_django
Running pre-migrate handlers for application crispy_forms
Running pre-migrate handlers for application compressor
Running pre-migrate handlers for application rest_framework
Running pre-migrate handlers for application authtoken
Running pre-migrate handlers for application trans
Running pre-migrate handlers for application lang
Running pre-migrate handlers for application screenshots
Running pre-migrate handlers for application accounts
Running pre-migrate handlers for application utils
Running pre-migrate handlers for application weblate
Running migrations:
  Applying contenttypes.0001_initial... OK (0.047s)
  Applying contenttypes.0002_remove_content_type_name... OK (0.057s)
  Applying auth.0001_initial... OK (0.317s)
  Applying auth.0002_alter_permission_name_max_length... OK (0.040s)
  Applying auth.0003_alter_user_email_max_length... OK (0.054s)
  Applying auth.0004_alter_user_username_opts... OK (0.031s)
  Applying auth.0005_alter_user_last_login_null... OK (0.045s)
  Applying auth.0006_require_contenttypes_0002... OK (0.005s)
  Applying auth.0007_alter_validators_add_error_messages... OK (0.025s)
  Applying auth.0008_alter_user_username_max_length... OK (0.043s)
  Applying authtoken.0001_initial... OK (0.060s)
  Applying lang.0001_initial... OK (0.025s)
  Applying trans.0001_squashed_0018_auto_20150213_1447...Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/models.py", line 96, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 295, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 112, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.ProgrammingError: (1146, "Table 'weblate.trans_whiteboardmessage' doesn't exist")
```

**Comment by nijel** [comment]
Can you try to install Weblate 2.10 first? I've have squashed the migrations for 2.11 and maybe that's what's causing troubles...

**Comment by marcinkunert** [comment]
Ok so the steps I did:

1. `git fetch --tags`
2. `git checkout tags/weblate-2.10.1`
3. Replace the `settings.py` file with the `settings_exapmle.py` one, adjust database credentials
4. Try to run `./manage.py` migrate -v 3` - no luck, python import something problem
5. I figured there are dependencies missing so: `pip install -r requirements.txt` and `pip install -r requirements_optional.txt`
6. Still something wrong, seems like one of the social modules
7. Remove those modules `pip uninstall python-social-auth`, `pip uninstall social-auth-core`, `pip uninstall social-auth-app-django`
8. Install them again `pip install -r requirements.txt` and `pip install -r requirements_optional.txt`
9. Weird one was not installed that seems to be needed (`ImportError: No module named social_django.models`), so I installed it manually `pip install social-auth-app-django`
10. I am stuck now at `./manage.py migrate -v 3` with error pasted below. `./migrate.py list_versions` shows the same error.

`pip freeze`

```
Babel==1.3
beautifulsoup4==4.3.2
boto==2.34.0
chardet==2.3.0
Cheetah==2.4.4
cloud-init==0.7.6
colorama==0.3.2
configobj==5.0.6
defusedxml==0.5.0
diff-match-patch==20121119
distro-info==0.14
Django==1.10.5
django-appconf==1.0.2
django-compressor==2.1.1
django-crispy-forms==1.6.1
django-filter==0.7
django-guardian==1.2.5.dev0
django-rest==0.0.1
djangorestframework==3.5.4
ecdsa==0.11
euca2ools==3.1.0
html5lib==0.999
iniparse==0.4
jsonpatch==1.3
jsonpointer==1.0
lxml==3.7.3
Markdown==2.5.1
mercurial==3.1.2
MySQL-python==1.2.3
oauth==1.0.1
oauthlib==2.0.1
olefile==0.44
paramiko==1.15.1
Pillow==4.0.0
prettytable==0.7.2
pycrypto==2.6.1
pydns==2.3.6
pyenchant==1.6.6
Pygments==2.0.1
PyJWT==1.4.2
pyLibravatar==1.6
pyserial==2.6
python-apt==0.9.3.12
python-bidi==0.4.0
python-dateutil==2.6.0
python-Levenshtein==0.11.2
python-memcached==1.58
python-openid==2.2.5
python-social-auth==0.3.6
pytz==2016.10
pyuca==1.1.2
PyYAML==3.11
rcssmin==1.0.6
requestbuilder==0.2.3
requests==2.13.0
requests-oauthlib==0.8.0
requirements==0.1
rjsmin==1.0.12
simplejson==3.6.5
siphashc==0.7
siphashc3==3
six==1.10.0
social-auth-app-django==1.1.0
social-auth-core==1.2.0
sqlparse==0.1.13
translate-toolkit==2.0.0
urllib3==1.9.1
uTidylib==0.2
vobject==0.8.1rc0
Whoosh==2.7.4
```

```
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 342, in execute
    self.check()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/weblate/weblate/urls.py", line 34, in <module>
    import weblate.accounts.views
  File "/opt/weblate/weblate/accounts/views.py", line 45, in <module>
    from social.apps.django_app.utils import BACKENDS
  File "/usr/local/lib/python2.7/dist-packages/social/apps/django_app/utils.py", line 1, in <module>
    from social_django.utils import load_strategy, load_backend, psa, setting, BackendWrapper, strategy
ImportError: cannot import name strategy
```

Sorry for bothering you with my silly problems. As you can tell I'm not really a python guy. I really appreciate your help and love to use weblate to translate my Android apps.

**Comment by nijel** [comment]
Ah, you need to install python-social-auth to version older than 0.3 (probably 0.2.21).
