### ISSUE TITLE
django.contrib.auth.models.DoesNotExist: Permission matching query does not exist.

### ISSUE THREAD

**Issue by whedro** [WeblateOrg/weblate#1390]
### Steps to reproduce
1. git pull
2. compare new settings (diff settings.py settings_example.py)
3. upgrade requirments
3. `./manage.py migrate`   or   `./manage.py setupgroups`

### Actual behaviour
```
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/opt/weblate/weblate/accounts/management/commands/setupgroups.py", line 50, in handle
    create_groups(options['update'])
  File "/opt/weblate/weblate/accounts/models.py", line 1013, in create_groups
    Permission.objects.get(codename='add_screenshot'),
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: Permission matching query does not exist.
```
### Server configuration
```
* Weblate weblate-2.11-427-ga1b2555
 * Python 2.7.12
 * Django 1.10.6
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.7.3
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.4
 * pytz 2016.10
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.1.3
 * Mercurial 4.1
 * git-review 1.25.0
 * Database backends: django.db.backends.mysql
```

**Comment by nijel** [comment]
Probably missing screenshots app in INSTALLED_APPS. See also https://github.com/WeblateOrg/weblate/issues/1089#issuecomment-281139691

**Comment by whedro** [comment]
```
INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admin',
    'django.contrib.admindocs',
    'django.contrib.sitemaps',
#    'social.apps.django_app.default',
    'crispy_forms',
    'compressor',
    'rest_framework',
    'rest_framework.authtoken',
    'weblate.trans',
    'weblate.lang',
    'weblate.accounts',
    # Needed for javascript localization
    'weblate',
    'social_django',
    'weblate.utils',
    'weblate.gitexport',
    'weblate.screenshots',
)
```

**Comment by whedro** [comment]
ok .. I don't have 'weblate' as last ...

I think, will be better, if you add comment before `'weblate',`, that must be last in `INSTALLED_APPS`

**Comment by whedro** [comment]
After change `weblate` order is OK ... thanks for help ..

**Comment by nijel** [comment]
That comment is already there :-) https://github.com/WeblateOrg/weblate/blob/master/weblate/settings_example.py#L307

**Comment by whedro** [comment]
I see .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. sorry .. :)
