### ISSUE TITLE
OperationalError: (1054, "Unknown column 'trans_source.screenshot' in 'field list'")

### ISSUE THREAD

**Issue by whedro** [WeblateOrg/weblate#1398]
### Steps to reproduce
1. click  on link "Not translated strings" or "Strings needing action" or another else when I want to translate component

### Actual behaviour
`The server had serious problems while serving your request. We've just sent our trained monkeys to fix the issue.`

```
2017-03-07 14:41:52,178 ERROR Internal Server Error: /translate/project/component/en/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    @wraps(get_response, assigned=available_attrs(get_response))
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/weblate/weblate/trans/views/edit.py", line 605, in translate
    'secondary': secondary,
  File "/opt/weblate/weblate/trans/util.py", line 227, in render
    return django_render(request, template, context, status=status)
  File "/usr/local/lib/python2.7/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 510, in render
    return self.nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python2.7/dist-packages/django/template/library.py", line 225, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/opt/weblate/weblate/trans/templatetags/translations.py", line 167, in format_translation
    value = fmt_highlights(raw_value, value, unit)
  File "/opt/weblate/weblate/trans/templatetags/translations.py", line 104, in fmt_highlights
    highlights = highlight_string(raw_value, unit)
  File "/opt/weblate/weblate/trans/checks/__init__.py", line 32, in highlight_string
    highlights += CHECKS[check].check_highlight(source, unit)
  File "/opt/weblate/weblate/trans/checks/angularjs.py", line 70, in check_highlight
    if self.should_skip(unit):
  File "/opt/weblate/weblate/trans/checks/base.py", line 50, in should_skip
    if self.default_disabled and self.enable_string not in unit.all_flags:
  File "/opt/weblate/weblate/trans/models/unit.py", line 1097, in all_flags
    def translate(self, request, new_target, new_fuzzy, change_action=None,
  File "/opt/weblate/weblate/trans/models/unit.py", line 1111, in source_info
    return saved
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 379, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
OperationalError: (1054, "Unknown column 'trans_source.screenshot' in 'field list'")

```
### Server configuration

```
 * Weblate weblate-2.12-6-g5f0f8e0
 * Python 2.7.12
 * Django 1.10.6
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.7.3
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.4
 * pytz 2016.10
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.1.3
 * Mercurial 4.1.1
 * git-review 1.25.0
 * Database backends: django.db.backends.mysql
```

**Comment by whedro** [comment]
I tried as last option restart uwsgi and nginx .. now its working ...
I closing this issue
