### ISSUE TITLE
Fresh installation: ERROR: accounts.VerifiedEmail.social: (fields.E300)

### ISSUE THREAD

**Issue by marcinkunert** [WeblateOrg/weblate#1405]
### Steps to reproduce
1. Get master branch
2. Install all stuff
3. Install all through `pip install -r requirements.txt` just to make sure
4. Type `./manage migrate -v 3`

The database schema was totally empty before executing the command. Afterwards it still has no tables.

### Actual behaviour
Fails with error

> SystemCheckError: System check identified some issues:
> 
> ERRORS:
> accounts.VerifiedEmail.social: (fields.E300) Field defines a relation with model 'UserSocialAuth', which is either not installed, or is abstract.

### Expected behaviour
Migrates without problems

### Server configuration
`./manage.py list_versions` gives the same error mentioned before

`pip freeze | grep social`
python-social-auth==0.2.21
social-auth-app-django==1.1.0
social-auth-core==1.2.0

`pip freeze`

```
Babel==1.3
beautifulsoup4==4.3.2
boto==2.34.0
chardet==2.3.0
Cheetah==2.4.4
cloud-init==0.7.6
colorama==0.3.2
configobj==5.0.6
Cython==0.25.2
defusedxml==0.5.0
diff-match-patch==20121119
distro-info==0.14
Django==1.10.5
django-appconf==1.0.2
django-compressor==2.1.1
django-crispy-forms==1.6.1
django-filter==0.7
django-guardian==1.2.5.dev0
django-rest==0.0.1
djangorestframework==3.5.4
ecdsa==0.11
euca2ools==3.1.0
html5lib==0.999
iniparse==0.4
jsonpatch==1.3
jsonpointer==1.0
lxml==3.7.3
Markdown==2.5.1
mercurial==3.1.2
MySQL-python==1.2.3
oauth==1.0.1
oauthlib==2.0.1
olefile==0.44
paramiko==1.15.1
Pillow==4.0.0
prettytable==0.7.2
pycrypto==2.6.1
pydns==2.3.6
pyenchant==1.6.6
Pygments==2.0.1
PyJWT==1.4.2
pyLibravatar==1.6
pyserial==2.6
python-apt==0.9.3.12
python-bidi==0.4.0
python-dateutil==2.6.0
python-Levenshtein==0.11.2
python-memcached==1.58
python-openid==2.2.5
python-social-auth==0.2.21
pytz==2016.10
pyuca==1.1.2
PyYAML==3.11
rcssmin==1.0.6
requestbuilder==0.2.3
requests==2.13.0
requests-oauthlib==0.8.0
requirements==0.1
rjsmin==1.0.12
simplejson==3.6.5
siphashc==0.7
siphashc3==3
six==1.10.0
social-auth-app-django==1.1.0
social-auth-core==1.2.0
sqlparse==0.1.13
translate-toolkit==2.0.0
urllib3==1.9.1
uTidylib==0.2
vobject==0.8.1rc0
Whoosh==2.7.4
```

I guess the social plugins are problematic. In my case I don't care about social login at all. Is there a way to disable it to get rid of this problem?

**Comment by nijel** [comment]
You should not need  python-social-auth at all on current Weblate. How does your settings.py look like?

**Comment by marcinkunert** [comment]
Good point. Seems like I've had something wrong with my settings.py. I've copied the oryginal one `settings_example.py` and adjusted the database part.

Now the problem is as follows:
` ./manage.py migrate -v 3`

```
Operations to perform:
  Apply all migrations: accounts, admin, auth, authtoken, contenttypes, lang, screenshots, sessions, sites, social_django, trans
Running pre-migrate handlers for application auth
Running pre-migrate handlers for application contenttypes
Running pre-migrate handlers for application sessions
Running pre-migrate handlers for application sites
Running pre-migrate handlers for application admin
Running pre-migrate handlers for application social_django
Running pre-migrate handlers for application crispy_forms
Running pre-migrate handlers for application compressor
Running pre-migrate handlers for application rest_framework
Running pre-migrate handlers for application authtoken
Running pre-migrate handlers for application trans
Running pre-migrate handlers for application lang
Running pre-migrate handlers for application screenshots
Running pre-migrate handlers for application accounts
Running pre-migrate handlers for application utils
Running pre-migrate handlers for application weblate
Running migrations:
  Applying contenttypes.0001_initial... OK (0.039s)
  Applying contenttypes.0002_remove_content_type_name... OK (0.038s)
  Applying auth.0001_initial... OK (0.266s)
  Applying auth.0002_alter_permission_name_max_length... OK (0.036s)
  Applying auth.0003_alter_user_email_max_length... OK (0.036s)
  Applying auth.0004_alter_user_username_opts... OK (0.021s)
  Applying auth.0005_alter_user_last_login_null... OK (0.038s)
  Applying auth.0006_require_contenttypes_0002... OK (0.005s)
  Applying auth.0007_alter_validators_add_error_messages... OK (0.024s)
  Applying auth.0008_alter_user_username_max_length... OK (0.048s)
  Applying authtoken.0001_initial... OK (0.064s)
  Applying lang.0001_initial... OK (0.020s)
  Applying trans.0001_initial...Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/models.py", line 96, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 295, in create_model
    self.execute(sql, params or None)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 112, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.ProgrammingError: (1146, "Table 'weblate.trans_whiteboardmessage' doesn't exist")
```

Before execution the database was empty. Below you can see which tables were created.
![Tables](http://i.imgur.com/zBxSHpP.png)

**Comment by nijel** [comment]
That's strange, the migration doesn't touch this table at all. What does `./manage.py showmigrations` print?

**Comment by marcinkunert** [comment]
```
accounts
 [ ] 0001_initial
 [ ] 0002_auto_20140923_1543
 [ ] 0003_auto_20141104_1159
 [ ] 0004_auto_20150108_1424
 [ ] 0005_auto_20150330_1358
 [ ] 0006_profile_hide_completed
 [ ] 0007_auto_20150427_1505
 [ ] 0008_profile_hide_source_secondary
 [ ] 0009_auto_20150630_1213
 [ ] 0010_auto_20150819_1457
 [ ] 0011_auto_20150916_0952
 [ ] 0012_auto_20151112_0738
 [ ] 0013_auto_20151222_1006
 [ ] 0014_auto_20160302_1025
 [ ] 0015_auto_20160304_1418
 [ ] 0016_add-api-keys
 [ ] 0017_anonymous_profile
 [ ] 0018_autogroup_users
 [ ] 0019_auto_20160520_1358
 [ ] 0020_remove_projects_dashboard
 [ ] 0021_auto_20160520_1401
 [ ] 0022_auto_20160520_1434
 [ ] 0023_auto_20161021_1502
 [ ] 0024_auto_20161024_0902
 [ ] 0025_auto_20170211_1609
 [ ] 0026_profile_special_chars
admin
 [ ] 0001_initial
 [ ] 0002_logentry_remove_auto_add
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
authtoken
 [X] 0001_initial
 [ ] 0002_auto_20160226_1747
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
lang
 [X] 0001_initial
 [ ] 0002_auto_20150630_1208
 [ ] 0003_auto_20160721_0849
 [ ] 0004_auto_20161222_1459
screenshots
 [ ] 0001_initial
 [ ] 0002_auto_20170215_0849
 [ ] 0003_auto_20170215_1633
sessions
 [ ] 0001_initial
sites
 [ ] 0001_initial
 [ ] 0002_alter_domain_unique
social_django
 [ ] 0001_initial (2 squashed migrations)
 [ ] 0002_add_related_name (2 squashed migrations)
 [ ] 0003_alter_email_max_length (2 squashed migrations)
 [ ] 0004_auto_20160423_0400 (2 squashed migrations)
 [ ] 0005_auto_20160727_2333 (1 squashed migrations)
 [ ] 0006_partial
trans
 [ ] 0001_initial
 [ ] 0002_auto_20141021_1347
 [ ] 0003_auto_20141021_1348
 [ ] 0004_auto_20141021_1550
 [ ] 0005_auto_20141021_1550
 [ ] 0006_auto_20141021_1609
 [ ] 0007_auto_20141022_1159
 [ ] 0008_auto_20141104_1200
 [ ] 0009_auto_20141110_1501
 [ ] 0010_source_check_flags
 [ ] 0011_auto_20141114_1008
 [ ] 0012_translation_have_comment
 [ ] 0013_auto_20141124_1036
 [ ] 0014_auto_20141202_1101
 [ ] 0015_auto_20141203_1345
 [ ] 0016_auto_20141208_1029
 [ ] 0017_auto_20150108_1424
 [ ] 0018_auto_20150213_1447
 [ ] 0019_auto_20150220_1354
 [ ] 0020_auto_20150220_1356
 [ ] 0021_auto_20150306_1605
 [ ] 0022_auto_20150309_0932
 [ ] 0023_project_owner
 [ ] 0024_subproject_edit_template
 [ ] 0025_subproject_post_update_script
 [ ] 0026_auto_20150401_1029
 [ ] 0027_auto_20150401_1030
 [ ] 0028_auto_20150402_1430
 [ ] 0029_auto_20150415_1318
 [ ] 0030_change_subproject
 [ ] 0031_auto_20150415_1339
 [ ] 0032_subproject_agreement
 [ ] 0033_auto_20150618_1138
 [ ] 0034_auto_20150618_1140
 [ ] 0035_auto_20150630_1208
 [ ] 0036_auto_20150709_1005
 [ ] 0037_auto_20150810_1348
 [ ] 0038_auto_20150810_1354
 [ ] 0039_remove_project_owner
 [ ] 0040_auto_20150818_1643
 [ ] 0041_auto_20150819_1457
 [ ] 0042_auto_20150910_0854
 [ ] 0043_auto_20150910_0909
 [ ] 0044_auto_20150916_0952
 [ ] 0045_auto_20150916_1007
 [ ] 0046_auto_20151111_1456
 [ ] 0047_project_source_language
 [ ] 0048_auto_20151120_1306
 [ ] 0049_auto_20151222_0949
 [ ] 0050_auto_20151222_1006
 [ ] 0051_auto_20151222_1059
 [ ] 0052_install_group_acl
 [ ] 0053_auto_20160202_1145
 [ ] 0054_auto_20160202_1219
 [ ] 0055_auto_20160202_1221
 [ ] 0056_auto_20160202_1224
 [ ] 0057_indexupdate_language_code
 [ ] 0058_componentlist
 [ ] 0059_auto_20160303_0934
 [ ] 0060_auto_20160310_0950
 [ ] 0061_auto_20160404_1841
 [ ] 0062_auto_20160419_1429
 [ ] 0063_whiteboardmessage_category
 [ ] 0064_auto_20160428_1813
 [ ] 0065_auto_20160722_0923
 [ ] 0066_auto_20160816_1031
 [ ] 0067_auto_20161024_0922
 [ ] 0068_auto_20161025_1632
 [ ] 0069_source_screenshot
 [ ] 0070_auto_20161103_1412
 [ ] 0071_auto_20170124_1345
 [ ] 0072_auto_20170209_1234
 [ ] 0073_auto_20170209_1359
 [ ] 0074_auto_20170209_1412
 [ ] 0075_auto_20170215_1750
utils
 (no migrations)
```

**Comment by nijel** [comment]
Hmm, this looks correct, I don't see anything obviously wrong in that...

**Comment by marcinkunert** [comment]
I created a new database user and schema with different names and it did the trick. Weird stuff.
Thanks for the support!
