### ISSUE TITLE
Exception: Plural forms do not match the language.

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1407]
View details in Rollbar: [https://rollbar.com/nijel/weblate/items/654/](https://rollbar.com/nijel/weblate/items/654/)

```
Traceback (most recent call last):
  File "/home/nijel/weblate_hosted/weblate/trans/views/files.py", line 118, in upload_translation
    fuzzy=form.cleaned_data['fuzzy'],
  File "/home/nijel/weblate_hosted/weblate/trans/models/translation.py", line 1122, in merge_upload
    raise Exception('Plural forms do not match the language.')
Exception: Plural forms do not match the language.
```

**Comment by nijel** [comment]
Sometimes this is legitimate, but the check is too strict right now:

> I was trying to upload the Weblate website translation, but keep getting an error saying plural forms don't match the language.
> I'm using pt_PT and gTranslator, with: 'nplurals=2; plural=(n != 1);'
> 
> What is wrong here, please?

The problem is that even additional parenthesis around plural formula make the check fail.

**Comment by nijel** [comment]
Code has been introduced in https://github.com/WeblateOrg/weblate/pull/984
