### ISSUE TITLE
Migration from 2.11 to 2.12 fails

### ISSUE THREAD

**Issue by paour** [WeblateOrg/weblate#1417]
### Steps to reproduce
1. I upgraded from 2.8 to 2.9, 2.10 and 2.11, applying requirements and importing `settings.py` changes with every step
2. I attempted to upgrade from 2.11 to 2.12

### Actual behaviour

I got the following error:

```
~/weblate$ sudo -u www-data ./manage.py migrate
Operations to perform:
  Apply all migrations: accounts, admin, auth, authtoken, contenttypes, lang, screenshots, sessions, sites, social_django, trans
Running migrations:
  Applying accounts.0025_auto_20170211_1609... OK
  Applying accounts.0026_profile_special_chars... OK
  Applying trans.0072_auto_20170209_1234... OK
  Applying trans.0073_auto_20170209_1359... OK
  Applying trans.0074_auto_20170209_1412...Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/models.py", line 532, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 329, in alter_unique_together
    self._delete_composed_index(model, fields, {'unique': True}, self.sql_delete_unique)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/schema.py", line 83, in _delete_composed_index
    return super(DatabaseSchemaEditor, self)._delete_composed_index(model, fields, *args)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 358, in _delete_composed_index
    ", ".join(columns),
ValueError: Found wrong number (0) of constraints for trans_check(contentsum, project_id, language_id, check)
```

### Expected behaviour
I was hoping the migration would work.

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

```
~/weblate$ sudo -u www-data ./manage.py list_versions
 * Weblate weblate-2.12
 * Python 2.7.9
 * Django 1.10.6
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.7.3
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.2
 * pytz 2016.6.1
 * pyuca N/A
 * pyLibravatar N/A
 * PyYAML 3.11
 * Database backends: django.db.backends.mysql
```

**Comment by paour** [comment]
If I try running the migration again, I get

```
~/weblate$ sudo -u www-data ./manage.py migrate
Operations to perform:
  Apply all migrations: accounts, admin, auth, authtoken, contenttypes, lang, screenshots, sessions, sites, social_django, trans
Running migrations:
  Applying trans.0074_auto_20170209_1412...Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/fields.py", line 147, in database_forwards
    schema_editor.remove_field(from_model, from_model._meta.get_field(self.name))
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 451, in remove_field
    self.execute(sql)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 112, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1091, "Can't DROP 'contentsum'; check that column/key exists")
```

**Comment by paour** [comment]
Thanks @nijel, which version of django is your patch targeting? On Django 1.10 and 1.10.6, that file only has 947 lines and the `_constraint_names` function is significantly different…

**Comment by nijel** [comment]
Ah, the patch was on 1.11 git, I will try to find patch for 1.10 (which I was actually using).

**Comment by nijel** [comment]
Following patch should do it (it's also attached for easier download):

```patch
diff --git a/django/db/backends/base/schema.py b/django/db/backends/base/schema.py
index 0d35f7be68..4f2719b703 100644
--- a/django/db/backends/base/schema.py
+++ b/django/db/backends/base/schema.py
@@ -926,12 +926,12 @@ class BaseDatabaseSchemaEditor(object):
         """
         Returns all constraint names matching the columns and conditions
         """
-        column_names = list(column_names) if column_names else None
+        column_names = set(column_names) if column_names else None
         with self.connection.cursor() as cursor:
             constraints = self.connection.introspection.get_constraints(cursor, model._meta.db_table)
         result = []
         for name, infodict in constraints.items():
-            if column_names is None or column_names == infodict['columns']:
+            if column_names is None or column_names == set(infodict['columns']):
                 if unique is not None and infodict['unique'] != unique:
                     continue
                 if primary_key is not None and infodict['primary_key'] != primary_key:
```

[django-constraints.txt](https://github.com/WeblateOrg/weblate/files/855366/django-constraints.txt)

**Comment by paour** [comment]
I'm still getting the second error:

```
~/weblate$ sudo -u www-data ./manage.py migrate
Operations to perform:
  Apply all migrations: accounts, admin, auth, authtoken, contenttypes, lang, screenshots, sessions, sites, social_django, trans
Running migrations:
  Applying trans.0074_auto_20170209_1412...Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/fields.py", line 147, in database_forwards
    schema_editor.remove_field(from_model, from_model._meta.get_field(self.name))
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 451, in remove_field
    self.execute(sql)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 112, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py", line 110, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/local/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1091, "Can't DROP 'contentsum'; check that column/key exists")
```

**Comment by nijel** [comment]
I've already mentioned that above (https://github.com/WeblateOrg/weblate/issues/1417#issuecomment-287761288) - you need to remove first two migrations from weblate/trans/migrations/0074_auto_20170209_1412.py as they were already applied:

```patch
diff --git a/weblate/trans/migrations/0074_auto_20170209_1412.py b/weblate/trans/migrations/0074_auto_20170209_1412.py
index a8e2987a0..3ad5d7ea1 100644
--- a/weblate/trans/migrations/0074_auto_20170209_1412.py
+++ b/weblate/trans/migrations/0074_auto_20170209_1412.py
@@ -13,14 +13,6 @@ class Migration(migrations.Migration):
     ]
 
     operations = [
-        migrations.RemoveField(
-            model_name='comment',
-            name='contentsum',
-        ),
-        migrations.RemoveField(
-            model_name='suggestion',
-            name='contentsum',
-        ),
         migrations.AlterUniqueTogether(
             name='check',
             unique_together=set([('content_hash', 'project', 'language', 'check')]),
```

**Comment by paour** [comment]
Sorry about that, I misunderstood your earlier instructions (django migrations are black magic to me). Thank you for the detailed steps.
