### ISSUE TITLE
TypeError: int() argument must be a string or a number, not 'tuple'

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1424]
View details in Rollbar: [https://rollbar.com/nijel/weblate/items/985/](https://rollbar.com/nijel/weblate/items/985/)

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nijel/weblate_hosted/weblate/trans/views/edit.py", line 614, in translate
    'addword_form': InlineWordForm(),
  File "/home/nijel/weblate_hosted/weblate/trans/util.py", line 227, in render
    return django_render(request, template, context, status=status)
  File "/usr/lib/python2.7/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python2.7/dist-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python2.7/dist-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/lib/python2.7/dist-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/lib/python2.7/dist-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/lib/python2.7/dist-packages/compressor/templatetags/compress.py", line 127, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/usr/lib/python2.7/dist-packages/compressor/templatetags/compress.py", line 103, in render_compressed
    rendered_output = compressor.output(mode, forced=forced)
  File "/usr/lib/python2.7/dist-packages/compressor/css.py", line 49, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/usr/lib/python2.7/dist-packages/compressor/css.py", line 51, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/compressor/base.py", line 292, in output
    output = '\n'.join(self.filter_input(forced))
  File "/usr/lib/python2.7/dist-packages/compressor/base.py", line 232, in filter_input
    for hunk in self.hunks(forced):
  File "/usr/lib/python2.7/dist-packages/compressor/base.py", line 207, in hunks
    yield self.filter(value, self.cached_filters, **options)
  File "/usr/lib/python2.7/dist-packages/compressor/base.py", line 281, in filter
    content = filter_func(**kwargs)
  File "/usr/lib/python2.7/dist-packages/compressor/filters/css_default.py", line 37, in input
    URL_PATTERN.sub(self.url_converter, self.content))
  File "/usr/lib/python2.7/dist-packages/compressor/filters/css_default.py", line 103, in url_converter
    return self._converter(matchobj, 1, "url(%s%s%s)")
  File "/usr/lib/python2.7/dist-packages/compressor/filters/css_default.py", line 100, in _converter
    return template % (wrap, self.add_suffix(full_url), wrap)
  File "/usr/lib/python2.7/dist-packages/compressor/filters/css_default.py", line 62, in add_suffix
    suffix = get_hashed_mtime(filename)
  File "/usr/lib/python2.7/dist-packages/compressor/cache.py", line 111, in get_hashed_mtime
    mtime = str(int(get_mtime(filename)))
TypeError: int() argument must be a string or a number, not 'tuple'
```

**Comment by nijel** [comment]
Reported at django-compressor to see if it can't be problem there: https://github.com/django-compressor/django-compressor/issues/838
