### ISSUE TITLE
TypeError: 'float' object is not iterable

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1425]
View details in Rollbar: [https://rollbar.com/nijel/weblate/items/983/](https://rollbar.com/nijel/weblate/items/983/)

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/nijel/weblate_hosted/weblate/trans/views/edit.py", line 614, in translate
    'addword_form': InlineWordForm(),
  File "/home/nijel/weblate_hosted/weblate/trans/util.py", line 227, in render
    return django_render(request, template, context, status=status)
  File "/usr/lib/python2.7/dist-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python2.7/dist-packages/django/template/loader.py", line 68, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python2.7/dist-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/lib/python2.7/dist-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/lib/python2.7/dist-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/lib/python2.7/dist-packages/compressor/templatetags/compress.py", line 127, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/usr/lib/python2.7/dist-packages/compressor/templatetags/compress.py", line 99, in render_compressed
    cache_key, cache_content = self.render_cached(compressor, kind, mode)
  File "/usr/lib/python2.7/dist-packages/compressor/templatetags/compress.py", line 79, in render_cached
    cache_content = cache_get(cache_key)
  File "/usr/lib/python2.7/dist-packages/compressor/cache.py", line 136, in cache_get
    val, refresh_time, refreshed = packed_val
TypeError: 'float' object is not iterable
```

**Comment by nijel** [comment]
Probably same cause as #1424.
