### ISSUE TITLE
Migration dependencies reference nonexistent parent node

### ISSUE THREAD

**Issue by lz1irq** [WeblateOrg/weblate#1430]
### Steps to reproduce

Using Debian Jessie 64-bit.

```
apt install libxml2-dev libxslt-dev libfreetype6-dev libjpeg-dev libz-dev libyaml-dev python-dev git libpq-dev postgresql-9.4 memcached
apt-get install python-pip python-virtualenv
virtualenv /opt/weblate/env
source /opt/weblate/env/bin/activate
pip install Weblate python-bidi PyYaML Babel pyuca pylibravatar pydns psycopg2 python-memcached
export PYTHONPATH=/opt/weblate/env
export DJANGO_SETTINGS_MODULE=weblate.settings
cd /opt/weblate
weblate migrate
```

### Actual behaviour
```
(env)root@translate:/opt/weblate# weblate migrate
Traceback (most recent call last):
  File "/opt/weblate/env/bin/weblate", line 9, in <module>
    load_entry_point('Weblate==2.12', 'console_scripts', 'weblate')()
  File "/opt/weblate/env/local/lib/python2.7/site-packages/weblate/runner.py", line 33, in main
    execute_from_command_line(argv)
  File "/opt/weblate/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/opt/weblate/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/weblate/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/weblate/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/weblate/env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/opt/weblate/env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/opt/weblate/env/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/opt/weblate/env/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 274, in build_graph
    raise exc
django.db.migrations.exceptions.NodeNotFoundError: Migration trans.0075_auto_20170215_1750 dependencies reference nonexistent parent node (u'screenshots', u'0002_auto_20170215_0849')
```

### Expected behaviour
I expect the initial migrations to initialize the database structure.

### Server configuration
```
 * Weblate 2.12
 * Python 2.7.9
 * Django 1.11
 * six 1.10.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.1.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.7.3
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.6.2
 * pytz 2017.2
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Database backends: django.db.backends.postgresql_psycopg2
```

### Other
I've tried the various other options of installing Weblate (e.g. from git with virtualenv for the dependencies, or installing them systemwide), and I get this error every time. The table `django_migrations` is created in the database, but nothing after that. Also, the migration Django claims is non-existent, is actually there - the file `0002_auto_20170215_0849.py` exists in `/opt/weblate/env/lib/python2.7/site-packages/weblate/screenshots/migrations` (or the respective path when installing from git).

**Comment by nijel** [comment]
What is your settings.py? Does it contain screenshots app?

**Comment by lz1irq** [comment]
Here is a sanitized version of settings.py: https://gist.github.com/lz1irq/557eff65fe4db0a77925f701da0f6fb2

It does not say anything about the screenshots app.

**Comment by nijel** [comment]
The configuration is probably from older Weblate, adjust INSTALLED_APPS to include 'weblate.screenshots',. There might be more things to adjust, check [sample configuration](https://docs.weblate.org/en/weblate-2.12/admin/sample.html) and [upgrading instructions](https://docs.weblate.org/en/weblate-2.12/admin/upgrade.html#upgrade-from-2-11-to-2-12).
