### ISSUE TITLE
GroupACL migration failed on permissions.0006_auto_20170404_1637

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1489]
When trying to migrate https://l10n.opensuse.org/ in a cloned instance from 2.6 to 2.13.1, I experienced a migration failure.

Note that GroupACL were actively used. 16 languages and two projects (zypper, libzypp) has 32 rules in format:
language | project | SLE Review Team, SLE Translators
SLE Review Team, SLE Translators are two groups with access to projects in particular languages

I can make test instance with all these rules deleted.

### Steps to reproduce
1. Migrate 2.6 to intermediate 2.10 with upgraded python-social-auth-0.2.21; direct migration from 2.6 + python-social-auth-0.2.7 is not possible. Went OK.
2. Migrate 2.10 to 2.13.1 by ./manage.py migrate

### Actual behaviour
  Applying permissions.0006_auto_20170404_1637...Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/migration.py", line 126, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 189, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/usr/share/weblate/weblate/permissions/migrations/0006_auto_20170404_1637.py", line 40, in migrate_acl
    group_acl = GroupACL.objects.get_or_create(project=project)[0]
  File "/usr/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 473, in get_or_create
    return self.get(**lookup), False
  File "/usr/lib/python2.7/site-packages/django/db/models/query.py", line 389, in get
    (self.model._meta.object_name, num)
__fake__.MultipleObjectsReturned: get() returned more than one GroupACL -- it returned 16!

### Expected behaviour
Success.

### Server configuration
 * Weblate 2.13.1
 * Python 2.7.12
 * Django 1.10.5
 * six 1.9.0
 * social-auth-core 1.2.0
 * social-auth-app-django 1.1.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.0.0
 * Whoosh 2.7.0
 * defusedxml 0.4.1
 * Git 2.12.0
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.6.1
 * django-crispy-forms 1.6.1
 * compressor 2.1.1
 * djangorestframework 3.5.3
 * pytz 2015.2
 * pyuca N/A
 * PyYAML 3.11
 * Mercurial 3.8.3
 * git-svn 2.12.0
 * git-review 1.25.0
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
This should be fixed since 1c7cd65bfcb73ccd87a25224133921baf141c964. Still there might be some corner cases as described in #1480.
