### ISSUE TITLE
TypeError when creating new component w/ QT Linguist file-format

### ISSUE THREAD

**Issue by tc77** [WeblateOrg/weblate#1490]
### Steps to reproduce
1. Trying to add a new (the first one) component to a project which uses QT Linguist as file-format

### Actual behaviour
`TypeError`, see below

```
weblate_1   | ERROR Internal Server Error: /admin/trans/subproject/add/
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
weblate_1   |     response = get_response(request)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
weblate_1   |     response = self._get_response(request)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
weblate_1   |     response = self.process_exception_by_middleware(e, request)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
weblate_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 551, in wrapper
weblate_1   |     return self.admin_site.admin_view(view)(*args, **kwargs)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
weblate_1   |     response = view_func(request, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
weblate_1   |     response = view_func(request, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 224, in inner
weblate_1   |     return view(request, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1508, in add_view
weblate_1   |     return self.changeform_view(request, None, form_url, extra_context)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 67, in _wrapper
weblate_1   |     return bound_func(*args, **kwargs)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
weblate_1   |     response = view_func(request, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 63, in bound_func
weblate_1   |     return func.__get__(self, type(self))(*args2, **kwargs2)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1408, in changeform_view
weblate_1   |     return self._changeform_view(request, object_id, form_url, extra_context)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1448, in _changeform_view
weblate_1   |     self.save_model(request, new_object, form, not add)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 979, in save_model
weblate_1   |     obj.save()
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/trans/models/subproject.py", line 1412, in save
weblate_1   |     self.create_translations()
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/trans/models/subproject.py", line 1026, in create_translations
weblate_1   |     self, lang, code, path, force, request=request
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/trans/models/translation.py", line 79, in check_sync
weblate_1   |     translation.check_sync(force, request=request)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/trans/models/translation.py", line 453, in check_sync
weblate_1   |     self, unit, pos
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/trans/models/unit.py", line 113, in update_from_unit
weblate_1   |     dbunit.update_from_unit(unit, pos, created)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/trans/models/unit.py", line 438, in update_from_unit
weblate_1   |     location = unit.get_locations()
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/trans/formats.py", line 151, in get_locations
weblate_1   |     result = ', '.join(self.mainunit.getlocations())
weblate_1   | TypeError: sequence item 0: expected string or Unicode, NoneType found
weblate_1   | Internal Server Error: /admin/trans/subproject/add/
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
weblate_1   |     response = get_response(request)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
weblate_1   |     response = self._get_response(request)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
weblate_1   |     response = self.process_exception_by_middleware(e, request)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
weblate_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 551, in wrapper
weblate_1   |     return self.admin_site.admin_view(view)(*args, **kwargs)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
weblate_1   |     response = view_func(request, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
weblate_1   |     response = view_func(request, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 224, in inner
weblate_1   |     return view(request, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1508, in add_view
weblate_1   |     return self.changeform_view(request, None, form_url, extra_context)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 67, in _wrapper
weblate_1   |     return bound_func(*args, **kwargs)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 149, in _wrapped_view
weblate_1   |     response = view_func(request, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/utils/decorators.py", line 63, in bound_func
weblate_1   |     return func.__get__(self, type(self))(*args2, **kwargs2)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1408, in changeform_view
weblate_1   |     return self._changeform_view(request, object_id, form_url, extra_context)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 1448, in _changeform_view
weblate_1   |     self.save_model(request, new_object, form, not add)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/options.py", line 979, in save_model
weblate_1   |     obj.save()
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/trans/models/subproject.py", line 1412, in save
weblate_1   |     self.create_translations()
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/trans/models/subproject.py", line 1026, in create_translations
weblate_1   |     self, lang, code, path, force, request=request
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/trans/models/translation.py", line 79, in check_sync
weblate_1   |     translation.check_sync(force, request=request)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/trans/models/translation.py", line 453, in check_sync
weblate_1   |     self, unit, pos
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/trans/models/unit.py", line 113, in update_from_unit
weblate_1   |     dbunit.update_from_unit(unit, pos, created)
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/trans/models/unit.py", line 438, in update_from_unit
weblate_1   |     location = unit.get_locations()
weblate_1   |   File "/usr/local/lib/python2.7/dist-packages/weblate/trans/formats.py", line 151, in get_locations
weblate_1   |     result = ', '.join(self.mainunit.getlocations())
weblate_1   | TypeError: sequence item 0: expected string or Unicode, NoneType found
```

### Expected behaviour
I expected there to be a new component.

### Server configuration
I am using the Docker container from https://github.com/WeblateOrg/docker with Weblate 2.14

**Comment by nijel** [comment]
I guess that your ts file contains empty location tags such as `<location />`, am I right?

**Comment by nijel** [comment]
I've fixed this case in Weblate and submitted fix to translate-toolkit as well in https://github.com/translate/translate/pull/3624

**Comment by tc77** [comment]
@nijel Yes you are right and AFAIK that's always the case.

Just had a look at the spec (http://doc.qt.io/qt-4.8/linguist-ts-file-format.html):
```
<!ELEMENT location EMPTY>
<!ATTLIST location
          filename CDATA #IMPLIED
          line CDATA #IMPLIED>
```

Thank you!

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
