### ISSUE TITLE
Weblate fails to close database connections in time

### ISSUE THREAD

**Issue by ieugen** [WeblateOrg/weblate#1576]
### Steps to reproduce
1. Have weblate working for some time with translators
2. 
3.

In order to fix this I have to restart postgresql to force all connections to close (I also restart uwsgi). 
I have added a cron to restart the database once a day but it seems not to work.

I believe the issue appears when we run git pull for the translations. We have around 20 components. 

### Actual behaviour

Weblate hangs with 500 error page. 

````
Linux aaa 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux
````

uwsgi configuration
````
[uwsgi]
plugins       = python
master        = true
protocol      = uwsgi
socket        = 127.0.0.1:8085
chdir         = /var/www/weblate/weblate
wsgi-file     = /var/www/weblate/weblate/wsgi.py
python-path   = /var/www/weblate
# Needed for OAuth/OpenID
buffer-size   = 8192
# Increase number of workers for heavily loaded sites
workers       = 3
# Needed for background processing
enable-threads = true
# Child processes do not need file descriptors
close-on-exec = true
# Avoid default 0000 umask
umask = 0022
````

seetings.py
````
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'weblate',
        'USER': 'weblate',
        'PASSWORD': 'secure',
        'HOST': '127.0.0.1',     
        'PORT': '',
    }
}
````

````
ytes in 20 msecs (HTTP/1.1 200) 9 headers in 303 bytes (1 switches on core 0)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 170, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 86, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 124, in handle_uncaught_exception
    extra={'status_code': 500, 'request': request},
  File "/usr/lib/python2.7/logging/__init__.py", line 1186, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1279, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1289, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1329, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 757, in handle
    self.emit(record)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/log.py", line 119, in emit
    message = "%s\n\n%s" % (self.format(no_exc_record), reporter.get_traceback_text())
  File "/usr/local/lib/python2.7/dist-packages/django/views/debug.py", line 334, in get_traceback_text
    c = Context(self.get_traceback_data(), autoescape=False, use_l10n=False)
  File "/usr/local/lib/python2.7/dist-packages/django/views/debug.py", line 304, in get_traceback_data
    'filtered_POST': self.filter.get_post_parameters(self.request),
  File "/var/www/weblate/weblate/trans/debug.py", line 35, in get_post_parameters
    'django_language' in request.session):
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 54, in __contains__
    return key in self._session
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/base.py", line 207, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/sessions/backends/db.py", line 35, in load
    expire_date__gt=timezone.now()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 379, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 238, in __len__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 833, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 233, in cursor
    cursor = self.make_cursor(self._cursor())
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 204, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 199, in ensure_connection
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/base.py", line 171, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
django.db.utils.OperationalError: FATAL:  remaining connection slots are reserved for non-replication superuser connections
````

### Expected behaviour
Tell us what should happen

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

**Comment by nijel** [comment]
The Django uwsgi workers should reuse the connections and I've never seen this error so far. Did you configure the persistent connections somehow? See also https://docs.djangoproject.com/en/1.11/ref/databases/#persistent-connections

Aren't there some background jobs (eg. executed by cron) consuming the connections?

**Comment by ieugen** [comment]
Answering (late, sorry) so the info is here: Weblate was alone on the VM, no other service was running. 

My crontab looks like this: 

````
@daily service postgresql restart
@daily service uwsgi restart
# Commit pending changes after 96 hours
@hourly cd /var/www/weblate/; ./manage.py commit_pending --all --age=12 --verbosity=0
@hourly chown -R www-data:www-data /var/lib/weblate/vcs
````

The restarts are there to make sure the connections are reset/closed, as a way to avoid this isssue. It did not work that much. 

I ended up increasing postgresql max connections to 200. 
In retrospect, it might be related to the fact that we where not using shared repositories and when updating git - that created an avalanche of parallel Weblate updates that caused the connections to be used up.
