### ISSUE TITLE
manage.py migrate: ImportError: cannot import name WeblateGroupAdmin

### ISSUE THREAD

**Issue by romanr** [WeblateOrg/weblate#1581]
Please help, what can I do, this message appears on any `./manage.py` command

### Steps to reproduce

```
./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/django/weblate/weblate/admin.py", line 41, in <module>
ImportError: cannot import name WeblateGroupAdmin
```

### Server configuration

```
./manage.py list_versions
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/django/weblate/weblate/admin.py", line 41, in <module>
ImportError: cannot import name WeblateGroupAdmin

```

**Comment by nijel** [comment]
Does ``./manage.py shell`` work for you? 

It if does, can you try running ``import weblate.accounts.admin`` from there?

If not, can you run the command as ``python -v ./manage.py shell``?

**Comment by romanr** [comment]
Thank you for answering!

./manage.py shell is same error.


`python -v ./manage.py shell` output:
```
python -v ./manage.py shell
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# /usr/lib/python2.7/site.pyc matches /usr/lib/python2.7/site.py
import site # precompiled from /usr/lib/python2.7/site.pyc
# /usr/lib/python2.7/os.pyc matches /usr/lib/python2.7/os.py
import os # precompiled from /usr/lib/python2.7/os.pyc
import errno # builtin
import posix # builtin
# /usr/lib/python2.7/posixpath.pyc matches /usr/lib/python2.7/posixpath.py
import posixpath # precompiled from /usr/lib/python2.7/posixpath.pyc
# /usr/lib/python2.7/stat.pyc matches /usr/lib/python2.7/stat.py
import stat # precompiled from /usr/lib/python2.7/stat.pyc
# /usr/lib/python2.7/genericpath.pyc matches /usr/lib/python2.7/genericpath.py
import genericpath # precompiled from /usr/lib/python2.7/genericpath.pyc
# /usr/lib/python2.7/warnings.pyc matches /usr/lib/python2.7/warnings.py
import warnings # precompiled from /usr/lib/python2.7/warnings.pyc
# /usr/lib/python2.7/linecache.pyc matches /usr/lib/python2.7/linecache.py
import linecache # precompiled from /usr/lib/python2.7/linecache.pyc
# /usr/lib/python2.7/types.pyc matches /usr/lib/python2.7/types.py
import types # precompiled from /usr/lib/python2.7/types.pyc
# /usr/lib/python2.7/UserDict.pyc matches /usr/lib/python2.7/UserDict.py
import UserDict # precompiled from /usr/lib/python2.7/UserDict.pyc
# /usr/lib/python2.7/_abcoll.pyc matches /usr/lib/python2.7/_abcoll.py
import _abcoll # precompiled from /usr/lib/python2.7/_abcoll.pyc
# /usr/lib/python2.7/abc.pyc matches /usr/lib/python2.7/abc.py
import abc # precompiled from /usr/lib/python2.7/abc.pyc
# /usr/lib/python2.7/_weakrefset.pyc matches /usr/lib/python2.7/_weakrefset.py
import _weakrefset # precompiled from /usr/lib/python2.7/_weakrefset.pyc
import _weakref # builtin
# /usr/lib/python2.7/copy_reg.pyc matches /usr/lib/python2.7/copy_reg.py
import copy_reg # precompiled from /usr/lib/python2.7/copy_reg.pyc
# /usr/lib/python2.7/traceback.pyc matches /usr/lib/python2.7/traceback.py
import traceback # precompiled from /usr/lib/python2.7/traceback.pyc
# /usr/lib/python2.7/sysconfig.pyc matches /usr/lib/python2.7/sysconfig.py
import sysconfig # precompiled from /usr/lib/python2.7/sysconfig.pyc
# /usr/lib/python2.7/re.pyc matches /usr/lib/python2.7/re.py
import re # precompiled from /usr/lib/python2.7/re.pyc
# /usr/lib/python2.7/sre_compile.pyc matches /usr/lib/python2.7/sre_compile.py
import sre_compile # precompiled from /usr/lib/python2.7/sre_compile.pyc
import _sre # builtin
# /usr/lib/python2.7/sre_parse.pyc matches /usr/lib/python2.7/sre_parse.py
import sre_parse # precompiled from /usr/lib/python2.7/sre_parse.pyc
# /usr/lib/python2.7/sre_constants.pyc matches /usr/lib/python2.7/sre_constants.py
import sre_constants # precompiled from /usr/lib/python2.7/sre_constants.pyc
# /usr/lib/python2.7/_sysconfigdata.pyc matches /usr/lib/python2.7/_sysconfigdata.py
import _sysconfigdata # precompiled from /usr/lib/python2.7/_sysconfigdata.pyc
# /usr/lib/python2.7/_sysconfigdata_nd.pyc matches /usr/lib/python2.7/_sysconfigdata_nd.py
import _sysconfigdata_nd # precompiled from /usr/lib/python2.7/_sysconfigdata_nd.pyc
# /usr/lib/python2.7/sitecustomize.pyc matches /usr/lib/python2.7/sitecustomize.py
import sitecustomize # precompiled from /usr/lib/python2.7/sitecustomize.pyc
import encodings # directory /usr/lib/python2.7/encodings
# /usr/lib/python2.7/encodings/__init__.pyc matches /usr/lib/python2.7/encodings/__init__.py
import encodings # precompiled from /usr/lib/python2.7/encodings/__init__.pyc
# /usr/lib/python2.7/codecs.pyc matches /usr/lib/python2.7/codecs.py
import codecs # precompiled from /usr/lib/python2.7/codecs.pyc
import _codecs # builtin
# /usr/lib/python2.7/encodings/aliases.pyc matches /usr/lib/python2.7/encodings/aliases.py
import encodings.aliases # precompiled from /usr/lib/python2.7/encodings/aliases.pyc
# /usr/lib/python2.7/encodings/utf_8.pyc matches /usr/lib/python2.7/encodings/utf_8.py
import encodings.utf_8 # precompiled from /usr/lib/python2.7/encodings/utf_8.pyc
Python 2.7.3 (default, Jun 21 2016, 18:38:19)
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
import django # directory /usr/local/lib/python2.7/dist-packages/django
# /usr/local/lib/python2.7/dist-packages/django/__init__.pyc matches /usr/local/lib/python2.7/dist-packages/django/__init__.py
import django # precompiled from /usr/local/lib/python2.7/dist-packages/django/__init__.pyc
# /usr/lib/python2.7/__future__.pyc matches /usr/lib/python2.7/__future__.py
import __future__ # precompiled from /usr/lib/python2.7/__future__.pyc
import django.utils # directory /usr/local/lib/python2.7/dist-packages/django/utils
# /usr/local/lib/python2.7/dist-packages/django/utils/__init__.pyc matches /usr/local/lib/python2.7/dist-packages/django/utils/__init__.py
import django.utils # precompiled from /usr/local/lib/python2.7/dist-packages/django/utils/__init__.pyc
# /usr/local/lib/python2.7/dist-packages/django/utils/version.pyc matches /usr/local/lib/python2.7/dist-packages/django/utils/version.py
import django.utils.version # precompiled from /usr/local/lib/python2.7/dist-packages/django/utils/version.pyc
dlopen("/usr/lib/python2.7/lib-dynload/datetime.so", 2);
import datetime # dynamically loaded from /usr/lib/python2.7/lib-dynload/datetime.so
# /usr/lib/python2.7/subprocess.pyc matches /usr/lib/python2.7/subprocess.py
import subprocess # precompiled from /usr/lib/python2.7/subprocess.pyc
import gc # builtin
import time # builtin

..... skip... 


# /usr/local/lib/python2.7/dist-packages/crispy_forms/bootstrap.pyc matches /usr/local/lib/python2.7/dist-packages/crispy_forms/bootstrap.py
import crispy_forms.bootstrap # precompiled from /usr/local/lib/python2.7/dist-packages/crispy_forms/bootstrap.pyc
# /var/www/django/weblate/weblate/accounts/captcha.pyc matches /var/www/django/weblate/weblate/accounts/captcha.py
import weblate.accounts.captcha # precompiled from /var/www/django/weblate/weblate/accounts/captcha.pyc
# /usr/lib/python2.7/ast.pyc matches /usr/lib/python2.7/ast.py
import ast # precompiled from /usr/lib/python2.7/ast.pyc
import _ast # builtin
# /var/www/django/weblate/weblate/utils/admin.pyc matches /var/www/django/weblate/weblate/utils/admin.py
import weblate.utils.admin # precompiled from /var/www/django/weblate/weblate/utils/admin.pyc
import weblate.admin # precompiled from /var/www/django/weblate/weblate/admin.pyc
# /usr/local/lib/python2.7/dist-packages/django/contrib/auth/views.pyc matches /usr/local/lib/python2.7/dist-packages/django/contrib/auth/views.py
import django.contrib.auth.views # precompiled from /usr/local/lib/python2.7/dist-packages/django/contrib/auth/views.pyc
# /usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.pyc matches /usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py
import django.contrib.auth.decorators # precompiled from /usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.pyc
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 337, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/apps.py", line 23, in ready
    self.module.autodiscover()
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/django/weblate/weblate/admin.py", line 41, in <module>
ImportError: cannot import name WeblateGroupAdmin
# clear __builtin__._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.exitfunc
# clear sys.exc_type
# clear sys.exc_value
# clear sys.exc_traceback
# clear sys.last_type
# clear sys.last_value
```

**Comment by romanr** [comment]
I am using weblate 2.10 and was making this check before upgrading to latest.

**Comment by nijel** [comment]
Can you try cleaning up cached byte-compiled python files: ``find . -name '*.pyc' -delete``?

PS: There was no weblate/admin.py file in the 2.10 release, are you sure you haven't mixed your sources with newever version?

**Comment by romanr** [comment]
Yes that's right, I attempted to upgrade and rolled back, which caused pyc files to get mixed up. Sorry about that.
Now it cleared out and I get error:

```
./manage.py list_versions
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/django/weblate/weblate/urls.py", line 34, in <module>
    import weblate.accounts.views
  File "/var/www/django/weblate/weblate/accounts/views.py", line 45, in <module>
    from social.apps.django_app.utils import BACKENDS
  File "/usr/local/lib/python2.7/dist-packages/social/apps/django_app/utils.py", line 1, in <module>
    from social_django.utils import load_strategy, load_backend, psa, setting, BackendWrapper, strategy
ImportError: cannot import name strategy
```

all deps seem to be installed ok:

```
pip install -r requirements.txt
Requirement already satisfied: Django>=1.9 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Requirement already satisfied: Whoosh!=2.6.0,>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2))
Requirement already satisfied: translate-toolkit>=2.0.0b4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4))
Requirement already satisfied: Pillow in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
Requirement already satisfied: six>=1.7.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
Requirement already satisfied: python-dateutil in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied: python-social-auth>=0.2.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
Requirement already satisfied: django-crispy-forms>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
Requirement already satisfied: oauthlib>=0.6.3 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10))
Requirement already satisfied: django_compressor!=2.0,>=1.5.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
Requirement already satisfied: djangorestframework>=3.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12))
Requirement already satisfied: defusedxml>=0.4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13))
Requirement already satisfied: pytz in /usr/local/lib/python2.7/dist-packages (from Django>=1.9->-r requirements.txt (line 1))
Requirement already satisfied: diff-match-patch==20121119 in /usr/local/lib/python2.7/dist-packages (from translate-toolkit>=2.0.0b4->-r requirements.txt (line 3))
Requirement already satisfied: social-auth-core in /usr/local/lib/python2.7/dist-packages (from python-social-auth>=0.2.0->-r requirements.txt (line 8))
Requirement already satisfied: django-appconf>=1.0 in /usr/local/lib/python2.7/dist-packages (from django_compressor!=2.0,>=1.5.0->-r requirements.txt (line 11))
Requirement already satisfied: rcssmin==1.0.6 in /usr/local/lib/python2.7/dist-packages (from django_compressor!=2.0,>=1.5.0->-r requirements.txt (line 11))
Requirement already satisfied: rjsmin==1.0.12 in /usr/local/lib/python2.7/dist-packages (from django_compressor!=2.0,>=1.5.0->-r requirements.txt (line 11))
Requirement already satisfied: python-openid>=2.2.5 in /usr/local/lib/python2.7/dist-packages (from social-auth-core->python-social-auth>=0.2.0->-r requirements.txt (line 8))
Requirement already satisfied: requests-oauthlib>=0.6.1 in /usr/local/lib/python2.7/dist-packages (from social-auth-core->python-social-auth>=0.2.0->-r requirements.txt (line 8))
Requirement already satisfied: requests>=2.9.1 in /usr/local/lib/python2.7/dist-packages (from social-auth-core->python-social-auth>=0.2.0->-r requirements.txt (line 8))
Requirement already satisfied: PyJWT>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from social-auth-core->python-social-auth>=0.2.0->-r requirements.txt (line 8))
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests>=2.9.1->social-auth-core->python-social-auth>=0.2.0->-r requirements.txt (line 8))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests>=2.9.1->social-auth-core->python-social-auth>=0.2.0->-r requirements.txt (line 8))
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests>=2.9.1->social-auth-core->python-social-auth>=0.2.0->-r requirements.txt (line 8))
Requirement already satisfied: idna<2.6,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests>=2.9.1->social-auth-core->python-social-auth>=0.2.0->-r requirements.txt (line 8))
```

**Comment by nijel** [comment]
See instructions for upgrading: https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-2-10-to-2-11, unfortunately python-social-auth has made incompatible changes.

First install old version on 2.10: ``pip install python-social-auth==0.2.21``, let it do the migration and then continue in upgrading Weblate.

**Comment by romanr** [comment]
Thank you os much! it worked.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
