### ISSUE TITLE
Failed migration from 2.11 to 2.12

### ISSUE THREAD

**Issue by Pitel** [WeblateOrg/weblate#1631]
### Steps to reproduce
1. `git checkout weblate-2.12`
2. Update `config.py`
3. `./manage.py migrate --noinput`

### Actual behaviour
```
Operations to perform:
  Apply all migrations: accounts, admin, auth, authtoken, contenttypes, lang, screenshots, sessions, sites, social_django, trans
Running migrations:
  Applying accounts.0025_auto_20170211_1609... OK
  Applying accounts.0026_profile_special_chars... OK
  Applying accounts.0027_merge_20170913_1539... OK
  Applying trans.0072_auto_20170209_1234... OK
  Applying trans.0073_auto_20170209_1359... OK
  Applying trans.0074_auto_20170209_1412...Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 536, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "/usr/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 353, in alter_unique_together
    self.execute(self._create_unique_sql(model, columns))
  File "/usr/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 120, in execute
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.IntegrityError: (1062, "Duplicate entry '-3979142367816790127-20-99-same' for key 'trans_check_content_hash_project_id__f5590916_uniq'")
```

And now when I try to run migrations again, I get

```
Operations to perform:
  Apply all migrations: accounts, admin, auth, authtoken, contenttypes, lang, screenshots, sessions, sites, social_django, trans
Running migrations:
  Applying trans.0074_auto_20170209_1412...Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 155, in database_forwards
    schema_editor.remove_field(from_model, from_model._meta.get_field(self.name))
  File "/usr/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 471, in remove_field
    self.execute(sql)
  File "/usr/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 120, in execute
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1091, "Can't DROP 'contentsum'; check that column/key exists")
```

I found similiar issue #1417 and when I tired to apply the patch mentioned here and commented out the 2 migrations, I get this:

```
Operations to perform:
  Apply all migrations: accounts, admin, auth, authtoken, contenttypes, lang, screenshots, sessions, sites, social_django, trans
Running migrations:
  Applying trans.0074_auto_20170209_1412...Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 536, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "/usr/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 349, in alter_unique_together
    self._delete_composed_index(model, fields, {'unique': True}, self.sql_delete_unique)
  File "/usr/lib/python2.7/site-packages/django/db/backends/mysql/schema.py", line 88, in _delete_composed_index
    return super(DatabaseSchemaEditor, self)._delete_composed_index(model, fields, *args)
  File "/usr/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 378, in _delete_composed_index
    ", ".join(columns),
ValueError: Found wrong number (0) of constraints for trans_check(contentsum, project_id, language_id, check)
```

### Expected behaviour
Migration finishes without error

### Server configuration
 * Weblate weblate-2.12
 * Python 2.7.5
 * Django 1.11.5
 * six 1.9.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.2
 * defusedxml 0.5.0
 * Git 1.8.3.1
 * Pillow (PIL) 1.1.7
 * dateutil 1.5
 * lxml 3.2.1
 * django-crispy-forms 1.6.1
 * compressor 2.2
 * djangorestframework 3.6.4
 * pytz 2017.2
 * pyuca N/A
 * Database backends: django.db.backends.mysql

**Comment by nijel** [comment]
See also https://github.com/WeblateOrg/weblate/issues/1417

The problem is that Django is now strict on order of constraints, but it didn't used to be in the past and created some of them in wrong order (maybe it was South, but it really doesn't matter now). 

The workaround is to patch Django to ignore ordering for constraints, see https://github.com/WeblateOrg/weblate/issues/1417#issuecomment-287784714, Django upstream isn't going to fix this, see https://code.djangoproject.com/ticket/27826 and https://code.djangoproject.com/ticket/23906

**Comment by Pitel** [comment]
I said I already did it, but it didn't helped.

**Comment by nijel** [comment]
Can you please dump the constraints in the database for the trans_check table? Maybe the initial setup didn't work correctly for you for whatever reason. Also do you remember what Weblate version did you install first?

**Comment by Pitel** [comment]
How can I dump the constraints?

I've started the migrations from some version between 2.5 and 2.6. But I've inherited from my coleague and I don't know what he did couple of years ago.

**Comment by nijel** [comment]
You can do that in the SQL, for example you can start SQL session by `./manage.py dbshell
` and then `SHOW CREATE TABLE trans_check`.

**Comment by Pitel** [comment]
```
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 1300
Server version: 5.5.52-MariaDB MariaDB Server

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [weblate]> SHOW CREATE TABLE trans_check;
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table       | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| trans_check | CREATE TABLE `trans_check` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `contentsum` varchar(40) NOT NULL,
  `check` varchar(20) NOT NULL,
  `ignore` tinyint(1) NOT NULL,
  `language_id` int(11) DEFAULT NULL,
  `project_id` int(11) NOT NULL,
  `content_hash` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `trans_check_language_id_346f512c_fk_lang_language_id` (`language_id`),
  KEY `trans_check_66551423` (`contentsum`),
  KEY `trans_check_567bc1d2` (`ignore`),
  KEY `trans_check_b098ad43` (`project_id`),
  KEY `trans_check_content_hash_ea5724e1` (`content_hash`),
  CONSTRAINT `trans_check_language_id_346f512c_fk_lang_language_id` FOREIGN KEY (`language_id`) REFERENCES `lang_language` (`id`),
  CONSTRAINT `trans_check_project_id_b0266166_fk_trans_project_id` FOREIGN KEY (`project_id`) REFERENCES `trans_project` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=20907 DEFAULT CHARSET=utf8 |
+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by nijel** [comment]
Hmm, indeed the index is missing there. I really wonder how the database got to this shape, but we're probably not able to figure this out.

Anyway following SQL should create it in a way it should have existed:

```mysql
ALTER TABLE trans_check ADD INDEX (`contentsum`, `project_id`, `language_id`, `check`);
```

**Comment by Pitel** [comment]
Thanks, the `contentsum` is now here:
```
+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table       | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| trans_check | CREATE TABLE `trans_check` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `contentsum` varchar(40) NOT NULL,
  `check` varchar(20) NOT NULL,
  `ignore` tinyint(1) NOT NULL,
  `language_id` int(11) DEFAULT NULL,
  `project_id` int(11) NOT NULL,
  `content_hash` bigint(20) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `trans_check_language_id_346f512c_fk_lang_language_id` (`language_id`),
  KEY `trans_check_66551423` (`contentsum`),
  KEY `trans_check_567bc1d2` (`ignore`),
  KEY `trans_check_b098ad43` (`project_id`),
  KEY `trans_check_content_hash_ea5724e1` (`content_hash`),
  KEY `contentsum` (`contentsum`,`project_id`,`language_id`,`check`),
  CONSTRAINT `trans_check_language_id_346f512c_fk_lang_language_id` FOREIGN KEY (`language_id`) REFERENCES `lang_language` (`id`),
  CONSTRAINT `trans_check_project_id_b0266166_fk_trans_project_id` FOREIGN KEY (`project_id`) REFERENCES `trans_project` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=20907 DEFAULT CHARSET=utf8 |
+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

But the issues are still the same. If I don't comment the first 2 migrations, I get 
```
django.db.utils.OperationalError: (1091, "Can't DROP 'contentsum'; check that column/key exists")
```

If I comment them out, I get
```
ValueError: Found wrong number (0) of constraints for trans_check(contentsum, project_id, language_id, check)
```

And it doesn't matter if I have [the patch](https://code.djangoproject.com/attachment/ticket/27826/columns-ordering.patch) applied or not. I even try to remove .pyc file.

**Comment by nijel** [comment]
Sorry, it should have been:

```mysql
# Remove the wrongly created one
ALTER TABLE trans_check DROP INDEX (`contentsum`, `project_id`, `language_id`, `check`);
# Create correct unique index
ALTER TABLE trans_check ADD UNIQUE (`contentsum`, `project_id`, `language_id`, `check`);
```

**Comment by Pitel** [comment]
When I added the `UNIQUE` constraint, I get this error again
```
django.db.utils.IntegrityError: (1062, "Duplicate entry '-3979142367816790127-20-99-same' for key 'trans_check_content_hash_project_id__f5590916_uniq'")
```

...and when run migratins again, I get again
```
ValueError: Found wrong number (0) of constraints for trans_check(contentsum, project_id, language_id, check)
```

**Comment by Pitel** [comment]
```
MariaDB [weblate]> select * from trans_check where content_hash = -3979142367816790127 and language_id = 99;
+------+----------------------------------+-------+--------+-------------+------------+----------------------+
| id   | contentsum                       | check | ignore | language_id | project_id | content_hash         |
+------+----------------------------------+-------+--------+-------------+------------+----------------------+
| 7685 | 7b5b906b0235098ed98ccfd7ad719c3e | same  |      0 |          99 |         20 | -3979142367816790127 |
| 7856 | 6f602e73e59a34f3b5a90e7667b34780 | same  |      0 |          99 |         20 | -3979142367816790127 |
+------+----------------------------------+-------+--------+-------------+------------+----------------------+
2 rows in set (0.00 sec)
```
Hmm, I don't know what is this table for. Could I maye delete one of those rows?

**Comment by nijel** [comment]
It's quality check flags, so yes, removing them is an option, though I'd like to see why the conflict does exist.

Can you try running following query:

```mysql
select  trans_unit.source, trans_unit.context, trans_unit.contentsum from trans_unit JOIN trans_translation ON trans_unit.translation_id = trans_translation.id  where trans_unit.content_hash = -3979142367816790127 and  trans_translation.language_id = 99
```

**Comment by Pitel** [comment]
```
+------------+---------+----------------------------------+
| source     | context | contentsum                       |
+------------+---------+----------------------------------+
| SkyBuilder | Title   | 6f602e73e59a34f3b5a90e7667b34780 |
| SkyBuilder | Title   | 7b5b906b0235098ed98ccfd7ad719c3e |
+------------+---------+----------------------------------+
2 rows in set (0.00 sec)
```

SkyBuilder is one of our old project which will probably never be touched ever again. So yeah, I might delete those rows from `trans_check`.

**Comment by Pitel** [comment]
Alright, now when I deleted the row, and also plenty of ther suplicates, all from same project, just with different `language_id`, the migrations finally finished. Thak you very much! <3

But, when I try to rerun them again, it says
```
Your models have changes that are not yet reflected in a migration, and so won't be applied.
Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

And when I do, I get those dreaded `contentsum` kays in there

```python
# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0077_auto_20171006_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='contentsum',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='contentsum',
        ),
    ]
```

And finished with error that known error:
```
django.db.utils.OperationalError: (1091, "Can't DROP 'contentsum'; check that column/key exists")
```

Could you please provide me with the `ALTER TABLE`s, so the migrations will finally be happy and I won't have to comment them out every time I run them again in the future?

**Comment by nijel** [comment]
I'm a bit lost - the table structure you've posted doesn't show the contentsum fields.

The warning is sort of expected, see https://docs.weblate.org/en/latest/faq.html#why-do-i-get-a-warning-about-not-reflected-changes-on-database-migration, but you might be getting it because you've commented those two in the actual migration where it should happen.
