### ISSUE TITLE
make akismet dependency optional in the test suite

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#1669]
Akismet is optional requirement for weblate, but mandatory requirement for the test suite in Weblate-2.17.1.

Work, around:
rm weblate/utils/tests/test_antispam.py

### Steps to reproduce
1. Build without akismet installed

### Actual behaviour
```
======================================================================
ERROR: test_akismet_nospam (weblate.utils.tests.test_antispam.SpamTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/httpretty/core.py", line 1057, in wrapper
    return test(*args, **kw)
  File "/usr/lib/python2.7/site-packages/django/test/utils.py", line 205, in inner
    return func(*args, **kwargs)
  File "/home/abuild/rpmbuild/BUILD/Weblate-2.17.1/weblate/utils/tests/test_antispam.py", line 59, in test_akismet_nospam
    self.assertFalse(is_spam('text', HttpRequest()))
  File "/home/abuild/rpmbuild/BUILD/Weblate-2.17.1/weblate/utils/antispam.py", line 30, in is_spam
    from akismet import Akismet
ImportError: No module named akismet

======================================================================
ERROR: test_akismet_spam (weblate.utils.tests.test_antispam.SpamTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/httpretty/core.py", line 1057, in wrapper
    return test(*args, **kw)
  File "/usr/lib/python2.7/site-packages/django/test/utils.py", line 205, in inner
    return func(*args, **kwargs)
  File "/home/abuild/rpmbuild/BUILD/Weblate-2.17.1/weblate/utils/tests/test_antispam.py", line 53, in test_akismet_spam
    self.assertTrue(is_spam('text', HttpRequest()))
  File "/home/abuild/rpmbuild/BUILD/Weblate-2.17.1/weblate/utils/antispam.py", line 30, in is_spam
    from akismet import Akismet
ImportError: No module named akismet

----------------------------------------------------------------------
Ran 1812 tests in 793.228s

FAILED (errors=2, skipped=32)
Destroying test database for alias 'default' (':memory:')...
```
### Expected behaviour
Akismet is optional requirement for weblate. Make it optional for test suite as well.

### Server configuration
N/A
It is a build error of Weblate-2.17.1.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
