### ISSUE TITLE
missed manage.py file after clean install on ubuntu

### ISSUE THREAD

**Issue by mrPsycho** [WeblateOrg/weblate#1795]
### Steps to reproduce
1. install ubuntu 16.04
2. install weblate via ```pip3 install weblate```

### Actual behaviour
there is no manage.py in **/usr/local/lib/python3.5/dist-packages/weblate**

### Expected behaviour
manage.py should exist, so i can do ```./manage.py migrate``` or `./manage.py list_versions`

### Server configuration
it is not applicable.

**Comment by mrPsycho** [comment]
ok. i'm blind: https://docs.weblate.org/en/latest/admin/install.html#installing-weblate-by-pip

but:
```
root@weblate:/usr/local/lib/python3.5/dist-packages# weblate --settings=settings.py migrate
Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 7, in <module>
    from weblate.runner import main
  File "/usr/local/lib/python3.5/dist-packages/weblate/__init__.py", line 23, in <module>
    from weblate.requirements import (
  File "/usr/local/lib/python3.5/dist-packages/weblate/requirements.py", line 29, in <module>
    from weblate.trans.vcs import (
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/vcs.py", line 370, in <module>
    class GitRepository(Repository):
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/vcs.py", line 55, in register_vcs
    if vcs.is_supported():
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/vcs.py", line 281, in is_supported
    version = cls.get_version()
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/vcs.py", line 304, in get_version
    cls._version = cls._get_version()
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/vcs.py", line 531, in _get_version
    return cls._popen(['--version']).split()[-1]
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/vcs.py", line 166, in _popen
    env=cls._getenv(),
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/vcs.py", line 155, in _getenv
    return get_clean_env({'GIT_SSH': get_wrapper_filename()})
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/ssh.py", line 57, in get_wrapper_filename
    md5.update(data_dir('ssh').encode('utf-8'))
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/data.py", line 48, in data_dir
    return os.path.join(settings.DATA_DIR, component)
  File "/usr/local/lib/python3.5/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.5/dist-packages/django/conf/__init__.py", line 41, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DATA_DIR, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

**Comment by mrPsycho** [comment]
another one try:
```
root@weblate:/usr/local/lib/python3.5/dist-packages/weblate# export DJANGO_SETTINGS_MODULE=settings.py
root@weblate:/usr/local/lib/python3.5/dist-packages/weblate# weblate migrate
Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 7, in <module>
    from weblate.runner import main
  File "/usr/local/lib/python3.5/dist-packages/weblate/__init__.py", line 23, in <module>
    from weblate.requirements import (
  File "/usr/local/lib/python3.5/dist-packages/weblate/requirements.py", line 29, in <module>
    from weblate.trans.vcs import (
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/vcs.py", line 370, in <module>
    class GitRepository(Repository):
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/vcs.py", line 55, in register_vcs
    if vcs.is_supported():
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/vcs.py", line 281, in is_supported
    version = cls.get_version()
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/vcs.py", line 304, in get_version
    cls._version = cls._get_version()
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/vcs.py", line 531, in _get_version
    return cls._popen(['--version']).split()[-1]
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/vcs.py", line 166, in _popen
    env=cls._getenv(),
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/vcs.py", line 155, in _getenv
    return get_clean_env({'GIT_SSH': get_wrapper_filename()})
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/ssh.py", line 57, in get_wrapper_filename
    md5.update(data_dir('ssh').encode('utf-8'))
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/data.py", line 48, in data_dir
    return os.path.join(settings.DATA_DIR, component)
  File "/usr/local/lib/python3.5/dist-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.5/dist-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.5/dist-packages/django/conf/__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named 'settings'
```

**Comment by mrPsycho** [comment]
```root@weblate:/usr/local/lib/python3.5/dist-packages/weblate# export DJANGO_SETTINGS_MODULE=weblate.settings
root@weblate:/usr/local/lib/python3.5/dist-packages/weblate# weblate migrate```

now it works.
