### ISSUE TITLE
LDAP doesn't work with python3 on clean ubuntu

### ISSUE THREAD

**Issue by mrPsycho** [WeblateOrg/weblate#1796]
### Steps to reproduce
1. settings.py:
```
AUTHENTICATION_BACKENDS = (
    'django_auth_ldap.backend.LDAPBackend',
    'weblate.accounts.auth.WeblateUserBackend',
)
import ldap
from django_auth_ldap.config import LDAPSearch, NestedActiveDirectoryGroupType

# Binding and connection options
AUTH_LDAP_SERVER_URI = "ldap://192.168.2.100:389"
AUTH_LDAP_BIND_DN = "CN=weblate bind,OU=System Users,DC=example,DC=local"
AUTH_LDAP_BIND_PASSWORD = "pass"
AUTH_LDAP_CONNECTION_OPTIONS = {
    ldap.OPT_DEBUG_LEVEL: 1,
    ldap.OPT_REFERRALS: 0,
}

# User and group search objects and types
AUTH_LDAP_USER_SEARCH = LDAPSearch("OU=Branches,DC=example,DC=local",
    ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)")
AUTH_LDAP_GROUP_SEARCH = LDAPSearch("CN=Groups,DC=example,DC=local",
    ldap.SCOPE_SUBTREE, "(objectClass=group)")
AUTH_LDAP_GROUP_TYPE = NestedActiveDirectoryGroupType()

# Cache settings
AUTH_LDAP_CACHE_GROUPS = True
AUTH_LDAP_GROUP_CACHE_TIMEOUT = 300

# What to do once the user is authenticated
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail"
}
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_staff": ["CN=all,CN=Groups,DC=example,DC=local"]
}
AUTH_LDAP_FIND_GROUP_PERMS = True
```
this is the most complete example. 

### Actual behaviour
i see this error:
```
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python3.5/dist-packages/weblate/accounts/views.py", line 568, in dispatch
    return super(WeblateLoginView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 62, in _wrapper
    return bound_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 58, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/views.py", line 65, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/usr/local/lib/python3.5/dist-packages/django/forms/forms.py", line 179, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.5/dist-packages/django/forms/forms.py", line 174, in errors
    self.full_clean()
  File "/usr/local/lib/python3.5/dist-packages/django/forms/forms.py", line 377, in full_clean
    self._clean_form()
  File "/usr/local/lib/python3.5/dist-packages/django/forms/forms.py", line 404, in _clean_form
    cleaned_data = self.clean()
  File "/usr/local/lib/python3.5/dist-packages/weblate/accounts/forms.py", line 570, in clean
    password=password
  File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/__init__.py", line 70, in authenticate
    user = _authenticate_with_backend(backend, backend_path, request, credentials)
  File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/__init__.py", line 115, in _authenticate_with_backend
    return backend.authenticate(*args, **credentials)
  File "/usr/local/lib/python3.5/dist-packages/django_auth_ldap/backend.py", line 148, in authenticate
    user = self.authenticate_ldap_user(ldap_user, password)
  File "/usr/local/lib/python3.5/dist-packages/django_auth_ldap/backend.py", line 208, in authenticate_ldap_user
    return ldap_user.authenticate(password)
  File "/usr/local/lib/python3.5/dist-packages/django_auth_ldap/backend.py", line 379, in authenticate
    self._get_or_create_user()
  File "/usr/local/lib/python3.5/dist-packages/django_auth_ldap/backend.py", line 634, in _get_or_create_user
    populate_user.send(self.backend.__class__, user=self._user, ldap_user=self)
  File "/usr/local/lib/python3.5/dist-packages/django/dispatch/dispatcher.py", line 178, in send
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.5/dist-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/usr/local/lib/python3.5/dist-packages/weblate/permissions/models.py", line 243, in auto_groups_upon_ldap
    auto_assign_group(user)
  File "/usr/local/lib/python3.5/dist-packages/weblate/permissions/models.py", line 195, in auto_assign_group
    user.groups.add(auto.group)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/fields/related_descriptors.py", line 498, in __get__
    return self.related_manager_cls(instance)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/fields/related_descriptors.py", line 795, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<User: y.n>" needs to have a value for field "id" before this many-to-many relationship can be used.
```

### Expected behaviour
login works without any problems

### Server configuration
```
root@weblate:/usr/local/lib/python3.5/dist-packages/weblate# weblate list_versions
 * Weblate 2.18
 * Python 3.5.2
 * Django 2.0.1
 * six 1.11.0
 * social-auth-core 1.6.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.1
 * lxml 4.1.1
 * django-crispy-forms 1.7.0
 * compressor 2.2
 * djangorestframework 3.7.7
 * pytz 2014.10
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 3.7.3
 * Database backends: django.db.backends.postgresql_psycopg2
```

**Comment by mrPsycho** [comment]
also, link about more details: https://docs.weblate.org/en/latest/admin/auth.html#ldap-authentication 
points to nowhere

**Comment by mrPsycho** [comment]
i reinstalled it from scratch via virtualenv - and 2.18 on python2 doesn't work too :(

have you removed support of it?

**Comment by nijel** [comment]
I've fixed the documentation link in b089f7561dd6f9623835ecf80186787549241da0.

It seems that the django_auth_ldap has changed the semantics of this signal. It is documented as 

> You can perform arbitrary population of your user models by adding listeners to the Django signal: django_auth_ldap.backend.populate_user. This signal is sent after the user object has been created and any configured attribute mapping has been applied (see below).

However in your case it's clear the user has not yet been created. I'll try to figure out when it has been changed and why.

**Comment by nijel** [comment]
I've filed the bug to django_auth_ldap: https://bitbucket.org/illocution/django-auth-ldap/issues/92/the-populate_user-signal-does-not-honor

As a workaround you can downgrade to older version, I'll do the change in docker container...

**Comment by nijel** [comment]
I've adjusted the docs to mention problems with django_auth_ldap 1.3.0.

I'll wait for clarification from django_auth_ldap whether this is intended change. In case it is, it seems that we could remove special casing for django_auth_ldap as it would behave consistently with other authentication backends (the user would be created with all information set).

**Comment by mrPsycho** [comment]
Thanks!

**Comment by mrPsycho** [comment]
1.2.6 works fine with my example from example in first post.
