### ISSUE TITLE
ConfigurationErrorsMiddleware causing error in 2.19

### ISSUE THREAD

**Issue by nikosdion** [WeblateOrg/weblate#1871]
### Steps to reproduce
1. Have a Weblate 2.18 installation
1. Apply the changes in `settings.py` from `settings_example.py` in the 2.19 distribution
1. Run migrations etc per [the fine manual page](https://docs.weblate.org/en/latest/admin/upgrade.html)
1. Reload Apache with `sudo service apache2 reload`
1. Try to access any page on my Weblate installation

### Actual behaviour

Weblate bombs out with the following trace in the Apache error log

```
[Fri Feb 23 09:04:55.384786 2018] [wsgi:error] [pid 23599:tid 140605736867584] [client 192.168.56.1:3865] mod_wsgi (pid=23599): Target WSGI script '/PATH_TO_MY_WEBLATE/weblate/wsgi.py' cannot be loaded as Python module.
[Fri Feb 23 09:04:55.384856 2018] [wsgi:error] [pid 23599:tid 140605736867584] [client 192.168.56.1:3865] mod_wsgi (pid=23599): Exception occurred processing WSGI script '/PATH_TO_MY_WEBLATE/weblate/wsgi.py'.
[Fri Feb 23 09:04:55.384958 2018] [wsgi:error] [pid 23599:tid 140605736867584] [client 192.168.56.1:3865] Traceback (most recent call last):
[Fri Feb 23 09:04:55.385157 2018] [wsgi:error] [pid 23599:tid 140605736867584] [client 192.168.56.1:3865]   File "/PATH_TO_MY_WEBLATE/weblate/wsgi.py", line 44, in <module>
[Fri Feb 23 09:04:55.385466 2018] [wsgi:error] [pid 23599:tid 140605736867584] [client 192.168.56.1:3865]     application = get_wsgi_application()
[Fri Feb 23 09:04:55.385539 2018] [wsgi:error] [pid 23599:tid 140605736867584] [client 192.168.56.1:3865]   File "/usr/local/lib/python2.7/dist-packages/django/core/wsgi.py", line 14, in get_wsgi_application
[Fri Feb 23 09:04:55.385622 2018] [wsgi:error] [pid 23599:tid 140605736867584] [client 192.168.56.1:3865]     return WSGIHandler()
[Fri Feb 23 09:04:55.385643 2018] [wsgi:error] [pid 23599:tid 140605736867584] [client 192.168.56.1:3865]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 151, in __init__
[Fri Feb 23 09:04:55.385759 2018] [wsgi:error] [pid 23599:tid 140605736867584] [client 192.168.56.1:3865]     self.load_middleware()
[Fri Feb 23 09:04:55.385783 2018] [wsgi:error] [pid 23599:tid 140605736867584] [client 192.168.56.1:3865]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 82, in load_middleware
[Fri Feb 23 09:04:55.385908 2018] [wsgi:error] [pid 23599:tid 140605736867584] [client 192.168.56.1:3865]     mw_instance = middleware(handler)
[Fri Feb 23 09:04:55.385922 2018] [wsgi:error] [pid 23599:tid 140605736867584] [client 192.168.56.1:3865]   File "/PATH_TO_MY_WEBLATE/weblate/wladmin/middleware.py", line 45, in __init__
[Fri Feb 23 09:04:55.386060 2018] [wsgi:error] [pid 23599:tid 140605736867584] [client 192.168.56.1:3865]     error['timestamp'],
[Fri Feb 23 09:04:55.386123 2018] [wsgi:error] [pid 23599:tid 140605736867584] [client 192.168.56.1:3865] KeyError: u'timestamp'
```

### Expected behaviour
Uh, um, Weblate actually working without an exception...? 😄 

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

```
$ ./manage.py list_versions
 * Weblate 2.19.1
 * Python 2.7.12
 * Django 1.11.6
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.1
 * Translate Toolkit 2.2.5
 * Whoosh 2.7.0
 * defusedxml 0.4.1
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.4.2
 * lxml 3.5.0
 * django-crispy-forms 1.6.1
 * compressor 2.2
 * djangorestframework 3.7.0
 * user-agents 1.1.0
 * pytz 2014.10
 * pyuca N/A
 * python-bidi 0.4.0
 * PyYAML 3.11
 * Mercurial 3.7.3
 * Database backends: django.db.backends.mysql

$ uname -a
Linux MY_HOSTNAME 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ apache2 -v
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-09-18T15:09:02
```

### Further information

Seeing that the error comes from the wladmin middleware it dawned on me that this is one of the updates I did to my settings.py to bring it up to par to 2.19. When I commented out the new middleware and reloaded Apache the Weblate installation worked just fine:

```python
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'weblate.accounts.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'weblate.accounts.middleware.RequireLoginMiddleware',
    'weblate.middleware.SecurityMiddleware',
    #'weblate.wladmin.middleware.ConfigurationErrorsMiddleware',
]
```

As I said in the issues I filed previously, I'm no Python developer. I'm a very experienced PHP developer, I have a very strong experience in the abject horror that's Visual Basic and Visual Basic for Applications and I can write some moderately passable JavaScript, C# and Delphi. So, that's as deep as I can go with this issue by myself _but_ I am willing to help. I have reproduced this issue on a local VM. If you give me instructions I can collect and provide further information or help with debugging it.

Thank you in advance!

**Comment by nijel** [comment]
It seems you're running older version at same time? The middleware apparently fails to process errors created by previous version.

As a workaround you can delete stored errors from cache:

```console
$ ./manage.py shell
Python 2.7.14+ (default, Feb  6 2018, 19:12:18) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from django.core.cache import cache
>>> cache.delete('configuration-errors')
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
