### ISSUE TITLE
error during import_project from different branch than master

### ISSUE THREAD

**Issue by raestio** [WeblateOrg/weblate#1885]
Hi, I am running weblate in docker and I am trying to import project with command `weblate import_project`. When I pass the branch name "master" to `<branch>` argument it works fine. But an error occurs when I pass some other branch to that argument (f.e. "release-60"). 

Here is the traceback:
```
INFO Cloning git repository...
INFO Updating working copy in git repository...
Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/weblate/runner.py", line 33, in main
    execute_from_command_line(argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/weblate/trans/management/commands/import_project.py", line 331, in handle
    project, repo, branch, slug_len, name_len
  File "/usr/local/lib/python2.7/dist-packages/weblate/trans/management/commands/import_project.py", line 387, in import_initial
    workdir = self.checkout_tmp(project, repo, branch)
  File "/usr/local/lib/python2.7/dist-packages/weblate/trans/management/commands/import_project.py", line 187, in checkout_tmp
    gitrepo.configure_branch(branch)
  File "/usr/local/lib/python2.7/dist-packages/weblate/trans/vcs.py", line 630, in configure_branch
    ['checkout', '-b', branch, 'origin/{0}'.format(branch)]
  File "/usr/local/lib/python2.7/dist-packages/weblate/trans/vcs.py", line 196, in execute
    self.last_output = self._popen(args, self.path, fullcmd=fullcmd)
  File "/usr/local/lib/python2.7/dist-packages/weblate/trans/vcs.py", line 183, in _popen
    output.decode('utf-8')
weblate.trans.vcs.RepositoryException: fatal: Cannot update paths and switch to branch 'release-60' at the same time.
Did you intend to checkout 'origin/release-60' which can not be resolved as commit? (128)```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
