### ISSUE TITLE
phply is not an optional dependency

### ISSUE THREAD

**Issue by rbu** [WeblateOrg/weblate#1908]
### Steps to reproduce
1. ```pip install Weblate```
2. ```weblate migrate```

### Actual behaviour
```
Traceback (most recent call last):
  File "bin/weblate", line 11, in <module>
    load_entry_point('Weblate==2.19.1', 'console_scripts', 'weblate')()
  File "lib/python2.7/site-packages/weblate/runner.py", line 33, in main
    execute_from_command_line(argv)
  File "lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "lib/python2.7/site-packages/weblate/addons/models.py", line 36, in <module>
    from weblate.trans.models import SubProject
  File "lib/python2.7/site-packages/weblate/trans/models/__init__.py", line 40, in <module>
    from weblate.trans.models.subproject import SubProject
  File "lib/python2.7/site-packages/weblate/trans/models/subproject.py", line 41, in <module>
    from weblate.trans.formats import FILE_FORMAT_CHOICES, FILE_FORMATS, ParseError
  File "lib/python2.7/site-packages/weblate/trans/formats.py", line 39, in <module>
    from translate.convert import po2php
  File "lib/python2.7/site-packages/translate/convert/po2php.py", line 31, in <module>
    from translate.storage import php, po
  File "lib/python2.7/site-packages/translate/storage/php.py", line 63, in <module>
    from phply.phpparse import make_parser
ImportError: No module named phply.phpparse
```

### Expected behaviour
No error or phply is installed as a dependency.

### Server configuration
Does not work due to other error.

**Comment by nijel** [comment]
Already fixed in d9418ab22bb9fe5afbc91bbfddd4c951cda4b548, you can workaround that by downgrading to translate-toolkit 2.2.5.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by rbu** [comment]
Thank you for pointing out the fix

**Comment by recena** [comment]
@nijel I'm still facing this issue on `3.1.1` where I see d9418ab22bb9fe5afbc91bbfddd4c951cda4b548 integrated.

**Comment by nijel** [comment]
Are you sure it's same issue? I've just tried it by uninstalling phply and I see no problem then. Also there are no direct imports for phply anymore. Can you please check the error you get?

**Comment by recena** [comment]
@nijel I'm preparing an Ansible Playbook in order to deploy this great software easily, and I am able to check it quickly on a fresh environment.

**Comment by nijel** [comment]
Still can you please check the exception you get? It has to be different as the direct import is no longer there :-). Maybe better to open separate issue with current error...

**Comment by recena** [comment]
@nijel On a fresh installation I see:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/weblate/formats/models.py", line 50, in load_data
    fileformat.get_class()
  File "/usr/local/lib/python3.6/dist-packages/weblate/formats/base.py", line 336, in get_class
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/translate/storage/php.py", line 63, in <module>
    from phply.phpparse import make_parser
ModuleNotFoundError: No module named 'phply'
```

I'm using Weblate `3.1.1` on Ubuntu `18.04.1 LTS`. Installation based on `pip`.

**Comment by nijel** [comment]
Where do you get this error? Does it make application crash? See also https://github.com/WeblateOrg/weblate/issues/2166

This is code is inside try/except block which does catch this exception:

https://github.com/WeblateOrg/weblate/blob/c81409eede99ed3ddec6c5e4482c21e7dc18d8ab/weblate/formats/models.py#L54-L61
