### ISSUE TITLE
Field u'origin' is not indexed

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#1921]
### Steps to reproduce
1. Running Weblate master
2. Execute `./manage.py list_memory`

### Actual behaviour

```
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/home/nijel/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/nijel/.local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/nijel/.local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/nijel/.local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/nijel/work/weblate/weblate/memory/management/commands/list_memory.py", line 48, in handle
    for origin in memory.get_origins():
  File "/home/nijel/work/weblate/weblate/memory/storage.py", line 171, in get_origins
    return self.searcher.lexicon('origin')
  File "/usr/lib/python2.7/dist-packages/whoosh/reading.py", line 774, in lexicon
    self._test_field(fieldname)
  File "/usr/lib/python2.7/dist-packages/whoosh/reading.py", line 740, in _test_field
    raise TermNotFound("Field %r is not indexed" % fieldname)
whoosh.reading.TermNotFound: Field u'origin' is not indexed
```

### Expected behaviour
It should list used origins.

### Server configuration
It happens when you've migrated to master between 674183e07a7bc1ac5d2cc56a734b70a0406b2b05 and 57ae4f52a82f238331194074ec4041076b2fc411.

**Comment by nijel** [comment]
This error is not easily fixable (Whoosh does not support to add index to existing field) and you will loose current translation memory content. Given that this feature is less than one day long, I assume nobody really started to use it, so this should be acceptable to do so.

To recover you need to rerun the translation memory migrations:

```console
$ ./manage.py migrate memory 0001
Operations to perform:
  Target specific migration: 0001_initial, from memory
Running migrations:
  Rendering model states... DONE
  Unapplying memory.0003_auto_20180321_1554... OK
  Unapplying memory.0002_init_whoosh... OK
$ ./manage.py migrate memory 
Operations to perform:
  Apply all migrations: memory
Running migrations:
  Applying memory.0002_init_whoosh... OK
  Applying memory.0003_auto_20180321_1554... OK
```
