### ISSUE TITLE
ERROR Handled exception ProgrammingError: relation "weblate_addon" does not exist

### ISSUE THREAD

**Issue by mrPsycho** [WeblateOrg/weblate#1961]
### Steps to reproduce
1. upgraded weblate via ```pip install --upgrade weblate```  from 2.18 to 2.20
2. did all the stuff here: https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-2-18-to-2-19 
```
weblate loadpo --all --lang dsb
weblate loadpo --all --lang he
weblate loadpo --all --lang hsb
weblate loadpo --all --lang kw
weblate loadpo --all --lang lt
weblate loadpo --all --lang lv
```
+ 
```
weblate loadpo --all --lang ru
weblate loadpo --all --lang en
```
3. trying to commit and see this

### Actual behaviour
```
ERROR Handled exception ProgrammingError: relation "weblate_addon" does not exist
LINE 1: ...on"."configuration", "weblate_addon"."state" FROM "weblate_a...
                                                             ^

ERROR Internal Server Error: /commit/project_name/android/
Traceback (most recent call last):
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/weblate/trans/views/git.py", line 125, in commit_subproject
    return perform_commit(request, obj)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/weblate/trans/views/git.py", line 68, in perform_commit
    request,
  File "/var/lib/weblate/local/lib/python2.7/site-packages/weblate/trans/views/git.py", line 45, in execute_locked
    result = call(*args, **kwargs)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/weblate/trans/models/subproject.py", line 879, in commit_pending
    translation.commit_pending(request, skip_push=True)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/weblate/trans/models/translation.py", line 439, in commit_pending
    self.update_units(author_name, change.author.id)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/weblate/trans/models/translation.py", line 565, in update_units
    pounit, add = self.store.find_unit(
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/weblate/trans/models/translation.py", line 242, in store
    self.subproject.handle_parse_error(exc, self)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/weblate/trans/models/subproject.py", line 901, in handle_parse_error
    filename
  File "/var/lib/weblate/local/lib/python2.7/site-packages/weblate/accounts/notifications.py", line 84, in notify_parse_error
    for subscription in subscriptions:
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 900, in execute_sql
    raise original_exception
InternalError: current transaction is aborted, commands ignored until end of transaction block

```
### Expected behaviour

it should work 

### Server configuration

```
(weblate) $ weblate list_versions
 * Weblate 2.20
 * Python 2.7.12
 * Django 1.11.12
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.7.2
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * pytz 2018.4
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 3.7.3
 * Database backends: django.db.backends.postgresql_psycopg2
```

**Comment by nijel** [comment]
Did you also do the [generic upgrade instructions](https://docs.weblate.org/en/latest/admin/upgrade.html#generic-upgrade-instructions)? It seems that `./manage.py migrate --noinput` was not executed.

**Comment by mrPsycho** [comment]
yep. i did it already. 

```
(weblate) $ weblate migrate
Operations to perform:
  Apply all migrations: accounts, admin, auth, authtoken, contenttypes, lang, permissions, screenshots, sessions, sites, social_django, trans, wladmin
Running migrations:
  No migrations to apply.
```

**Comment by mrPsycho** [comment]
and others steps i did too.

**Comment by nijel** [comment]
Apparently some new apps are missing there, so please adjust `INSTALLED_APPS` as documented in https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-2-18-to-2-19

**Comment by mrPsycho** [comment]
yep, thanks...

but it still has errors: "There is no merge to abort (MERGE_HEAD is missing). (128)"

**Comment by nijel** [comment]
When does it happen? Can you please provide some more details?

**Comment by mrPsycho** [comment]
looks like some errors in repo. 
we've resetted it , now all is works.


Thank you!
