### ISSUE TITLE
Migrations still looking for 'subproject' model after last update

### ISSUE THREAD

**Issue by jekkos** [WeblateOrg/weblate#1997]
### Steps to reproduce
1. Update git from f7b5dff -> 9b9f47e
2. run makemigrations
3. find a problem blocking running any further migrations

### Actual behaviour
So while upgrading to the latest master version, I found myself unable to run any further migrations. Something got stuck in the process, as I see current stacktrace now when running any open migrations for newly enabled apps

```
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/home/jekkos/weblate/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/jekkos/weblate/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jekkos/weblate/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/jekkos/weblate/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/jekkos/weblate/local/lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 150, in handle
    loader.project_state(),
  File "/home/jekkos/weblate/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 323, in project_state
    return self.graph.make_state(nodes=nodes, at_end=at_end, real_apps=list(self.unmigrated_apps))
  File "/home/jekkos/weblate/local/lib/python2.7/site-packages/django/db/migrations/graph.py", line 409, in make_state
    project_state = self.nodes[node].mutate_state(project_state, preserve=False)
  File "/home/jekkos/weblate/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 92, in mutate_state
    operation.state_forwards(self.app_label, new_state)
  File "/home/jekkos/weblate/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 201, in state_forwards
    state.models[app_label, self.model_name_lower].fields
KeyError: ('trans', u'subproject')
```

### Expected behaviour
Migrations should work fine 

### Server configuration
Please paste the output of command `./manage.py list_versions` over here
```
 * Weblate weblate-2.20-239-g9b9f47e
 * Python 2.7.12
 * Django 1.11.13
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.7.2
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * pytz 2018.4
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 4.5.2
 * Database backends: django.db.backends.postgresql_psycopg2
```

Maybe this is something django specific, but I guess Ithat the subproject model was renamed to 'component' and for some reason there is still an old migration looking for this table name. 

Any idea how I can check what migration it's trying to execute here? I checked showmigrations and it still has a couple of migrations open (which I can't execute due to this 'subproject' key missing)

Thanksi!

**Comment by nijel** [comment]
Why are you running `makemigrations`? The migrations are already shipped with Weblate.

Anyway did you migrate the database with `migrate`? Did that lead to any error?

**Comment by jekkos** [comment]
Hi there, yes i did run the migrate after makemigrations in this case. So currently it's permanently stuck on about any migration leading to this error. I think it complained on conflicting migrations at first after which it created a couple of 'merge migrations'.

**Comment by jekkos** [comment]
OK I've added a try except around the crashing code (in manage.py) and for some reason I was now able to execute the last migrations, looks fine for now.

**Comment by nijel** [comment]
Generally you should not create any migrations for Weblate. Most likely your created migrations are the ones which lead to this problem...

**Comment by jekkos** [comment]
Ok thanks for the answer here.
