### ISSUE TITLE
2.20 -> 3.0 upgrade

### ISSUE THREAD

**Issue by zjarkov** [WeblateOrg/weblate#2032]
Trying to run upgrade from 2.20 to 3.0 (master) to avoid multiple manual fixes that are already inbuilt in master. During upgrade process I am having some troubles though. I am not sure if something is wrong in our DB or just upgrade procedure is unstable yet as 3.0 is not officially out.

### Steps to reproduce
1. Folowing steps on [Upgrade from 2.20 to 3.0](https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-2-20-to-3-0)
2. Run all the steps one by one
3. On step 6. (`./manage.py migrate weblate_auth 0001`) following error occures:
```sh
$ ./manage.py migrate weblate_auth 0001
Operations to perform:
  Target specific migration: 0001_initial, from weblate_auth
Running migrations:
  Applying weblate_auth.0001_initial... OK
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 227, in handle
    self.verbosity, self.interactive, connection.alias, apps=post_migrate_apps, plan=plan,
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/core/management/sql.py", line 53, in emit_post_migrate_signal
    **kwargs
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/var/www/weblate/www/weblate/lang/models.py", line 335, in setup_lang
    Language.objects.setup(False)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/weblate/www/weblate/lang/models.py", line 266, in setup
    lang, created = self.get_or_create(code=code)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 466, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 498, in _create_object_from_params
    obj = self.create(**params)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 848, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/var/www/weblate/www/weblate/utils/decorators.py", line 30, in wrapper
    signal_handler(*args, **kwargs)
  File "/var/www/weblate/www/weblate/auth/models.py", line 533, in setup_language_groups
    for group in auto_languages:
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
    raise original_exception
django.db.utils.ProgrammingError: relation "weblate_auth_group" does not exist
LINE 1: ..._selection", "weblate_auth_group"."internal" FROM "weblate_a...
```

### Server configuration
```sh
$ ./manage.py list_versions
```
 * Weblate weblate-2.20-464-ga47b40b
 * Python 2.7.12
 * Django 1.11.13
 * six 1.10.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.4.1
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.0
 * lxml 3.7.1
 * django-crispy-forms 1.6.1
 * compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * pytz 2018.4
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.0.2
 * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
This should be addressed as of c3dc257c3b293072a0cfaeb3355ebbe0029e7953, do you have it applied?

**Comment by zjarkov** [comment]
I do not :-D => committed 3 hours ago
But actually `git pull` says `Already up-to-date.`, strange. I might have to wait a while.

**Comment by nijel** [comment]
what remote are you using?

**Comment by zjarkov** [comment]
Yes, that was the reason - historically I was on nijel/weblate.
Now it is better however it fails on running the rest of migrations:
```sh
$ ./manage.py migrate
Operations to perform:
  Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, lang, memory, permissions, screenshots, sessions, sites, social_django, trans, weblate_auth, wladmin
Running migrations:
  Applying accounts.0037_auto_20180416_1406... OK
  Applying addons.0006_addon_project_scope... OK
  Applying trans.0129_auto_20180416_1541... OK
  Applying trans.0130_auto_20180416_1503... OK
  Applying checks.0001_initial... OK
  Applying checks.0002_auto_20180416_1509... OK
  Applying trans.0131_auto_20180416_1610...Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/var/www/weblate/www/weblate/trans/migrations/0131_auto_20180416_1610.py", line 33, in restore_ids
    pk__in=cl.component_ids.split(',')
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/models/lookups.py", line 219, in get_prep_lookup
    rhs_value = self.lhs.output_field.get_prep_value(rhs_value)
  File "/var/www/weblate/env/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''
```

**Comment by nijel** [comment]
I think I've fixed this in 9b73da821f1e49119b9c22844d94d59a65514392.

**Comment by zjarkov** [comment]
Yes, it is fixed.
Just one additional question, from when there is "weblate_auth_user_email_aaabd769_uniq" key? I actually have two DB users with the same email address (root and normal user), it has been there since the installation (2.11). It seems I'll need to change the email address for one of them.

**Comment by zjarkov** [comment]
Thank you for your support, all issues has been fixed.
I am on 3.0-dev and up'n'running again.

**Comment by nijel** [comment]
Great, thanks for providing this feedback. The migration code is not yet much tested as it has been merged about week ago, so there are apparently some rough edges. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
