### ISSUE TITLE
Migration fails

### ISSUE THREAD

**Issue by jmaxxz** [WeblateOrg/weblate#2050]
### Steps to reproduce
1. Upgrade from weblate  to 3.0
2. Follow https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-3 guide
3. At step 8 (`./manage migrate`) an error occurs

### Actual behaviour
```
Operations to perform:
  Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, lang, memory, permissions, screenshots, sessions, sites, social_django, trans, weblate_auth, wladmin
Running migrations:
  Applying weblate_auth.0007_auto_20180509_0739...Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/usr/share/weblate/weblate/auth/migrations/0007_auto_20180509_0739.py", line 14, in forwards
    "weblate_auth", "Group")
  File "/usr/share/weblate/weblate/auth/migrations/0007_auto_20180509_0739.py", line 83, in change_foreign_keys
    schema_editor.alter_field(fk_field.model, old_field, new_field, strict=True)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 515, in alter_field
    old_db_params, new_db_params, strict)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/base/schema.py", line 529, in _alter_field
    old_field.column,
ValueError: Found wrong number (0) of foreign key constraints for weblate_auth_autogroup.group_id
```

### Expected behaviour
Migrations should complete

### Server configuration
Please paste the output of command `./manage.py list_versions` over here
```
* Weblate weblate-2.20-503-gab7a57c
 * Python 2.7.12
 * Django 1.11.4
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow (PIL) 1.1.7
 * dateutil 2.6.1
 * lxml 3.8.0
 * django-crispy-forms 1.6.1
 * compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * pytz 2017.2
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.12
 * Mercurial 3.9.1
 * hub 2.3.0-pre9
 * Database backends: django.db.backends.mysql
```

**Comment by jmaxxz** [comment]
used `--fake` to skip the migration for the time being.

**Comment by nijel** [comment]
Did you get any error before? Using `--fake` have most likely left your database in inconsistent state and will cause problems with future migrations.

We had similar issue in the past (see https://github.com/WeblateOrg/weblate/issues/1631), but I'm not sure these two are related.

Can you please dump SQL structure for the `weblate_auth_autogroup` table?

**Comment by nijel** [comment]
The foreign key is missing, it should be:

```mysql
CREATE TABLE `weblate_auth_autogroup` (   
 `id` int(11) NOT NULL AUTO_INCREMENT,   
 `match` varchar(200) NOT NULL,   
 `group_id` int(11) NOT NULL,   
 PRIMARY KEY (`id`),   
 KEY `weblate_auth_autogro_group_id_37b7ff0b_fk_weblate_a` (`group_id`), 
 CONSTRAINT `weblate_auth_autogro_group_id_37b7ff0b_fk_weblate_a`  FOREIGN KEY (`group_id`) REFERENCES `weblate_auth_group` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8
```

**Comment by nijel** [comment]
I've tried to address the migration error in ed01ef6fd, in case you have database backup it would be great if you can retry the migration if it really fixes the issue (I can not reproduce this issue).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by jmaxxz** [comment]
@nijel unfortunately I did this upgrade in YOLO mode and did not back up first.  Pretty stupid I know.

![shame](https://user-images.githubusercontent.com/828153/40743372-ee3f7aa2-6416-11e8-84e1-10fd727bc255.gif)
