### ISSUE TITLE
gitexport can not be added after initial install

### ISSUE THREAD

**Issue by jmaxxz** [WeblateOrg/weblate#2065]
### Steps to reproduce
1. Install latest without gitexport
2. Enable gitexport (https://docs.weblate.org/en/latest/admin/optionals.html#git-exporter)
3. Run ./manage migrate

### Actual behaviour
Crash
```
/usr/share/weblate# ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 86, in handle
    executor.loader.check_consistent_history(connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 298, in check_consistent_history
    connection.alias,
django.db.migrations.exceptions.InconsistentMigrationHistory: Migration trans.0131_auto_20180416_1610 is applied before its dependency gitexport.0001_initial on database 'default'.
```

### Expected behaviour
gitexport's migrations are run

Problem is here: https://github.com/WeblateOrg/weblate/commit/caa414ba85007b4c177a8c44ade2cecee0ebbafb#diff-da52276d69b89df6edb073e0f84de3d7R38

**Comment by nijel** [comment]
Thank you for your report, I think the issue you have reported has just been fixed. However I do not have time to reproduce the issue right now so it would be great if you can rest this.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by jmaxxz** [comment]
@nijel updated to latest migration still fails. I see your update is there but manage.py migrate is behaving as if it wasn't. Deleted pyc files, still no luck. Any ideas?

**Comment by nijel** [comment]
Okay, the fix was not really working, I've now reproduced the issue and created better fix.

**Comment by jmaxxz** [comment]
:+1: confirmed is now working
