### ISSUE TITLE
django.db.migrations.exceptions.IrreversibleError

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#2073]
I'm trying to apply upgrade instruction for Weblate's YunoHost package

### Steps to reproduce
1. Install weblate 2.20
2. follow https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-3 instructions
2. at step `Run first authentication migration: ./manage.py migrate weblate_auth 0001` the script fails.

### Actual behaviour

> weblate migrate weblate_auth 0001
> WARNING:root:Python-Levenshtein not found. Continuing with built-in (slower) fuzzy matching.
> Operations to perform:
> Target specific migration: 0001_initial, from weblate_auth
> Running migrations:
> Rendering model states... DONE
> Unapplying weblate_auth.0010_auto_20180509_1630... OK
> Unapplying weblate_auth.0009_auto_20180509_1552... OK
> 
>  Traceback (most recent call last):
>    File "/var/www/weblate/venv/bin/weblate", line 11, in <module>
>      sys.exit(main())
>    File "/var/www/weblate/venv/local/lib/python2.7/site-packages/weblate/runner.py", line 33, in main
>      execute_from_command_line(argv)
>    File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execu
> te_from_command_line
>      utility.execute()
>    File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
>      self.fetch_command(subcommand).run_from_argv(self.argv)
>    File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
>      self.execute(*args, **cmd_options)
>    File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
>      output = self.handle(*args, **options)
>    File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
>      fake_initial=fake_initial,
>    File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 119, in migrate
>      state = self._migrate_all_backwards(plan, full_plan, fake=fake)
>    File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 194, in _migrate_all_backwards
>      self.unapply_migration(states[migration], migration, fake=fake)
>    File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 264, in unapply_migration
>      state = migration.unapply(state, schema_editor)
>   File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 152, in unapply
>     raise IrreversibleError("Operation %s in %s is not reversible" % (operation, self))
> django.db.migrations.exceptions.IrreversibleError: Operation <RunPython <function run_migration at 0x7fb24f20dde8>> in weblate_auth.0008_email_fixup is not reversible

### Expected behaviour
Migration should not crash

### Server configuration
Please paste the output of command `./manage.py list_versions` over here

> (venv) weblate@jb9:~$ DJANGO_SETTINGS_MODULE="weblate.settings" weblate list_versions
>  * Weblate 2.20
>  * Python 2.7.13
>  * Django 1.11.13
>  * six 1.10.0
>  * social-auth-core 1.7.0
>  * social-auth-app-django 2.1.0
>  * django-appconf 1.0.2
>  * Translate Toolkit 2.3.0
>  * Whoosh 2.7.4
>  * defusedxml 0.5.0
>  * Git 2.11.0
>  * Pillow (PIL) 1.1.7
>  * dateutil 2.7.3
>  * lxml 3.7.1
>  * django-crispy-forms 1.7.2
>  * compressor 2.2
>  * djangorestframework 3.8.2
>  * user-agents 1.1.0
>  * pytz 2018.4
>  * pyuca N/A
>  * python-bidi 0.4.0
>  * pyLibravatar N/A
>  * PyYAML 3.12
>  * hub 2.3.0-pre10
>  * Database backends: django.db.backends.postgresql_psycopg2

**Comment by nijel** [comment]
You already have the weblate_auth migrations applied, so you probably have already executed them. And indeed those are not reversible.

**Comment by Jibec** [comment]
Thanks for your answer :)

That's true, migration was already ran, but that's also always the case. It's one of the first installation steps: https://docs.weblate.org/en/latest/admin/install.html#filling-up-the-database

So if I install weblate 2.20 and want to upgrade to 3.0, what should I do?

**Comment by Jibec** [comment]
Oh, I understand thanks :) I'll try and close the issue once done.
