### ISSUE TITLE
FieldError: Cannot resolve keyword 'first_name' into field. Choices are: agreement, auditlog, auth_token, author_set, change, comment, contributoragreement, date_joined, email, full_name, groups, id, is_active, is_superuser, last_login, logentry, password

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2077]
View details in Rollbar: [https://rollbar.com/nijel/weblate/items/1607/](https://rollbar.com/nijel/weblate/items/1607/)

```
Traceback (most recent call last):
  File "/home/www-data/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/www-data/.local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/www-data/.local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/www-data/.local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/www-data/.local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/home/www-data/.local/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/www-data/.local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/www-data/.local/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/www-data/.local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1542, in changelist_view
    self.list_max_show_all, self.list_editable, self,
  File "/home/www-data/.local/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 78, in __init__
    self.queryset = self.get_queryset(request)
  File "/home/www-data/.local/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 351, in get_queryset
    qs, search_use_distinct = self.model_admin.get_search_results(request, qs, self.query)
  File "/home/www-data/.local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 910, in get_search_results
    queryset = queryset.filter(reduce(operator.or_, or_queries))
  File "/home/www-data/.local/lib/python2.7/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/www-data/.local/lib/python2.7/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/www-data/.local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/www-data/.local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1270, in _add_q
    current_negated, allow_joins, split_subq)
  File "/home/www-data/.local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/www-data/.local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1154, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/www-data/.local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1034, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/www-data/.local/lib/python2.7/site-packages/django/db/models/sql/query.py", line 1352, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'first_name' into field. Choices are: agreement, auditlog, auth_token, author_set, change, comment, contributoragreement, date_joined, email, full_name, groups, id, is_active, is_superuser, last_login, logentry, password, profile, social_auth, suggestion, user_votes, username, vote
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
