### ISSUE TITLE
Migration 0007

### ISSUE THREAD

**Issue by gabn88** [WeblateOrg/weblate#2090]
Closely related to https://github.com/WeblateOrg/weblate/issues/2050, for me the migration fails with the updated migration 0007_auto_20180509_0739.

Traceback:

```
weblate_1   |   Applying weblate_auth.0007_auto_20180509_0739...
weblate_1   | Postgres is up
weblate_1   | Operations to perform:
weblate_1   |   Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, gitexport, lang, memory, permissions, screenshots, sessions, sites, social_django, trans, weblate_auth, wladmin
weblate_1   | Running migrations:
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
weblate_1   |     return self.cursor.execute(sql, params)
weblate_1   | psycopg2.IntegrityError: insert or update on table "auth_user_groups" violates foreign key constraint "auth_user_groups_group_id_97559544_fk_weblate_auth_group_id"
weblate_1   | DETAIL:  Key (group_id)=(36) is not present in table "weblate_auth_group".
weblate_1   | 
weblate_1   | 
weblate_1   | The above exception was the direct cause of the following exception:
weblate_1   | 
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/bin/weblate", line 11, in <module>
weblate_1   |     sys.exit(main())
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/weblate/runner.py", line 33, in main
weblate_1   |     execute_from_command_line(argv)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
weblate_1   |     utility.execute()
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 365, in execute
weblate_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 288, in run_from_argv
weblate_1   |     self.execute(*args, **cmd_options)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 335, in execute
weblate_1   |     output = self.handle(*args, **options)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/migrate.py", line 200, in handle
weblate_1   |     fake_initial=fake_initial,
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 117, in migrate
weblate_1   |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
weblate_1   |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
weblate_1   |     state = migration.apply(state, schema_editor)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/migration.py", line 122, in apply
weblate_1   |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
weblate_1   |     self.code(from_state.apps, schema_editor)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/weblate/auth/migrations/0007_auto_20180509_0739.py", line 14, in forwards
weblate_1   |     "weblate_auth", "Group")
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/weblate/auth/migrations/0007_auto_20180509_0739.py", line 82, in change_foreign_keys
weblate_1   |     schema_editor.alter_field(fk_field.model, old_field, new_field, strict=True)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/schema.py", line 525, in alter_field
weblate_1   |     old_db_params, new_db_params, strict)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/postgresql/schema.py", line 122, in _alter_field
weblate_1   |     new_db_params, strict,
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/schema.py", line 750, in _alter_field
weblate_1   |     self.execute(self._create_fk_sql(model, new_field, "_fk_%(to_table)s_%(to_column)s"))
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/schema.py", line 133, in execute
weblate_1   |     cursor.execute(sql, params)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 68, in execute
weblate_1   |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
weblate_1   |     return executor(sql, params, many, context)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
weblate_1   |     return self.cursor.execute(sql, params)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 89, in __exit__
weblate_1   |     raise dj_exc_value.with_traceback(traceback) from exc_value
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
weblate_1   |     return self.cursor.execute(sql, params)
weblate_1   | django.db.utils.IntegrityError: insert or update on table "auth_user_groups" violates foreign key constraint "auth_user_groups_group_id_97559544_fk_weblate_auth_group_id"
weblate_1   | DETAIL:  Key (group_id)=(36) is not present in table "weblate_auth_group".
weblate_1   | 

```

Upgrading from 2.18

**Comment by nijel** [comment]
Are you upgrading from 3.0 or something older?

**Comment by gabn88** [comment]
Upgrading from 2.18

**Comment by gabn88** [comment]
Manually running docker-compose run weblate migrate worked fine though. Strange.

**Comment by gabn88** [comment]
And up-and-running again! Thanks for your help, I really love this project :)

**Comment by gabn88** [comment]
Oh, now I can't login:

Traceback:

```
weblate_1   | ERROR Internal Server Error: /accounts/login/
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 35, in inner
weblate_1   |     response = get_response(request)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 128, in _get_response
weblate_1   |     response = self.process_exception_by_middleware(e, request)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 126, in _get_response
weblate_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py", line 69, in view
weblate_1   |     return self.dispatch(request, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 62, in _wrapper
weblate_1   |     return bound_func(*args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
weblate_1   |     response = view_func(request, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 58, in bound_func
weblate_1   |     return func.__get__(self, type(self))(*args2, **kwargs2)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/weblate/accounts/views.py", line 578, in dispatch
weblate_1   |     return super(WeblateLoginView, self).dispatch(request, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 62, in _wrapper
weblate_1   |     return bound_func(*args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
weblate_1   |     return view(request, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 58, in bound_func
weblate_1   |     return func.__get__(self, type(self))(*args2, **kwargs2)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 62, in _wrapper
weblate_1   |     return bound_func(*args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 142, in _wrapped_view
weblate_1   |     response = view_func(request, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 58, in bound_func
weblate_1   |     return func.__get__(self, type(self))(*args2, **kwargs2)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 62, in _wrapper
weblate_1   |     return bound_func(*args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
weblate_1   |     response = view_func(request, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/utils/decorators.py", line 58, in bound_func
weblate_1   |     return func.__get__(self, type(self))(*args2, **kwargs2)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/views.py", line 66, in dispatch
weblate_1   |     return super().dispatch(request, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py", line 89, in dispatch
weblate_1   |     return handler(request, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/views/generic/edit.py", line 142, in post
weblate_1   |     return self.form_valid(form)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/views.py", line 95, in form_valid
weblate_1   |     auth_login(self.request, form.get_user())
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/__init__.py", line 161, in login
weblate_1   |     user_logged_in.send(sender=user.__class__, request=request, user=user)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/dispatch/dispatcher.py", line 178, in send
weblate_1   |     for receiver in self._live_receivers(sender)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
weblate_1   |     for receiver in self._live_receivers(sender)
weblate_1   |   File "/usr/local/lib/python3.5/dist-packages/weblate/accounts/models.py", line 513, in post_login_handler
weblate_1   |     not user.social_auth.filter(provider='email').exists()):

```

**Comment by nijel** [comment]
It seems that the 0007 migration wasn't applied in the end...

**Comment by gabn88** [comment]
Somehow, stopping the container (docker-compose down) en restarting it made it work!
