### ISSUE TITLE
Internal server error after 

### ISSUE THREAD

**Issue by GhassenRjab** [WeblateOrg/weblate#2101]
### Steps to reproduce
1. Use Weblate For Azure (https://bitnami.com/stack/weblate/cloud/azure)
2. Fill registration form

### Actual behaviour
I get an internal server error message

### Expected behaviour
I receive an email to confirm my registration

### Server configuration
I didn't find the file `./manage.py list_versions`
Here is weblate.log content instead

2018-06-26 17:06:35,076 INFO Passed captcha for grj@colossalfactory.com (2 + 10 = 12)
2018-06-26 17:06:35,175 INFO sending notification activation on /accounts/complete/email/?verification_code=fe56e4322e5545f3a89422ca453870da&partial_token=b2701a226c7847ce8a9d7f56f870f7c2 to grj@colossalfactory.com
2018-06-26 17:06:35,234 ERROR Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/bitnami/apps/weblate/weblate/weblate/accounts/views.py", line 212, in rate_wrap
    return function(request, *args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/bitnami/apps/weblate/weblate/weblate/accounts/views.py", line 618, in register
    return social_complete(request, 'email')
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/bitnami/apps/weblate/weblate/weblate/accounts/views.py", line 193, in demo_wrap
    return function(request, *args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/bitnami/apps/weblate/weblate/weblate/accounts/views.py", line 910, in social_complete
    return complete(request, backend)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/social_django/utils.py", line 49, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/social_django/views.py", line 33, in complete
    *args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/social_core/actions.py", line 41, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/social_core/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/social_core/backends/legacy.py", line 25, in auth_complete
    return self.strategy.authenticate(*args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/social_django/strategy.py", line 107, in authenticate
    return authenticate(*args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 70, in authenticate
    user = _authenticate_with_backend(backend, backend_path, request, credentials)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 116, in _authenticate_with_backend
    return backend.authenticate(*args, **credentials)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/social_core/backends/base.py", line 80, in authenticate
    return self.pipeline(pipeline, *args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/social_core/backends/base.py", line 83, in pipeline
    out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/social_core/backends/base.py", line 113, in run_pipeline
    result = func(*args, **out) or {}
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/social_core/pipeline/partial.py", line 32, in wrapper
    *args, **kwargs) or {}
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/social_core/pipeline/mail.py", line 22, in mail_validation
    current_partial.token)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/social_core/strategy.py", line 133, in send_email_validation
    send_email(self, backend, code, partial_token)
  File "/opt/bitnami/apps/weblate/weblate/weblate/accounts/pipeline.py", line 159, in send_validation
    'url': url
  File "/opt/bitnami/apps/weblate/weblate/weblate/accounts/notifications.py", line 350, in send_notification_email
    send_mails([email])
  File "/opt/bitnami/apps/weblate/weblate/weblate/accounts/notifications.py", line 558, in send_mails
    [mail for mail in mails if mail is not None]
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 104, in send_messages
    new_conn_created = self.open()
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 64, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/opt/bitnami/python/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/opt/bitnami/python/lib/python2.7/smtplib.py", line 317, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/opt/bitnami/python/lib/python2.7/smtplib.py", line 292, in _get_socket
    return socket.create_connection((host, port), timeout)
  File "/opt/bitnami/python/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

I configured the SMTP server in global_settings.py

**Comment by nijel** [comment]
It really looks like the SMTP connection is not working. Are you sure the settings is correct? Are you sure the settings file is applied? 

Have you tried asking Bitnami as well? I have no clue how is the image built...

**Comment by GhassenRjab** [comment]
This is the email related settings<br/>
<br/>
`
# The email backend to use. For possible shortcuts see django.core.mail.<br/>
# The default is to use the SMTP backend.<br/>
# Third-party backends can be specified by providing a Python path<br/>
# to a module that defines an EmailBackend class.<br/>
EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'<br/>
# Uncomment the line below in order to enable SMTP:<br/>
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'<br/>
<br/>
# Host for sending email.<br/>
EMAIL_HOST = 'smtp.mailtrap.io'<br/>
<br/>
# Port for sending email.<br/>
EMAIL_PORT = '2525'<br/>
<br/>
# Whether to send SMTP 'Date' header in the local time zone or in UTC.<br/>
EMAIL_USE_LOCALTIME = False<br/>
<br/>
# Optional SMTP authentication information for EMAIL_HOST.<br/>
EMAIL_HOST_USER = '7bd52bc197220f'<br/>
EMAIL_HOST_PASSWORD = '1ce4cd153f8d9e'<br/>
EMAIL_USE_TLS = False<br/>
EMAIL_USE_SSL = False<br/>
EMAIL_SSL_CERTFILE = None<br/>
EMAIL_SSL_KEYFILE = None<br/>
EMAIL_TIMEOUT = None<br/>
`
<br/>
I did an apache restart after changing the setting files, through this command<br/>
<br/>
`sudo /opt/bitnami/ctlscript.sh restart apache`<br/>

**Comment by burner1024** [comment]
try telnetting from your server to smtp

**Comment by GhassenRjab** [comment]
The telnet test went well.

I followed [this documentation](https://docs.bitnami.com/virtual-machine/apps/weblate/#how-to-configure-outbound-email-settings) to configure the SMTP server.

But there is also [this documentation](https://docs.weblate.org/en/latest/admin/install.html#configuring-outgoing-mail) which uses another file to configure the SMTP server.
Maybe the problem comes from there.

**Comment by GhassenRjab** [comment]
The Django version that is being used is 1.11.13. So the path is

`/opt/bitnami/apps/django/lib/python2.7/site-packages/Django-1.11.13-py2.7.egg/django/conf/global_settings.py`

I am going to put the SMTP configuration in directly in Weblate settings file and see what happens

**Comment by GhassenRjab** [comment]
When I put the configuration in Weblate settings the registration worked and I received the email to complete my registration.

But the newly added user (me) has not the admin rights. So I am not able to add projects.
Here is a screenshot of the UI after logging
![image](https://user-images.githubusercontent.com/6123547/42034623-884e5a6e-7ad8-11e8-99f4-e46aa2205fad.png)

**Comment by nijel** [comment]
Registered users don't get automatically admin rights (for quite obvious reasons). You can use [createadmin](https://docs.weblate.org/en/latest/admin/management.html#createadmin) to create admin from command line.

PS: It seems that bitnami image comes with admin user, check [their docs](https://docs.bitnami.com/virtual-machine/apps/weblate/#what-credentials-do-i-need).
