### ISSUE TITLE
First setup: Migration weblate_auth.0007 failing on foreign key constraints

### ISSUE THREAD

**Issue by MPV** [WeblateOrg/weblate#2115]
Hi, 
I've tried setting up Weblate from scratch using both with version `2.19.1-3` and `3.0.1-4`, but the migrations fail in both of them.

### Steps to reproduce
1. Setup postgres database for Weblate.
2. Start memcached in Docker container.
3. Start weblate in Docker container.

Here's the command I used to start Weblate in Docker:

```
docker run \
    --name weblate-server \
    -v /var/lib/weblate-server:/var/lib/weblate-server:rw \
    -p 0.0.0.0:8888:80/tcp \
    --link weblate-memcached:cache \
    --restart always \
    --expose 80/tcp \
    -e 'WEBLATE_EMAIL_USER=postmaster@redacted.com' \
    -e 'POSTGRES_HOST=redacted' \
    -e 'POSTGRES_PASSWORD=redacted' \
    -e 'WEBLATE_ADMIN_PASSWORD=redacted' \
    -e 'WEBLATE_LOGLEVEL=DEBUG' \
    -e 'WEBLATE_DEBUG=0' \
    -e 'WEBLATE_ADMIN_EMAIL=redacted@redacted.com' \
    -e 'WEBLATE_ADMIN_NAME=Weblate Admin' \
    -e 'WEBLATE_EMAIL_HOST=smtp.redacted.org' \
    -e 'WEBLATE_SERVER_EMAIL=noreply@weblate.org' \
    -e 'WEBLATE_SITE_TITLE=Weblate' \
    -e 'MEMCACHED_PORT=11211' \
    -e 'WEBLATE_DATA_DIR=/var/lib/weblate-server' \
    -e 'WEBLATE_ALLOWED_HOSTS=*' \
    -e 'WEBLATE_AUTH_LDAP_USER_DN_TEMPLATE=uid=%(user)s,ou=Users,dc=redacted,dc=local' \
    -e 'WEBLATE_DEFAULT_FROM_EMAIL=noreply@weblate.org' \
    -e 'POSTGRES_DATABASE=weblate' \
    -e 'WEBLATE_REGISTRATION_OPEN=1' \
    -e 'WEBLATE_AUTH_LDAP_SERVER_URI=ldap://redacted' \
    -e 'POSTGRES_USER=redacted' \
    -e 'POSTGRES_PORT=5438' \
    -e 'MEMCACHED_HOST=cache' \
    -e 'WEBLATE_AUTH_LDAP_USER_ATTR_MAP=first_name:givenName,email:mail' \
    -e 'WEBLATE_EMAIL_PASSWORD=redacted' \
    -d \
    weblate/weblate:3.0.1-4
```

### Actual behaviour
Weblate failing to run it's migrations:

It keeps crashing with this output:
```
Postgres is up
Operations to perform:
  Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, gitexport, lang, memory, permissions, screenshots, sessions, sites, social_django, trans, weblate_auth, wladmin
Running migrations:
Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/weblate/runner.py", line 33, in main
    execute_from_command_line(argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/migration.py", line 122, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/usr/local/lib/python3.5/dist-packages/weblate/auth/migrations/0007_auto_20180509_0739.py", line 11, in forwards
    "weblate_auth", "User")
  File "/usr/local/lib/python3.5/dist-packages/weblate/auth/migrations/0007_auto_20180509_0739.py", line 82, in change_foreign_keys
    schema_editor.alter_field(fk_field.model, old_field, new_field, strict=True)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/schema.py", line 525, in alter_field
    old_db_params, new_db_params, strict)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/postgresql/schema.py", line 122, in _alter_field
    new_db_params, strict,
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/schema.py", line 538, in _alter_field
    old_field.column,
ValueError: Found wrong number (0) of foreign key constraints for accounts_auditlog.user_id
  Applying weblate_auth.0007_auto_20180509_0739...
``` 
...after which it crashes. 😊 

### Expected behaviour
Weblate succeeding with migrations and starting up properly.

**Comment by MPV** [comment]
I've just tested an earlier dockerized version of Weblate (`2.20-5`) that I can confirm works better: 

👍 The migrations complete successfully (towards both Postgres databases) and Weblate starts and works as expected.

**Comment by MPV** [comment]
Looking at the upgrade instructions from `2.20` to `3.0`, they don't seem to be compatible with running Weblate in it's prepared docker containers?

>Run first authentication migration: ./manage.py migrate weblate_auth 0001

https://docs.weblate.org/en/weblate-3.0.1/admin/upgrade.html?highlight=migrate#upgrade-from-2-20-to-3-0

I haven't been able to find the `manage.py` command when looking through the [packaging of the Weblate docker image](https://github.com/WeblateOrg/docker) — how can I access it using the Weblate docker image?

**Comment by nijel** [comment]
What PostgreSQL version do you use? I'm not really sure that might cause difference, but it's probably worth investigating.

**Comment by nijel** [comment]
Reading the report again, I've noticed that you see the same issue with `2.19.1-3`, while mentioned migration was not part of 2.19 release. Maybe it's different error there?

**Comment by MPV** [comment]
Sorry about the late reply. 
The postgres version we use is `9.6`.
