### ISSUE TITLE
IndexError: string index out of range in translate/storage/yaml.py

### ISSUE THREAD

**Issue by s4brown** [WeblateOrg/weblate#2128]
### Steps to reproduce
1. Attempt to commit changes in Repository maintenance to a component using YAML translation files. The repository is in sync with a "There are some uncommitted changes!" message

### Actual behaviour
Internal server error with the following in the logs:
```2018-07-13 20:52:33,939 ERROR Internal Server Error: /commit/project/messages/fr/
Traceback (most recent call last):
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/opt/bitnami/apps/weblate/weblate/weblate/trans/views/git.py", line 132, in commit_translation
    return perform_commit(request, obj)
  File "/opt/bitnami/apps/weblate/weblate/weblate/trans/views/git.py", line 64, in perform_commit
    request,
  File "/opt/bitnami/apps/weblate/weblate/weblate/trans/views/git.py", line 41, in execute_locked
    result = call(*args, **kwargs)
  File "/opt/bitnami/apps/weblate/weblate/weblate/trans/models/translation.py", line 426, in commit_pending
    self.update_units(author_name, change.author.id)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/opt/bitnami/apps/weblate/weblate/weblate/trans/models/translation.py", line 619, in update_units
    self.store.save()
  File "/opt/bitnami/apps/weblate/weblate/weblate/formats/base.py", line 474, in save
    self.store.serialize(temp)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/translate/storage/yaml.py", line 160, in serialize
    nested_set(units, unit.getid().split('->'), unit.target)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/translate/storage/yaml.py", line 145, in nested_set
    if len(path) == 2 and path[1][0] == '[' and path[1][-1] == ']' and path[1][1:-1].isdigit():
IndexError: string index out of range
```

### Expected behaviour
Changes should be commited

### Server configuration
 * Weblate 3.0.1
 * Python 2.7.15
 * Django 1.11.13
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.7.3
 * lxml 4.2.2
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * pytz 2018.4
 * PyYAML 3.12
 * Database backends: django.db.backends.mysql
 * Cache backends: default:LocMemCache

**Comment by nijel** [comment]
Can you please share the YAML file you're translating?

**Comment by nijel** [comment]
I *probably* found what might be issue here and I've created pull request against translate-toolkit to address this: https://github.com/translate/translate/pull/3816

It would be great if you could verify it actually works.

**Comment by nijel** [comment]
If you are using pip to install dependencies, you can use `pip install https://github.com/translate/translate.git@master` to install translate-toolkit with fix for this.

**Comment by s4brown** [comment]
This has resolved my issues. Thanks!

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
