### ISSUE TITLE
Translation memory: not created after importing TMX or JSON files

### ISSUE THREAD

**Issue by ccanon** [WeblateOrg/weblate#2137]
### Steps to reproduce
1. Only the service WeblateTranslation is set to active : 
# List of machine translations
MT_SERVICES = (
#     'weblate.machinery.apertium.ApertiumAPYTranslation',
#     'weblate.machinery.deepl.DeepLTranslation',
#     'weblate.machinery.glosbe.GlosbeTranslation',
#     'weblate.machinery.google.GoogleTranslation',
#     'weblate.machinery.microsoft.MicrosoftCognitiveTranslation',
#     'weblate.machinery.mymemory.MyMemoryTranslation',
#     'weblate.machinery.tmserver.AmagamaTranslation',
#     'weblate.machinery.tmserver.TMServerTranslation',
#     'weblate.machinery.yandex.YandexTranslation',
    'weblate.machinery.weblatetm.WeblateTranslation',
#     'weblate.machinery.saptranslationhub.SAPTranslationHub',
#    'weblate.memory.machine.WeblateMemory',
)

2. Invoke the command ./manage.py import_memory [translationFile].json or [translationFile].tmx
3. The result of this command is in both cases:
Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/vhosts/weblate/python35/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/var/www/vhosts/weblate/python35/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/vhosts/weblate/python35/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/vhosts/weblate/python35/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/var/www/vhosts/weblate/weblate/weblate/memory/management/commands/import_memory.py", line 59, in handle
    memory = TranslationMemory()
  File "/var/www/vhosts/weblate/weblate/weblate/memory/storage.py", line 71, in __init__
    self.index = FileStorage(data_dir('memory')).open_index()
  File "/var/www/vhosts/weblate/python35/lib/python3.5/site-packages/whoosh/filedb/filestore.py", line 176, in open_index
    return indexclass(self, schema=schema, indexname=indexname)
  File "/var/www/vhosts/weblate/python35/lib/python3.5/site-packages/whoosh/index.py", line 421, in __init__
    TOC.read(self.storage, self.indexname, schema=self._schema)
  File "/var/www/vhosts/weblate/python35/lib/python3.5/site-packages/whoosh/index.py", line 619, in read
    % (indexname, storage))
whoosh.index.EmptyIndexError: Index 'MAIN' does not exist in FileStorage('/var/www/vhosts/weblate/weblate/data/memory')
Exception ignored in: <bound method TranslationMemory.__del__ of <weblate.memory.storage.TranslationMemory object at 0x7faedf69fb70>>
Traceback (most recent call last):
  File "/var/www/vhosts/weblate/weblate/weblate/memory/storage.py", line 82, in __del__
    self.close()
  File "/var/www/vhosts/weblate/weblate/weblate/memory/storage.py", line 93, in close
    if self.searcher is not None:
AttributeError: 'TranslationMemory' object has no attribute 'searcher'

### Actual behaviour
Import terminology files (TMX and JSON formats) to create the translation memory is not functional.

### Expected behaviour
Translation memory is created.

### Server configuration
python manage.py list_versions --settings=weblate.settings
* Weblate 3.0.1
 * Python 3.5.5
 * Django 2.0.7
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * Translate Toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 1.8.3.1
 * Pillow (PIL) 1.1.7
 * dateutil 2.7.3
 * lxml 4.2.3
 * django-crispy-forms 1.7.2
 * compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * pytz 2018.5
 * pyuca N/A
 * python-bidi 0.4.0
 * pyLibravatar N/A
 * PyYAML 3.13
 * Database backends: django.db.backends.postgresql_psycopg2
 * Cache backends: default:MemcachedCache, avatar:FileBasedCache

### System checks
Please paste the output of command `./manage.py check --deploy` over here
python manage.py check --deploy --settings=weblate.settings System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W006) Your SECURE_CONTENT_TYPE_NOSNIFF setting is not set to True, so your pages will not be served with an 'x-content-type-options: nosniff' header. You should consider enabling this header to prevent the browser from identifying content types incorrectly.
?: (security.W007) Your SECURE_BROWSER_XSS_FILTER setting is not set to True, so your pages will not be served with an 'x-xss-protection: 1; mode=block' header. You should consider enabling this header to activate the browser's XSS filtering and help prevent XSS attacks.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W019) You have 'django.middleware.clickjacking.XFrameOptionsMiddleware' in your MIDDLEWARE, but X_FRAME_OPTIONS is not set to 'DENY'. The default is 'SAMEORIGIN', but unless there is a good reason for your site to serve other parts of itself in a frame, you should change it to 'DENY'.

System check identified 6 issues (0 silenced).

**Comment by nijel** [comment]
Can you please post your INSTALLED_APPS from settings? It might be that the translation memory app is missing there...

**Comment by nijel** [comment]
Hmm, that looks correct. Can you try running `./manage.py migrate memory` if that fixes the issue?

**Comment by ccanon** [comment]
Here is the result of the command we invoked:

python manage.py migrate memory --settings=weblate.settings
Operations to perform:
  Apply all migrations: memory
Running migrations:
  No migrations to apply.

**Comment by nijel** [comment]
Is the import still broken after this? Have you recently changed location of DATA_DIR?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
