### ISSUE TITLE
Can't run weblate command. 

### ISSUE THREAD

**Issue by mrPsycho** [WeblateOrg/weblate#2162]
### Steps to reproduce

1. upgrade weblate from 2.20 to latest via `pip install --upgrade weblate`
2. run `weblate`

### Actual behaviour

```
(weblate) $ ./bin/weblate
ERROR Handled exception ImportError: No module named permissions
Traceback (most recent call last):
  File "./bin/weblate", line 11, in <module>
    sys.exit(main())
  File "/var/lib/weblate/local/lib/python2.7/site-packages/weblate/runner.py", line 34, in main
    execute_from_command_line(argv)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/apps/config.py", line 127, in create
    import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named permissions
```
### Expected behaviour

it should work

### Server configuration and status

OS is Ubuntu

**Comment by nijel** [comment]
Please read [upgrading instructions](https://docs.weblate.org/en/latest/admin/upgrade.html). It would work if you would have followed them.

**Comment by mrPsycho** [comment]
@nijel thanks, but... 

what i've did:

* Backup your database and Weblate.
* Stop web server and any background jobs using Weblate.
* Downloaded from github settings_example.py with tab 3.0.1
* fixed it with commenting out AUTH_USER_MODEL in the configuration + adding ldap configuration. 

and tried to migrate:
```
(weblate) $ weblate migrate weblate_auth 0001
/var/lib/weblate/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
WARNING:root:Python-Levenshtein not found. Continuing with built-in (slower) fuzzy matching.
CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0143_auto_20180609_1655, 0129_auto_20180411_1725 in trans; 0037_auto_20180416_1406, 0037_auto_20180411_1725 in accounts).
To fix them run 'python manage.py makemigrations --merge'
```

is it correct behaviour?

**Comment by mrPsycho** [comment]
next: 

```
(weblate) $ weblate makemigrations --merge
/var/lib/weblate/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
WARNING:root:Python-Levenshtein not found. Continuing with built-in (slower) fuzzy matching.
Merging trans
  Branch 0143_auto_20180609_1655
    - Change Meta options on check
    - Change Meta options on unit
    - Custom state/database change combination
    - Add field component_ids to componentlist
    - Raw Python operation
    - Remove field components from componentlist
    - Rename model SubProject to Component
    - Add field components to componentlist
    - Raw Python operation
    - Remove field component_ids from componentlist
    - Change Meta options on component
    - Rename field subproject on change to component
    - Rename field subproject on source to component
    - Rename field subproject on translation to component
    - Rename field subproject on whiteboardmessage to component
    - Alter unique_together for source (1 constraint(s))
    - Alter unique_together for translation (1 constraint(s))
    - Change Meta options on change
    - Change Meta options on component
    - Change Meta options on dictionary
    - Change Meta options on project
    - Change Meta options on source
    - Change Meta options on suggestion
    - Change Meta options on translation
    - Change Meta options on unit
    - Remove field extra_commit_file from component
    - Remove field post_add_script from component
    - Remove field post_commit_script from component
    - Remove field post_push_script from component
    - Remove field post_update_script from component
    - Remove field pre_commit_script from component
    - Add field details to change
    - Add field project to change
    - Alter field action on change
    - Create model ContributorAgreement
    - Alter unique_together for contributoragreement (1 constraint(s))
    - Alter field add_message on component
    - Alter field commit_message on component
    - Alter field delete_message on component
    - Raw Python operation
    - Alter field add_message on component
    - Alter field commit_message on component
    - Alter field delete_message on component
    - Add field context to source
    - Raw Python operation
    - Add field linked_component to component
    - Raw Python operation
    - Alter field access_control on project
    - Alter field enable_review on project
    - Alter field set_translation_team on project
  Branch 0129_auto_20180411_1725
    - Alter field file_format on subproject
    - Alter field vcs on subproject

Merging will only work if the operations printed above do not conflict
with each other (working on different fields or models)
Do you want to merge these migration branches? [y/N] y

Created new merge migration /var/lib/weblate/local/lib/python2.7/site-packages/weblate/trans/migrations/0144_merge_20180810_0014.py
Merging accounts
  Branch 0037_auto_20180416_1406
    - Alter field address on auditlog
    - Alter field dashboard_view on profile
  Branch 0037_auto_20180411_1725
    - Alter field dashboard_view on profile
    - Alter field language on profile

Merging will only work if the operations printed above do not conflict
with each other (working on different fields or models)
Do you want to merge these migration branches? [y/N] y

Created new merge migration /var/lib/weblate/local/lib/python2.7/site-packages/weblate/accounts/migrations/0038_merge_20180810_0014.py
```
will it destroy my db?

**Comment by mrPsycho** [comment]
then `weblate migrate` passwd. 

after this, i started to upgrade to 3.1.1. 

did all the same tasks and now on migrate i have this: 
```
(weblate) $ weblate migrate
/var/lib/weblate/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Operations to perform:
  Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, lang, memory, screenshots, sessions, sites, social_django, trans, weblate_auth, wladmin
ERROR Handled exception KeyError: ('trans', u'subproject')
Traceback (most recent call last):
  File "/var/lib/weblate/bin/weblate", line 11, in <module>
    sys.exit(main())
  File "/var/lib/weblate/local/lib/python2.7/site-packages/weblate/runner.py", line 34, in main
    execute_from_command_line(argv)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 163, in handle
    pre_migrate_state = executor._create_project_state(with_applied_migrations=True)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 81, in _create_project_state
    migration.mutate_state(state, preserve=False)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 92, in mutate_state
    operation.state_forwards(self.app_label, new_state)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 201, in state_forwards
    state.models[app_label, self.model_name_lower].fields
KeyError: ('trans', u'subproject')
```

**Comment by mrPsycho** [comment]
ok. 

dropped bd, restored from dump and i was able to upgrade to 3.0.1.
it works.

now i'm struggling with 3.1.1 and this: 
```
(weblate) $ weblate migrate
/var/lib/weblate/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Operations to perform:
  Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, lang, memory, screenshots, sessions, sites, social_django, trans, weblate_auth, wladmin
ERROR Handled exception KeyError: ('trans', u'subproject')
Traceback (most recent call last):
  File "/var/lib/weblate/bin/weblate", line 11, in <module>
    sys.exit(main())
  File "/var/lib/weblate/local/lib/python2.7/site-packages/weblate/runner.py", line 34, in main
    execute_from_command_line(argv)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 163, in handle
    pre_migrate_state = executor._create_project_state(with_applied_migrations=True)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 81, in _create_project_state
    migration.mutate_state(state, preserve=False)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 92, in mutate_state
    operation.state_forwards(self.app_label, new_state)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 201, in state_forwards
    state.models[app_label, self.model_name_lower].fields
KeyError: ('trans', u'subproject')
```

**Comment by mrPsycho** [comment]
i threw it away and reinstalled 3.1.1 from scratch.

**Comment by nijel** [comment]
You seem to have created own migration (0129_auto_20180411_1725) which does conflict with the ones shipped with Weblate, that was probably root cause for your migration issues.
