### ISSUE TITLE
3.1.1 install from pip shows errors

### ISSUE THREAD

**Issue by mrPsycho** [WeblateOrg/weblate#2166]
After installing weblate by pip and logging in first time in admin page i see this: 

```
Traceback (most recent call last):   File "/var/lib/weblate/local/lib/python2.7/site-packages/weblate/formats/models.py", line 50, in load_data     fileformat.get_class()   File "/var/lib/weblate/local/lib/python2.7/site-packages/weblate/formats/base.py", line 336, in get_class     module = importlib.import_module(module_name)   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module     __import__(name)   File "/var/lib/weblate/local/lib/python2.7/site-packages/translate/storage/yaml.py", line 30, in <module>     import yaml ImportError: No module named yaml
--
```

```
Traceback (most recent call last):
  File "/var/lib/weblate/local/lib/python2.7/site-packages/weblate/formats/models.py", line 50, in load_data
    fileformat.get_class()
  File "/var/lib/weblate/local/lib/python2.7/site-packages/weblate/formats/base.py", line 336, in get_class
    module = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/translate/storage/php.py", line 63, in <module>
    from phply.phpparse import make_parser
ImportError: No module named phply.phpparse
```

(weblate) $ weblate list_versions
/var/lib/weblate/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
 * Weblate 3.1.1
 * Python 2.7.12
 * Django 1.11.15
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.7.4
 * Pillow 5.2.0
 * python-dateutil 2.7.3
 * lxml 4.2.4
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.5
 * PyYAML 3.13
 * Mercurial 3.7.3
 * Database backends: django.db.backends.postgresql_psycopg2
 * Cache backends: default:LocMemCache
 * Platform: Linux 2.6.32-042stab128.2 (x86_64)

**Comment by nijel** [comment]
You don't have some of the optional dependencies. If you don't plan to use yaml or php formats there is no problem in that.

**Comment by mrPsycho** [comment]
ok. thanks.
