### ISSUE TITLE
Problem with upgrade 3.0.1->3.1.1

### ISSUE THREAD

**Issue by czKKill** [WeblateOrg/weblate#2170]
### Steps to reproduce

1. Have fully working Weblate 3.0.1
2. git fetch
3. git checkout weblate-3.1.1
4. pip install -r requirements.txt
5. Compare weblate/settings.py with weblate/settings_example.py and process changes
6. find . -name '*.pyc' -delete
7. ./manage.py migrate --noinput

### Actual behaviour

```
./manage.py migrate --noinput
Operations to perform:
  Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, lang, memory, screenshots, sessions, sites, social_django, trans, weblate_auth, wladmin
ERROR Handled exception KeyError: ('trans', u'subproject')
Traceback (most recent call last):
  File "./manage.py", line 29, in <module>
    main()
  File "/opt/weblate/weblate/weblate/runner.py", line 34, in main
    execute_from_command_line(argv)
  File "/opt/weblate/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/weblate/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/weblate/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/weblate/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/weblate/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 163, in handle
    pre_migrate_state = executor._create_project_state(with_applied_migrations=True)
  File "/opt/weblate/lib/python2.7/site-packages/django/db/migrations/executor.py", line 81, in _create_project_state
    migration.mutate_state(state, preserve=False)
  File "/opt/weblate/lib/python2.7/site-packages/django/db/migrations/migration.py", line 92, in mutate_state
    operation.state_forwards(self.app_label, new_state)
  File "/opt/weblate/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 200, in state_forwards
    state.models[app_label, self.model_name_lower].fields
KeyError: ('trans', u'subproject')
```

### Expected behaviour

Migrations should be applied

### Server configuration and status

```
./manage.py list_versions
 * Weblate weblate-3.1.1
 * Python 2.7.5
 * Django 1.11.5
 * six 1.10.0
 * social-auth-core 1.4.0
 * social-auth-app-django 1.2.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 1.8.3.1
 * Pillow 4.2.1
 * python-dateutil 2.6.1
 * lxml 3.8.0
 * django-crispy-forms 1.6.1
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2017.2
 * pyuca 1.1.2
 * python-bidi 0.4.0
 * PyYAML 3.12
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:MemcachedCache, avatar:FileBasedCache
 * Platform: Linux 3.10.0-862.9.1.el7.x86_64 (x86_64)
```

```
./manage.py check --deploy
System check identified no issues (0 silenced).
```

Any idea where might be a problem?

**Comment by nijel** [comment]
Don't you have some old files around? There is nothing mentioning subproject in the 3.1.1 release. What's output of `git status`?

**Comment by czKKill** [comment]
Yes, that was the case - I had these there:
```
git status
# HEAD detached at weblate-3.1.1
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#       =1.3.0
#       weblate/settings_old.py
#       weblate/trans/migrations/0117_auto_20180111_1522.py
#       weblate/trans/migrations/0118_merge_20180111_1534.py
#       weblate/trans/migrations/0120_merge_20180127_1217.py
#       weblate/trans/migrations/0125_merge_20180301_1735.py
#       weblate/trans/migrations/0129_merge_20180421_1554.py
#       weblate/trans/migrations/0144_merge_20180627_1630.py
```

Not sure where I get them/why were they there, but after doing a `git clean -r` all is working fine. Thank you for you help!
