### ISSUE TITLE
ImportError: Windows RC file format is not supported on Python 3

### ISSUE THREAD

**Issue by burner1024** [WeblateOrg/weblate#2182]
### Steps to reproduce

1. Upgrade Weblate to 3.1.1
2. Switch to Python 3

### Actual behaviour
Seeing this in performance report:
```
Traceback (most recent call last):
  File "./weblate/formats/models.py", line 50, in load_data
    fileformat.get_class()
  File "./weblate/formats/ttkit.py", line 709, in get_class
    'Windows RC file format is not supported on Python 3'
ImportError: Windows RC file format is not supported on Python 3
```
### Expected behaviour
No errors.

### Server configuration and status
```
 * Weblate weblate-3.1.1-4-ge65c8c6a9c
 * Python 3.6.5
 * Django 2.1
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow 5.2.0
 * python-dateutil 2.7.3
 * lxml 4.2.4
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.5
 * PyYAML 3.13
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Platform: Linux 4.15.18-1-pve (x86_64)
```
```
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W018) You should not have DEBUG set to True in deployment.```
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
