### ISSUE TITLE
Show a helpful error message when VCS reset throws an error.

### ISSUE THREAD

**Issue by dburner** [WeblateOrg/weblate#2189]
When a user clicks a the `Reset` button on repository and a component is missing from the new sources Weblate shows a generic error saying `Internal Server Error` without a message telling what went wrong.

In this case weblate should show a nice error message notifying the user what exactly went wrong for example: `The component X had an error, the file Y could not be found`.

A nice to have feature would be to treat more error kinds (ie: missing file, out of storage space, etc)

Current stack trace from logs

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/views/git.py", line 209, in reset_project
    return perform_reset(request, obj)
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/views/git.py", line 98, in perform_reset
    request,
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/views/git.py", line 41, in execute_locked
    result = call(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/models/project.py", line 283, in do_reset
    ret |= component.do_reset(request)
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/models/component.py", line 88, in on_link_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/models/component.py", line 755, in do_reset
    self.create_translations(request=request)
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/models/component.py", line 968, in create_translations
    component.create_translations(force, langs, request=request)
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/models/component.py", line 939, in create_translations
    self, lang, code, path, force, request=request
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/models/translation.py", line 73, in check_sync
    translation.check_sync(force, request=request)
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/models/translation.py", line 239, in check_sync
    if self.revision != self.get_git_blob_hash():
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/models/translation.py", line 353, in get_git_blob_hash
    ret = self.component.repository.get_object_hash(self.get_filename())
  File "/usr/local/lib/python3.5/dist-packages/weblate/vcs/base.py", line 336, in get_object_hash
    with open(real_path, 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/app/data/vcs/<somefile>.extension'
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has been fixed by 53370ef058e7cf10092c91db2a9c37b10da4e364.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
