### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2195]
View details in Rollbar: [https://rollbar.com/nijel/weblate/items/1670/](https://rollbar.com/nijel/weblate/items/1670/)

```
Traceback (most recent call last):
  File "/home/nijel/weblate_demo/weblate/trans/views/dictionary.py", line 176, in upload_dictionary
    form.cleaned_data['method']
  File "/home/nijel/weblate_demo/weblate/trans/models/dictionary.py", line 49, in upload
    store = AutoFormat.parse(fileobj)
  File "/home/nijel/weblate_demo/weblate/formats/auto.py", line 95, in parse
    return storeclass(storefile, template_store, language_code)
  File "/home/nijel/weblate_demo/weblate/formats/ttkit.py", line 533, in __init__
    storefile, template_store, language_code
  File "/home/nijel/weblate_demo/weblate/formats/base.py", line 361, in __init__
    self.store = self.load(storefile)
  File "/home/nijel/weblate_demo/weblate/formats/base.py", line 325, in load
    return cls.parse_store(storefile)
  File "/home/nijel/weblate_demo/weblate/formats/ttkit.py", line 565, in parse_store
    store = storeclass.parsefile(storefile)
  File "/home/nijel/translate/translate/storage/base.py", line 899, in parsefile
    newstore = cls.parsestring(storestring)
  File "/home/nijel/translate/translate/storage/base.py", line 780, in parsestring
    newstore.parse(storestring)
  File "/home/nijel/translate/translate/storage/csvl10n.py", line 319, in parse
    sample = text[:1024]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by nijel** [comment]
Should be already fixed by https://github.com/translate/translate/pull/3818.
