### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: Error importing module weblate.formats.ttkit in WEBLATE_FORMATS: "No module named backports"

### ISSUE THREAD

**Issue by Jibec** [WeblateOrg/weblate#2294]
**Describe the bug**
The Weblate installation on YunoHost doesn't work anymore.

```
(venv) weblate@jb9:~$ weblate migrate --noinput
ERROR Handled exception ImproperlyConfigured: Error importing module weblate.formats.ttkit in WEBLATE_FORMATS: "No module named backports"
Traceback (most recent call last):
  File "/var/www/weblate/venv/bin/weblate", line 11, in <module>
    sys.exit(main())
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/weblate/runner.py", line 34, in main
    execute_from_command_line(argv)
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/weblate/addons/models.py", line 39, in <module>
    from weblate.trans.models import Component, Unit
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/weblate/trans/models/__init__.py", line 33, in <module>
    from weblate.trans.models.component import Component
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/weblate/trans/models/component.py", line 110, in <module>
    class Component(models.Model, URLMixin, PathMixin):
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/weblate/trans/models/component.py", line 233, in Component
    choices=FILE_FORMATS.get_choices(),
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/weblate/utils/classloader.py", line 107, in get_choices
    return [(x, self[x].name) for x in sorted(self)]
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/weblate/utils/classloader.py", line 95, in __iter__
    return self.data.__iter__()
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/weblate/utils/classloader.py", line 74, in data
    return self.load_data()
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/weblate/formats/models.py", line 50, in load_data
    result = super(FileFormatLoader, self).load_data()
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/weblate/utils/classloader.py", line 66, in load_data
    obj = load_class(path, self.name)
  File "/var/www/weblate/venv/local/lib/python2.7/site-packages/weblate/utils/classloader.py", line 43, in load_class
    module, setting, error
django.core.exceptions.ImproperlyConfigured: Error importing module weblate.formats.ttkit in WEBLATE_FORMATS: "No module named backports"
```

**To Reproduce**
1. Install YunoHost
2. fork https://github.com/YunoHost-Apps/weblate_ynh and go on 'testing' branch
3. install from script

**Expected behavior**

should give an error message I can understand ;)

On Git checkout:

```
./manage.py list_versions
./manage.py check --deploy
```

==> same error message

**Additional context**

I can't understand the link between the error message and the diff between my settings.py in version 3.1 and 3.2: https://github.com/YunoHost-Apps/weblate_ynh/commit/131f74288645b5e11e4cbac8f9d0dd5e6437601c

YunoHost version is up to date.

```
(venv) weblate@jb9:~$ pip freeze
amqp==2.3.2
Babel==2.6.0
billiard==3.5.0.4
celery==4.2.1
celery-batches==0.2
certifi==2018.8.24
chardet==3.0.4
defusedxml==0.5.0
diff-match-patch==20121119
Django==1.11.16
django-appconf==1.0.2
django-compressor==2.2
django-crispy-forms==1.7.2
django-sendmail-backend==0.1.2
djangorestframework==3.8.2
et-xmlfile==1.0.1
filelock==3.0.9
idna==2.7
jdcal==1.4
jellyfish==0.6.1
kombu==4.2.1
lxml==4.2.5
oauthlib==2.1.0
openpyxl==2.5.8
phply==1.2.5
Pillow==5.3.0
pkg-resources==0.0.0
ply==3.11
psycopg2-binary==2.7.5
pydns==2.3.6
PyJWT==1.6.4
pyLibravatar==1.7
python-bidi==0.4.0
python-dateutil==2.7.3
python-memcached==1.59
python-openid==2.2.5
pytz==2018.5
pyuca==1.2
PyYAML==3.13
rcssmin==1.0.6
requests==2.19.1
requests-oauthlib==1.0.0
rjsmin==1.0.12
siphashc==1.2
six==1.11.0
social-auth-app-django==2.1.0
social-auth-core==1.7.0
translate-toolkit==2.3.1
ua-parser==0.8.0
urllib3==1.23
user-agents==1.1.0
vine==1.1.4
Weblate==3.2
Whoosh==2.7.4
```

Thanks for your help!

**Comment by nijel** [comment]
You are missing `backports.csv`, this is dependency introduced by latest translate-toolkit (and I didn't expect it will get our few hours after Weblate release).

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. I've added it to `requirements.txt` and documentation, I don't think this on it's own warrants bugfix release.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
