### ISSUE TITLE
Occasional test failure in OSX strings loader

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#2296]
**Describe the bug**
Sometimes the tests fail on importing OSX strings. So far this has never happened during CI or development, but sometimes the failure can be seen in Docker CI runs.

**To Reproduce**
No clue, example can be seen in https://travis-ci.org/WeblateOrg/docker/jobs/438294475

**Additional context**
```
======================================================================
FAIL: test_import_author (weblate.trans.tests.test_files.StringsImportTest)
Test importing normally.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/tests/test_files.py", line 106, in test_import_author
    self.assertEqual(translation.stats.translated, 1)
AssertionError: 0 != 1
======================================================================
FAIL: test_import_fuzzy (weblate.trans.tests.test_files.StringsImportTest)
Test importing as fuzzy.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/tests/test_files.py", line 145, in test_import_fuzzy
    self.assertEqual(unit.target, TRANSLATION_PO)
AssertionError: '' != 'Ahoj světe!\n'
+ Ahoj světe!
======================================================================
FAIL: test_import_normal (weblate.trans.tests.test_files.StringsImportTest)
Test importing normally.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/tests/test_files.py", line 88, in test_import_normal
    self.assertEqual(translation.stats.translated, 1)
AssertionError: 0 != 1
======================================================================
FAIL: test_import_overwrite (weblate.trans.tests.test_files.StringsImportTest)
Test importing with overwriting.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/tests/test_files.py", line 124, in test_import_overwrite
    self.assertEqual(unit.target, TRANSLATION_PO)
AssertionError: 'Nazdar světe!\n' != 'Ahoj světe!\n'
- Nazdar světe!
+ Ahoj světe!
======================================================================
FAIL: test_import_suggest (weblate.trans.tests.test_files.StringsImportTest)
Test importing as suggestion.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/tests/test_files.py", line 170, in test_import_suggest
    1
AssertionError: 0 != 1
```

**Comment by nijel** [comment]
Okay, the problem seems to be in the uploaded cs.po file - it's valid UTF-16 file and is being parsed as a Strings properties file. Leading to single unit with source "‣穃捥⁨牴湡汳瑡潩獮映牯倠䍁䅋䕇瀠捡慫敧ਮ‣潃祰楲桧⁴䌨 〲㈱吠䕈倠䍁䅋䕇匧䌠偏剙䝉呈䠠䱏䕄੒‣桔獩映汩⁥獩搠獩牴扩瑵摥甠摮牥琠敨猠浡⁥楬散獮⁥獡琠敨倠䍁䅋䕇瀠捡慫敧ਮ‣畁潴慭楴慣汬⁹敧敮慲整Ɽ㈠㄰⸲⌊吠獥楴杮圠扥慬整‬〲㔱ਮ獭楧⁤∢洊杳瑳⁲∢∊牐橯捥⵴摉嘭牥楳湯›敗汢瑡⁥效汬⁯潗汲⁤〲㈱湜ਢ刢灥牯⵴獍楧ⵤ畂獧吭㩯㰠潮敲汰䁹硥浡汰⹥敮㹴湜ਢ倢呏䌭敲瑡潩⵮慄整›〲〰〭ⴱ㈰〠㨳㐰〫〱尰≮∊佐刭癥獩潩⵮慄整›〲㈱〭ⴳ㔰ㄠ㨵㔵〫〱尰≮∊慌瑳吭慲獮慬潴㩲䄠瑵浯瑡捩污祬朠湥牥瑡摥湜ਢ䰢湡畧条ⵥ敔浡›敔瑳吠慥⁭渼牯灥祬着扥慬整漮杲尾≮∊慌杮慵敧›獣湜ਢ䴢䵉ⵅ敖獲潩㩮ㄠ〮湜ਢ䌢湯整瑮吭灹㩥琠硥⽴汰楡㭮挠慨獲瑥唽䙔㠭湜ਢ䌢湯整瑮吭慲獮敦⵲湅潣楤杮›戸瑩湜ਢ倢畬慲⵬潆浲㩳渠汰牵污㵳㬳瀠畬慲㵬渨㴽⤱㼠〠㨠⠠㹮㈽☠…㱮㐽 ‿‱›㬲湜ਢ⌊›慭湩挮ㄺ਱Ⱓ挠昭牯慭ੴ獭楧⁤䠢汥潬‬潷汲Ⅴ湜ਢ獭獧牴∠桁橯猠쑶璛Ⅵ湜ਢ⌊›慭湩挮ㄺਲⰣ挠昭牯慭ੴ獭楧⁤伢慲杮瑵湡栠獡┠⁤慢慮慮尮≮洊杳摩灟畬慲⁬伢慲杮瑵湡栠獡┠⁤慢慮慮⹳湜ਢ獭獧牴せ⁝∢ਊ㨣洠楡⹮㩣㌱⌊‬ⵣ潦浲瑡洊杳摩∠牔⁹敗汢瑡⁥瑡㰠瑨灴㩳⼯敤潭眮扥慬整漮杲㸯尡≮洊杳瑳⁲∢ਊ㨣洠楡⹮㩣㐱洊杳摩∠桔湡⁫潹⁵潦⁲獵湩⁧敗汢瑡⹥ਢ獭獧牴∠ਢ"

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by nijel** [comment]
What is still unclear to me is why the tests did work correctly in most cases.
