### ISSUE TITLE
Crash on commit_pending when --age=<num> is used

### ISSUE THREAD

**Issue by SlavekB** [WeblateOrg/weblate#2341]
**Describe the bug**
If the commit_pending task is run from cron or CLI without specifying --age=&lt;number&gt;, the task is executed successfully. If I use the the same with --age=&lt;number&gt; for the test purposes, a crash occurs. I observe this problem since updating to Weblate 3.2.x.

**To Reproduce**
1. Make changes to some translation.
2. From the command line, enter:
`weblate commit_pending project/component --age=1`
3. See crash

**Expected behavior**
I expect the crash will not occur and the commit will be done properly.

**Server configuration and status**
$ weblate list_versions
 * Weblate 3.2.2
 * Python 2.7.13
 * Django 1.11.15
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.11.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 5.2.0
 * python-dateutil 2.7.3
 * lxml 4.2.5
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.8.2
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.5
 * pyuca 1.1.2
 * PyYAML 3.12
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Platform: Linux 3.16.6-042stab127.46 (x86_64)

$ weblate check --deploy
System check identified no issues (0 silenced).

**Additional context**
```
ERROR Handled exception UnboundLocalError: local variable 'age' referenced before assignment
Traceback (most recent call last):
  File "/var/lib/weblate/bin/weblate", line 11, in <module>
    sys.exit(main())
  File "/var/lib/weblate/local/lib/python2.7/site-packages/weblate/runner.py", line 34, in main
    execute_from_command_line(argv)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/weblate/trans/management/commands/__init__.py", line 42, in execute
    super(WeblateCommand, self).execute(*args, **options)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/weblate/trans/management/commands/commit_pending.py", line 45, in handle
    self.stdout.write if int(options['verbosity']) >= 1 else None,
  File "/var/lib/weblate/local/lib/python2.7/site-packages/celery/local.py", line 191, in __call__
    return self._get_current_object()(*a, **kw)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/celery/app/task.py", line 375, in __call__
    return self.run(*args, **kwargs)
  File "/var/lib/weblate/local/lib/python2.7/site-packages/weblate/trans/tasks.py", line 94, in commit_pending
    if last_change > age:
UnboundLocalError: local variable 'age' referenced before assignment
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by SlavekB** [comment]
Tested, works great!
