### ISSUE TITLE
wlc commit: AttributeError: type object 'RepoRequestSerializer' has no attribute 'Meta'

### ISSUE THREAD

**Issue by ihoru** [WeblateOrg/weblate#2356]
**Describe the bug**

```
ERROR Internal Server Error: /api/components/automatica/master-django/repository/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.5/dist-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/renderers.py", line 732, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/renderers.py", line 693, in get_context
    'description': self.get_description(view, response.status_code),
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/renderers.py", line 611, in get_description
    return view.get_view_description(html=True)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 247, in get_view_description
    return func(self, html)
  File "/usr/local/lib/python3.5/dist-packages/weblate/api/views.py", line 89, in get_view_description
    view_cls.serializer_class.Meta.model.__name__.lower()
AttributeError: type object 'RepoRequestSerializer' has no attribute 'Meta'
172.21.0.9 - - [29/Oct/2018:08:48:04 +0000] "GET /api/components/project/component/repository/ HTTP/1.0" 500 7139 "-" ""

```

**To Reproduce**
wlc commit

**Expected behavior**
Commit should be executed

**Server configuration and status**
`list_versions`

```
 * Weblate 3.2.2
 * Python 3.5.3
 * Django 2.1.2
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.10.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 4.0.0
 * python-dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.0
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.5
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.3.1
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Platform: Linux 4.4.0-138-generic (x86_64)
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f996b8bdea0>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f996b8bdea0>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable

```

`check --deploy` 
```
SystemCheckError: System check identified some issues:

ERRORS:
?: (weblate.E011) The site admins seem to be wrongly configured
	HINT: https://docs.weblate.org/en/weblate-3.2.2/admin/install.html#production-admins

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

System check identified 4 issues (0 silenced).
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa352639ea0>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fa352639ea0>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has been already fixed by b5e54664dc8a5307ee3f64b9c632b9a85c229c23.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
