### ISSUE TITLE
[docker] Celery not working after version-by-version upgrade from 3.2-1 to 3.2.2-3

### ISSUE THREAD

**Issue by shindler** [WeblateOrg/weblate#2394]
Celery stopped working as expected after we have bumped up our docker based Weblate to version 3.2.2-3 (version by version from 3.2-1). We were getting same error regarding celery during updates from: 3.2.1-2 to 3.2.2-1, 3.2.2-1 to 3.2.2-2 and further to 3.2.2-3.

Stack trace given while trying to run callery (via bash; same given container startup):
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'scheduler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: 'entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/beat.py", line 515, in _create_schedule
    self._store[str('entries')]
  File "/usr/lib/python3.5/shelve.py", line 113, in __getitem__
    f = BytesIO(self.dict[key.encode(self.keyencoding)])
KeyError: b'entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/celery/beat.py", line 664, in run
    self.service.start(embedded_process=True)
  File "/usr/local/lib/python3.5/dist-packages/celery/beat.py", line 579, in start
    humanize_seconds(self.scheduler.max_interval))
  File "/usr/local/lib/python3.5/dist-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/usr/local/lib/python3.5/dist-packages/celery/beat.py", line 623, in scheduler
    return self.get_scheduler()
  File "/usr/local/lib/python3.5/dist-packages/celery/beat.py", line 618, in get_scheduler
    lazy=lazy,
  File "/usr/local/lib/python3.5/dist-packages/celery/beat.py", line 458, in __init__
    Scheduler.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/beat.py", line 225, in __init__
    self.setup_schedule()
  File "/usr/local/lib/python3.5/dist-packages/celery/beat.py", line 486, in setup_schedule
    self._create_schedule()
  File "/usr/local/lib/python3.5/dist-packages/celery/beat.py", line 519, in _create_schedule
    self._store[str('entries')] = {}
  File "/usr/lib/python3.5/shelve.py", line 125, in __setitem__
    self.dict[key.encode(self.keyencoding)] = f.getvalue()
_dbm.error: cannot add item to database
Process Beat:
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/kombu/utils/objects.py", line 42, in __get__
    return obj.__dict__[self.__name__]
KeyError: 'scheduler'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/lib/python3.5/shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: 'entries'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/celery/beat.py", line 515, in _create_schedule
    self._store[str('entries')]
File "/usr/lib/python3.5/shelve.py", line 113, in __getitem__
    f = BytesIO(self.dict[key.encode(self.keyencoding)])
KeyError: b'entries'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/billiard/process.py", line 327, in _bootstrap
    self.run()
File "/usr/local/lib/python3.5/dist-packages/celery/beat.py", line 664, in run
    self.service.start(embedded_process=True)
File "/usr/local/lib/python3.5/dist-packages/celery/beat.py", line 579, in start
    humanize_seconds(self.scheduler.max_interval))
File "/usr/local/lib/python3.5/dist-packages/kombu/utils/objects.py", line 44, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
File "/usr/local/lib/python3.5/dist-packages/celery/beat.py", line 623, in scheduler
    return self.get_scheduler()
File "/usr/local/lib/python3.5/dist-packages/celery/beat.py", line 618, in get_scheduler
    lazy=lazy,
File "/usr/local/lib/python3.5/dist-packages/celery/beat.py", line 458, in __init__
    Scheduler.__init__(self, *args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/celery/beat.py", line 225, in __init__
    self.setup_schedule()
File "/usr/local/lib/python3.5/dist-packages/celery/beat.py", line 486, in setup_schedule
    self._create_schedule()
File "/usr/local/lib/python3.5/dist-packages/celery/beat.py", line 519, in _create_schedule
    self._store[str('entries')] = {}
File "/usr/lib/python3.5/shelve.py", line 125, in __setitem__
    self.dict[key.encode(self.keyencoding)] = f.getvalue()
_dbm.error: cannot add item to database
Exception ignored in:
<bound method Shelf.__del__ of <shelve.DbfilenameShelf object at 0x7f587438db00>>
Traceback (most recent call last):
File "/usr/lib/python3.5/shelve.py", line 162, in __del__
self.close()
File "/usr/lib/python3.5/shelve.py", line 144, in close
self.sync()
File "/usr/lib/python3.5/shelve.py", line 168, in sync
self[key] = entry
File "/usr/lib/python3.5/shelve.py", line 125, in __setitem__
self.dict[key.encode(self.keyencoding)] = f.getvalue()
_dbm.error: cannot add item to database
```

list versions ouput:
```
* Weblate 3.2.2
 * Python 3.5.3
 * Django 2.1.2
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.10.0
 * social-auth-core 1.7.0
 * social-auth-app-django 2.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 4.0.0
 * python-dateutil 2.5.3
 * lxml 3.7.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.0
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.7
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.3.1
 * Mercurial 4.0
 * git-svn 2.11.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Platform: Linux 4.4.0-134-generic (x86_64)
```

check --deploy output
```
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E018) Failed to download avatar: <urlopen error [Errno 99] Cannot assign requested address>
	HINT: https://docs.weblate.org/en/weblate-3.2.2/admin/optionals.html#avatars

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

System check identified 4 issues (0 silenced).
```

**Additional context**
We have a custom task scheduled using `settings-override.py` with content:
```
CELERY_BEAT_SCHEDULE = {
    'commit': {
        'task': 'weblate.trans.tasks.commit_pending',
	'kwargs': {'hours': 0},
        'schedule': 120,
     }
}
```

**Comment by nijel** [comment]
This seems to be caused by corrupted celery beats database, see https://github.com/celery/celery/issues/2907. Can you try if removing `/app/data/celery/beat-schedule*` helps?
