### ISSUE TITLE
import_json incorrect repository error is confusing

### ISSUE THREAD

**Issue by Kingdutch** [WeblateOrg/weblate#2417]
**Describe the bug**
I've been trying to get the `import_json` command to work unsuccesfully. The error was quite confusing:

```
Traceback (most recent call last):
  File "/app/.global/bin/weblate", line 11, in <module>
    sys.exit(main())
  File "/app/.global/lib/python3.7/site-packages/weblate/runner.py", line 34, in main
    execute_from_command_line(argv)
  File "/app/.global/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/app/.global/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.global/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.global/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/app/.global/lib/python3.7/site-packages/weblate/trans/management/commands/import_json.py", line 143, in handle
    component = Component.objects.create(**item)
  File "/app/.global/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/app/.global/lib/python3.7/site-packages/django/db/models/query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "/app/.global/lib/python3.7/site-packages/weblate/trans/models/component.py", line 1388, in save
    self.sync_git_repo(skip_push=kwargs.get('force_insert', False))
  File "/app/.global/lib/python3.7/site-packages/weblate/trans/models/component.py", line 1055, in sync_git_repo
    self.configure_branch()
  File "/app/.global/lib/python3.7/site-packages/weblate/trans/models/component.py", line 606, in configure_branch
    self.repository.configure_branch(self.branch)
  File "/app/.global/lib/python3.7/site-packages/weblate/vcs/git.py", line 322, in configure_branch
    ['checkout', '-b', branch, 'origin/{0}'.format(branch)]
  File "/app/.global/lib/python3.7/site-packages/weblate/vcs/base.py", line 188, in execute
    args, self.path, fullcmd=fullcmd, local=self.local
  File "/app/.global/lib/python3.7/site-packages/weblate/vcs/base.py", line 172, in _popen
    output.decode('utf-8')
weblate.vcs.base.RepositoryException: fatal: Cannot update paths and switch to branch 'master' at the same time.
Did you intend to checkout 'origin/master' which can not be resolved as commit? (128)
Traceback (most recent call last):
  File "/app/.global/lib/python3.7/site-packages/weblate/trans/management/commands/import_json.py", line 124, in handle
    slug=item['slug'], project=item['project']
  File "/app/.global/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/app/.global/lib/python3.7/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
weblate.trans.models.component.DoesNotExist: Component matching query does not exist.
```

Furthermore if you keep running the command it seems to create a single component each time and then error out on the second new component.

The error "Component matching query does not exist" draws the attention and is confusing becaue it's of a type that doesn't seem to exist (`component.` instead of `Component.`).

**To Reproduce**
1. Create a valid file for json import and then input a repo URL for each entry that isn't working (e.g. a non-existant bitbucket repo over ssh)
2. Run the import command `weblate import_json --project project --ignore /tmp/components.json`
3. See error

**Expected behavior**
Feedback that the Git repository is incorrect without any other errors as and either aborting of the import or ignoring of the specific component. This allows the json file to be corrected and retried.

**Server configuration and status**
```
 * Weblate 3.2.2
 * Python 3.7.0
 * Django 2.1.3
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.11.0
 * social-auth-core 2.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.11.0
 * Pillow 5.3.0
 * python-dateutil 2.7.5
 * lxml 4.2.5
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.0
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.7
 * Mercurial 4.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Platform: Linux 4.18.10-pl1 (x86_64)


System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.

System check identified 1 issue (0 silenced).

```

**Comment by nijel** [comment]
This really looks like you're passing some wrong parameters to the import_json command. The problem is that it didn't do any validation of passed data, so that could easily lead to broken setup. I've just added validation of the args in 5f0d701a99, that should make the situation easier to debug.

**Comment by Kingdutch** [comment]
After manually trying to create the component it indeed showed me that my Bitbucket git URL was incorrect so it couldn't retrieve the repo (in the UI this prevents saving).

Looks like a great addition!
