### ISSUE TITLE
Internal server error after each reboot

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#2467]
**Describe the bug**
One of testing instances of weblate breaks after each reboot, and permanently generates Internal server error until `service uwsgi restart`.

It seems that weblate attempts to use `redis@weblate.service` in time it is starting and it is in an intermediate state. It confuses weblate, and even if it becomes available afterwards, weblate stays in the Internal server error state forever.

It seems to be a strange race condition.

**To Reproduce**
I cannot reproduce this problem on a different system. But it is 100% reproducible on my testing instance.

**Expected behavior**
Reboot without problems.

**Screenshots**
N/A

**Server configuration and status**
```
./manage.py list_versions
 * Weblate 3.3
 * Python 3.6.5
 * Django 2.0.8
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.11.0
 * social-auth-core 2.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.16.4
 * Pillow 5.0.0
 * python-dateutil 2.6.1
 * lxml 4.0.0
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.0
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2017.3
 * pyuca 1.2
 * python-bidi 0.4.0
 * PyYAML 3.12
 * tesserocr 2.2.2
 * Mercurial 4.5.2
 * git-svn 2.16.4
 * git-review 1.25.0
 * Database backends: django.db.backends.postgresql_psycopg2
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.12.14-lp150.12.25-default (x86_64)

./manage.py check --deploy
System check identified no issues (0 silenced).
```

**Additional context**

This can be found in the system log:
```
pro 20 20:49:45 dhcp152 uwsgi[827]: Traceback (most recent call last):
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/lib/python3.6/site-packages/django_redis/cache.py", line 32, in _decorator
pro 20 20:49:45 dhcp152 uwsgi[827]:     return method(self, *args, **kwargs)
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/lib/python3.6/site-packages/django_redis/cache.py", line 81, in get
pro 20 20:49:45 dhcp152 uwsgi[827]:     client=client)
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/lib/python3.6/site-packages/django_redis/client/default.py", line 205, in get
pro 20 20:49:45 dhcp152 uwsgi[827]:     raise ConnectionInterrupted(connection=client, parent=e)
pro 20 20:49:45 dhcp152 uwsgi[827]: django_redis.exceptions.ConnectionInterrupted: Redis ConnectionError: Error 2 connecting to unix socket: /run/redis/weblate.sock. No such file or directory.
pro 20 20:49:45 dhcp152 uwsgi[827]: During handling of the above exception, another exception occurred:
pro 20 20:49:45 dhcp152 uwsgi[827]: Traceback (most recent call last):
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/share/weblate/weblate/wsgi.py", line 44, in <module>
pro 20 20:49:45 dhcp152 uwsgi[827]:     application = get_wsgi_application()
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
pro 20 20:49:45 dhcp152 uwsgi[827]:     django.setup(set_prefix=False)
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
pro 20 20:49:45 dhcp152 uwsgi[827]:     apps.populate(settings.INSTALLED_APPS)
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
pro 20 20:49:45 dhcp152 uwsgi[827]:     app_config.import_models()
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
pro 20 20:49:45 dhcp152 uwsgi[827]:     self.models_module = import_module(models_module_name)
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
pro 20 20:49:45 dhcp152 uwsgi[827]:     return _bootstrap._gcd_import(name[level:], package, level)
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/share/weblate/weblate/addons/models.py", line 39, in <module>
pro 20 20:49:45 dhcp152 uwsgi[827]:     from weblate.trans.models import Component, Unit
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/share/weblate/weblate/trans/models/__init__.py", line 34, in <module>
pro 20 20:49:45 dhcp152 uwsgi[827]:     from weblate.trans.models.component import Component
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/share/weblate/weblate/trans/models/component.py", line 113, in <module>
pro 20 20:49:45 dhcp152 uwsgi[827]:     class Component(models.Model, URLMixin, PathMixin):
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/share/weblate/weblate/trans/models/component.py", line 136, in Component
pro 20 20:49:45 dhcp152 uwsgi[827]:     choices=VCS_REGISTRY.get_choices(),
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/share/weblate/weblate/utils/classloader.py", line 107, in get_choices
pro 20 20:49:45 dhcp152 uwsgi[827]:     return [(x, self[x].name) for x in sorted(self)]
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/share/weblate/weblate/utils/classloader.py", line 95, in __iter__
pro 20 20:49:45 dhcp152 uwsgi[827]:     return self.data.__iter__()
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
pro 20 20:49:45 dhcp152 uwsgi[827]:     res = instance.__dict__[self.name] = self.func(instance)
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/share/weblate/weblate/utils/classloader.py", line 74, in data
pro 20 20:49:45 dhcp152 uwsgi[827]:     return self.load_data()
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/share/weblate/weblate/vcs/models.py", line 36, in load_data
pro 20 20:49:45 dhcp152 uwsgi[827]:     if not vcs.is_supported():
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/share/weblate/weblate/vcs/base.py", line 307, in is_supported
pro 20 20:49:45 dhcp152 uwsgi[827]:     delete_configuration_error(cls.name.lower())
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/share/weblate/weblate/trans/util.py", line 156, in delete_configuration_error
pro 20 20:49:45 dhcp152 uwsgi[827]:     errors = cache.get('configuration-errors', [])
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/lib/python3.6/site-packages/django_redis/cache.py", line 39, in _decorator
pro 20 20:49:45 dhcp152 uwsgi[827]:     raise e.parent
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/lib/python3.6/site-packages/django_redis/client/default.py", line 203, in get
pro 20 20:49:45 dhcp152 uwsgi[827]:     value = client.get(key)
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/lib/python3.6/site-packages/redis/client.py", line 976, in get
pro 20 20:49:45 dhcp152 uwsgi[827]:     return self.execute_command('GET', name)
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/lib/python3.6/site-packages/redis/client.py", line 673, in execute_command
pro 20 20:49:45 dhcp152 uwsgi[827]:     connection.send_command(*args)
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/lib/python3.6/site-packages/redis/connection.py", line 610, in send_command
pro 20 20:49:45 dhcp152 uwsgi[827]:     self.send_packed_command(self.pack_command(*args))
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/lib/python3.6/site-packages/redis/connection.py", line 585, in send_packed_command
pro 20 20:49:45 dhcp152 uwsgi[827]:     self.connect()
pro 20 20:49:45 dhcp152 uwsgi[827]:   File "/usr/lib/python3.6/site-packages/redis/connection.py", line 489, in connect
pro 20 20:49:45 dhcp152 uwsgi[827]:     raise ConnectionError(self._error_message(e))
pro 20 20:49:45 dhcp152 uwsgi[827]: redis.exceptions.ConnectionError: Error 2 connecting to unix socket: /run/redis/weblate.sock. No such file or directory.
pro 20 20:49:45 dhcp152 uwsgi[827]: unable to load app 0 (mountpoint='') (callable not found or import error)
pro 20 20:49:45 dhcp152 uwsgi[827]: *** no app loaded. going in full dynamic mode ***
pro 20 20:49:45 dhcp152 uwsgi[827]: *** uWSGI is running in multiple interpreter mode ***
pro 20 20:49:45 dhcp152 uwsgi[827]: spawned uWSGI master process (pid: 875)
pro 20 20:49:45 dhcp152 uwsgi[827]: Thu Dec 20 20:49:45 2018 - [emperor] vassal weblate.ini has been spawned
pro 20 20:49:45 dhcp152 uwsgi[827]: spawned uWSGI worker 1 (pid: 1367, cores: 1)
pro 20 20:49:45 dhcp152 uwsgi[827]: spawned uWSGI worker 2 (pid: 1368, cores: 1)
pro 20 20:49:45 dhcp152 uwsgi[827]: spawned uWSGI worker 3 (pid: 1369, cores: 1)
pro 20 20:49:45 dhcp152 uwsgi[827]: spawned uWSGI worker 4 (pid: 1370, cores: 1)
pro 20 20:49:45 dhcp152 uwsgi[827]: spawned uWSGI worker 5 (pid: 1371, cores: 1)
pro 20 20:49:45 dhcp152 uwsgi[827]: spawned uWSGI worker 6 (pid: 1372, cores: 1)
pro 20 20:49:45 dhcp152 uwsgi[827]: Thu Dec 20 20:49:45 2018 - [emperor] vassal weblate.ini is ready to accept requests
```

```
pro 20 20:55:31 dhcp152 uwsgi[827]: --- no python application found, check your startup logs for errors ---
pro 20 20:55:31 dhcp152 uwsgi[827]: [pid: 1371|app: -1|req: -1/4] 10.100.51.224 () {44 vars in 708 bytes} [Thu Dec 20 19:55:31 2018] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
```

It seems that a change in the third party `redis@.service` template fixes the problem:
```
--- redis@.service.orig	2018-06-15 14:43:46.000000000 +0200
+++ redis@.service	2018-12-20 21:08:46.891208801 +0100
@@ -2,6 +2,7 @@
 Description=Redis
 After=network.target
 PartOf=redis.target
+Before=uwsgi.service
 
 [Service]
 Type=simple
```

But it is not a correct fix, as it modifies third party file. We probably need a new target that is fulfilled after redis@weblate:

Here is a `weblate.target` solution that worked for me:
```
[Unit]
Description=Weblate Prerequisities
Requires=redis@weblate.service
Wants=celery-weblate.service
Before=uwsgi.service

[Install]
WantedBy=uwsgi.service
```

And then:
```
systemctl enable weblate.target
```

**Comment by nijel** [comment]
Yes, the cache backend currently needs to be working on startup, not sure we can avoid that.

**Comment by stanislav-brabec** [comment]
Confirming. This will trigger the problem as well:
```
service uwsgi stop
service redis@weblate stop
service uwsgi start
service redis@weblate start
```

Even if redis server is running, weblate remains broken.

The upper mentioned `weblate.target` ensures that services are started in a correct order. If you consider it as correct, you should add it to the documentation of the production installation.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
