### ISSUE TITLE
Weblate 3.3 - select_for_update cannot be used outside of a transaction

### ISSUE THREAD

**Issue by cigamit** [WeblateOrg/weblate#2479]
**Describe the bug**
2019-01-07 13:52:43,790 INFO "GET /new-lang/cacti/audit/ HTTP/1.0" 200 24748
2019-01-07 13:53:02,748 INFO cacti/audit/es: processing locales/po/es.po, new file
2019-01-07 13:53:02,769 ERROR Internal Server Error: /new-lang/cacti/audit/
Traceback (most recent call last):
  File "/home/weblate/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/weblate/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/weblate/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/weblate/venv/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/weblate/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/weblate/venv/lib/python2.7/site-packages/weblate/trans/views/basic.py", line 375, in new_language
    obj.add_new_language(language, request)
  File "/home/weblate/venv/lib/python2.7/site-packages/weblate/trans/models/component.py", line 1608, in add_new_language
    translation.check_sync(force=True, request=request)
  File "/home/weblate/venv/lib/python2.7/site-packages/weblate/trans/models/translation.py", line 274, in check_sync
    unit.id_hash: unit for unit in self.unit_set.select_for_update()
  File "/home/weblate/venv/lib/python2.7/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/home/weblate/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/weblate/venv/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "/home/weblate/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 876, in execute_sql
    sql, params = self.as_sql()
  File "/home/weblate/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 468, in as_sql
    raise TransactionManagementError('select_for_update cannot be used outside of a transaction.')
TransactionManagementError: select_for_update cannot be used outside of a transaction.
2019-01-07 13:53:03,238 ERROR "POST /new-lang/cacti/audit/ HTTP/1.0" 500 7106

**To Reproduce**
1. Go to a Component
2. Click on Start New Translation
3. Click a language and press Start New Translation
4. See error page
5. Pull above error from log

**Expected behavior**
Language to be added and be usable immediately

**Server configuration and status**
(venv) [weblate@weblate ~]$ weblate list_versions
 * Weblate 3.3
 * Python 2.7.5
 * Django 1.11.17
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 2.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 1.8.3.1
 * Pillow 5.3.0
 * python-dateutil 2.7.5
 * lxml 4.2.5
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.0
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * pytz 2018.7
 * Database backends: django.db.backends.mysql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 3.10.0-957.1.3.el7.x86_64 (x86_64)

(venv) [weblate@weblate ~]$ weblate check --deploy
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

System check identified 3 issues (0 silenced).

**Additional context**
The language is actually created, but its in a weird state.  It shows that it has strings and words but trying to click on a filter, like "Not translated strings" shows "No string matched your search!"
I have to goto Repo Management and reset the Repo before it can be used.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has been already fixed in 7202c130639627ac5ad1e55eaa263ca40c56170e.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
