### ISSUE TITLE
Error during migrations on weblate 3.4

### ISSUE THREAD

**Issue by doubledare704** [WeblateOrg/weblate#2566]
**Describe the bug**

LookupError: on migrating, on first setup of weblate 3.4
**To Reproduce**
1. Checkout weblate 3.4, or make branch from tag 3.4
2. install all deps
3. Try ti migrate with manage.py migrate

**Expected behavior**
All migrations run ok

**Got error**
```
Running migrations:
ERROR Handled exception LookupError: No installed app with label 'weblate_auth'.
  Applying accounts.0004_create_profile...Traceback (most recent call last):
  File "/home/alexey/main/workspace/weblate/.weblateenv2/lib/python3.6/site-packages/django/apps/registry.py", line 152, in get_app_config
    return self.app_configs[app_label]
KeyError: 'weblate_auth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 33, in <module>
    main()
  File "/home/alexey/main/workspace/weblate/weblate/runner.py", line 34, in main
    execute_from_command_line(argv)
  File "/home/alexey/main/workspace/weblate/.weblateenv2/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/alexey/main/workspace/weblate/.weblateenv2/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/alexey/main/workspace/weblate/.weblateenv2/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/alexey/main/workspace/weblate/.weblateenv2/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/alexey/main/workspace/weblate/.weblateenv2/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/alexey/main/workspace/weblate/.weblateenv2/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/home/alexey/main/workspace/weblate/.weblateenv2/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/alexey/main/workspace/weblate/.weblateenv2/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/alexey/main/workspace/weblate/.weblateenv2/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/alexey/main/workspace/weblate/.weblateenv2/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/alexey/main/workspace/weblate/.weblateenv2/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/alexey/main/workspace/weblate/weblate/accounts/migrations/0004_create_profile.py", line 10, in create_profiles
    User = apps.get_model('weblate_auth', 'User')
  File "/home/alexey/main/workspace/weblate/.weblateenv2/lib/python3.6/site-packages/django/apps/registry.py", line 202, in get_model
    app_config = self.get_app_config(app_label)
  File "/home/alexey/main/workspace/weblate/.weblateenv2/lib/python3.6/site-packages/django/apps/registry.py", line 159, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'weblate_auth'.
```

**Server configuration and status**

On Git checkout:
```
./manage.py list_versions
DEBUG git: exec git --version [retcode=0]
DEBUG git: exec git review --version [retcode=1]
DEBUG git: exec git svn --version [retcode=1]
DEBUG hg: exec hg version -q [retcode=0]
 * Weblate weblate-3.4-1-g2148169052
 * Python 3.6.7
 * Django 2.1.7
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.1.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * translation-finder 1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.20.1
 * Pillow 5.4.1
 * python-dateutil 2.8.0
 * lxml 4.3.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.1
 * user-agents 1.1.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2018.9
 * Mercurial 4.5.3
 * Database backends: django.db.backends.postgresql_psycopg2
 * Cache backends: default:LocMemCache
 * Celery: memory://, N/A, eager
 * Platform: Linux 4.15.0-45-generic (x86_64)


./manage.py check --deploy

ERROR Handled exception ProgrammingError: relation "django_site" does not exist
LINE 1: ..."django_site"."domain", "django_site"."name" FROM "django_si...

```
Check deploy gives error, because not all migrations where ok.

**Comment by nijel** [comment]
What is your settings? Most importantly `INSTALLED_APPS`...

**Comment by doubledare704** [comment]
Here it is
```
# Django and Weblate apps
INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admin.apps.SimpleAdminConfig',
    'django.contrib.admindocs',
    'django.contrib.sitemaps',
    'social_django',
    'crispy_forms',
    'compressor',
    'rest_framework',
    'rest_framework.authtoken',
    'weblate.addons',
    'weblate.auth',
    'weblate.checks',
    'weblate.formats',
    'weblate.machinery',
    'weblate.trans',
    'weblate.lang',
    'weblate.langdata',
    'weblate.memory',
    'weblate.screenshots',
    'weblate.accounts',
    'weblate.utils',
    'weblate.vcs',
    'weblate.wladmin',
    'weblate',

    # Optional: Git exporter
    # 'weblate.gitexport',
)
```
