### ISSUE TITLE
2.20 - 3.0.1 upgrade is failing (using docker images)

### ISSUE THREAD

**Issue by wichert** [WeblateOrg/weblate#2576]
**Describe the bug**

I am trying to upgrade from the weblate running using the weblate/weblate:2.20-1 docker image to a more recent version. The upgrade is failing when trying to run the 3.0.1 migrations:

```
+ docker run --rm -e WEBLATE_ALLOWED_HOSTS=translate.curvetips.net -e WEBLATE_ADMIN_NAME=Wichert -e WEBLATE_ADMIN_EMAIL=wichert@curvetips.com -e REDIS_HOST=172.16.1.221 -e POSTGRES_HOST=172.16.1.221 -e POSTGRES_USER=weblate -e POSTGRES_PASSWORD=weblate -e POSTGRES_DATABASE=weblate -e WEBLATE_SERVER_EMAIL=noreply@curvetips.com -e WEBLATE_DEFAULT_FROM_EMAIL=noreply@curvetips.net --mount type=bind,src=/Users/wichert/CurveTips/third-party/wl,dst=/app/data weblate/weblate:3.0.1-6 migrate --noinput
Postgres is up
Operations to perform:
  Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, gitexport, lang, memory, permissions, screenshots, sessions, sites, social_django, trans, weblate_auth, wladmin
Running migrations:
  Applying accounts.0037_auto_20180416_1406... OK
  Applying addons.0006_addon_project_scope... OK
  Applying addons.0007_auto_20180629_1736... OK
  Applying trans.0129_auto_20180416_1541... OK
  Applying trans.0130_auto_20180416_1503... OK
  Applying checks.0001_initial... OK
  Applying checks.0002_auto_20180416_1509... OK
  Applying trans.0131_auto_20180416_1610... OK
  Applying gitexport.0002_fill_in_url... OK
  Applying weblate_auth.0002_auto_20180507_1540... OK
  Applying weblate_auth.0003_permissions... OK
  Applying weblate_auth.0004_auto_20180508_1032... OK
  Applying permissions.0009_auto_20180416_1610... OK
  Applying weblate_auth.0005_groups... OK
  Applying permissions.0010_auto_20180508_1210... OK
  Applying permissions.0011_auto_20180508_1548... OK
  Applying trans.0132_auto_20180517_1413... OK
  Applying trans.0133_auto_20180517_1425... OK
  Applying trans.0134_auto_20180517_1624... OK
  Applying trans.0135_auto_20180518_1149... OK
  Applying trans.0136_auto_20180521_1048... OK
  Applying trans.0137_commit_formatting... OK
  Applying trans.0138_auto_20180521_1116... OK
  Applying trans.0139_source_context... OK
  Applying trans.0140_change_project... OK
  Applying trans.0141_component_linked_component... OK
  Applying trans.0142_linked_component_data...Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/weblate/runner.py", line 33, in main
    execute_from_command_line(argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/migration.py", line 122, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/usr/local/lib/python3.5/dist-packages/weblate/trans/migrations/0142_linked_component_data.py", line 14, in run_migration
    slug=component, project__slug=project
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
__fake__.DoesNotExist: Component matching query does not exist.
```

**To Reproduce**

Using a PostgreSQL dump and filesystem data from a production instance, I can replicate the error using this script:

```
set -x

PARAMS="-e WEBLATE_ALLOWED_HOSTS=translate.curvetips.net -e WEBLATE_ADMIN_NAME=Wichert -e WEBLATE_ADMIN_EMAIL=wichert@curvetips.com -e REDIS_HOST=172.16.1.221 -e POSTGRES_HOST=172.16.1.221 -e POSTGRES_USER=weblate -e POSTGRES_PASSWORD=weblate -e POSTGRES_DATABASE=weblate -e WEBLATE_SERVER_EMAIL=noreply@curvetips.com -e WEBLATE_DEFAULT_FROM_EMAIL=noreply@curvetips.net --mount type=bind,src=`pwd`,dst=/app/data"

if [ -e data ] ; then rm -rf data ; fi
tar xfz data.tar.gz

psql -c 'drop database weblate'
psql -c 'create database weblate owner weblate'
pg_restore -d weblate psql-weblate-2019-02-25.pgdump

set -e

docker run --rm $PARAMS weblate/weblate:2.20-5 migrate --noinput
docker run --rm $PARAMS weblate/weblate:2.20-5 collectstatic --noinput
docker run --rm $PARAMS weblate/weblate:2.20-5 setuplang
docker run --rm $PARAMS weblate/weblate:2.20-5 setupgroups
docker run --rm $PARAMS weblate/weblate:2.20-5 check --deploy

docker run --rm $PARAMS \
        --entrypoint=/bin/bash weblate/weblate:2.20-5\ 
         -c "sed -ie /AUTH_USER_MODEL/d /app/etc/settings.py ; /app/bin/start migrate weblate_auth 0001"

for version in 3.0.1-6 3.4-4 ; do
        docker run --rm $PARAMS weblate/weblate:$version migrate --noinput
        docker run --rm $PARAMS weblate/weblate:$version collectstatic --noinput
        docker run --rm $PARAMS weblate/weblate:$version setuplang
        docker run --rm $PARAMS weblate/weblate:$version setupgroups
        docker run --rm $PARAMS weblate/weblate:$version check --deploy
done
```

**Comment by nijel** [comment]
You most likely have repository link (`weblate:/...`) to non existing component, that's why it fails.

**Comment by wichert** [comment]
You are correct! Removing that component made the error go away.
