### ISSUE TITLE
Docker container fails with middleware error

### ISSUE THREAD

**Issue by wichert** [WeblateOrg/weblate#2578]
**Describe the bug**

I am trying to deploy the `weblate/weblate:3.4-4` docker container on AWS. Trying to start the container always results in this error:

```
django.core.exceptions.ImproperlyConfigured: CSRF_USE_SESSIONS is enabled, but request.session is not set. SessionMiddleware must appear before CsrfViewMiddleware in MIDDLEWARE.
```

<details>
<summary>Complete traceback</summary>

```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
response = get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/utils/deprecation.py", line 90, in __call__
response = self.process_request(request)
File "/usr/local/lib/python3.6/dist-packages/django/middleware/security.py", line 25, in process_request
host = self.redirect_host or request.get_host()
File "/usr/local/lib/python3.6/dist-packages/django/http/request.py", line 106, in get_host
raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '10.180.28.95:32804'. You may need to add '10.180.28.95' to ALLOWED_HOSTS.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/django/middleware/csrf.py", line 162, in _get_token
return request.session.get(CSRF_SESSION_KEY)
AttributeError: 'WSGIRequest' object has no attribute 'session'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 108, in get_exception_response
response = callback(request, **{**param_dict, 'exception': exception})
File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py", line 134, in _wrapped_view
result = middleware.process_request(request)
File "/usr/local/lib/python3.6/dist-packages/django/middleware/csrf.py", line 200, in process_request
csrf_token = self._get_token(request)
File "/usr/local/lib/python3.6/dist-packages/django/middleware/csrf.py", line 167, in _get_token
'in MIDDLEWARE%s.' % ('_CLASSES' if settings.MIDDLEWARE is None else '')
django.core.exceptions.ImproperlyConfigured: CSRF_USE_SESSIONS is enabled, but request.session is not set. SessionMiddleware must appear before CsrfViewMiddleware in MIDDLEWARE.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/weblate/trans/views/basic.py", line 319, in server_error
status=500,
File "/usr/local/lib/python3.6/dist-packages/weblate/trans/util.py", line 257, in render
return django_render(request, template, context, status=status)
File "/usr/local/lib/python3.6/dist-packages/django/shortcuts.py", line 36, in render
content = loader.render_to_string(template_name, context, request, using=using)
File "/usr/local/lib/python3.6/dist-packages/django/template/loader.py", line 62, in render_to_string
return template.render(context, request)
File "/usr/local/lib/python3.6/dist-packages/django/template/backends/django.py", line 61, in render
return self.template.render(context)
File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 169, in render
with context.bind_template(self):
File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
return next(self.gen)
File "/usr/local/lib/python3.6/dist-packages/django/template/context.py", line 246, in bind_template
updates.update(processor(self.request))
File "/usr/local/lib/python3.6/dist-packages/weblate/trans/context_processors.py", line 93, in weblate_context
if request.user.is_authenticated:
AttributeError: 'WSGIRequest' object has no attribute 'user'
```
</details>

**To Reproduce**
1. Grab the weblate/weblate:3.4-4 docker image
2. Configure it with environment `WEBLATE_ENABLE_HTTPS=1` and in settings-override.py:
```
SECURE_HSTS_SECONDS = 86400
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
```
3. Start a docker container

**Expected behavior**
Weblate starts normally

**Comment by nijel** [comment]
The middleware is properly configured this way, see https://github.com/WeblateOrg/docker/blob/d6b7dc67e32683d61e54620bd739d20561d5fb9b/etc/weblate/settings.py#L374-L388

So the problem most likely lies somewhere else. Is there something else in your settings override? From the error it really looks like most of the middleware is not configured.

**Comment by wichert** [comment]
That was the complete content of `settings-override.py`, there is nothing else in there.

It has me puzzled as well. `/usr/local/lib/python3.6/dist-packages/weblate/settings.py` seems to be the configuration used for the docker container, and that has the correct middleware as well.

**Comment by nijel** [comment]
Does it work when you fix the first error? (You may need to add '10.180.28.95' to ALLOWED_HOSTS.)

**Comment by wichert** [comment]
For reference, the environment variables I set are:

* WEBLATE_DEBUG=0
* SITE_TITLE
* WEBLATE_ADMIN_NAME
* WEBLATE_ADMIN_EMAIO
* WEBLATE_ALLOWED_HOSTS
* WEBLATE_ENABLE_HTTPS=1
* WEBLATE_IP_PROXY_HEADER=HTTP_X_FORWARDED_FOR
* WEBLATE_REGISTRATION_OPEN=0
* WEBLATE_TIME_ZONE=Europe/Amsterdam
* POSTGRES_HOST
* POSTGRES_PORT
* POSTGRES_DATABASE
* POSTGRES_USER
* POSTGRES_PASSWORD
* REDIS_HOST
* REDIS_PORT
* REDIS_DB
* WEBLATE_EMAIL_PORT
* WEBLATE_EMAIL_HOST
* WEBLATE_EMAIL_HOST_USER
* WEBLATE_EMAIL_HOST_PASSWORD
* WEBLATE_DEFAULT_FROM_EMAIL
* WEBLATE_SERVER_EMAIL
* SENTRY_DSN
* SENTRY_PUBLIC_SDN
* SENTRY_ENVIRONMENT

**Comment by wichert** [comment]
Hm, that's a bit tricky. What happens here is that AWS ALB forwards the request to the ECS cluster, and it resets the Host header to the VM that happens to be running the container. I can try to add the VM IP by doing something like this in settings-override:

```python
import requests

MY_IP = requests.get('http://169.254.169.254/latest/meta-data/local-ipv4').text
ALLOWED_HOSTS.append(MY_IP)
```

**Comment by wichert** [comment]
That seems to have fixed it! And since you can only access that system via a load balancer which checks hostname I suspect I can just leave ALLOWED_HOSTS at its default value of `*`.
