### ISSUE TITLE
Cannot push from Weblate to remote Git repository

### ISSUE THREAD

**Issue by montacerdk** [WeblateOrg/weblate#2590]
Hello,

I am using Weblate as a translation platform. After a modification in files content,
I clicked on Push button in (Repository maintenance -> Push)

And then I got this Error : 

![image](https://user-images.githubusercontent.com/26897940/53574324-aceafa00-3b6f-11e9-8a79-3d82d2e42262.png)

are there any solutions ?

Thanks.

**Comment by montacerdk** [comment]
This what I found on log : 

```
2019-02-28 10:11:15,335 INFO quiktext/zoe/en: committing pending changes (push)
2019-02-28 10:11:15,404 ERROR Internal Server Error: /push/quiktext/
Traceback (most recent call last):
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/opt/bitnami/apps/weblate/weblate/weblate/trans/views/git.py", line 184, in push_project
    return perform_push(request, obj)
  File "/opt/bitnami/apps/weblate/weblate/weblate/trans/views/git.py", line 84, in perform_push
    request,
  File "/opt/bitnami/apps/weblate/weblate/weblate/trans/views/git.py", line 39, in execute_locked
    result = call(*args, **kwargs)
  File "/opt/bitnami/apps/weblate/weblate/weblate/trans/models/project.py", line 281, in do_push
    return self.commit_pending('push', request, on_commit=False)
  File "/opt/bitnami/apps/weblate/weblate/weblate/trans/models/project.py", line 263, in commit_pending
    component.commit_pending(reason, request, skip_push=True)
  File "/opt/bitnami/apps/weblate/weblate/weblate/trans/models/component.py", line 806, in commit_pending
    translation.commit_pending(reason, request, skip_push=True)
  File "/opt/bitnami/apps/weblate/weblate/weblate/trans/models/translation.py", line 405, in commit_pending
    self.update_units(author_name, change.author.id)
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/utils/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/opt/bitnami/apps/weblate/weblate/weblate/trans/models/translation.py", line 505, in update_units
    unit_change = unit.change_set.content().order_by('-timestamp')[0]
  File "/opt/bitnami/apps/weblate/venv/lib/python2.7/site-packages/django/db/models/query.py", line 289, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
```

**Comment by nijel** [comment]
It looks like some inconsistency in the database, have you done any manual changes to that?

**Comment by montacerdk** [comment]
@nijel, I didn't any manual changes.
I cannot even download the translation files to my local PC.

**Comment by nijel** [comment]
Possibly related to #2108, it seems that the fix there is incomplete...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
