### ISSUE TITLE
UWSGI failing. ImportError: No module named async.timer

### ISSUE THREAD

**Issue by SBSolera** [WeblateOrg/weblate#2624]
**Describe the bug**
I had weblate properly working on my VM and then I worked on getting Celery working.  Once I thought I had celery working, I had some other issue with nginx related to a known issue on ubuntu.  Once I fixed that, I started getting this uWSGI error which I pasted down below.

Any idea what could be happening? Like I said this was working in the past and now I'm getting this weird import error.

**To Reproduce**
1. run `systemctl start celery`
2. Try to access weblate client, but it gives 500 error

**Expected behavior**
Weblate login screen should appear.

**Server configuration and status**
 * Weblate 3.4
 * Python 2.7.15rc1
 * Django 1.11.11
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.11.0
 * social-auth-core 3.1.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * translation-finder 1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow 5.1.0
 * python-dateutil 2.6.1
 * lxml 4.2.1
 * django-crispy-forms 1.7.0
 * django_compressor 2.2
 * djangorestframework 3.9.1
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * diff-match-patch 20121119
 * pytz 2018.9
 * pyuca 1.2
 * PyYAML 3.12
 * Mercurial 4.5.3
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.18.0-1013-azure (x86_64)

**Additional context**
Error in `weblate.uwsgi.log`
```
Traceback (most recent call last):
  File "/usr/share/weblate/weblate/wsgi.py", line 44, in <module>
    application = get_wsgi_application()
  File "/usr/lib/python2.7/dist-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python2.7/dist-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/lib/python2.7/dist-packages/django/apps/config.py", line 120, in create
    mod = import_module(mod_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/share/weblate/weblate/utils/apps.py", line 25, in <module>
    from weblate.utils.checks import (
  File "/usr/share/weblate/weblate/utils/checks.py", line 36, in <module>
    from weblate.utils.celery import get_queue_length
  File "/usr/share/weblate/weblate/utils/celery.py", line 25, in <module>
    from celery_batches import SimpleRequest
  File "/usr/local/lib/python2.7/dist-packages/celery_batches/__init__.py", line 94, in <module>
    from celery.worker.strategy import proto1_to_proto2
  File "/usr/lib/python2.7/dist-packages/celery/worker/strategy.py", line 7, in <module>
    from kombu.async.timer import to_timestamp
ImportError: No module named async.timer
Tue Mar 12 17:08:07 2019 - unable to load app 0 (mountpoint='') (callable not found or import error)
Tue Mar 12 17:08:07 2019 - *** no app loaded. going in full dynamic mode ***
Tue Mar 12 17:08:07 2019 - dropping root privileges after application loading
Tue Mar 12 17:08:07 2019 - *** uWSGI is running in multiple interpreter mode ***
Tue Mar 12 17:08:07 2019 - spawned uWSGI master process (pid: 6774)
Tue Mar 12 17:08:07 2019 - spawned uWSGI worker 1 (pid: 6789, cores: 1)
Tue Mar 12 17:08:07 2019 - spawned uWSGI worker 2 (pid: 6790, cores: 1)
Tue Mar 12 17:13:26 2019 - --- no python application found, check your startup logs for errors ---
```

**celery.service**
```
[Unit]
Description=Celery Service (Weblate)
After=network.target

[Service]
Type=forking
User=weblate
Group=weblate
EnvironmentFile=/etc/default/celery-weblate
WorkingDirectory=/usr/share/weblate/
PermissionsStartOnly=true
ExecStartPre=/bin/mkdir -p /var/run/celery
ExecStartPre=/bin/chown -R weblate /var/run/celery/
ExecStartPre=/bin/mkdir -p /var/log/celery
ExecStartPre=/bin/chown -R weblate /var/log/celery/
ExecStart=/bin/sh -c '${CELERY_BIN} multi start ${CELERYD_NODES} \
  -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE} \
  --logfile=${CELERYD_LOG_FILE} --loglevel=${CELERYD_LOG_LEVEL} ${CELERYD_OPTS}'
ExecStop=/bin/sh -c '${CELERY_BIN} multi stopwait ${CELERYD_NODES} \
  --pidfile=${CELERYD_PID_FILE}'
ExecReload=/bin/sh -c '${CELERY_BIN} multi restart ${CELERYD_NODES} \
  -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE} \
  --logfile=${CELERYD_LOG_FILE} --loglevel=${CELERYD_LOG_LEVEL} ${CELERYD_OPTS}'

[Install]
WantedBy=multi-user.target
```

**weblate.uwsgi.ini**
```
[uwsgi]
plugins       = python
master        = true
protocol      = uwsgi
socket        = 127.0.0.1:8080
wsgi-file     = /usr/share/weblate/weblate/wsgi.py

## UNCOMMENT THIS ONCE YOU'VE GOT UNIX SOCKETS FIGURED OUT ##
# updated socket to be consistent with usage of unix sockets in the nginx configuration
# socket        = unix:///run/uwsgi/app/weblate/socket
# updated path to wsgi.py file because it is installed in a different directory
## UNCOMMENT THIS ONCE YOU'VE GOT UNIX SOCKETS FIGURED OUT ##

# Add path to Weblate checkout if you did not install
# Weblate by pip
python-path   = /usr/share/weblate

# Needed for OAuth/OpenID
buffer-size   = 8192

# Increase number of workers for heavily loaded sites
# workers       = 6

# Child processes do not need file descriptors
close-on-exec = true

# Avoid default 0000 umask
umask = 0022

# Run as weblate user
uid = weblate
gid = weblate

# Enable harakiri mode (kill requests after some time)
# harakiri = 3600
# harakiri-verbose = true

# Enable uWSGI stats server
# stats = :1717
# stats-http = true

# Do not log some errors caused by client disconnects
ignore-sigpipe = true
ignore-write-errors = true
disable-write-exception = true
```

**Comment by nijel** [comment]
Looks like Celery and kombu versions are not compatible, try downgrading kombu to older than 4.2.0 or using Celery 4.2.0rc4 (or newer if it exists).u

Similar issue is here: https://github.com/celery/celery/issues/4772

**Comment by SBSolera** [comment]
Thanks, I did find that bug report when researching, but I wasn't clear what the next steps should be.  Do you think it would also be a good idea to go ahead and upgrade to using python 3.* as well? It looks like Celery is about to drop support for 2.7
> This is the last version to support Python 2.7, and from the next version (Celery 5.x) Python 3.5 or newer is required.

**Comment by nijel** [comment]
Python 3 is certainly recommended these days. Weblate itself doesn't have yet depreciation date set, see https://github.com/WeblateOrg/weblate/issues/2201

**Comment by SBSolera** [comment]
Thanks for the info, moving to Python 3.6 and reinstalling all dependencies seems to have fixed the issue
