### ISSUE TITLE
Gerrit tests are failing on openSUSE

### ISSUE THREAD

**Issue by scarabeusiv** [WeblateOrg/weblate#2671]
Gerrit tests are failing in openSUSE build, regardless of version since 3.1 release:
```
[  927s] ERROR: test_merge_both (weblate.vcs.tests.test_vcs.VCSGerritTest)
[  927s] ----------------------------------------------------------------------
[  927s] Traceback (most recent call last):
[  927s]   File "/home/abuild/rpmbuild/BUILD/Weblate-3.5.1/weblate/vcs/tests/test_vcs.py", line 201, in test_merge_both
[  927s]     self.add_remote_commit()
[  927s]   File "/home/abuild/rpmbuild/BUILD/Weblate-3.5.1/weblate/vcs/tests/test_vcs.py", line 139, in add_remote_commit
[  927s]     repo.push()
[  927s]   File "/home/abuild/rpmbuild/BUILD/Weblate-3.5.1/weblate/vcs/git.py", line 378, in push
[  927s]     self.execute(['review', '--yes', self.branch])
[  927s]   File "/home/abuild/rpmbuild/BUILD/Weblate-3.5.1/weblate/vcs/base.py", line 194, in execute
[  927s]     args, self.path, fullcmd=fullcmd, local=self.local
[  927s]   File "/home/abuild/rpmbuild/BUILD/Weblate-3.5.1/weblate/vcs/base.py", line 178, in _popen
[  927s]     output.decode('utf-8')
[  927s] weblate.vcs.base.RepositoryException: No '.gitreview' file found in this repository. We don't know where
[  927s] your gerrit is.
[  927s] Please manually create a remote named "gerrit" and try again. (1)
```

We have git and git-review pulled in the system. Full log:
[weblate.txt](https://github.com/WeblateOrg/weblate/files/3034061/weblate.txt)

**Comment by nijel** [comment]
Newer gerrit versions need configuration in the repo and the test one lacks this. Thanks for reporting.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed by https://github.com/WeblateOrg/weblate/pull/2672.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
