### ISSUE TITLE
Incorrect version of sqlite is required

### ISSUE THREAD

**Issue by alesrosina** [WeblateOrg/weblate#2675]
When deploying to Openshift, I got an error:
```
ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).
```

This happens in a step 
```
python manage.py collectstatic --noinput
```
of `.s2i/action_hooks/build`.

I did not change any configuration on OpenShift, I just wanted to rebuild image, to get the latest version deployed - this means pulling from git latest from master.

See full error stack:

```
Handled exception ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).
Traceback (most recent call last):
  File "manage.py", line 33, in <module>
    main()
  File "/opt/app-root/src/weblate/runner.py", line 34, in main
    execute_from_command_line(argv)
  File "/opt/app-root/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/app-root/lib/python3.5/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/opt/app-root/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/app-root/lib/python3.5/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/opt/app-root/lib/python3.5/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/app-root/lib64/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/app-root/lib/python3.5/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/opt/app-root/lib/python3.5/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/opt/app-root/lib/python3.5/site-packages/django/db/models/base.py", line 117, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/opt/app-root/lib/python3.5/site-packages/django/db/models/base.py", line 321, in add_to_class
    value.contribute_to_class(cls, name)
  File "/opt/app-root/lib/python3.5/site-packages/django/db/models/options.py", line 204, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/opt/app-root/lib/python3.5/site-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/opt/app-root/lib/python3.5/site-packages/django/db/utils.py", line 201, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/opt/app-root/lib/python3.5/site-packages/django/db/utils.py", line 110, in load_backend
    return import_module('%s.base' % backend_name)
  File "/opt/app-root/lib64/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/app-root/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 66, in <module>
    check_sqlite_version()
  File "/opt/app-root/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 63, in check_sqlite_version
    raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).
```

**Comment by nijel** [comment]
This is probably a Django requirement, Weblate doesn't limit this anyhow.

**Comment by alesrosina** [comment]
Probably. But googling didn't find anything I could fix it with, so maybe any hints of what can I do?

**Comment by nijel** [comment]
First of all you should not be using sqlite for production :-). I'm not sure how to upgrade sqlite in openshift environment...

The [Django 2.2](https://docs.djangoproject.com/en/2.2/releases/2.2/) release changed this:

> The minimum supported version of SQLite is increased from 3.7.15 to 3.8.3.

**Comment by alesrosina** [comment]
Yes, I agree! It is in a "build" phase, when doing deployment postgres is used. But yes, this seems like openshift config could be fixed somehow. Will try to investigate in this direction.

**Comment by nijel** [comment]
Alternatively you can limit Django to `< 2.2`...

**Comment by alesrosina** [comment]
@nijel ok, I've found the solution, so I've opened new merge request: https://github.com/WeblateOrg/weblate/pull/2676

**Comment by selvakumar04** [comment]
Hi folks can u pls how to solve this problem.
python3 manage.py collectstatic --noinput                                                               
Traceback (most recent call last):                                                                                        
  File "manage.py", line 21, in <module>                                                                                  
    main()                                                                                                                
  File "manage.py", line 17, in main                                                                                      
    execute_from_command_line(sys.argv)                                                                                   
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()                                                                                                     
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute                  
    django.setup()                                                                                                        
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup                                     
    apps.populate(settings.INSTALLED_APPS)                                                                                
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 114, in populate                            
    app_config.import_models()                                                                                            
  File "/usr/local/lib/python3.7/site-packages/django/apps/config.py", line 211, in import_models                         
    self.models_module = import_module(models_module_name)                                                                
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module                                       
    return _bootstrap._gcd_import(name[level:], package, level)                                                           
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import                                                         
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load                                                       
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked                                              
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked                                                       
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module                                                 
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed                                            
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/models.py", line 2, in <module>                        
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager                                           
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/base_user.py", line 47, in <module>                    
    class AbstractBaseUser(models.Model):                                                                                 
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 117, in __new__                            
    new_class.add_to_class('_meta', Options(meta, app_label))                                                             
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 321, in add_to_class                       
    value.contribute_to_class(cls, name)                                                                                  
  File "/usr/local/lib/python3.7/site-packages/django/db/models/options.py", line 204, in contribute_to_class             
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())                                        
  File "/usr/local/lib/python3.7/site-packages/django/db/__init__.py", line 28, in __getattr__                            
    return getattr(connections[DEFAULT_DB_ALIAS], item)                                                                   
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 201, in __getitem__                              
    backend = load_backend(db['ENGINE'])                                                                                  
  File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 110, in load_backend                             
    return import_module('%s.base' % backend_name)                                                                        
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module                                       
    return _bootstrap._gcd_import(name[level:], package, level)                                                           
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 66, in <module>                  
    check_sqlite_version()                                                                                                
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 63, in check_sqlite_version      
    raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)                 
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).

**Comment by nijel** [comment]
Upgrade the SQLite library, see https://github.com/sclorg/s2i-python-container/issues/333#issuecomment-549238030
