### ISSUE TITLE
Can't add a new Language

### ISSUE THREAD

**Issue by VerisureKrister** [WeblateOrg/weblate#2687]
**Describe the bug**
When adding a new language to Weblate we get a IndexError at /admin/lang/language/add/. The language isn't added. All help is appreciated.

**To Reproduce**
1. Go to /admin/lang/language/
2. Click "ADD LANGUAGE"
3. Add Language code "tttt"
4. Add Language name "tttt"
5. Optionally click "Add another Plural form". The same error is shown with and without adding a plural form
6. Click "SAVE"
7. The error shows

**Expected behavior**
The language with language code "tttt", language name "tttt" and optionally plural form should be added.

**Screenshots**
Not applicable

**Server configuration and status**
list_versions
```
 * Weblate 3.5.1
 * Python 3.6.7
 * Django 2.1.7
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.1.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.3.1
 * translation-finder 1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow 5.1.0
 * python-dateutil 2.8.0
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.2
 * user-agents 1.1.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2018.9
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.4.0
 * Mercurial 4.5.3
 * git-svn 2.17.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Celery: redis://weblate-redis:6379/1, redis://weblate-redis:6379/1, regular
 * Platform: Linux 3.10.0-957.10.1.el7.x86_64 (x86_64)
```
check --deploy
```
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Can not send email ([Errno 101] Network is unreachable), please check EMAIL_* settings.
	HINT: https://docs.weblate.org/en/weblate-3.5.1/admin/install.html#out-mail

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-3.5.1/admin/install.html#collecting-errors
```

**Additional context**
The issue seems to be almost exactly the same as https://github.com/WeblateOrg/weblate/issues/2370, which is solved with https://github.com/WeblateOrg/weblate/commit/d7217eec22ce8a792eaea0850329e40ec1ea3b28 and have a tag for weblate-3.5.1. The main differences I've noticed are the versions of Weblate, Python and Django.

Logs:
```
ERROR Internal Server Error: /admin/lang/language/add/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py", line 604, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py", line 1637, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py", line 1525, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py", line 1565, in _changeform_view
    self.save_related(request, form, formsets, not add)
  File "/usr/local/lib/python3.6/dist-packages/weblate/lang/admin.py", line 50, in save_related
    baseplural = baselang.plural
  File "/usr/local/lib/python3.6/dist-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/dist-packages/weblate/lang/models.py", line 438, in plural
    return self.plural_set.filter(source=Plural.SOURCE_DEFAULT)[0]
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 303, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
Internal Server Error: /admin/lang/language/add/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py", line 604, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py", line 1637, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py", line 1525, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.6/dist-packages/django/contrib/admin/options.py", line 1565, in _changeform_view
    self.save_related(request, form, formsets, not add)
  File "/usr/local/lib/python3.6/dist-packages/weblate/lang/admin.py", line 50, in save_related
    baseplural = baselang.plural
  File "/usr/local/lib/python3.6/dist-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/dist-packages/weblate/lang/models.py", line 438, in plural
    return self.plural_set.filter(source=Plural.SOURCE_DEFAULT)[0]
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 303, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
[pid: 171|app: 0|req: 105/155] 172.19.0.1 () {56 vars in 1179 bytes} [Fri Apr 12 10:18:45 2019] POST /admin/lang/language/add/ => generated 163126 bytes in 195 msecs (HTTP/1.1 500) 7 headers in 229 bytes (1 switches on core 0)
172.19.0.1 - - [12/Apr/2019:10:18:45 +0000] "POST /admin/lang/language/add/ HTTP/1.1" 500 163126 "https://scrambled.com/admin/lang/language/add/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0"
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
