### ISSUE TITLE
Weblate 3.6.1: SMTP Issue when adding a component

### ISSUE THREAD

**Issue by javsalgar** [WeblateOrg/weblate#2721]
**Describe the bug**
When adding a component, if the SMTP settings are not enabled, it will return a 500 error because it will try sending a mail to a non-existent host.

```
2019-05-01 15:08:46,128 ERROR Internal Server Error: /create/component/
Traceback (most recent call last):
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/bitnami/apps/weblate/weblate/weblate/trans/views/create.py", line 195, in dispatch
    return super(CreateComponent, self).dispatch(request, *args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/django/views/generic/edit.py", line 172, in post
    return super().post(request, *args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/django/views/generic/edit.py", line 142, in post
    return self.form_valid(form)
  File "/opt/bitnami/apps/weblate/weblate/weblate/trans/views/create.py", line 143, in form_valid
    result = super(CreateComponent, self).form_valid(form)
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/django/views/generic/edit.py", line 125, in form_valid
    self.object = form.save()
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/django/forms/models.py", line 458, in save
    self.instance.save()
  File "/opt/bitnami/apps/weblate/weblate/weblate/trans/models/component.py", line 1619, in save
    self.create_translations()
  File "/opt/bitnami/apps/weblate/weblate/weblate/trans/models/component.py", line 1289, in create_translations
    translation.notify_new(request)
  File "/opt/bitnami/apps/weblate/weblate/weblate/trans/models/translation.py", line 166, in notify_new
    author=request.user if request else None,
  File "/opt/bitnami/apps/weblate/weblate/weblate/trans/models/change.py", line 148, in create
    return super(ChangeManager, self).create(user=user, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/opt/bitnami/apps/weblate/weblate/weblate/trans/models/change.py", line 452, in save
    notify_change.delay(self.pk)
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/celery/app/task.py", line 427, in delay
    return self.apply_async(args, kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/celery/app/task.py", line 552, in apply_async
    link=link, link_error=link_error, **options)
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/celery/app/task.py", line 774, in apply
    ret = tracer(task_id, args, kwargs, request)
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/celery/app/trace.py", line 399, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/celery/app/base.py", line 472, in run
    return task._orig_run(*args, **kwargs)
  File "/opt/bitnami/apps/weblate/weblate/weblate/accounts/tasks.py", line 78, in notify_change
    with get_connection() as connection:
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/django/core/mail/backends/base.py", line 45, in __enter__
    self.open()
  File "/opt/bitnami/apps/weblate/venv/lib/python3.7/site-packages/django/core/mail/backends/smtp.py", line 63, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/opt/bitnami/python/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/opt/bitnami/python/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/opt/bitnami/python/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/opt/bitnami/python/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/opt/bitnami/python/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

This is because my default SMTP settings in global_settings.py are:

```
# The email backend to use. For possible shortcuts see django.core.mail.
# The default is to use the SMTP backend.
# Third-party backends can be specified by providing a Python path
# to a module that defines an EmailBackend class.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# Host for sending email.
EMAIL_HOST = 'localhost'

# Port for sending email.
EMAIL_PORT = 25

# Whether to send SMTP 'Date' header in the local time zone or in UTC.
EMAIL_USE_LOCALTIME = False

# Optional SMTP authentication information for EMAIL_HOST.
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = False
EMAIL_USE_SSL = False
EMAIL_SSL_CERTFILE = None
EMAIL_SSL_KEYFILE = None
```
We have packaged the different versions of the application for a long time and this is the first time we see the issue. 

If I configure my SMTP correctly, I am able to add the component without problems. However, if I set empty SMTP settings after adding the first components, the 500 error does not appear anymore.

**To Reproduce**
1. Create Project
2. Under the new project, add a new component (we use this repo https://github.com/WeblateOrg/test)
3. When submitting, the error will appear

**Expected behavior**
The component should be created successfully and no e-mail should be sent
**Screenshots**
![image](https://user-images.githubusercontent.com/1133777/57070498-efe45d80-6cd7-11e9-99ea-4be604498180.png)

**Server configuration and status**
Please paste the output of `list_versions` and `check --deploy` commands over
here. Depending on installation these can be executed in different way, please
consult https://docs.weblate.org/en/latest/admin/management.html for more
details.

```
daemon@weblatefinal3:/opt/bitnami/apps/weblate/weblate$ ./manage.py list_versions
 * Weblate 3.6.1
 * Python 3.7.3
 * Django 2.2
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.1.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.3.1
 * translation-finder 1.2
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.19.1
 * Pillow 6.0.0
 * python-dateutil 2.8.0
 * lxml 4.3.3
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.2
 * user-agents 2.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2019.1
 * pyuca 1.2
 * python-bidi 0.4.0
 * PyYAML 5.1
 * Database backends: django.db.backends.mysql
 * Cache backends: default:LocMemCache
 * Celery: memory://, N/A, eager
 * Platform: Linux 4.9.0-8-amd64 (x86_64)
```

**Additional context**

**Comment by nijel** [comment]
Previous versions didn't send notification here, that's why you didn't see the error.

Anyway `./manage.py check --deploy` should give you more information what is wrong, but most likely there is no MTA running on localhost port 25. Also running Celery in eager is not really good for production environment.

**Comment by javsalgar** [comment]
Hi,

The thing is. How can I disable the sending of these notifications? By default we do not want to have any mail notification unless the user configures it.

**Comment by rhofer** [comment]
I encounter a similar problem when using the "Automatic translation" feature from "Tools" -box for a specific language. There seems to be a hard coupling to email sending and this functionality. Openshift console log:

```
[Tue May 07 05:36:34.494206 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128] INFO sending notification changed_translation on BT Products - Harmonize/BO-cleanup - German to awesom.translator@example.com
--
  | [Tue May 07 05:36:35.246297 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128] ERROR Internal Server Error: /auto-translate/bt-products-harmonize/bo-cleanup/de/
  | [Tue May 07 05:36:35.246345 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128] Traceback (most recent call last):
  | [Tue May 07 05:36:35.246351 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
  | [Tue May 07 05:36:35.246355 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     response = get_response(request)
  | [Tue May 07 05:36:35.246377 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
  | [Tue May 07 05:36:35.246381 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     response = self.process_exception_by_middleware(e, request)
  | [Tue May 07 05:36:35.246385 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
  | [Tue May 07 05:36:35.246393 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
  | [Tue May 07 05:36:35.246397 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/lib/python3.5/site-packages/django/views/decorators/http.py", line 40, in inner
  | [Tue May 07 05:36:35.246401 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     return func(request, *args, **kwargs)
  | [Tue May 07 05:36:35.246418 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
  | [Tue May 07 05:36:35.246422 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     return view_func(request, *args, **kwargs)
  | [Tue May 07 05:36:35.246425 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/src/weblate/trans/views/edit.py", line 597, in auto_translation
  | [Tue May 07 05:36:35.246429 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     autoform.cleaned_data['component'],
  | [Tue May 07 05:36:35.246432 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/rh/rh-python35/root/usr/lib64/python3.5/contextlib.py", line 30, in inner
  | [Tue May 07 05:36:35.246435 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     return func(*args, **kwds)
  | [Tue May 07 05:36:35.246439 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/src/weblate/trans/autotranslate.py", line 88, in process_others
  | [Tue May 07 05:36:35.246443 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     self.update(unit, update.state, update.target)
  | [Tue May 07 05:36:35.246446 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/src/weblate/trans/autotranslate.py", line 45, in update
  | [Tue May 07 05:36:35.246450 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     unit.translate(self.request, target, state, Change.ACTION_AUTO, False)
  | [Tue May 07 05:36:35.246454 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/rh/rh-python35/root/usr/lib64/python3.5/contextlib.py", line 30, in inner
  | [Tue May 07 05:36:35.246457 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     return func(*args, **kwds)
  | [Tue May 07 05:36:35.246461 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/src/weblate/trans/models/unit.py", line 899, in translate
  | [Tue May 07 05:36:35.246465 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     propagate=propagate
  | [Tue May 07 05:36:35.246481 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/src/weblate/trans/models/unit.py", line 577, in save_backend
  | [Tue May 07 05:36:35.246485 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     self.generate_change(request, user, change_action)
  | [Tue May 07 05:36:35.246488 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/src/weblate/trans/models/unit.py", line 679, in generate_change
  | [Tue May 07 05:36:35.246492 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     **kwargs
  | [Tue May 07 05:36:35.246495 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/src/weblate/trans/models/change.py", line 148, in create
  | [Tue May 07 05:36:35.246499 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     return super(ChangeManager, self).create(user=user, **kwargs)
  | [Tue May 07 05:36:35.246503 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
  | [Tue May 07 05:36:35.246506 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     return getattr(self.get_queryset(), name)(*args, **kwargs)
  | [Tue May 07 05:36:35.246510 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/lib/python3.5/site-packages/django/db/models/query.py", line 422, in create
  | [Tue May 07 05:36:35.246514 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     obj.save(force_insert=True, using=self.db)
  | [Tue May 07 05:36:35.246517 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/src/weblate/trans/models/change.py", line 448, in save
  | [Tue May 07 05:36:35.246521 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     notify_change.delay(self.pk)
  | [Tue May 07 05:36:35.246525 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/lib/python3.5/site-packages/celery/app/task.py", line 427, in delay
  | [Tue May 07 05:36:35.246529 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     return self.apply_async(args, kwargs)
  | [Tue May 07 05:36:35.246532 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/lib/python3.5/site-packages/celery/app/task.py", line 552, in apply_async
  | [Tue May 07 05:36:35.246536 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     link=link, link_error=link_error, **options)
  | [Tue May 07 05:36:35.246540 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/lib/python3.5/site-packages/celery/app/task.py", line 774, in apply
  | [Tue May 07 05:36:35.246544 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     ret = tracer(task_id, args, kwargs, request)
  | [Tue May 07 05:36:35.246547 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/lib/python3.5/site-packages/celery/app/trace.py", line 399, in trace_task
  | [Tue May 07 05:36:35.246551 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     I, R, state, retval = on_error(task_request, exc, uuid)
  | [Tue May 07 05:36:35.246555 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/lib/python3.5/site-packages/celery/app/trace.py", line 385, in trace_task
  | [Tue May 07 05:36:35.246559 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     R = retval = fun(*args, **kwargs)
  | [Tue May 07 05:36:35.246562 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/lib/python3.5/site-packages/celery/app/base.py", line 472, in run
  | [Tue May 07 05:36:35.246566 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     return task._orig_run(*args, **kwargs)
  | [Tue May 07 05:36:35.246570 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/src/weblate/accounts/tasks.py", line 91, in notify_change
  | [Tue May 07 05:36:35.246573 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     notify_new_translation(change)
  | [Tue May 07 05:36:35.246582 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/src/weblate/accounts/notifications.py", line 159, in notify_new_translation
  | [Tue May 07 05:36:35.246586 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     enqueue_mails(mails)
  | [Tue May 07 05:36:35.246589 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/src/weblate/accounts/notifications.py", line 504, in enqueue_mails
  | [Tue May 07 05:36:35.246593 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     send_mails.delay(mails)
  | [Tue May 07 05:36:35.246597 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/lib/python3.5/site-packages/celery/app/task.py", line 427, in delay
  | [Tue May 07 05:36:35.246601 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     return self.apply_async(args, kwargs)
  | [Tue May 07 05:36:35.246604 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/lib/python3.5/site-packages/celery/app/task.py", line 552, in apply_async
  | [Tue May 07 05:36:35.246608 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     link=link, link_error=link_error, **options)
  | [Tue May 07 05:36:35.246612 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/lib/python3.5/site-packages/celery/app/task.py", line 774, in apply
  | [Tue May 07 05:36:35.246616 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     ret = tracer(task_id, args, kwargs, request)
  | [Tue May 07 05:36:35.246620 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/lib/python3.5/site-packages/celery/app/trace.py", line 399, in trace_task
  | [Tue May 07 05:36:35.246624 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     I, R, state, retval = on_error(task_request, exc, uuid)
  | [Tue May 07 05:36:35.246627 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/lib/python3.5/site-packages/celery/app/trace.py", line 385, in trace_task
  | [Tue May 07 05:36:35.246631 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     R = retval = fun(*args, **kwargs)
  | [Tue May 07 05:36:35.246635 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/src/weblate/accounts/notifications.py", line 510, in send_mails
  | [Tue May 07 05:36:35.246639 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     with get_connection() as connection:
  | [Tue May 07 05:36:35.246643 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/lib/python3.5/site-packages/django/core/mail/backends/base.py", line 45, in __enter__
  | [Tue May 07 05:36:35.246648 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     self.open()
  | [Tue May 07 05:36:35.246651 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/app-root/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 63, in open
  | [Tue May 07 05:36:35.246655 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     self.connection = self.connection_class(self.host, self.port, **connection_params)
  | [Tue May 07 05:36:35.246659 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/rh/rh-python35/root/usr/lib64/python3.5/smtplib.py", line 251, in __init__
  | [Tue May 07 05:36:35.246664 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     (code, msg) = self.connect(host, port)
  | [Tue May 07 05:36:35.246667 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/rh/rh-python35/root/usr/lib64/python3.5/smtplib.py", line 335, in connect
  | [Tue May 07 05:36:35.246671 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     self.sock = self._get_socket(host, port, self.timeout)
  | [Tue May 07 05:36:35.246675 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/rh/rh-python35/root/usr/lib64/python3.5/smtplib.py", line 306, in _get_socket
  | [Tue May 07 05:36:35.246679 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     self.source_address)
  | [Tue May 07 05:36:35.246682 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/rh/rh-python35/root/usr/lib64/python3.5/socket.py", line 711, in create_connection
  | [Tue May 07 05:36:35.246686 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     raise err
  | [Tue May 07 05:36:35.246690 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]   File "/opt/rh/rh-python35/root/usr/lib64/python3.5/socket.py", line 702, in create_connection
  | [Tue May 07 05:36:35.246715 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128]     sock.connect(sa)
  | [Tue May 07 05:36:35.246723 2019] [wsgi:error] [pid 60:tid 140335345063680] [remote 185.46.214.71:45128] ConnectionRefusedError: [Errno 111] Connection refused
```

Even if email fails (for whatever reason), other functionality must continue working! This error should go into a log but not stopping functionality as "Automatic translation", "Component creation" etc.

**Comment by nijel** [comment]
Hmm, looking at the code, the actual problem there is that it tries open the SMTP connection even in case no notification would be sent...

**Comment by nijel** [comment]
Still if you are not running Celery in eager mode, the only thing which will fail is the notification.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by javsalgar** [comment]
Hi,

Thank you very much. I presume that this fix will be in the next release of Weblate, right? Do you plan to make a release any time soon?

**Comment by nijel** [comment]
You can see the schedule from the assigned milestone: https://github.com/WeblateOrg/weblate/milestone/41

Anyway you can fix the annoying part of the bug yourself, just [configure Celery](https://docs.weblate.org/en/latest/admin/install.html#celery) and do not use eager mode.
