### ISSUE TITLE
Weblate commands output at the end: "TypeError: 'NoneType' object is not callable"

### ISSUE THREAD

**Issue by romanr** [WeblateOrg/weblate#2806]
**Describe the bug**
Initial database migration (fails?) when installing Weblate with Exception message.
Exception is also present in output of other Weblate commands.

**To Reproduce**

1. Create a VM
2. Install latest version of Debian
3. Install packages using Virtualenv installation type as instructed in https://docs.weblate.org/en/latest/admin/quick.html#installing-in-a-virtualenv
4. Create Postgres 11 database
5. run `weblate migrate` command

**Error Output**

```
# weblate migrate
Operations to perform:
  Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, lang, memory, screenshots, sessions, sites, social_django, trans, weblate_auth, wladmin
Running migrations:
  Applying weblate_auth.0001_initial... OK
  Applying lang.0001_squashed_0011_auto_20180215_1158... OK
  Applying trans.0001_squashed_0143_auto_20180609_1655... OK
  Applying trans.0002_delete_indexupdate... OK
  Applying trans.0003_remove_translation_commit_message... OK
  Applying trans.0004_project_use_shared_tm... OK
  Applying trans.0005_auto_20180914_1135... OK
  Applying trans.0006_suggestion_userdetails... OK
  Applying trans.0007_auto_20181011_1634... OK
  Applying trans.0008_auto_20181015_2104... OK
  Applying trans.0009_auto_20181113_1219... OK
  Applying trans.0010_auto_20181205_1505... OK
  Applying trans.0011_component_merge_message... OK
  Applying trans.0012_auto_20190129_1325... OK
  Applying trans.0013_component_addon_message... OK
  Applying trans.0014_auto_20190203_1923... OK
  Applying trans.0015_linked_component_branch... OK
  Applying trans.0016_fix_alert_occurrence... OK
  Applying trans.0017_component_language_code_style... OK
  Applying trans.0018_remove_unusednewbase_alert... OK
  Applying trans.0019_auto_20190321_1003... OK
  Applying trans.0020_auto_20190321_0921... OK
  Applying trans.0021_auto_20190321_1004... OK
  Applying trans.0022_auto_20190321_1443... OK
  Applying trans.0023_auto_20190325_1037... OK
  Applying trans.0024_resolve_auto_format... OK
  Applying social_django.0001_initial... OK
  Applying accounts.0001_squashed_0037_auto_20180416_1406... OK
  Applying accounts.0002_profile_uploaded... OK
  Applying accounts.0003_profile_translate_mode... OK
  Applying accounts.0004_create_profile... OK
  Applying accounts.0005_auto_20190331_2126... OK
  Applying accounts.0006_subscriptions... OK
  Applying accounts.0007_auto_20190411_0807... OK
  Applying addons.0001_squashed_0006_addon_project_scope... OK
  Applying addons.0007_auto_20180629_1736... OK
  Applying addons.0008_auto_20180727_1454... OK
  Applying addons.0009_auto_20181207_1322... OK
  Applying addons.0010_auto_20181214_1232... OK
  Applying addons.0011_squash_addon... OK
  Applying addons.0012_addon_repo_scope... OK
  Applying addons.0013_fix_repo_scope... OK
  Applying contenttypes.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying checks.0001_squashed_0002_auto_20180416_1509... OK
  Applying memory.0001_squashed_0003_auto_20180321_1554... OK
  Applying screenshots.0001_squashed_0003_auto_20170215_1633... OK
  Applying screenshots.0002_auto_20180826_0839... OK
  Applying sessions.0001_initial... OK
  Applying sites.0001_initial... OK
  Applying sites.0002_alter_domain_unique... OK
  Applying social_django.0002_add_related_name... OK
  Applying social_django.0003_alter_email_max_length... OK
  Applying social_django.0004_auto_20160423_0400... OK
  Applying social_django.0005_auto_20160727_2333... OK
  Applying social_django.0006_partial... OK
  Applying social_django.0007_code_timestamp... OK
  Applying social_django.0008_partial_timestamp... OK
  Applying weblate_auth.0002_auto_20180507_1540_squashed_0011_auto_20180509_0739... OK
  Applying weblate_auth.0003_auto_20180724_1120... OK
  Applying weblate_auth.0004_auto_20180827_1406... OK
  Applying wladmin.0001_squashed_0003_auto_20180215_1127... OK
  Applying wladmin.0002_auto_20181127_2116... OK
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fb47b376f28>
Traceback (most recent call last):
  File "/weblate-env/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fb47b376f28>
Traceback (most recent call last):
  File "/weblate-env/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```

So is it failed or migration was successful?

**Server configuration and status**

same issue using other Weblate command:

```
# weblate list_versions
 * Weblate 3.6.1
 * Python 3.5.3
 * Django 2.2.1
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.3.1
 * translation-finder 1.5
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.11.0
 * Pillow 6.0.0
 * python-dateutil 2.8.0
 * lxml 4.3.3
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.9.4
 * user-agents 2.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2019.1
 * pyuca 1.2
 * python-bidi 0.4.0
 * PyYAML 5.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:LocMemCache
 * Celery: memory://, N/A, eager
 * Platform: Linux 4.9.0-9-amd64 (x86_64)
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fd907bd1f28>
Traceback (most recent call last):
  File "/weblate-env/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7fd907bd1f28>
Traceback (most recent call last):
  File "/weblate-env/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
```

**Comment by nijel** [comment]
That should be (harmless) bug in Python, see https://bugs.python.org/issue29519
