### ISSUE TITLE
cannot import name 'TYPE_STRING' from 'openpyxl.cell.cell

### ISSUE THREAD

**Issue by darthginger** [WeblateOrg/weblate#2824]
**Describe the bug**
upgrading from 3.6.1 to 3.7 results in this error:
ERROR Handled exception: ImproperlyConfigured: Error importing module weblate.formats.external in WEBLATE_FORMATS: "cannot import name 'TYPE_STRING' from 'openpyxl.cell.cell' (/home/nouser4u/.local/lib/python3.7/site-packages/openpyxl/cell/cell.py)"
Traceback (most recent call last):
  File "/home/nouser4u/weblate/weblate/utils/classloader.py", line 39, in load_class
    mod = import_module(module)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nouser4u/weblate/weblate/formats/external.py", line 29, in <module>
    from openpyxl.cell.cell import TYPE_STRING
ImportError: cannot import name 'TYPE_STRING' from 'openpyxl.cell.cell' (/home/nouser4u/.local/lib/python3.7/site-packages/openpyxl/cell/cell.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 33, in <module>
    main()
  File "/home/nouser4u/weblate/weblate/runner.py", line 34, in main
    execute_from_command_line(argv)
  File "/home/nouser4u/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/nouser4u/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/nouser4u/.local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/nouser4u/.local/lib/python3.7/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/nouser4u/.local/lib/python3.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/nouser4u/weblate/weblate/addons/models.py", line 47, in <module>
    from weblate.trans.models import Component, Unit
  File "/home/nouser4u/weblate/weblate/trans/models/__init__.py", line 35, in <module>
    from weblate.trans.models.component import Component
  File "/home/nouser4u/weblate/weblate/trans/models/component.py", line 149, in <module>
    class Component(models.Model, URLMixin, PathMixin):
  File "/home/nouser4u/weblate/weblate/trans/models/component.py", line 274, in Component
    choices=FILE_FORMATS.get_choices(),
  File "/home/nouser4u/weblate/weblate/utils/classloader.py", line 108, in get_choices
    return [(x, self[x].name) for x in sorted(self)]
  File "/home/nouser4u/weblate/weblate/utils/classloader.py", line 96, in __iter__
    return self.data.__iter__()
  File "/home/nouser4u/.local/lib/python3.7/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/nouser4u/weblate/weblate/utils/classloader.py", line 75, in data
    return self.load_data()
  File "/home/nouser4u/weblate/weblate/formats/models.py", line 44, in load_data
    result = super(FileFormatLoader, self).load_data()
  File "/home/nouser4u/weblate/weblate/utils/classloader.py", line 67, in load_data
    obj = load_class(path, self.name)
  File "/home/nouser4u/weblate/weblate/utils/classloader.py", line 43, in load_class
    module, setting, error
django.core.exceptions.ImproperlyConfigured: Error importing module weblate.formats.external in WEBLATE_FORMATS: "cannot import name 'TYPE_STRING' from 'openpyxl.cell.cell' (/home/nouser4u/.local/lib/python3.7/site-packages/openpyxl/cell/cell.py)"

**To Reproduce**
1. have 3.6.1 working
2. update/install python dependencies
3. manage.py migrate

**Expected behavior**
successful upgrade

**Additional context**
my settings.py has minimal changes compared to settings_example.py. There is also no section called WEBLATE_FORMATS in my settings.py.

**Comment by nijel** [comment]
What openpyxl version do you have? Upgrading it should fix that.

**Comment by darthginger** [comment]
2.5.12

**Comment by darthginger** [comment]
requirements.txt demands >=2.5.0 nevertheless i did a python3 -m pip install --upgrade openpyxl to version 2.6.2 and now i can successfully update weblate.

**Comment by nijel** [comment]
Indeed it was moved in 2.6 release (see https://bitbucket.org/openpyxl/openpyxl/commits/b733e47647b3301dd912c1ecd85f2b9e5aef4252), I'l adjust the requirement...

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
