### ISSUE TITLE
'[Errno 111] Connection refused' when testing user registration

### ISSUE THREAD

**Issue by erciccione** [WeblateOrg/weblate#2838]
Hello, i'm migrating to Weblate from Pootle and i'm having problems with the user registration. I get this error: `[Errno 111] Connection refused`. I'm running weblate in a virtualenv. I don't understand if i should run an external smtp server or if something is broken. Pootle was sending emails from the same machine with no issues (default settings).

I just started the tests on this machine, but when i was testing locally i had a slightly different problem: the registration of a new user went "fine", but the registration email was never sent/received. Now i just get the error.

Stack trace:
```
[25/Jun/2019 15:39:52] "GET / HTTP/1.0" 200 18830
[25/Jun/2019 15:40:05] "GET / HTTP/1.0" 200 7814
[25/Jun/2019 15:40:07] "GET /accounts/register/ HTTP/1.0" 200 9917
INFO Passed captcha for zrzcjnuj@sharklasers.com (9 * 2 = 18)
INFO sending notification activation on /accounts/complete/email/?verification_code=11ac3a71175742cd891a3d4340ad5cc1&partial_token=6bdd0f57afb243bfa357fdcfc6b08b51 to zrzcjnuj@sharklasers.com
ERROR Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/weblate/accounts/views.py", line 687, in register
    return social_complete(request, 'email')
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/weblate/accounts/views.py", line 209, in demo_wrap
    return function(request, *args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/weblate/accounts/views.py", line 1058, in social_complete
    return complete(request, backend)
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_django/utils.py", line 49, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_django/views.py", line 33, in complete
    *args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_core/actions.py", line 43, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_core/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_core/backends/legacy.py", line 25, in auth_complete
    return self.strategy.authenticate(*args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_django/strategy.py", line 107, in authenticate
    return authenticate(*args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_core/backends/base.py", line 80, in authenticate
    return self.pipeline(pipeline, *args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_core/backends/base.py", line 83, in pipeline
    out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_core/backends/base.py", line 113, in run_pipeline
    result = func(*args, **out) or {}
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_core/pipeline/partial.py", line 34, in wrapper
    *args, **kwargs) or {}
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_core/pipeline/mail.py", line 22, in mail_validation
    current_partial.token)
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_core/strategy.py", line 134, in send_email_validation
    send_email(self, backend, code, partial_token)
  File "/var/www/weblate-env/lib/python3.6/site-packages/weblate/accounts/pipeline.py", line 149, in send_validation
    'url': url
  File "/var/www/weblate-env/lib/python3.6/site-packages/weblate/accounts/notifications.py", line 533, in send_notification_email
    send_mails.delay([email])
  File "/var/www/weblate-env/lib/python3.6/site-packages/celery/app/task.py", line 427, in delay
    return self.apply_async(args, kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/celery/app/task.py", line 552, in apply_async
    link=link, link_error=link_error, **options)
  File "/var/www/weblate-env/lib/python3.6/site-packages/celery/app/task.py", line 774, in apply
    ret = tracer(task_id, args, kwargs, request)
  File "/var/www/weblate-env/lib/python3.6/site-packages/celery/app/trace.py", line 399, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/var/www/weblate-env/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/weblate/accounts/notifications.py", line 539, in send_mails
    with get_connection() as connection:
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/core/mail/backends/base.py", line 45, in __enter__
    self.open()
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 63, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
Internal Server Error: /accounts/register/
Traceback (most recent call last):
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/weblate/accounts/views.py", line 687, in register
    return social_complete(request, 'email')
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/weblate/accounts/views.py", line 209, in demo_wrap
    return function(request, *args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/weblate/accounts/views.py", line 1058, in social_complete
    return complete(request, backend)
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_django/utils.py", line 49, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_django/views.py", line 33, in complete
    *args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_core/actions.py", line 43, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_core/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_core/backends/legacy.py", line 25, in auth_complete
    return self.strategy.authenticate(*args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_django/strategy.py", line 107, in authenticate
    return authenticate(*args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_core/backends/base.py", line 80, in authenticate
    return self.pipeline(pipeline, *args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_core/backends/base.py", line 83, in pipeline
    out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_core/backends/base.py", line 113, in run_pipeline
    result = func(*args, **out) or {}
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_core/pipeline/partial.py", line 34, in wrapper
    *args, **kwargs) or {}
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_core/pipeline/mail.py", line 22, in mail_validation
    current_partial.token)
  File "/var/www/weblate-env/lib/python3.6/site-packages/social_core/strategy.py", line 134, in send_email_validation
    send_email(self, backend, code, partial_token)
  File "/var/www/weblate-env/lib/python3.6/site-packages/weblate/accounts/pipeline.py", line 149, in send_validation
    'url': url
  File "/var/www/weblate-env/lib/python3.6/site-packages/weblate/accounts/notifications.py", line 533, in send_notification_email
    send_mails.delay([email])
  File "/var/www/weblate-env/lib/python3.6/site-packages/celery/app/task.py", line 427, in delay
    return self.apply_async(args, kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/celery/app/task.py", line 552, in apply_async
    link=link, link_error=link_error, **options)
  File "/var/www/weblate-env/lib/python3.6/site-packages/celery/app/task.py", line 774, in apply
    ret = tracer(task_id, args, kwargs, request)
  File "/var/www/weblate-env/lib/python3.6/site-packages/celery/app/trace.py", line 399, in trace_task
    I, R, state, retval = on_error(task_request, exc, uuid)
  File "/var/www/weblate-env/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/var/www/weblate-env/lib/python3.6/site-packages/weblate/accounts/notifications.py", line 539, in send_mails
    with get_connection() as connection:
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/core/mail/backends/base.py", line 45, in __enter__
    self.open()
  File "/var/www/weblate-env/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 63, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

The settings in `global_settings.py` are the default:
```
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Host for sending email.
EMAIL_HOST = 'localhost'

# Port for sending email.
EMAIL_PORT = 25

# Whether to send SMTP 'Date' header in the local time zone or in UTC.
EMAIL_USE_LOCALTIME = False

# Optional SMTP authentication information for EMAIL_HOST.
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = False
EMAIL_USE_SSL = False
EMAIL_SSL_CERTFILE = None
EMAIL_SSL_KEYFILE = None
EMAIL_TIMEOUT = None
```
 output of `weblate list_versions`:
```
 * Weblate 3.6.1
 * Python 3.6.7
 * Django 2.2.2
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.3.1
 * translation-finder 1.5
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.17.1
 * Pillow 6.0.0
 * python-dateutil 2.8.0
 * lxml 4.3.4
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.9.4
 * user-agents 2.0
 * jellyfish 0.7.2
 * diff-match-patch 20121119
 * pytz 2019.1
 * pyuca 1.2
 * PyYAML 5.1.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:LocMemCache
 * Celery: memory://, N/A, eager
 * Platform: Linux 4.15.0-12-generic (x86_64)
```

**Comment by nijel** [comment]
First of all don't edit `global_settings.py`, it's Django defaults, you're supposed to change `settings.py` for Weblate.

You're trying to use SMTP server on localhost which is not running, so you need to configure some server that is actually working. `weblate check --deploy` will tell you that email setup is broken.

**Comment by erciccione** [comment]
Thank you for the answer @nijel . I resolved installing a mail server. I suggest to specify in the documentation the need to install a smtp server, the documentation specify you need to configure one, but doesn't specify if it's included or not.

**Comment by nijel** [comment]
Good point.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
