### ISSUE TITLE
Reliability in docker setup

### ISSUE THREAD

**Issue by weeblr** [WeblateOrg/weblate#2960]
**Describe the bug**
I am setting up Weblate using docker, per the corresponding guide. Things went well in general. However I am sometimes experiencing a failure similar to issue https://github.com/WeblateOrg/docker/issues/117.

Upon starting up the containers with docker-compose... up, the weblate app tries to insert the admin email again. This causes an key constraints error in Postgres and the application cannot start.

In the linked issue above, you said the user did not properly set the default environment variables.

In my case, the email that weblate tries to insert is the real admin email so #117 does not seem to apply.

The weird thing is that things will work for like a few hours of stopping and restarting the app and all of a sudden one down/up cycle will cause the problem to happen.

So my question really is: what can cause the weblate app to try inject again the admin email even though it's already there in the db and the postgres container is up and running? A race between both containers? Any advice welcome!

**To Reproduce**

My setup is based on Ansible scripts, so I don't think it can be reproduced as is. Ansible allows reconfiguring the server setup quickly and repeatedly. As part of that, weblate containers are cycled down/up easily and often while I adjust configuration of other things (backups,etc). Often means a few times an hour, not like every minute.

1. Install as docker
2. docker-compose up 
3. Apps starts and can be used normally over the web
4. docker-compose down and later up a few times and after a while, I get the error described

**Expected behavior**
Reliable down/up cycles.

**Server configuration and status**

Versions:

```
 * Weblate 3.7.1
 * Python 3.7.3
 * Django 2.2.4
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.4.0
 * translation-finder 1.6
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.20.1
 * Pillow 5.4.1
 * python-dateutil 2.8.0
 * lxml 4.3.2
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.10.2
 * user-agents 2.0
 * jellyfish 0.7.2
 * diff-match-patch 20121119
 * pytz 2019.2
 * pyuca 1.2
 * ruamel.yaml 0.16.0
 * tesserocr 2.4.0
 * Mercurial 4.8.2
 * git-svn 2.20.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.mailgun.com
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.19.0-5-amd64 (x86_64)

```

Output of `check --deploy`: none

**Additional context**

Note that:
- admin email has been replaced with xxxx@yyyyy.com
- site URL has been replaced with translate.yyyyy.com

**docker-compose-https.yml**:

```
version: '3'
services:
  weblate:
    build: ./app
    container_name: wbl_tx_app
    volumes:
      - weblate-data:/app/data
      - /opt/weblate/inbox:/app/inbox
    env_file:
      - ./environment
    restart: unless-stopped
    depends_on:
      - database
      - cache
    environment:
      WEBLATE_ENABLE_HTTPS: 1
      WEBLATE_DEBUG: 0
      WEBLATE_LOGLEVEL: INFO
      WEBLATE_TIME_ZONE: UTC
      WEBLATE_IP_PROXY_HEADER: HTTP_X_FORWARDED_FOR
  database:
    build: ./db
    container_name: wbl_tx_database
    env_file:
      - ./environment
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /opt/weblate/inbox:/app/inbox
    restart: unless-stopped
  cache:
    image: redis:4-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    environment:
      STAGE: production
      PROXY_READ_TIMEOUT: 3600
    volumes:
      - ssl-certs:/var/lib/https-portal
volumes:
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
  ssl-certs: {}

```

**docker-compose-https.override.yml**:

```
version: '3'
services:
  weblate:
    environment:
      WEBLATE_ALLOWED_HOSTS: translate.yyyyy.com
      WEBLATE_REGISTRATION_OPEN: 0
      WEBLATE_REQUIRE_LOGIN: 1
      WEBLATE_EMAIL_HOST: smtp.someprovider.com
      WEBLATE_EMAIL_HOST_USER: postmaster@mg.yyyyy.com
      WEBLATE_EMAIL_HOST_PASSWORD: bc3--------------------------------------62
      WEBLATE_SERVER_EMAIL: xxxx@yyyyy.com
      WEBLATE_DEFAULT_FROM_EMAIL: xxxx@yyyyy.com
      WEBLATE_ADMIN_PASSWORD: ---------------------------
      WEBLATE_ADMIN_EMAIL: xxxx@yyyyy.com
  https-portal:
    environment:
      DOMAINS: 'translate.yyyyy.com -> http://weblate:8080'

```

Environment:

```
# See Weblate documentation for detailed description:
# https://docs.weblate.org/en/latest/admin/deployments.html#docker

# Weblate setup
WEBLATE_DEBUG=0
WEBLATE_LOGLEVEL=INFO
WEBLATE_SITE_TITLE=YYYYY Translate
WEBLATE_ADMIN_NAME=YYYYY Admin
WEBLATE_ADMIN_EMAIL=xxxx@yyyyy.com
WEBLATE_ADMIN_PASSWORD=------------------------
WEBLATE_SERVER_EMAIL=xxxx@yyyyy.com
WEBLATE_DEFAULT_FROM_EMAIL=xxxx@yyyyy.com
WEBLATE_ALLOWED_HOSTS=translate.yyyyy.com
WEBLATE_REGISTRATION_OPEN=0

# Extra
WEBLATE_TIME_ZONE=UTC
#WEBLATE_MT_GOOGLE_KEY=
#WEBLATE_SOCIAL_AUTH_GITHUB_KEY=
#WEBLATE_SOCIAL_AUTH_GITHUB_SECRET=
#WEBLATE_SOCIAL_AUTH_BITBUCKET_KEY=
#WEBLATE_SOCIAL_AUTH_BITBUCKET_SECRET=
#WEBLATE_SOCIAL_AUTH_FACEBOOK_KEY=
#WEBLATE_SOCIAL_AUTH_FACEBOOK_SECRET=
#WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=
#WEBLATE_SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=

#WEBLATE_OFFLOAD_INDEXING=1
#WEBLATE_GOOGLE_ANALYTICS_ID=

WEBLATE_ENABLE_HTTPS=1
WEBLATE_IP_PROXY_HEADER=HTTP_X_FORWARDED_FOR
WEBLATE_REQUIRE_LOGIN=1

# LDAP Auth
#WEBLATE_AUTH_LDAP_SERVER_URI=ldap://ldap.example.org
#WEBLATE_AUTH_LDAP_USER_DN_TEMPLATE=uid=%(user)s,ou=People,dc=example,dc=net
#WEBLATE_AUTH_LDAP_USER_ATTR_MAP=first_name:name,email:mail

# PostgreSQL setup
POSTGRES_PASSWORD=weblate
POSTGRES_USER=weblate
POSTGRES_DATABASE=weblate
POSTGRES_HOST=database
POSTGRES_PORT=

# Cache setup
# https://docs.weblate.org/en/latest/admin/install.html#production-cache
REDIS_HOST=cache
REDIS_PORT=6379

# Mail server, the server has to listen on port 587 and understand TLS
WEBLATE_EMAIL_HOST=smtp.someprovider.com
# Do NOT use quotes here
WEBLATE_EMAIL_USER=postmaster@mg.yyyyy.com
# Do NOT use quotes here
WEBLATE_EMAIL_PASSWORD=bc3--------------------------------------62

# These keys are named differently in docs and in environment file. We use both for now.
WEBLATE_EMAIL_HOST_USER: postmaster@mg.yyyyy.com
WEBLATE_EMAIL_HOST_PASSWORD: bc3--------------------------------------62
```

**Here is a log of the start up sequence when the problem occurs. Only the start of the log, it repeats itself as the container is restarted again and again**:

```
Attaching to wbl_tx_database, weblate_cache_1, weblate_https-portal_1, wbl_tx_app
[wbl_tx_database]  LOG:  database system was shut down at 2019-08-14 06:47:02 UTC
[wbl_tx_database]  LOG:  MultiXact member wraparound protections are now enabled
[wbl_tx_database]  LOG:  database system is ready to accept connections
[wbl_tx_database]  LOG:  autovacuum launcher started
[cache_1    ]  1:C 14 Aug 06:48:30.343 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
[cache_1    ]  1:C 14 Aug 06:48:30.343 # Redis version=4.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
[cache_1    ]  1:C 14 Aug 06:48:30.343 # Configuration loaded
[cache_1    ]  1:M 14 Aug 06:48:30.345 * Running mode=standalone, port=6379.
[cache_1    ]  1:M 14 Aug 06:48:30.345 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
[cache_1    ]  1:M 14 Aug 06:48:30.345 # Server initialized
[cache_1    ]  1:M 14 Aug 06:48:30.345 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
[cache_1    ]  1:M 14 Aug 06:48:30.467 * DB loaded from append only file: 0.122 seconds
[cache_1    ]  1:M 14 Aug 06:48:30.467 * Ready to accept connections
[https-portal_1 ]  [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[https-portal_1 ]  [s6-init] ensuring user provided files have correct perms...exited 0.
[https-portal_1 ]  [fix-attrs.d] applying ownership & permissions fixes...
[https-portal_1 ]  [fix-attrs.d] done.
[https-portal_1 ]  [cont-init.d] executing container initialization scripts...
[https-portal_1 ]  [cont-init.d] 00-welcome: executing... 
[https-portal_1 ]  
[https-portal_1 ]  ========================================
[https-portal_1 ]  HTTPS-PORTAL v1.7.2
[https-portal_1 ]  ========================================
[https-portal_1 ]  
[https-portal_1 ]  [cont-init.d] 00-welcome: exited 0.
[https-portal_1 ]  [cont-init.d] 10-persist-env: executing... 
[https-portal_1 ]  [cont-init.d] 10-persist-env: exited 0.
[https-portal_1 ]  [cont-init.d] 20-setup: executing... 
[https-portal_1 ]  RSA key ok
[https-portal_1 ]  2019/08/14 06:48:30 [notice] 246#246: signal process started
[https-portal_1 ]  2019/08/14 06:48:30 [notice] 249#249: signal process started
[https-portal_1 ]  Signing skipped for translate.yyyyy.com, it expires at 89 days from now.
[https-portal_1 ]  2019/08/14 06:48:30 [notice] 251#251: signal process started
[wbl_tx_app ]  Starting...
[wbl_tx_app ]  Updating system timezone to UTC
[wbl_tx_app ]  weblate
[wbl_tx_app ]  Postgres is up
[https-portal_1 ]  [cont-init.d] 20-setup: exited 0.
[https-portal_1 ]  [cont-init.d] 30-set-docker-gen-status: executing... 
[https-portal_1 ]  [cont-init.d] 30-set-docker-gen-status: exited 0.
[https-portal_1 ]  [cont-init.d] done.
[https-portal_1 ]  [services.d] starting services
[https-portal_1 ]  [services.d] done.
[wbl_tx_app ]  Operations to perform:
[wbl_tx_app ]    Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, fonts, gitexport, lang, memory, screenshots, sessions, sites, social_django, trans, weblate_auth, wladmin
[wbl_tx_app ]  Running migrations:
[wbl_tx_app ]    No migrations to apply.
[wbl_tx_app ]  
[wbl_tx_app ]  0 static files copied to '/app/data/static', 252 unmodified.
[wbl_tx_database]  ERROR:  duplicate key value violates unique constraint "weblate_auth_user_email_aaabd769_uniq"
[wbl_tx_database]  DETAIL:  Key (email)=(xxxx@yyyyy.com) already exists.
[wbl_tx_database]  STATEMENT:  INSERT INTO "weblate_auth_user" ("password", "last_login", "username", "full_name", "email", "is_superuser", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$bQUbz7io6WW0$NFHjPFLhC8DWiURFquK1owBZdz/l5gUYYbm1eRNy140=', NULL, 'admin', '', 'xxxx@yyyyy.com', false, true, '2019-08-14T06:48:48.995440+00:00'::timestamptz) RETURNING "weblate_auth_user"."id"
[wbl_tx_app ]  ERROR Handled exception: IntegrityError: duplicate key value violates unique constraint "weblate_auth_user_email_aaabd769_uniq"
[wbl_tx_app ]  DETAIL:  Key (email)=(xxxx@yyyyy.com) already exists.
[wbl_tx_app ]  
[wbl_tx_app ]  Creating user admin
[wbl_tx_app ]  Traceback (most recent call last):
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
[wbl_tx_app ]      return self.cursor.execute(sql, params)
[wbl_tx_app ]  psycopg2.IntegrityError: duplicate key value violates unique constraint "weblate_auth_user_email_aaabd769_uniq"
[wbl_tx_app ]  DETAIL:  Key (email)=(xxxx@yyyyy.com) already exists.
[wbl_tx_app ]  
[wbl_tx_app ]  
[wbl_tx_app ]  The above exception was the direct cause of the following exception:
[wbl_tx_app ]  
[wbl_tx_app ]  Traceback (most recent call last):
[wbl_tx_app ]    File "/usr/local/bin/weblate", line 11, in <module>
[wbl_tx_app ]      load_entry_point('Weblate==3.7.1', 'console_scripts', 'weblate')()
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/weblate/runner.py", line 34, in main
[wbl_tx_app ]      execute_from_command_line(argv)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
[wbl_tx_app ]      utility.execute()
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 375, in execute
[wbl_tx_app ]      self.fetch_command(subcommand).run_from_argv(self.argv)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 323, in run_from_argv
[wbl_tx_app ]      self.execute(*args, **cmd_options)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 364, in execute
[wbl_tx_app ]      output = self.handle(*args, **options)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/weblate/auth/management/commands/createadmin.py", line 108, in handle
[wbl_tx_app ]      password
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/weblate/auth/models.py", line 226, in create_user
[wbl_tx_app ]      return self._create_user(username, email, password, **extra_fields)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/weblate/auth/models.py", line 221, in _create_user
[wbl_tx_app ]      user.save(using=self._db)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/weblate/auth/models.py", line 410, in save
[wbl_tx_app ]      super(User, self).save(*args, **kwargs)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/base_user.py", line 66, in save
[wbl_tx_app ]      super().save(*args, **kwargs)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 741, in save
[wbl_tx_app ]      force_update=force_update, update_fields=update_fields)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 779, in save_base
[wbl_tx_app ]      force_update, using, update_fields,
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 870, in _save_table
[wbl_tx_app ]      result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 908, in _do_insert
[wbl_tx_app ]      using=using, raw=raw)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/models/manager.py", line 82, in manager_method
[wbl_tx_app ]      return getattr(self.get_queryset(), name)(*args, **kwargs)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 1186, in _insert
[wbl_tx_app ]      return query.get_compiler(using=using).execute_sql(return_id)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
[wbl_tx_app ]      cursor.execute(sql, params)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 67, in execute
[wbl_tx_app ]      return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
[wbl_tx_app ]      return executor(sql, params, many, context)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
[wbl_tx_app ]      return self.cursor.execute(sql, params)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 89, in __exit__
[wbl_tx_app ]      raise dj_exc_value.with_traceback(traceback) from exc_value
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
[wbl_tx_app ]      return self.cursor.execute(sql, params)
[wbl_tx_app ]  django.db.utils.IntegrityError: duplicate key value violates unique constraint "weblate_auth_user_email_aaabd769_uniq"
[wbl_tx_app ]  DETAIL:  Key (email)=(xxxx@yyyyy.com) already exists.
[wbl_tx_app ]  
[wbl_tx_database]  ERROR:  duplicate key value violates unique constraint "weblate_auth_user_email_aaabd769_uniq"
[wbl_tx_database]  DETAIL:  Key (email)=(xxxx@yyyyy.com) already exists.
[wbl_tx_database]  STATEMENT:  INSERT INTO "weblate_auth_user" ("password", "last_login", "username", "full_name", "email", "is_superuser", "is_active", "date_joined") VALUES ('pbkdf2_sha256$150000$NiSp7aOLySpZ$kKZM8uOjAhTlOPKW0LQ875iyw5FNv/bCz5kJkHhCVZs=', NULL, 'admin', '', 'xxxx@yyyyy.com', false, true, '2019-08-14T06:49:08.281865+00:00'::timestamptz) RETURNING "weblate_auth_user"."id"
[wbl_tx_app exited with code 1
[[wbl_tx_app ]  Starting...
[wbl_tx_app ]  weblate
[wbl_tx_app ]  Updating system timezone to UTC
[wbl_tx_app ]  Postgres is up
[wbl_tx_app ]  Operations to perform:
[wbl_tx_app ]    Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, fonts, gitexport, lang, memory, screenshots, sessions, sites, social_django, trans, weblate_auth, wladmin
[wbl_tx_app ]  Running migrations:
[wbl_tx_app ]    No migrations to apply.
[wbl_tx_app ]  
[wbl_tx_app ]  0 static files copied to '/app/data/static', 252 unmodified.
[wbl_tx_app ]  ERROR Handled exception: IntegrityError: duplicate key value violates unique constraint "weblate_auth_user_email_aaabd769_uniq"
[wbl_tx_app ]  DETAIL:  Key (email)=(xxxx@yyyyy.com) already exists.
[wbl_tx_app ]  
[wbl_tx_app ]  Creating user admin
[wbl_tx_app ]  Traceback (most recent call last):
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
[wbl_tx_app ]      return self.cursor.execute(sql, params)
[wbl_tx_app ]  psycopg2.IntegrityError: duplicate key value violates unique constraint "weblate_auth_user_email_aaabd769_uniq"
[wbl_tx_app ]  DETAIL:  Key (email)=(xxxx@yyyyy.com) already exists.
[wbl_tx_app ]  
[wbl_tx_app ]  
[wbl_tx_app ]  The above exception was the direct cause of the following exception:
[wbl_tx_app ]  
[wbl_tx_app ]  Traceback (most recent call last):
[wbl_tx_app ]    File "/usr/local/bin/weblate", line 11, in <module>
[wbl_tx_app ]      load_entry_point('Weblate==3.7.1', 'console_scripts', 'weblate')()
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/weblate/runner.py", line 34, in main
[wbl_tx_app ]      execute_from_command_line(argv)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
[wbl_tx_app ]      utility.execute()
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 375, in execute
[wbl_tx_app ]      self.fetch_command(subcommand).run_from_argv(self.argv)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 323, in run_from_argv
[wbl_tx_app ]      self.execute(*args, **cmd_options)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 364, in execute
[wbl_tx_app ]      output = self.handle(*args, **options)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/weblate/auth/management/commands/createadmin.py", line 108, in handle
[wbl_tx_app ]      password
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/weblate/auth/models.py", line 226, in create_user
[wbl_tx_app ]      return self._create_user(username, email, password, **extra_fields)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/weblate/auth/models.py", line 221, in _create_user
[wbl_tx_app ]      user.save(using=self._db)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/weblate/auth/models.py", line 410, in save
[wbl_tx_app ]      super(User, self).save(*args, **kwargs)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/base_user.py", line 66, in save
[wbl_tx_app ]      super().save(*args, **kwargs)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 741, in save
[wbl_tx_app ]      force_update=force_update, update_fields=update_fields)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 779, in save_base
[wbl_tx_app ]      force_update, using, update_fields,
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 870, in _save_table
[wbl_tx_app ]      result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 908, in _do_insert
[wbl_tx_app ]      using=using, raw=raw)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/models/manager.py", line 82, in manager_method
[wbl_tx_app ]      return getattr(self.get_queryset(), name)(*args, **kwargs)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 1186, in _insert
[wbl_tx_app ]      return query.get_compiler(using=using).execute_sql(return_id)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
[wbl_tx_app ]      cursor.execute(sql, params)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 67, in execute
[wbl_tx_app ]      return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
[wbl_tx_app ]      return executor(sql, params, many, context)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
[wbl_tx_app ]      return self.cursor.execute(sql, params)
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 89, in __exit__
[wbl_tx_app ]      raise dj_exc_value.with_traceback(traceback) from exc_value
[wbl_tx_app ]    File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
[wbl_tx_app ]      return self.cursor.execute(sql, params)
[wbl_tx_app ]  django.db.utils.IntegrityError: duplicate key value violates unique constraint "weblate_auth_user_email_aaabd769_uniq"
[wbl_tx_app ]  DETAIL:  Key (email)=(xxxx@yyyyy.com) already exists.
[wbl_tx_app ]  
[wbl_tx_app ]  Starting...
[wbl_tx_app ]  Updating system timezone to UTC
[wbl_tx_app ]  weblate
[wbl_tx_app ]  Postgres is up
[wbl_tx_app ]  Operations to perform:
[wbl_tx_app ]    Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, fonts, gitexport, lang, memory, screenshots, sessions, sites, social_django, trans, weblate_auth, wladmin
[wbl_tx_app ]  Running migrations:
[wbl_tx_app ]    No migrations to apply.
[wbl_tx_app ]  
[wbl_tx_app ]  0 static files copied to '/app/data/static', 252 unmodified.
[wbl_tx_app ]  ERROR Handled exception: IntegrityError: duplicate key value violates unique constraint "weblate_auth_user_email_aaabd769_uniq"
[wbl_tx_app ]  DETAIL:  Key (email)=(xxxx@yyyyy.com) already exists.
```

**Comment by nijel** [comment]
My guess is that you have changed admin username to something different, is that correct?

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by weeblr** [comment]
Hi,

Yes, at some point I changed the admin username. I see you've fixed it, which is great.
How can I go from there? Can I update to this fixed version now somehow? Do I have to wait til it's released?

Thanks

**Comment by nijel** [comment]
The fix will be part of 3.8 release which will be out tomorrow, so you have to wait one day :-).

**Comment by weeblr** [comment]
That's cool 😁

**Comment by weeblr** [comment]
Hi @nijel 

I see that 3.8 is available for download from weblate.org but the docker version is not at hub.docker.com, it seems the build is failing?

Cheers

**Comment by nijel** [comment]
It took some time to update it, but it's now there (or at least building).

**Comment by weeblr** [comment]
oh yeah, I see "Latest" successfully built. The 3.8 tag is not showing there but not needed. I'll go ahead and test now. Thanks for this!

Best regards

**Comment by nijel** [comment]
It's probably still building, I've pushed it recently.

**Comment by weeblr** [comment]
Yes, 3.8-1 is now available :)

**Comment by weeblr** [comment]
Works now! Many thanks!
