### ISSUE TITLE
git is misdetected on macOS

### ISSUE THREAD

**Issue by minusf** [WeblateOrg/weblate#3097]
**Describe the bug**
`git` on `macOS` has a custom `--version` banner and this confuses weblate.

```
$ git --version
git version 2.20.1 (Apple Git-117)
```

**To Reproduce**
1. `weblate migrate`

```
weblate migrate
ERROR Handled exception: TypeError: '<' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "./venv/bin/weblate", line 11, in <module>
    load_entry_point('Weblate==3.8', 'console_scripts', 'weblate')()
  File "/Users/user/src/weblate/venv/lib/python3.6/site-packages/weblate/runner.py", line 34, in main
    execute_from_command_line(argv)
  File "/Users/user/src/weblate/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/user/src/weblate/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/Users/user/src/weblate/venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/user/src/weblate/venv/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/Users/user/src/weblate/venv/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/user/src/weblate/venv/lib/python3.6/site-packages/weblate/addons/models.py", line 47, in <module>
    from weblate.trans.models import Component, Unit
  File "/Users/user/src/weblate/venv/lib/python3.6/site-packages/weblate/trans/models/__init__.py", line 35, in <module>
    from weblate.trans.models.component import Component
  File "/Users/user/src/weblate/venv/lib/python3.6/site-packages/weblate/trans/models/component.py", line 158, in <module>
    class Component(models.Model, URLMixin, PathMixin):
  File "/Users/user/src/weblate/venv/lib/python3.6/site-packages/weblate/trans/models/component.py", line 183, in Component
    choices=VCS_REGISTRY.get_choices(),
  File "/Users/user/src/weblate/venv/lib/python3.6/site-packages/weblate/utils/classloader.py", line 110, in get_choices
    for x in sorted(self)
  File "/Users/user/src/weblate/venv/lib/python3.6/site-packages/weblate/utils/classloader.py", line 96, in __iter__
    return self.data.__iter__()
  File "/Users/user/src/weblate/venv/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/user/src/weblate/venv/lib/python3.6/site-packages/weblate/utils/classloader.py", line 75, in data
    return self.load_data()
  File "/Users/user/src/weblate/venv/lib/python3.6/site-packages/weblate/vcs/models.py", line 36, in load_data
    if not vcs.is_supported():
  File "/Users/user/src/weblate/venv/lib/python3.6/site-packages/weblate/vcs/base.py", line 317, in is_supported
    or LooseVersion(version) >= LooseVersion(cls.req_version)):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/version.py", line 70, in __ge__
    c = self._cmp(other)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Expected behavior**
Running weblate

**Comment by minusf** [comment]
I submitted a possible fix in #3096
