### ISSUE TITLE
RuntimeError: populate() isn't reentrant

### ISSUE THREAD

**Issue by maicol07** [WeblateOrg/weblate#3117]
**Describe the bug**
Internal server error when going to URL after update (3.8 to 3.9)
Error in Apache's logs:
```
[Wed Oct 16 19:06:25.434813 2019] [wsgi:error] [pid 742] [remote 192.168.1.101:49453] mod_wsgi (pid=742): Target WSGI script '/var/www/html/weblate/lib/python3.6/site-packages/weblate/wsgi.py' cannot be loaded as Python module.
[Wed Oct 16 19:06:25.434931 2019] [wsgi:error] [pid 742] [remote 192.168.1.101:49453] mod_wsgi (pid=742): Exception occurred processing WSGI script '/var/www/html/weblate/lib/python3.6/site-packages/weblate/wsgi.py'.
[Wed Oct 16 19:06:25.435207 2019] [wsgi:error] [pid 742] [remote 192.168.1.101:49453] Traceback (most recent call last):
[Wed Oct 16 19:06:25.435297 2019] [wsgi:error] [pid 742] [remote 192.168.1.101:49453]   File "/var/www/html/weblate/lib/python3.6/site-packages/weblate/wsgi.py", line 45, in <module>
[Wed Oct 16 19:06:25.435316 2019] [wsgi:error] [pid 742] [remote 192.168.1.101:49453]     application = get_wsgi_application()
[Wed Oct 16 19:06:25.435347 2019] [wsgi:error] [pid 742] [remote 192.168.1.101:49453]   File "/var/www/html/weblate/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Wed Oct 16 19:06:25.435365 2019] [wsgi:error] [pid 742] [remote 192.168.1.101:49453]     django.setup(set_prefix=False)
[Wed Oct 16 19:06:25.435394 2019] [wsgi:error] [pid 742] [remote 192.168.1.101:49453]   File "/var/www/html/weblate/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
[Wed Oct 16 19:06:25.435412 2019] [wsgi:error] [pid 742] [remote 192.168.1.101:49453]     apps.populate(settings.INSTALLED_APPS)
[Wed Oct 16 19:06:25.435441 2019] [wsgi:error] [pid 742] [remote 192.168.1.101:49453]   File "/var/www/html/weblate/lib/python3.6/site-packages/django/apps/registry.py", line 83, in populate
[Wed Oct 16 19:06:25.435459 2019] [wsgi:error] [pid 742] [remote 192.168.1.101:49453]     raise RuntimeError("populate() isn't reentrant")
[Wed Oct 16 19:06:25.435505 2019] [wsgi:error] [pid 742] [remote 192.168.1.101:49453] RuntimeError: populate() isn't reentrant
```

**To Reproduce**
1. Finish the update
2. Open your weblate URL

**Expected behavior**
Weblate should working normally

**Screenshots**

**Server configuration and status**
Output of `list_versions`:
(weblate) maicol07@maicol07:/var/www/html/weblate$ weblate list_versions
```
 * Weblate 3.9
 * Python 3.6.8
 * Django 2.2.5
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.4.0
 * translation-finder 1.7
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.17.1
 * Pillow 6.2.0
 * python-dateutil 2.8.0
 * lxml 4.4.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.10.3
 * user-agents 2.0
 * jellyfish 0.7.2
 * diff-match-patch 20181111
 * ruamel.yaml 0.16.5
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.maicol07.it
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 5.3.5-050305-generic (x86_64)
```

Output of `check --deploy`:
```
(weblate) maicol07@maicol07:/var/www/html/weblate$ weblate check --deploy
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E019) The Celery does not process tasks or is too slow in processing them.
        HINT: https://docs.weblate.org/en/weblate-3.9/admin/install.html#celery

WARNINGS:
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.9/admin/backup.html
```

**Comment by maicol07** [comment]
Solved this error by copying from `settings_example.py` to `settings.py` the `TEMPLATES `variable.

**Comment by maicol07** [comment]
Facing again this issue, but I can't find what's wrong this time...

**Comment by nijel** [comment]
It might be just hiding another error, see https://stackoverflow.com/a/55929118/225718

**Comment by maicol07** [comment]
Strange... restarting Apache did the trick...

Ok, thanks @nijel for the tip!

**Comment by namjoo** [comment]
> Strange... restarting Apache did the trick...
> 
> Ok, thanks @nijel for the tip!

This is temporary.

**Comment by namjoo** [comment]
> It might be just hiding another error, see https://stackoverflow.com/a/55929118/225718

Thanks. It works for me.

**Comment by Nadeemaslam** [comment]
In my case had mysqlclient not installed .Unfortunately, Django's hiding the bug behind this generic and un-useful error message. To reveal the true problem, open django/apps/registry.py and around line 80, replace:

` raise RuntimeError("populate() isn't reentrant") 
`
with:

` self.app_configs = {}
`
and then check the error.log to find the actual bug. fix that and restart apache server
