### ISSUE TITLE
PostgreSQL migration doesn't seem to work properly

### ISSUE THREAD

**Issue by BhaaLseN** [WeblateOrg/weblate#3129]
**Describe the bug**
Since MySQL will be deprecated with 4.0, I tried to follow the [migration steps shown in the docs](https://docs.weblate.org/en/latest/admin/install.html#create-empty-tables-in-the-postgresql), but got stopped in my tracks by this one:
```
$ ./manage.py migrate --database=postgresql
Operations to perform:
  Apply all migrations: accounts, addons, admin, auth, authtoken, checks, conten
ttypes, fonts, gitexport, lang, memory, screenshots, sessions, sites, social_dja
ngo, trans, weblate_auth, wladmin
Running migrations:
  Applying weblate_auth.0001_initial... OK
  Applying lang.0001_squashed_0011_auto_20180215_1158... OK
  Applying trans.0001_squashed_0143_auto_20180609_1655... OK
  Applying trans.0002_delete_indexupdate... OK
  Applying trans.0003_remove_translation_commit_message... OK
  Applying trans.0004_project_use_shared_tm... OK
  Applying trans.0005_auto_20180914_1135... OK
  Applying trans.0006_suggestion_userdetails... OK
  Applying trans.0007_auto_20181011_1634... OK
  Applying trans.0008_auto_20181015_2104... OK
  Applying trans.0009_auto_20181113_1219... OK
  Applying trans.0010_auto_20181205_1505... OK
  Applying trans.0011_component_merge_message... OK
  Applying trans.0012_auto_20190129_1325... OK
  Applying trans.0013_component_addon_message... OK
  Applying trans.0014_auto_20190203_1923... OK
  Applying trans.0015_linked_component_branch... OK
  Applying trans.0016_fix_alert_occurrence... OK
  Applying trans.0017_component_language_code_style... OK
  Applying trans.0018_remove_unusednewbase_alert... OK
  Applying trans.0019_auto_20190321_1003... OK
  Applying trans.0020_auto_20190321_0921... OK
  Applying trans.0021_auto_20190321_1004... OK
  Applying trans.0022_auto_20190321_1443... OK
  Applying trans.0023_auto_20190325_1037... OK
  Applying trans.0024_resolve_auto_format... OK
  Applying social_django.0001_initial... OK
  Applying accounts.0001_squashed_0037_auto_20180416_1406... OK
  Applying accounts.0002_profile_uploaded... OK
  Applying accounts.0003_profile_translate_mode... OK
ERROR Handled exception: OperationalError: (1054, "Unknown column 'accounts_profile.subscribe_any_translation' in 'field list'")
  Applying accounts.0004_create_profile...Traceback (most recent call last):
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'accounts_profile.subscribe_any_translation' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
 File "./manage.py", line 33, in <module>
    main()
  File "/home/weblate/weblate/weblate/runner.py", line 34, in main
    execute_from_command_line(argv)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/weblate/weblate/weblate/accounts/migrations/0004_create_profile.py", line 12, in create_profiles
    Profile.objects.get_or_create(user=user)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/models/query.py", line 538, in get_or_create
    return self.get(**kwargs), False
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/MySQLdb/cursors.py", line 312, in _query
    db.query(q)
  File "/home/weblate/.pyenv/versions/3.7.3/lib/python3.7/site-packages/MySQLdb/connections.py", line 224, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'accounts_profile.subscribe_any_translation' in 'field list'")
```

I'm not quite sure why it is listing `MySQLdb` packages either, so I can't really tell if those are related or not.

This *also* fails on an empty MySQL DB (running `./manage.py migrate --database=mysqltest` instead), so I believe it might be a general migration issue rather than related to PostgreSQL; or the migration itself.

**To Reproduce**
1. [Create a new PostgreSQL database to use as target](https://docs.weblate.org/en/latest/admin/install.html#id1)
2. [Add a second connection to `DATABASES`](https://docs.weblate.org/en/latest/admin/install.html#id2)
3. Run `./manage.py migrate --database=postgresql` as described by [the docs as next step](https://docs.weblate.org/en/latest/admin/install.html#create-empty-tables-in-the-postgresql)

**Expected behavior**
Migration succeeds and creates empty tables.

**Server configuration and status**
Please paste the output of `list_versions` and `check --deploy` commands over
here. Depending on installation these can be executed in different way, please
consult https://docs.weblate.org/en/latest/admin/management.html for more
details.

```
$ ./manage.py list_versions
 * Weblate weblate-3.8
 * Python 3.7.3
 * Django 2.2.4
 * Celery 4.3.0
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.2.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.4.0
 * translation-finder 1.6
 * Whoosh 2.7.4
 * defusedxml 0.6.0
 * Git 2.20.1
 * Pillow 6.1.0
 * python-dateutil 2.8.0
 * lxml 4.4.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.3
 * djangorestframework 3.10.2
 * user-agents 2.0
 * jellyfish 0.7.2
 * diff-match-patch 20181111
 * ruamel.yaml 0.15.97
 * Database backends: django.db.backends.mysql, django.db.backends.postgresql
 * Cache backends: default:RedisCache
 * Email setup: django.core.mail.backends.dummy.EmailBackend:
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.19.0-6-amd64 (x86_64)

$ ./manage.py check --deploy
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.8/admin/install.html#collecting-errors

System check identified 2 issues (1 silenced).
```
(Note, the silenced check is `admin.E408`)

**Additional context**
This is still on Weblate 3.8, because I wanted to do this _before_ upgrading (even though 3.9 should still support MySQL as-is). I can upgrade _first_ if this should have been fixed already; but I'd rather not spend unnecessary time on attempting this if it still has issues.

**Comment by Bachstelze** [comment]
It seems that there is missing a column in the model. Did you try `./manage.py makemigrations` before the migtation?

**Comment by BhaaLseN** [comment]
No, but:
```
$ ./manage.py makemigrations
No changes detected
```

**Comment by Bachstelze** [comment]
Did you update your production MySQL database?
`manage.py migrate --settings=settings.production`

**Comment by BhaaLseN** [comment]
I'm not sure what that has to do with the initial creation of the PostgreSQL DB. The production MySQL setup works just fine, but creating a new DB from scratch in PostgreSQL does not (at least thats my understanding of what `migrate` followed by `flushsql` is supposed to do in those two steps).

However, your question gave me an idea. Turns out that running `migrate` on an empty MySQL database doesn't work either. It looks like the migration scripts are broken at this point and don't allow a fresh installation at all.

I'll be updating the issue title in a bit to reflect that.

**Comment by nijel** [comment]
The migrations are tested in our CI for every commit, so they can't be generally broken without noticing. 

It however looks like it's trying to execute the code which is supposed to run on PostgreSQL on the MySQL database, what fails, because the field is later removed in one of later migrations. It doesn't matter whether it's PostgreSQL or MySQL, the problem is that migrations code which is expecting past state of tables is executed on current database.

Looking at the problematic migration I don't see anything wrong there:

https://github.com/WeblateOrg/weblate/blob/2a8e8f04f1ebdeffc7520c589dd8706c8d71ce86/weblate/accounts/migrations/0004_create_profile.py#L12

**Comment by nijel** [comment]
I think https://github.com/WeblateOrg/weblate/pull/3130 should address this, it would be great if you can verify it does fix the bug for you. I still wonder why it worked for me while testing this migration.

**Comment by BhaaLseN** [comment]
I'm just trying to follow the [steps from the docs](https://docs.weblate.org/en/latest/admin/install.html#create-empty-tables-in-the-postgresql), since I'm not really too knowledgeable about PostgreSQL at all.

I just tried removing the two configurations and just set PostgreSQL as default; now it worked.

**Comment by BhaaLseN** [comment]
#3130 seems to help (Note that I cherry-picked the commit onto 3.8 and ignored the 3 newest migrations), `migrate` finishes without errors 👍

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).
