### ISSUE TITLE
Redis SSL error for ssl_cert_reqs settings in use with rediss://

### ISSUE THREAD

**Issue by rhofer** [WeblateOrg/weblate#3146]
**Describe the bug**
- External redis instance with SSL enabled is set-up
- Weblate docker image from hub.docker.com, tag: 3.9-1 instantiated and connected, params:
  - REDIS_TLS : true
  - REDIS_VERIFY_SSL : false
  - REDIS_PASSWORD : is set

Results in the following start-up error:

```
Starting...
--
  | whoami: cannot find name for user ID 1000770000
  | Postgres is up
  | Operations to perform:
  | Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, fonts, gitexport, lang, memory, screenshots, sessions, sites, social_django, trans, weblate_auth, wladmin
  | Running migrations:
  | No migrations to apply.
  | Removing corrupted schedule file: ValueError('\nA rediss:// URL must have parameter ssl_cert_reqs and this must be set to CERT_REQUIRED, CERT_OPTIONAL, or CERT_NONE\n')
  | ERROR Handled exception: ValueError:
  | A rediss:// URL must have parameter ssl_cert_reqs and this must be set to CERT_REQUIRED, CERT_OPTIONAL, or CERT_NONE
  |  
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.7/dist-packages/kombu/utils/objects.py", line 42, in __get__
  | return obj.__dict__[self.__name__]
  | KeyError: 'backend'
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/usr/local/lib/python3.7/dist-packages/weblate/utils/management/commands/cleanup_celery.py", line 46, in handle
  | self.setup_schedule()
  | File "/usr/local/lib/python3.7/dist-packages/weblate/utils/management/commands/cleanup_celery.py", line 41, in setup_schedule
  | scheduler = service.get_scheduler()
  | File "/usr/local/lib/python3.7/dist-packages/celery/beat.py", line 627, in get_scheduler
  | lazy=lazy,
  | File "/usr/local/lib/python3.7/dist-packages/celery/beat.py", line 467, in __init__
  | Scheduler.__init__(self, *args, **kwargs)
  | File "/usr/local/lib/python3.7/dist-packages/celery/beat.py", line 226, in __init__
  | self.setup_schedule()
  | File "/usr/local/lib/python3.7/dist-packages/celery/beat.py", line 511, in setup_schedule
  | self.install_default_entries(self.schedule)
  | File "/usr/local/lib/python3.7/dist-packages/celery/beat.py", line 231, in install_default_entries
  | not self.app.backend.supports_autoexpire:
  | File "/usr/local/lib/python3.7/dist-packages/kombu/utils/objects.py", line 44, in __get__
  | value = obj.__dict__[self.__name__] = self.__get(obj)
  | File "/usr/local/lib/python3.7/dist-packages/celery/app/base.py", line 1207, in backend
  | return self._get_backend()
  | File "/usr/local/lib/python3.7/dist-packages/celery/app/base.py", line 926, in _get_backend
  | return backend(app=self, url=url)
  | File "/usr/local/lib/python3.7/dist-packages/celery/backends/redis.py", line 219, in __init__
  | raise ValueError(E_REDIS_SSL_CERT_REQS_MISSING_INVALID)
  | ValueError:
  | A rediss:// URL must have parameter ssl_cert_reqs and this must be set to CERT_REQUIRED, CERT_OPTIONAL, or CERT_NONE
```

Could this be related to missing or wrong settings in e.g. `settings_docker.py`, where REDIS_VERIFY_SSL is treated?

```
if not get_env_bool("REDIS_VERIFY_SSL", True):
    CACHES["default"]["OPTIONS"]["CONNECTION_POOL_KWARGS"]["ssl_cert_reqs"] = None
```

**Comment by nijel** [comment]
That one is correct, but SSL is not properly set for celery later.

**Comment by rhofer** [comment]
Will this fix be available early in an docker image "edge" build, or only when 3.10 is released? (Would appreciate to get it early for testing.)

**Comment by rhofer** [comment]
Just tested with docker image 3.9.1-1 and connected to AWS redis instance with in-transit encryption. Works fine! @nijel many thanks for the fix.
