### ISSUE TITLE
Wrong dependency to redis-py when upgrading Weblate 3.8 -> 3.9.1

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#3188]
**Describe the bug**
I upgraded Weblate 3.8 to 3.9.1 on a Debian 9 (Stretch) server, our install of Weblate is done with pip and we are still using python2.7.
I performed the upgrade of Weblate using `pip install --upgrade weblate` and it works without any issue: no weird warning or anything.
After having performed the other commands for the upgrade (migrate, collectstatic, etc), I tried the usual `check --deploy` but I then obtained the following error (fullstack available below if needed):
> kombu.exceptions.VersionMismatch: Redis transport requires redis-py versions 3.2.0 or later. You have 2.10.6

I have been able to fix the problem by manually calling: `pip install --upgrade redis` which installed the version 3.3.11 on my server, but I expect it to be done directly by the weblate upgrade.

Not sure how to reproduce the issue easily.

**Additional context**
Note that I didn't get the issue when preparing the upgrade on my personal machine (ArchLinux): on both machines I'm using virtualenv, but I don't have the same versions of python apparently.

So, here's the configuration of the machine where I got the problem:
  - Debian 9 (Stretch)
  - Redis server installed through the packages (version (3:3.2.6-3+deb9u3))
  - Weblate installed via pip under virtualenv
  - Python 2.7.9 in the venv
  - Pip 18.1 in the venv

Here's the config of my machine where I did not had the issue:
  - ArchLinux
  - Redis server installed through pacman (version redis-5.0.6-1)
  - Weblate installed via pip under virtualenv
  - Python 2.7.17 in the venv
  - pip 18.1 in the venv

Here's the full stacktrace I get first time I called `check --deploy`:
```
(weblate)weblate@weblate-prod:~$ weblate check --deploy
Traceback (most recent call last):
  File "/home/weblate/weblate/bin/weblate", line 11, in <module>
    load_entry_point('Weblate==3.9.1', 'console_scripts', 'weblate')()
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/weblate/runner.py", line 34, in main
    execute_from_command_line(argv)
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/django/core/management/commands/check.py", line 68, in handle
    fail_level=getattr(checks, options['fail_level']),
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/weblate/utils/checks.py", line 86, in check_celery
    stats = get_queue_stats()
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/weblate/utils/celery.py", line 73, in get_queue_stats
    return {queue: get_queue_length(queue) for queue in get_queue_list()}
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/weblate/utils/celery.py", line 73, in <dictcomp>
    return {queue: get_queue_length(queue) for queue in get_queue_list()}
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/weblate/utils/celery.py", line 57, in get_queue_length
    return conn.default_channel.queue_declare(
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/kombu/connection.py", line 866, in default_channel
    self.ensure_connection(**conn_opts)
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/kombu/connection.py", line 430, in ensure_connection
    callback, timeout=timeout)
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/kombu/utils/functional.py", line 343, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/kombu/connection.py", line 283, in connect
    return self.connection
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/kombu/connection.py", line 837, in connection
    self._connection = self._establish_connection()
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/kombu/connection.py", line 792, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 941, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 923, in create_channel
    channel = self.Channel(connection)
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 493, in __init__
    self.Client = self._get_client()
  File "/home/weblate/weblate/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 1006, in _get_client
    'You have {0.__version__}'.format(redis))
kombu.exceptions.VersionMismatch: Redis transport requires redis-py versions 3.2.0 or later. You have 2.10.6
```

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see a problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by surli** [comment]
That was fast :+1:
