### ISSUE TITLE
TypeError: 'Flags' object is not iterable

### ISSUE THREAD

**Issue by lmwattebled** [WeblateOrg/weblate#3217]
Hi, 

I have just upgraded to weblate 3.9.1 (upgraded via docker-compose pull).
When trying to save a translation string, I am getting this error:

```
uwsgi stderr | ERROR Internal Server Error: /translate/mypocket/mypocket-app/fr/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/views/edit.py", line 450, in translate
    request, translation, this_unit_url, next_unit_url
  File "/usr/local/lib/python3.7/dist-packages/weblate/utils/ratelimit.py", line 119, in rate_wrap
    return function(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/views/edit.py", line 268, in handle_translate
    go_next = perform_translation(unit, form, request)
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/views/edit.py", line 210, in perform_translation
    saved = unit.translate(request.user, new_target, form.cleaned_data['state'])
  File "/usr/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/unit.py", line 867, in translate
    user, change_action=change_action, propagate=propagate
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/unit.py", line 547, in save_backend
    self.save()
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/unit.py", line 658, in save
    self.run_checks(same_state, same_content)
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/unit.py", line 755, in run_checks
    if check_obj.check_target(src, tgt, self):
  File "/usr/local/lib/python3.7/dist-packages/weblate/checks/base.py", line 70, in check_target
    return self.check_target_unit(sources, targets, unit)
  File "/usr/local/lib/python3.7/dist-packages/weblate/checks/base.py", line 79, in check_target_unit
    if self.check_single(sources[0], targets[0], unit):
  File "/home/weblate/customized_checks/ignore_empty_strings/checks.py", line 22, in check_single
    print('[%s]' % ', '.join(map(str, unit.all_flags)))
TypeError: 'Flags' object is not iterable

```

**Comment by lmwattebled** [comment]
Sorry, it was due to my customization indeed.
Thanks for your job!

**Comment by nijel** [comment]
On the other side, there is no good reason why this should not be iterable, done in 429051780f.
