### ISSUE TITLE
Running specific test from master

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#3300]
**Describe the bug**
The documentation from https://docs.weblate.org/en/weblate-3.9.1/contributing.html specifies that we can use: 
> DJANGO_SETTINGS_MODULE=weblate.settings_test ./manage.py test weblate.gitexport

to run some tests individually.
However it looks like it's not working from some tests? In my case I'm trying to run the PropertiesFormatTest and I keep getting the following:
> OperationalError: Problem installing fixtures: no such table: trans_component__old

Using: 
```
[urli@vivat weblate]$ DJANGO_SETTINGS_MODULE=weblate.settings_test ./manage.py test weblate.formats.tests.test_formats.PropertiesFormatTest
```

I tried to run `DJANGO_SETTINGS_MODULE=weblate.settings_test ./manage.py migrate` just in case but apparently I still get an issue.
Is there some interdependency between the tests?

For information, I'm using latest version from master with python 2.7 right now.

Sorry to bother your with that, it's not exactly a bug, but it prevents me from working properly on #3187.

**Comment by nijel** [comment]
This is Django incompatibility with older sqlite libraries. Either switch to older Django or upgrade sqlite or test against postgresq.

**Comment by nijel** [comment]
See  https://code.djangoproject.com/ticket/29182

**Comment by surli** [comment]
Thanks for the info.
For info I tried to switch to Python3 again to see if it changes something, but apparently I'm not able to run anything with it: I'm keep getting the following stacktrace:
```
File "/home/urli/Github/weblate/weblate/vcs/base.py", line 316, in is_supported
    if cls.req_version is None or LooseVersion(version) >= LooseVersion(
  File "/usr/lib64/python3.8/distutils/version.py", line 70, in __ge__
    c = self._cmp(other)
  File "/usr/lib64/python3.8/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
```
Using python 3.8.0.

Now re the original issue, I have locally sqlite 3.30.1 installed. I guess I'll try to switch back to python2 and downgrade Django.

**Comment by nijel** [comment]
Sorry for confusion, it's actually other way - you need newer Django once you have newer SQLite. See https://code.djangoproject.com/ticket/29182 for more details

**Comment by surli** [comment]
Sorry to bother you with that but I'm actually a bit stuck.
From what I see on https://code.djangoproject.com/ticket/29182 the fix has not been backported on Django 1.11, which means I cannot use Python2.7 at all for running the tests.

And now when using Python3.8 as mentioned above I keep getting the following error, which does not look related to Django (but I might be wrong there):
```
File "/home/urli/Github/weblate/weblate/vcs/base.py", line 316, in is_supported
    if cls.req_version is None or LooseVersion(version) >= LooseVersion(
  File "/usr/lib64/python3.8/distutils/version.py", line 70, in __ge__
    c = self._cmp(other)
  File "/usr/lib64/python3.8/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
```

Looks like I should have been a bit more careful before upgrading to Python 3.8 :) I guess last option would be to use a docker container with Python 3.7 for running the tests.

**Comment by nijel** [comment]
Don't waste time with Python 2.7. Python 3.8 should just work, our CI tests that. This must be some different issue. Do you know in which VCS this happens? Most likely it reports something different than expected as version, check git, hub, lab, git-svn and mercurial versions.

**Comment by surli** [comment]
> Python 3.8 should just work, our CI tests that

Good to know :)

So here's my reproduction steps:
  - Git clone 
  - virtualenv with python 3.8
  - `pip install -r requirements.txt`
  - `pip install -r requirements-test.txt`
  - `DJANGO_SETTINGS_MODULE=weblate.settings_test ./manage.py test weblate.formats.tests.test_formats.PropertiesFormatTest`

Here's the full stack:
```
(weblate) [urli@vivat weblate]$ DJANGO_SETTINGS_MODULE=weblate.settings_test ./manage.py test weblate.formats.tests.test_formats.PropertiesFormatTest
Handled exception: TypeError: '<' not supported between instances of 'str' and 'int'
Traceback (most recent call last):
  File "./manage.py", line 33, in <module>
    main()
  File "/tmp/weblate/weblate/runner.py", line 34, in main
    execute_from_command_line(argv)
  File "/tmp/weblate/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/tmp/weblate/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/tmp/weblate/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/tmp/weblate/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/tmp/weblate/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/tmp/weblate/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tmp/weblate/weblate/addons/models.py", line 47, in <module>
    from weblate.trans.models import Component, Unit
  File "/tmp/weblate/weblate/trans/models/__init__.py", line 35, in <module>
    from weblate.trans.models.component import Component
  File "/tmp/weblate/weblate/trans/models/component.py", line 160, in <module>
    class Component(models.Model, URLMixin, PathMixin):
  File "/tmp/weblate/weblate/trans/models/component.py", line 185, in Component
    choices=VCS_REGISTRY.get_choices(),
  File "/tmp/weblate/weblate/utils/classloader.py", line 110, in get_choices
    for x in sorted(self)
  File "/tmp/weblate/weblate/utils/classloader.py", line 96, in __iter__
    return self.data.__iter__()
  File "/tmp/weblate/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tmp/weblate/weblate/utils/classloader.py", line 75, in data
    return self.load_data()
  File "/tmp/weblate/weblate/vcs/models.py", line 36, in load_data
    if not vcs.is_supported():
  File "/tmp/weblate/weblate/vcs/base.py", line 316, in is_supported
    if cls.req_version is None or LooseVersion(version) >= LooseVersion(
  File "/usr/lib64/python3.8/distutils/version.py", line 70, in __ge__
    c = self._cmp(other)
  File "/usr/lib64/python3.8/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
```

I'll try to debug to see when exactly it fails.

Here's the version I have locally:
```
(weblate) [urli@vivat weblate]$ git --version
git version 2.24.1
(weblate) [urli@vivat weblate]$ hub --version
git version 2.24.1
hub version 2.13.0
(weblate) [urli@vivat weblate]$ hg --version
Mercurial Distributed SCM (version 5.2)
```

**Comment by nijel** [comment]
You can invoke the methods directly to see which of them is failing,

```
python -c 'from weblate.vcs.git import GitRepository; print(GitRepository.is_supported()); print(GitRepository.get_version())'
```

And similarly for other classes.

**Comment by surli** [comment]
Looks like the import is failing immediately:
```
>>> from weblate.vcs.git import GitRepository
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/weblate/weblate/__init__.py", line 49, in <module>
    GIT_VERSION = GIT_REPO.describe()
  File "/tmp/weblate/weblate/vcs/git.py", line 298, in describe
    return self.execute(
  File "/tmp/weblate/weblate/vcs/base.py", line 182, in execute
    self.last_output = self._popen(
  File "/tmp/weblate/weblate/vcs/base.py", line 166, in _popen
    cls.add_breadcrumb(
  File "/tmp/weblate/weblate/vcs/base.py", line 105, in add_breadcrumb
    if getattr(settings, 'SENTRY_DSN', None):
  File "/tmp/weblate/lib/python3.8/site-packages/django/conf/__init__.py", line 76, in __getattr__
    self._setup(name)
  File "/tmp/weblate/lib/python3.8/site-packages/django/conf/__init__.py", line 63, in _setup
    self._wrapped = Settings(settings_module)
  File "/tmp/weblate/lib/python3.8/site-packages/django/conf/__init__.py", line 142, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/tmp/weblate/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'weblate.settings'
```

**Comment by surli** [comment]
So, looks like it's related to svn:
```
>>> print(SubversionRepository.is_supported())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/weblate/weblate/vcs/base.py", line 316, in is_supported
    if cls.req_version is None or LooseVersion(version) >= LooseVersion(
  File "/usr/lib64/python3.8/distutils/version.py", line 70, in __ge__
    c = self._cmp(other)
  File "/usr/lib64/python3.8/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'
>>> 
>>> print(SubversionRepository.get_version())
Setting
```

Now locally in command line I have the following:
```
(weblate) [urli@vivat weblate]$ svn --version
svn, version 1.13.0 (r1867053)
   compiled Nov 15 2019, 18:49:41 on x86_64-pc-linux-gnu
```

**Comment by nijel** [comment]
The more important is `git svn --version`

**Comment by surli** [comment]
Here it is: 
```
(weblate) [urli@vivat weblate]$ git svn --version
git-svn version 2.24.1 (svn 1.13.0)
```

I don't see where "Setting" is coming from.

**Comment by nijel** [comment]
You can debug that further here:

https://github.com/WeblateOrg/weblate/blob/a614b0aa56c59785710ea629bdb0fef3339f509b/weblate/vcs/git.py#L404-L407

Anyway I've just changed the code to avoid crash in such case.

**Comment by surli** [comment]
Yeah I saw it, trying to enable debugger to see the actual command sent to get the version, but apparently I'm doing it wrong:
```
>>> logging.getLogger('weblate.vcs').setLevel(logging.DEBUG)
>>> print(SubversionRepository.get_version())
Setting
```

**Comment by nijel** [comment]
Probably logging is not configured to print to console

**Comment by surli** [comment]
So I enabled the logs and printed the full output it got before splitting it, and here's the result:
```
>>> print(SubversionRepository.get_version())
git: exec git svn --version [retcode=0]
git: perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "C.UTF-8",
	LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
git-svn version 2.24.1 (svn 1.13.0)

```

**Comment by surli** [comment]
Thanks for fixing this! I'm indeed finally able to use Python3.8 properly :)
