### ISSUE TITLE
HTTP 405 on logout and ignoring checks

### ISSUE THREAD

**Issue by pleonex** [WeblateOrg/weblate#3338]
**Describe the bug**
After migrating from 3.8 to 3.10 (deployed with Docker), we are getting HTTP 405 _Method Not Allowed_ when we try to ignore a check or log out. We tried from different browsers and from private mode.

**To Reproduce**

1. Click in the `Dismiss` button to ignore a check.
2. The browser tries to navigate to `https://<server>/js/ignore-check/337884/`
3. Server returns HTTP 405 without content in the response (blank page).

The same happens trying to logout. In that case with the address: `https://<server>/accounts/logout/`.

No error is reported in the logs of the server and the operation does not succeed (user is not logged out and checks are not ignored).

**Expected behavior**
We can ignore checks and logout, or at least receive an error explaining the reason why is not allowed.

**Server configuration and status**
* list_versions
```
 * Weblate: 3.10
 * Django: 2.2.8
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.4.0
 * lxml: 4.3.2
 * Pillow: 6.2.1
 * bleach: 3.1.0
 * six: 1.13.0
 * python-dateutil: 2.8.1
 * social-auth-core: 3.2.0
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.8.1
 * oauthlib: 3.1.0
 * django-compressor: 2.3
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.3
 * user-agents: 2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.1
 * celery: 4.3.0
 * kombu: 4.6.3
 * celery-batches: 0.2
 * translation-finder: 1.7
 * html2text: 2019.9.26
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.22.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.13.5
 * Cython: 0.29.14
 * misaka: 2.1.1
 * GitPython: 3.0.5
 * borgbackup: 1.1.10
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.7.7
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.5
 * tesserocr: 2.5.0
 * akismet: 1.0.1
 * boto3: 1.10.44
 * zeep: 3.4.0
 * aeidon: 1.6.0
 * Mercurial: 4.8.2
 * git-svn: 2.20.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.sendgrid.net
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 3.10.0-1062.9.1.el7.x86_64 (x86_64)
```

* check --deploy
```
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.

INFOS:
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.10/admin/backup.html

System check identified 2 issues (1 silenced).
```

**Comment by nijel** [comment]
Do you have javascript disabled? These requests should be done by POST, but the related script doesn't seem to be used in your case.

**Comment by pleonex** [comment]
JS is enabled. I tried from the PC and mobile and different people tried too with the same results. I restarted with debug enabled and I saw this error at the beginning:
```plain
weblate_1       | pyrollbar: No access_token provided. Please configure by calling rollbar.init() with your access token.
weblate_1       | ERROR Handled exception: BusyLoadingError: Redis is loading the dataset in memory
weblate_1       | Traceback (most recent call last):
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/django_redis/cache.py", line 32, in _decorator
weblate_1       |     return method(self, *args, **kwargs)
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/django_redis/cache.py", line 81, in get
weblate_1       |     client=client)
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/django_redis/client/default.py", line 201, in get
weblate_1       |     raise ConnectionInterrupted(connection=client, parent=e)
weblate_1       | django_redis.exceptions.ConnectionInterrupted: Redis BusyLoadingError: Redis is loading the dataset in memory
weblate_1       |
weblate_1       | During handling of the above exception, another exception occurred:
weblate_1       |
weblate_1       | Traceback (most recent call last):
weblate_1       |   File "/usr/local/bin/weblate", line 11, in <module>
weblate_1       |     load_entry_point('Weblate==3.10', 'console_scripts', 'weblate')()
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/weblate/runner.py", line 34, in main
weblate_1       |     execute_from_command_line(argv)
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_li
ne
weblate_1       |     utility.execute()
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 357, in execute
weblate_1       |     django.setup()
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/django/__init__.py", line 24, in setup
weblate_1       |     apps.populate(settings.INSTALLED_APPS)
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/django/apps/registry.py", line 114, in populate
weblate_1       |     app_config.import_models()
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/django/apps/config.py", line 211, in import_models
weblate_1       |     self.models_module = import_module(models_module_name)
weblate_1       |   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
weblate_1       |     return _bootstrap._gcd_import(name[level:], package, level)
weblate_1       |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
weblate_1       |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
weblate_1       |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
weblate_1       |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
weblate_1       |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
weblate_1       |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/weblate/addons/models.py", line 47, in <module>
weblate_1       |     from weblate.trans.models import Component, Unit
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/__init__.py", line 35, in <module>
weblate_1       |     from weblate.trans.models.component import Component
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/component.py", line 160, in <module>
weblate_1       |     class Component(models.Model, URLMixin, PathMixin):
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/component.py", line 185, in Component
weblate_1       |     choices=VCS_REGISTRY.get_choices(),
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/weblate/utils/classloader.py", line 110, in get_choices
weblate_1       |     for x in sorted(self)
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/weblate/utils/classloader.py", line 96, in __iter__
weblate_1       |     return self.data.__iter__()
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py", line 80, in __get__
weblate_1       |     res = instance.__dict__[self.name] = self.func(instance)
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/weblate/utils/classloader.py", line 75, in data
weblate_1       |     return self.load_data()
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/weblate/vcs/models.py", line 36, in load_data
weblate_1       |     if not vcs.is_supported():
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/weblate/vcs/base.py", line 327, in is_supported
weblate_1       |     cls.name, version, cls.req_version, error
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/weblate/trans/util.py", line 141, in add_configuration_error
weblate_1       |     errors = cache.get('configuration-errors', [])
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/django_redis/cache.py", line 39, in _decorator
weblate_1       |     raise e.parent
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/django_redis/client/default.py", line 199, in get
weblate_1       |     value = client.get(key)
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/redis/client.py", line 1332, in get
weblate_1       |     return self.execute_command('GET', name)
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/redis/client.py", line 839, in execute_command
weblate_1       |     return self.parse_response(conn, command_name, **options)
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/redis/client.py", line 853, in parse_response
weblate_1       |     response = connection.read_response()
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/redis/connection.py", line 700, in read_response
weblate_1       |     response = self._parser.read_response()
weblate_1       |   File "/usr/local/lib/python3.7/dist-packages/redis/connection.py", line 471, in read_response
weblate_1       |     raise response
weblate_1       | redis.exceptions.BusyLoadingError: Redis is loading the dataset in memory
weblate_1       | redis is unavailable - waiting 30
```
but later
```
weblate_1       | celery-notify stderr | [2019-12-28 10:46:01,335: INFO/MainProcess] Connected to redis://cache:6379/1
```

Also I see a new warning:
```
weblate_1       | ?: (weblate.E016) Configure cached template loader for better performance
weblate_1       |       HINT: https://docs.weblate.org/en/weblate-3.10/admin/install.html#production-templates
```

Any tip to debug or provide more information?

**Comment by pleonex** [comment]
We are having also other problems like the `Clone source` button in the translation dialog doesn't work, the textbox for the target language is always very small (doesn't resize). I can't reproduce these problems in the weblate hosted by you, so I am wondering if it's a problem related to the Docker upgrade. Maybe some cache files? Some files didn't update?

**Comment by pleonex** [comment]
It seems it was a problem of cache. I deleted the redis file (_appendonly.aof_) from its docker volume and now it is working fine (also we had to delete the cache from our web browsers).
