### ISSUE TITLE
500 errors on WLC with error in get_permissions:  BasePermissionMetaclass' object is not iterable

### ISSUE THREAD

**Issue by AnianZ** [WeblateOrg/weblate#3356]
After the update of my weblate instance to version 3.10 in a docker deployment my integrations with wlc stopped working. I always get a `Error: HTTP error 500: Internal Server Error` and on the server the following log: 
```
uwsgi stderr | ERROR Internal Server Error: /api/projects/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 411, in initial
    self.check_permissions(request)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 331, in check_permissions
    for permission in self.get_permissions():
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 278, in get_permissions
    return [permission() for permission in self.permission_classes]
TypeError: 'BasePermissionMetaclass' object is not iterable
```

**To Reproduce**
1. Update docker deployment of weblate to version 3.10 (tried `latest` and `edge` tag)
2. Try to use `wlc list-projects`

**Expected behavior**
List of projects returned

**Server configuration and status**

```
docker-compose exec weblate weblate list_versions
```
```
 * Weblate: 3.10 
 * Django: 2.2.8      
 * siphashc: 1.3   
 * Whoosh: 2.7.4 
 * translate-toolkit: 2.4.0
 * lxml: 4.3.2
 * Pillow: 6.2.2
 * bleach: 3.1.0   
 * six: 1.13.0    
 * python-dateutil: 2.8.1                                                                      
 * social-auth-core: 3.2.0                                                                     
 * social-auth-app-django: 3.1.0                                                               
 * django-crispy-forms: 1.8.1  
 * oauthlib: 3.1.0
 * django-compressor: 2.3
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.3
 * user-agents: 2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.1
 * celery: 4.3.0
 * kombu: 4.6.3
 * celery-batches: 0.2
 * translation-finder: 1.7
 * html2text: 2019.9.26
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.22.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.13.5
 * Cython: 0.29.14
 * misaka: 2.1.1
 * GitPython: 3.0.5
 * borgbackup: 1.1.10
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.7.7
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.5
 * tesserocr: 2.5.0
 * akismet: 1.0.1
 * boto3: 1.10.48
 * zeep: 3.4.0
 * aeidon: 1.6.0
 * Mercurial: 4.8.2
 * git-svn: 2.20.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.office365.com
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.0.0-1028-azure (x86_64)
```

```
docker-compose exec --user weblate weblate weblate check --deploy
```
```
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.10/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.10/admin/backup.html

System check identified 3 issues (1 silenced).
```

**Additional context**
wlc version: `1.2`

I already tried different user accounts, generating a new access tokens and giving the user different permissions. The error also occurs if I use `curl` so it does not seem to be `wlc` specific.

**Comment by AnianZ** [comment]
Awesome :tada: That was a very quick fix. I was able to fix my instance by patching the `settings_docker.py` and mounting it into the container for now. Fixes the problem, my CI is running again. Thanks for the great work.
