### ISSUE TITLE
mangled po file causes celery crash

### ISSUE THREAD

**Issue by stanislav-brabec** [WeblateOrg/weblate#3411]
**Describe the bug**
If git repository gets mangled po files, celery crashes. I have inspected these files, and the most probable source of the crash is a lack of "POT-Creation-Date" in the po file header.

**To Reproduce**
1. Remove POT-Creation-Date from a po file.
2. Commit to git.
3. Wait.
4. See celery error
```
2020-01-14T22:02:15.151802+00:00 weblate weblate[1578]: INFO customer-tool/i18n: updating repository
2020-01-14T22:02:15.152257+00:00 weblate uwsgi[1394]: INFO:weblate:customer-tool/i18n: updating repository
2020-01-14T22:02:16.729739+00:00 weblate weblate[1578]: INFO customer-tool/i18n: update took 1.57 seconds
2020-01-14T22:02:16.730116+00:00 weblate uwsgi[1394]: INFO:weblate:customer-tool/i18n: update took 1.57 seconds
2020-01-14T22:02:16.738650+00:00 weblate weblate[1578]: INFO customer-tool/i18n: resetting to remote repo
2020-01-14T22:02:16.739184+00:00 weblate uwsgi[1394]: INFO:weblate:customer-tool/i18n: resetting to remote repo
2020-01-14T22:02:17.085451+00:00 weblate weblate[1578]: INFO customer-tool/i18n: checking glue/locale/de/glue.po (de) [1/7]
2020-01-14T22:02:17.086020+00:00 weblate uwsgi[1394]: INFO:weblate:customer-tool/i18n: checking glue/locale/de/glue.po (de) [1/7]
2020-01-14T22:02:17.115394+00:00 weblate weblate[1578]: INFO customer-tool/i18n/de: processing glue/locale/de/glue.po, content changed
2020-01-14T22:02:17.115934+00:00 weblate uwsgi[1394]: INFO:weblate:customer-tool/i18n/de: processing glue/locale/de/glue.po, content changed
2020-01-14T22:02:19.227617+00:00 weblate weblate[1578]: ERROR Internal Server Error: /reset/customer-tool/i18n/de/#012Traceback (most recent call last):#012  File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner#012    response = get_response(request)#012  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response#012    response = self.process_exception_by_middleware(e, request)#012  File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response#012    response = wrapped_callback(request, *callback_args, **callback_kwargs)#012  File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view#012    return view_func(request, *args, **kwargs)#012  File "/usr/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner#012    return func(request, *args, **kwargs)#012  File "/usr/share/weblate/weblate/trans/views/git.py", line 237, in reset_translation#012    return perform_reset(request, obj)#012  File "/usr/share/weblate/weblate/trans/views/git.py", line 93, in perform_reset#012    request,#012  File "/usr/share/weblate/weblate/trans/views/git.py", line 37, in execute_locked#012    result = call(*args, **kwargs)#012  File "/usr/share/weblate/weblate/trans/models/translation.py", line 378, in do_reset#012    return self.component.do_reset(request)#012  File "/usr/share/weblate/weblate/trans/models/component.py", line 109, in on_link_wrapper#012    return func(self, *args, **kwargs)#012  File "/usr/share/weblate/weblate/trans/models/component.py", line 902, in do_reset#012    self.create_translations(request=request)#012  File "/usr/share/weblate/weblate/trans/models/component.py", line 1233, in create_translations#012    self, lang, code, path, force, request=request#012  File "/usr/share/weblate/weblate/trans/models/translation.py", line 77, in check_sync#012    translation.check_sync(force, request=request)#012  File "/usr/share/weblate/weblate/trans/models/translation.py", line 331, in check_sync#012    newunit.update_from_unit(unit, pos, is_new)#012  File "/usr/share/weblate/weblate/trans/models/unit.py", line 470, in update_from_unit#012    same_state=same_state,#012  File "/usr/share/weblate/weblate/trans/models/unit.py", line 693, in save#012    super(Unit, self).save(**kwargs)#012  File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 741, in save#012    force_update=force_update, update_fields=update_fields)#012  File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 779, in save_base#012    force_update, using, update_fields,#012  File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 870, in _save_table#012    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)#012  File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 908, in _do_insert#012    using=using, raw=raw)#012  File "/usr/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method#012    return getattr(self.get_queryset(), name)(*args, **kwargs)#012  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert#012    return query.get_compiler(using=using).execute_sql(return_id)#012  File "/usr/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1368, in execute_sql#012    cursor.execute(sql, params)#012  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute#012    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)#012  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers#012    return executor(sql, params, many, context)#012  File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute#012    return self.cursor.execute(sql, params)#012ValueError: A string literal cannot contain NUL (0x00) characters.
2020-01-14T22:02:19.726024+00:00 weblate uwsgi[1394]: ERROR:django.request:Internal Server Error: /reset/customer-tool/i18n/de/
2020-01-14T22:02:19.726320+00:00 weblate uwsgi[1394]: Traceback (most recent call last):
2020-01-14T22:02:19.726551+00:00 weblate uwsgi[1394]:   File "/usr/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
2020-01-14T22:02:19.726766+00:00 weblate uwsgi[1394]:     response = get_response(request)
2020-01-14T22:02:19.726929+00:00 weblate uwsgi[1394]:   File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
2020-01-14T22:02:19.727098+00:00 weblate uwsgi[1394]:     response = self.process_exception_by_middleware(e, request)
2020-01-14T22:02:19.727253+00:00 weblate uwsgi[1394]:   File "/usr/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
2020-01-14T22:02:19.727431+00:00 weblate uwsgi[1394]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2020-01-14T22:02:19.727607+00:00 weblate uwsgi[1394]:   File "/usr/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
2020-01-14T22:02:19.727817+00:00 weblate uwsgi[1394]:     return view_func(request, *args, **kwargs)
2020-01-14T22:02:19.727988+00:00 weblate uwsgi[1394]:   File "/usr/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
2020-01-14T22:02:19.728195+00:00 weblate uwsgi[1394]:     return func(request, *args, **kwargs)
2020-01-14T22:02:19.728358+00:00 weblate uwsgi[1394]:   File "/usr/share/weblate/weblate/trans/views/git.py", line 237, in reset_translation
2020-01-14T22:02:19.728519+00:00 weblate uwsgi[1394]:     return perform_reset(request, obj)
2020-01-14T22:02:19.728677+00:00 weblate uwsgi[1394]:   File "/usr/share/weblate/weblate/trans/views/git.py", line 93, in perform_reset
2020-01-14T22:02:19.728880+00:00 weblate uwsgi[1394]:     request,
2020-01-14T22:02:19.729037+00:00 weblate uwsgi[1394]:   File "/usr/share/weblate/weblate/trans/views/git.py", line 37, in execute_locked
2020-01-14T22:02:19.729192+00:00 weblate uwsgi[1394]:     result = call(*args, **kwargs)
2020-01-14T22:02:19.729395+00:00 weblate uwsgi[1394]:   File "/usr/share/weblate/weblate/trans/models/translation.py", line 378, in do_reset
2020-01-14T22:02:19.729699+00:00 weblate uwsgi[1394]:     return self.component.do_reset(request)
2020-01-14T22:02:19.729978+00:00 weblate uwsgi[1394]:   File "/usr/share/weblate/weblate/trans/models/component.py", line 109, in on_link_wrapper
2020-01-14T22:02:19.730260+00:00 weblate uwsgi[1394]:     return func(self, *args, **kwargs)
2020-01-14T22:02:19.730537+00:00 weblate uwsgi[1394]:   File "/usr/share/weblate/weblate/trans/models/component.py", line 902, in do_reset
2020-01-14T22:02:19.730794+00:00 weblate uwsgi[1394]:     self.create_translations(request=request)
2020-01-14T22:02:19.731046+00:00 weblate uwsgi[1394]:   File "/usr/share/weblate/weblate/trans/models/component.py", line 1233, in create_translations
2020-01-14T22:02:19.731301+00:00 weblate uwsgi[1394]:     self, lang, code, path, force, request=request
2020-01-14T22:02:19.731597+00:00 weblate uwsgi[1394]:   File "/usr/share/weblate/weblate/trans/models/translation.py", line 77, in check_sync
2020-01-14T22:02:19.731863+00:00 weblate uwsgi[1394]:     translation.check_sync(force, request=request)
2020-01-14T22:02:19.732138+00:00 weblate uwsgi[1394]:   File "/usr/share/weblate/weblate/trans/models/translation.py", line 331, in check_sync
2020-01-14T22:02:19.732441+00:00 weblate uwsgi[1394]:     newunit.update_from_unit(unit, pos, is_new)
2020-01-14T22:02:19.732767+00:00 weblate uwsgi[1394]:   File "/usr/share/weblate/weblate/trans/models/unit.py", line 470, in update_from_unit
2020-01-14T22:02:19.733047+00:00 weblate uwsgi[1394]:     same_state=same_state,
2020-01-14T22:02:19.733323+00:00 weblate uwsgi[1394]:   File "/usr/share/weblate/weblate/trans/models/unit.py", line 693, in save
2020-01-14T22:02:19.733584+00:00 weblate uwsgi[1394]:     super(Unit, self).save(**kwargs)
2020-01-14T22:02:19.733828+00:00 weblate uwsgi[1394]:   File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 741, in save
2020-01-14T22:02:19.734069+00:00 weblate uwsgi[1394]:     force_update=force_update, update_fields=update_fields)
2020-01-14T22:02:19.734318+00:00 weblate uwsgi[1394]:   File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
2020-01-14T22:02:19.734576+00:00 weblate uwsgi[1394]:     force_update, using, update_fields,
2020-01-14T22:02:19.734829+00:00 weblate uwsgi[1394]:   File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 870, in _save_table
2020-01-14T22:02:19.735073+00:00 weblate uwsgi[1394]:     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
2020-01-14T22:02:19.735312+00:00 weblate uwsgi[1394]:   File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 908, in _do_insert
2020-01-14T22:02:19.735606+00:00 weblate uwsgi[1394]:     using=using, raw=raw)
2020-01-14T22:02:19.735847+00:00 weblate uwsgi[1394]:   File "/usr/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
2020-01-14T22:02:19.736136+00:00 weblate uwsgi[1394]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
2020-01-14T22:02:19.736385+00:00 weblate uwsgi[1394]:   File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert
2020-01-14T22:02:19.736632+00:00 weblate uwsgi[1394]:     return query.get_compiler(using=using).execute_sql(return_id)
2020-01-14T22:02:19.736917+00:00 weblate uwsgi[1394]:   File "/usr/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1368, in execute_sql
2020-01-14T22:02:19.737369+00:00 weblate uwsgi[1394]:     cursor.execute(sql, params)
2020-01-14T22:02:19.737634+00:00 weblate uwsgi[1394]:   File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
2020-01-14T22:02:19.737917+00:00 weblate uwsgi[1394]:     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
2020-01-14T22:02:19.738187+00:00 weblate uwsgi[1394]:   File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
2020-01-14T22:02:19.738434+00:00 weblate uwsgi[1394]:     return executor(sql, params, many, context)
2020-01-14T22:02:19.738674+00:00 weblate uwsgi[1394]:   File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
2020-01-14T22:02:19.738941+00:00 weblate uwsgi[1394]:     return self.cursor.execute(sql, params)
2020-01-14T22:02:19.739247+00:00 weblate uwsgi[1394]: ValueError: A string literal cannot contain NUL (0x00) characters.
2020-01-14T22:02:19.739516+00:00 weblate uwsgi[1394]: [pid: 1578|app: 0|req: 5955/40682] 192.168.0.1 () {64 vars in 1368 bytes} [Tue Jan 14 22:02:15 2020] POST /reset/customer-tool/i18n/de/ => generated 7924 bytes in 4621 msecs (HTTP/1.1 500) 9 headers in 523 bytes (1 switches on core 0)
```

**Expected behavior**
Either ignore or process broken files.

**Server configuration and status**
Please paste the output of `list_versions` and `check --deploy` commands over
here. Depending on installation these can be executed in different way, please
consult https://docs.weblate.org/en/latest/admin/management.html for more
details.

On Git checkout:

```
./manage.py list_versions
 * Weblate 3.6.1
 * Python 3.6.9
 * Django 2.2.8
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.11.0
 * social-auth-core 3.1.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.3
 * translate-toolkit 2.4.0
 * translation-finder 1.7
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.16.4
 * Pillow 5.0.0
 * python-dateutil 2.7.3
 * lxml 4.0.0
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.0
 * user-agents 1.1.0
 * jellyfish 0.6.1
 * diff-match-patch 20181111
 * pytz 2018.5
 * pyuca 1.2
 * PyYAML 3.13
 * Database backends: django.db.backends.postgresql_psycopg2
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.12.14-lp151.28.36-default (x86_64)
./manage.py check --deploy
System check identified some issues:

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-3.6.1/admin/install.html#collecting-errors

System check identified 1 issue (1 silenced).
```

**Comment by nijel** [comment]
I don't think it's related to the item in the header file. Weblate doesn't import the header at all and only updates it on saving, what didn't happen here.

What is more likely is that you deleted something more and that lead to a syntax error in the file. That was silently ignored by translate-toolkit older than 2.5.0, so you might be hitting this. It was fixed by https://github.com/translate/translate/pull/3912

**Comment by nijel** [comment]
Reply mistakenly posted in https://github.com/translate/translate/pull/3912#issuecomment-579417914: 

> I am not sure what caused the crash, but a new commit fixed it. Differences between these commits:
> 
>     * Fix missing POT-Creation-Date
> 
>     * The original source contains lines like msgstr "Paket^@pakete", where ^@ is a NUL character.
> 
>     * Context comments starting with "#:"
> 
>     * "Language-Team: header is in a single line instead of two physical lines.
> 
> 
> One of these changes fixed the problem. I suspected missing POT-Creation-Date, but NUL msgstr could be the problem source as well.

**Comment by nijel** [comment]
I think it's the NUL char, will try to reproduce this tomorrow.
