### ISSUE TITLE
SysLog config

### ISSUE THREAD

**Issue by freshtranslation** [WeblateOrg/weblate#344]
I trying Weblate for the first time and trying to get the page up. When I run 'python manage.py' I get the following.

I've probably got something very simple wrong, but I can't tell what it is. Any suggestions?

  -h, --help            show this help message and exit
Traceback (most recent call last):
  File "manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/boxen/homebrew/Cellar/python/2.7.3-boxen2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/**init**.py", line 453, in execute_from_command_line
    utility.execute()
  File "/opt/boxen/homebrew/Cellar/python/2.7.3-boxen2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/**init**.py", line 376, in execute
    sys.stdout.write(self.main_help_text() + '\n')
  File "/opt/boxen/homebrew/Cellar/python/2.7.3-boxen2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/**init**.py", line 242, in main_help_text
    for name, app in six.iteritems(get_commands()):
  File "/opt/boxen/homebrew/Cellar/python/2.7.3-boxen2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/**init**.py", line 109, in get_commands
    apps = settings.INSTALLED_APPS
  File "/opt/boxen/homebrew/Cellar/python/2.7.3-boxen2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/conf/**init**.py", line 53, in **getattr**
    self._setup(name)
  File "/opt/boxen/homebrew/Cellar/python/2.7.3-boxen2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/conf/__init__.py", line 49, in _setup
    self._configure_logging()
  File "/opt/boxen/homebrew/Cellar/python/2.7.3-boxen2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/conf/__init__.py", line 84, in _configure_logging
    logging_config_func(self.LOGGING)
  File "/opt/boxen/homebrew/Cellar/python/2.7.3-boxen2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/config.py", line 777, in dictConfig
    dictConfigClass(config).configure()
  File "/opt/boxen/homebrew/Cellar/python/2.7.3-boxen2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/config.py", line 575, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'syslog': [Errno 2] No such file or directory

**Comment by ppawel** [comment]
This still happens when `/dev/log` is not present - even if I set `DEFAULT_LOG` to `console`.

**Comment by nijel** [comment]
Does it happen after ad64bef958e6216ba6df263c546c55ce3508d870 as well?
