### ISSUE TITLE
Delete and revert of upstream branch causes component to be unusable

### ISSUE THREAD

**Issue by ionmincu** [WeblateOrg/weblate#3443]
**Describe the bug**
Delete upstream branch then restore it will cause the component to be "unusable".

**To Reproduce**
1. Delete upstream branch of a component
2. Go to the component, in the logs you will see:
```
weblate.vcs.base.RepositoryException: fatal: ambiguous argument '@{upstream}': unknown revision or path not in the working tree.
```
3. Restore deleted branch on upstream
4. Go to the component
5. Same error:

**Full Error:**
```
celery-main stderr | [2020-02-03 09:01:29,989: INFO/MainProcess] Received task: weblate.utils.tasks.heartbeat[c1c419aa-da0a-4a6d-ae33-f93d3251244c]
uwsgi stderr | ERROR Internal Server Error: /projects/<some_project>/<some_compnent>/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/views/basic.py", line 218, in show_component
    'alerts': obj.all_alerts,
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/util.py", line 268, in render
    return django_render(request, template, context, status=status)
  File "/usr/local/lib/python3.7/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.7/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/loader_tags.py", line 188, in render
    return template.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/defaulttags.py", line 309, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/defaulttags.py", line 511, in render
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/usr/local/lib/python3.7/dist-packages/django/template/defaulttags.py", line 511, in <dictcomp>
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 670, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 795, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 857, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/component.py", line 683, in get_last_remote_commit
    return self.repository.get_revision_info(self.repository.last_remote_revision)
  File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/dist-packages/weblate/vcs/base.py", line 216, in last_remote_revision
    self._cmd_last_remote_revision, needs_lock=False, merge_err=False
  File "/usr/local/lib/python3.7/dist-packages/weblate/vcs/base.py", line 183, in execute
    args, self.path, fullcmd=fullcmd, local=self.local, merge_err=merge_err
  File "/usr/local/lib/python3.7/dist-packages/weblate/vcs/base.py", line 173, in _popen
    raise RepositoryException(retcode, output)
weblate.vcs.base.RepositoryException: fatal: ambiguous argument '@{upstream}': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
 (128)
```

**Expected behavior**
I expected the component to be usable again, or at least to have a `fetch` button available that will update the repository to make it working again.

**Additional context**
If i go to `http://weblate/settings/<some_project>/<some_component>/#vcs` edit the upstream branch to be someting that does not exist and click save it will cause `git` to `fetch` and get upstream branch working again.

**Versions**
- Weblate 3.10.1 (docker)

**Comment by ionmincu** [comment]
@nijel bug is still present on 4.0.1

```
wsgi stderr | ERROR Internal Server Error: /js/git/<project>/<component>/
raceback (most recent call last):
 File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
   response = get_response(request)
 File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 115, in _get_response
   response = self.process_exception_by_middleware(e, request)
 File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 113, in _get_response
   response = wrapped_callback(request, *callback_args, **callback_kwargs)
 File "/usr/local/lib/python3.7/dist-packages/weblate/trans/views/js.py", line 207, in git_status_component
   "component": obj,
 File "/usr/local/lib/python3.7/dist-packages/django/shortcuts.py", line 19, in render
   content = loader.render_to_string(template_name, context, request, using=using)
 File "/usr/local/lib/python3.7/dist-packages/django/template/loader.py", line 62, in render_to_string
   return template.render(context, request)
 File "/usr/local/lib/python3.7/dist-packages/django/template/backends/django.py", line 61, in render
   return self.template.render(context)
 File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 171, in render
   return self._render(context)
 File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 163, in _render
   return self.nodelist.render(context)
 File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 936, in render
   bit = node.render_annotated(context)
 File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 903, in render_annotated
   return self.render(context)
 File "/usr/local/lib/python3.7/dist-packages/django/template/defaulttags.py", line 513, in render
   return self.nodelist.render(context)
 File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 936, in render
   bit = node.render_annotated(context)
 File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 903, in render_annotated
   return self.render(context)
 File "/usr/local/lib/python3.7/dist-packages/django/template/defaulttags.py", line 309, in render
   return nodelist.render(context)
 File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 936, in render
   bit = node.render_annotated(context)
 File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 903, in render_annotated
   return self.render(context)
 File "/usr/local/lib/python3.7/dist-packages/django/template/defaulttags.py", line 302, in render
   match = condition.eval(context)
 File "/usr/local/lib/python3.7/dist-packages/django/template/defaulttags.py", line 876, in eval
   return self.value.resolve(context, ignore_failures=True)
 File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 670, in resolve
   obj = self.var.resolve(context)
 File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 795, in resolve
   value = self._resolve_lookup(context)
 File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 857, in _resolve_lookup
   current = current()
 File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/component.py", line 2024, in repo_needs_merge
   return self.repository.needs_merge()
 File "/usr/local/lib/python3.7/dist-packages/weblate/vcs/base.py", line 294, in needs_merge
   return self.count_missing() > 0
 File "/usr/local/lib/python3.7/dist-packages/weblate/vcs/base.py", line 278, in count_missing
   self.log_revisions(self.ref_to_remote.format(self.get_remote_branch_name()))
```

**Comment by nijel** [comment]
Strictly speaking, it is a different bug, but indeed related.
