### ISSUE TITLE
The --settings parameter on command line does not work

### ISSUE THREAD

**Issue by scarabeusiv** [WeblateOrg/weblate#3489]
When building the package from 3.10.0 onwards this tests (and others using static assets) seem to fail.

```
[ 1221s] ======================================================================
[ 1221s] ERROR: test_digest (weblate.accounts.tests.test_notifications.NotificationTest)
[ 1221s] ----------------------------------------------------------------------
[ 1221s] Traceback (most recent call last):
[ 1221s]   File "/home/abuild/rpmbuild/BUILD/Weblate-3.10.3/weblate/accounts/tests/test_notifications.py", line 327, in test_digest
[ 1221s]     notify()
[ 1221s]   File "/usr/lib/python3.7/site-packages/celery/local.py", line 191, in __call__
[ 1221s]     return self._get_current_object()(*a, **kw)
[ 1221s]   File "/usr/lib/python3.7/site-packages/celery/app/task.py", line 392, in __call__
[ 1221s]     return self.run(*args, **kwargs)
[ 1221s]   File "/home/abuild/rpmbuild/BUILD/Weblate-3.10.3/weblate/accounts/tasks.py", line 95, in notify_daily
[ 1221s]     notify_digest('notify_daily')
[ 1221s]   File "/home/abuild/rpmbuild/BUILD/Weblate-3.10.3/weblate/accounts/tasks.py", line 90, in notify_digest
[ 1221s]     send_mails.delay(outgoing)
[ 1221s]   File "/usr/lib/python3.7/site-packages/celery/app/task.py", line 425, in delay
[ 1221s]     return self.apply_async(args, kwargs)
[ 1221s]   File "/usr/lib/python3.7/site-packages/celery/app/task.py", line 562, in apply_async
[ 1221s]     link=link, link_error=link_error, **options)
[ 1221s]   File "/usr/lib/python3.7/site-packages/celery/app/task.py", line 775, in apply
[ 1221s]     ret = tracer(task_id, args, kwargs, request)
[ 1221s]   File "/usr/lib/python3.7/site-packages/celery/app/trace.py", line 399, in trace_task
[ 1221s]     I, R, state, retval = on_error(task_request, exc, uuid)
[ 1221s]   File "/usr/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
[ 1221s]     R = retval = fun(*args, **kwargs)
[ 1221s]   File "/home/abuild/rpmbuild/BUILD/Weblate-3.10.3/weblate/accounts/tasks.py", line 134, in send_mails
[ 1221s]     with open(filename, 'rb') as handle:
[ 1221s] FileNotFoundError: [Errno 2] No such file or directory: '/home/abuild/rpmbuild/BUILD/Weblate-3.10.3/data-test/static/email-logo.png'
```

I suppose the same culprit is cause for following test failure:
```
[ 1221s] ERROR: test_site_og (weblate.trans.tests.test_widgets.WidgetsTest)
[ 1221s] ----------------------------------------------------------------------
[ 1221s] Traceback (most recent call last):
[ 1221s]   File "/home/abuild/rpmbuild/BUILD/Weblate-3.10.3/weblate/trans/tests/test_widgets.py", line 59, in test_site_og
[ 1221s]     response = self.client.get(reverse('og-image'))
[ 1221s]   File "/usr/lib/python3.7/site-packages/django/test/client.py", line 535, in get
[ 1221s]     response = super().get(path, data=data, secure=secure, **extra)
[ 1221s]   File "/usr/lib/python3.7/site-packages/django/test/client.py", line 347, in get
[ 1221s]     **extra,
[ 1221s]   File "/usr/lib/python3.7/site-packages/django/test/client.py", line 422, in generic
[ 1221s]     return self.request(**r)
[ 1221s]   File "/usr/lib/python3.7/site-packages/django/test/client.py", line 503, in request
[ 1221s]     raise exc_value
[ 1221s]   File "/usr/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
[ 1221s]     response = get_response(request)
[ 1221s]   File "/usr/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
[ 1221s]     response = self.process_exception_by_middleware(e, request)
[ 1221s]   File "/usr/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
[ 1221s]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[ 1221s]   File "/usr/lib/python3.7/site-packages/django/views/decorators/vary.py", line 38, in inner_func
[ 1221s]     response = func(*args, **kwargs)
[ 1221s]   File "/usr/lib/python3.7/site-packages/django/views/decorators/cache.py", line 31, in _cache_controlled
[ 1221s]     response = viewfunc(request, *args, **kw)
[ 1221s]   File "/home/abuild/rpmbuild/BUILD/Weblate-3.10.3/weblate/trans/views/widgets.py", line 175, in render_og
[ 1221s]     widget_obj.render(response)
[ 1221s]   File "/home/abuild/rpmbuild/BUILD/Weblate-3.10.3/weblate/trans/widgets.py", line 167, in render
[ 1221s]     surface = cairo.ImageSurface.create_from_png(self.get_filename())
[ 1221s] cairo.Error: file not found
```

But the file is present in the package:
```
find ./ -name email-logo.png
./docs/_build/html/_static/email-logo.png
./weblate/static/email-logo.png
```

The tests are executed by us as follows:
```
# first make sure we use buildroot properly
sed -i 's@^BASE_DIR = .*@BASE_DIR = "%{buildroot}%{WLDIR}"@g' weblate/settings.py
sed -i 's@^DATA_DIR = .*@DATA_DIR = "%{buildroot}%{WLDATADIR}"@g' weblate/settings.py

export PYTHONDONTWRITEBYTECODE=1
export LANG=en_US.UTF-8
# start the redis server
%{_sbindir}/redis-server &
# Collect static files for testsuite
python3 ./manage.py collectstatic --noinput --settings=weblate.settings_test -v 2
python3 ./manage.py compilemessages --settings=weblate.settings_test -v 2
# Run the testsuite
python3 ./manage.py check --settings=weblate.settings_test -v 2
python3 ./manage.py test --settings=weblate.settings_test -v 2
# kill the redis server
kill %%1
```

**Comment by nijel** [comment]
It seems that the static file collection did not work well. Did `collectstatic` fail with some error and did it use correct location?

PS: You might want to use `export DJANGO_SETTINGS_MODULE=weblate.settings_test` instead of specifying ``--settings=weblate.settings_test`` with every invocation.

**Comment by scarabeusiv** [comment]
Full build log: [weblate.txt](https://github.com/WeblateOrg/weblate/files/4213006/weblate.txt)

There seem to be no error reported there:
`[  110s] 349 static files copied to '/home/abuild/rpmbuild/BUILDROOT/weblate-3.10.3-2.1.x86_64/var/lib/weblate/static'.`

And good point about the error, it was just simple copy&paste, so I tweaked it to be shorter now ;-)

**Comment by nijel** [comment]
Guessing from path, it's not using the test settings (which are passed on command line). Strange that should work (but AFAIK pass this by environment in our CI, so it's not really tested).

**Comment by scarabeusiv** [comment]
Ok testing build will take ~30 mins to see the result -> I will post back here when it is finished.

**Comment by scarabeusiv** [comment]
But preliminary it seems goodTM:

`[  110s] 349 static files copied to '/home/abuild/rpmbuild/BUILDROOT/weblate-3.10.3-2.1.x86_64/var/lib/weblate/static'.`

**Comment by nijel** [comment]
That's same as above, I don't see a difference.

I did some testing and indeed ``--settings`` is not working properly with Weblate. It seems to be caused by combination of own wrapper and using Celery. 

1. The wrapper causes importing of `weblate` module 
2. This imports and configures Celery
3. Celery is configured from Django settings so it makes them load based on environment only
4. Next command line args are processed, but as the settings are already loaded, this has ho effect

**Comment by scarabeusiv** [comment]
Seems working with the enviroment variable:

```[ 1243s] Ran 2966 tests in 1209.161s
[ 1243s] 
[ 1243s] FAILED (failures=2, skipped=45)
```
