### ISSUE TITLE
Problem with Redis is loading the dataset in memory

### ISSUE THREAD

**Issue by rwrx** [WeblateOrg/weblate#3529]
Four days ago, I have pulled new Docker image of Weblate - 3.11.2-1 and it is always showing this log:

```
ERROR Handled exception: BusyLoadingError: Redis is loading the dataset in memory
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django_redis/cache.py", line 81, in get
    client=client)
  File "/usr/local/lib/python3.7/dist-packages/django_redis/client/default.py", line 201, in get
    raise ConnectionInterrupted(connection=client, parent=e)
django_redis.exceptions.ConnectionInterrupted: Redis BusyLoadingError: Redis is loading the dataset in memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 11, in <module>
    load_entry_point('Weblate==3.11.2', 'console_scripts', 'weblate')()
  File "/usr/local/lib/python3.7/dist-packages/weblate/runner.py", line 33, in main
    execute_from_command_line(argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.7/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/dist-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.7/dist-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/weblate/addons/models.py", line 48, in <module>
    from weblate.trans.models import Component, Unit
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/__init__.py", line 34, in <module>
    from weblate.trans.models.component import Component
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/component.py", line 166, in <module>
    class Component(models.Model, URLMixin, PathMixin):
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/component.py", line 191, in Component
    choices=VCS_REGISTRY.get_choices(),
  File "/usr/local/lib/python3.7/dist-packages/weblate/utils/classloader.py", line 107, in get_choices
    for x in sorted(self)
  File "/usr/local/lib/python3.7/dist-packages/weblate/utils/classloader.py", line 93, in __iter__
    return self.data.__iter__()
  File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/dist-packages/weblate/utils/classloader.py", line 72, in data
    return self.load_data()
  File "/usr/local/lib/python3.7/dist-packages/weblate/vcs/models.py", line 36, in load_data
    if not vcs.is_supported():
  File "/usr/local/lib/python3.7/dist-packages/weblate/vcs/base.py", line 335, in is_supported
    cls.name, version, cls.req_version, error
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/util.py", line 143, in add_configuration_error
    errors = cache.get('configuration-errors', [])
  File "/usr/local/lib/python3.7/dist-packages/django_redis/cache.py", line 39, in _decorator
    raise e.parent
  File "/usr/local/lib/python3.7/dist-packages/django_redis/client/default.py", line 199, in get
    value = client.get(key)
  File "/usr/local/lib/python3.7/dist-packages/redis/client.py", line 1579, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.7/dist-packages/redis/client.py", line 878, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.7/dist-packages/redis/client.py", line 892, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.7/dist-packages/redis/connection.py", line 734, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.7/dist-packages/redis/connection.py", line 477, in read_response
    raise response
redis.exceptions.BusyLoadingError: Redis is loading the dataset in memory
tomasvajda@Ubuntu1804:~/weblate-docker$ sudo docker-compose exec weblate weblate shell
ERROR Handled exception: BusyLoadingError: Redis is loading the dataset in memory
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django_redis/cache.py", line 81, in get
    client=client)
  File "/usr/local/lib/python3.7/dist-packages/django_redis/client/default.py", line 201, in get
    raise ConnectionInterrupted(connection=client, parent=e)
django_redis.exceptions.ConnectionInterrupted: Redis BusyLoadingError: Redis is loading the dataset in memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 11, in <module>
    load_entry_point('Weblate==3.11.2', 'console_scripts', 'weblate')()
  File "/usr/local/lib/python3.7/dist-packages/weblate/runner.py", line 33, in main
    execute_from_command_line(argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.7/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/dist-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.7/dist-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/weblate/addons/models.py", line 48, in <module>
    from weblate.trans.models import Component, Unit
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/__init__.py", line 34, in <module>
    from weblate.trans.models.component import Component
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/component.py", line 166, in <module>
    class Component(models.Model, URLMixin, PathMixin):
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/component.py", line 191, in Component
    choices=VCS_REGISTRY.get_choices(),
  File "/usr/local/lib/python3.7/dist-packages/weblate/utils/classloader.py", line 107, in get_choices
    for x in sorted(self)
  File "/usr/local/lib/python3.7/dist-packages/weblate/utils/classloader.py", line 93, in __iter__
    return self.data.__iter__()
  File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/dist-packages/weblate/utils/classloader.py", line 72, in data
    return self.load_data()
  File "/usr/local/lib/python3.7/dist-packages/weblate/vcs/models.py", line 36, in load_data
    if not vcs.is_supported():
  File "/usr/local/lib/python3.7/dist-packages/weblate/vcs/base.py", line 335, in is_supported
    cls.name, version, cls.req_version, error
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/util.py", line 143, in add_configuration_error
    errors = cache.get('configuration-errors', [])
  File "/usr/local/lib/python3.7/dist-packages/django_redis/cache.py", line 39, in _decorator
    raise e.parent
  File "/usr/local/lib/python3.7/dist-packages/django_redis/client/default.py", line 199, in get
    value = client.get(key)
  File "/usr/local/lib/python3.7/dist-packages/redis/client.py", line 1579, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.7/dist-packages/redis/client.py", line 878, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.7/dist-packages/redis/client.py", line 892, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.7/dist-packages/redis/connection.py", line 734, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.7/dist-packages/redis/connection.py", line 477, in read_response
    raise response
redis.exceptions.BusyLoadingError: Redis is loading the dataset in memory
```

before update it has worked flawlessly. Could there be a problem with not enough of available memory. VPS has only 1 GB of RAM. Here is an output of `free -m`:

```
              total        used        free      shared  buff/cache   available
Mem:            985         207          71           1         706         628
Swap:           951         291         660
```

Thank you.

**Comment by nijel** [comment]
Check logs of redis container why it's taking so long, probably the problem lies there.

**Comment by rwrx** [comment]
Thank you. I have checked it, there are some warnings, but no errors:

```
1:M 27 Feb 08:33:27.021 # Bad file format reading the append only file: make a backup of your AOF file, then use ./redis-check-aof --fix <filename>
1:C 27 Feb 08:33:28.703 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 27 Feb 08:33:28.703 # Redis version=4.0.14, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 27 Feb 08:33:28.703 # Configuration loaded
1:M 27 Feb 08:33:28.705 * Running mode=standalone, port=6379.
1:M 27 Feb 08:33:28.705 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 27 Feb 08:33:28.705 # Server initialized
1:M 27 Feb 08:33:28.705 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 27 Feb 08:33:28.705 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
```

I am not sure what I can do to resolve this. I do not want to broke it more.

**Comment by nijel** [comment]
"Bad file format reading the append only file" looks like a file corruption, see for example https://stackoverflow.com/q/50504692/225718

**Comment by rwrx** [comment]
@nijel Thank you a lot. I am running Weblate in Docker and running this command fixed corrupted `appendonly.aof` file: `sudo redis-check-aof --fix /var/lib/docker/volumes/weblatedocker_redis-data/_data/appendonly.aof`. Maybe it will also help someone in the future.
