### ISSUE TITLE
Wrong source string when using Qt linguist monolingual as a template

### ISSUE THREAD

**Issue by loktionovam** [WeblateOrg/weblate#3603]
**Describe the bug**

Wrong source string when using Qt linguist **monolingual** as a template

![image](https://user-images.githubusercontent.com/24241455/76624619-b363ce00-6546-11ea-8e25-3029812b2f47.png)

**To Reproduce**

1. Create ts template file (I used the example from https://doc.qt.io/qt-5/linguist-id-based-i18n.html)

```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
<context>
    <name></name>
    <message id="id-back-not-front">
        <source>Back</source>
        <extracomment>The back of the object, not the front</extracomment>
        <translation type="unfinished"></translation>
        <extra-Context>Not related to back-stepping</extra-Context>
    </message>
</context>
</TS>
```
2. Create translation project

```json
{
    "count": 2,
    "next": null,
    "previous": null,
    "results": [
        {
            "name": "l10n-tests",
            "slug": "l10n-tests",
            "web": "https://github.com/loktionovam/l10n-tests",
            "source_language": {
                "code": "templates",
                "name": "templates (generated)",
                "direction": "ltr",
                "web_url": "http://example.com/languages/templates/",
                "url": "https://weblate.example.com/api/languages/templates/"
            },
            "web_url": "http://example.com/projects/l10n-tests/",
            "url": "https://weblate.example.com/api/projects/l10n-tests/",
            "components_list_url": "https://weblate.example.com/api/projects/l10n-tests/components/",
            "repository_url": "https://weblate.example.com/api/projects/l10n-tests/repository/",
            "statistics_url": "https://weblate.example.com/api/projects/l10n-tests/statistics/",
            "changes_list_url": "https://weblate.example.com/api/projects/l10n-tests/changes/",
            "languages_url": "https://weblate.example.com/api/projects/l10n-tests/languages/"
        },
        {
            "name": "weblate-test",
            "slug": "weblate-test",
            "web": "https://github.com/WeblateOrg",
            "source_language": {
                "code": "en",
                "name": "English",
                "direction": "ltr",
                "web_url": "http://example.com/languages/en/",
                "url": "https://weblate.example.com/api/languages/en/"
            },
            "web_url": "http://example.com/projects/weblate-test/",
            "url": "https://weblate.example.com/api/projects/weblate-test/",
            "components_list_url": "https://weblate.example.com/api/projects/weblate-test/components/",
            "repository_url": "https://weblate.example.com/api/projects/weblate-test/repository/",
            "statistics_url": "https://weblate.example.com/api/projects/weblate-test/statistics/",
            "changes_list_url": "https://weblate.example.com/api/projects/weblate-test/changes/",
            "languages_url": "https://weblate.example.com/api/projects/weblate-test/languages/"
        }
    ]
}
```

3. Create a translation component inside the translation project

```json
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "name": "qt-monolingual-ts-qtlinguist-example",
            "slug": "qt-monolingual-ts-qtlinguist-example",
            "project": {
                "name": "l10n-tests",
                "slug": "l10n-tests",
                "web": "https://github.com/loktionovam/l10n-tests",
                "source_language": {
                    "code": "templates",
                    "name": "templates (generated)",
                    "direction": "ltr",
                    "web_url": "http://example.com/languages/templates/",
                    "url": "https://weblate.example.com/api/languages/templates/"
                },
                "web_url": "http://example.com/projects/l10n-tests/",
                "url": "https://weblate.example.com/api/projects/l10n-tests/",
                "components_list_url": "https://weblate.example.com/api/projects/l10n-tests/components/",
                "repository_url": "https://weblate.example.com/api/projects/l10n-tests/repository/",
                "statistics_url": "https://weblate.example.com/api/projects/l10n-tests/statistics/",
                "changes_list_url": "https://weblate.example.com/api/projects/l10n-tests/changes/",
                "languages_url": "https://weblate.example.com/api/projects/l10n-tests/languages/"
            },
            "vcs": "git",
            "repo": "https://github.com/loktionovam/l10n-tests",
            "git_export": "http://example.com/git/l10n-tests/qt-monolingual-ts-qtlinguist-example/",
            "branch": "qtlingust-example",
            "filemask": "*/qt-monolingual.ts",
            "template": "templates/qt-monolingual.ts",
            "new_base": "templates/qt-monolingual.ts",
            "file_format": "ts",
            "license": "",
            "license_url": null,
            "web_url": "http://example.com/projects/l10n-tests/qt-monolingual-ts-qtlinguist-example/",
            "url": "https://weblate.example.com/api/components/l10n-tests/qt-monolingual-ts-qtlinguist-example/",
            "repository_url": "https://weblate.example.com/api/components/l10n-tests/qt-monolingual-ts-qtlinguist-example/repository/",
            "translations_url": "https://weblate.example.com/api/components/l10n-tests/qt-monolingual-ts-qtlinguist-example/translations/",
            "statistics_url": "https://weblate.example.com/api/components/l10n-tests/qt-monolingual-ts-qtlinguist-example/statistics/",
            "lock_url": "https://weblate.example.com/api/components/l10n-tests/qt-monolingual-ts-qtlinguist-example/lock/",
            "changes_list_url": "https://weblate.example.com/api/components/l10n-tests/qt-monolingual-ts-qtlinguist-example/changes/",
            "new_lang": "add",
            "push": "",
            "check_flags": "",
            "enforced_checks": ""
        }
    ]
}

```

4. Translation source string is empty

```json
        {
            "translation": "https://weblate.example.com/api/translations/l10n-tests/qt-monolingual-ts-qtlinguist-example/es/",
            "source": "",
            "previous_source": "",
            "target": "",
            "id_hash": -9209624781982387811,
            "content_hash": -9209624781982387811,
            "location": "",
            "context": "id-back-not-frontBack",
            "note": "The back of the object, not the front",
            "flags": "",
            "fuzzy": false,
            "translated": false,
            "position": 1,
            "has_suggestion": false,
            "has_comment": false,
            "has_failing_check": false,
            "num_words": 0,
            "priority": 100,
            "id": 29,
            "web_url": "http://example.com/translate/l10n-tests/qt-monolingual-ts-qtlinguist-example/es/?checksum=30d70e334e319d",
            "url": "https://weblate.example.com/api/units/29/"
        }
```

**Expected behavior**

'Back' string expected as source string.

**Screenshots**

![image](https://user-images.githubusercontent.com/24241455/76623498-a80fa300-6544-11ea-9b2a-a41be2c72bd4.png)

**Server configuration and status**

```
docker-compose exec weblate weblate list_versions
INFOS:
?: (weblate.I031) New Weblate version is available, please upgrade to 3.11.3.
	HINT: https://docs.weblate.org/en/weblate-3.11/admin/upgrade.html
 * Weblate: 3.11
 * Django: 3.0.3
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.0
 * lxml: 4.3.2
 * Pillow: 7.0.0
 * bleach: 3.1.0
 * six: 1.14.0
 * python-dateutil: 2.8.1
 * social-auth-core: 3.2.0
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.8.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.3
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.1
 * celery: 4.4.0
 * kombu: 4.6.7
 * celery-batches: 0.3
 * translation-finder: 1.7
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.22.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.1
 * Cython: 0.29.15
 * misaka: 2.1.1
 * GitPython: 3.0.8
 * borgbackup: 1.1.10
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.7.7
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.0
 * akismet: 1.1
 * boto3: 1.12.0
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * Mercurial: 4.8.2
 * git-svn: 2.20.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.lancloud.ru
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.3.0-40-generic (x86_64)

docker-compose exec --user weblate weblate weblate check --deploy
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E017) Configure correct site domain
	HINT: https://docs.weblate.org/en/weblate-3.11/admin/install.html#production-site
?: (weblate.E027) Path /app/data/settings-override.py is owned by different user, check your DATA_DIR settings.
	HINT: https://docs.weblate.org/en/weblate-3.11/admin/install.html#file-permissions
?: (weblate.E027) Path /app/data/ssl is owned by different user, check your DATA_DIR settings.
	HINT: https://docs.weblate.org/en/weblate-3.11/admin/install.html#file-permissions

ERRORS:
?: (weblate.E016) Configure cached template loader for better performance
	HINT: https://docs.weblate.org/en/weblate-3.11/admin/install.html#production-templates

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W018) You should not have DEBUG set to True in deployment.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-3.11/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-3.11/admin/backup.html
?: (weblate.I031) New Weblate version is available, please upgrade to 3.11.3.
	HINT: https://docs.weblate.org/en/weblate-3.11/admin/upgrade.html

System check identified 11 issues (1 silenced).

```

**Additional context**

When I used a template as bilingual (i.e. **Monolingual base language file ** field is empty), it is ok

![image](https://user-images.githubusercontent.com/24241455/76624875-2f5e1600-6547-11ea-9854-c450fd23df0e.png)

```json
        {
            "translation": "https://weblate.example.com/api/translations/l10n-tests/qt-monolingual-ts-qtlinguist-example/es/",
            "source": "Back",
            "previous_source": "",
            "target": "",
            "id_hash": 6139380178251588747,
            "content_hash": 6139380178251588747,
            "location": "",
            "context": "id-back-not-front",
            "note": "The back of the object, not the front",
            "flags": "",
            "fuzzy": false,
            "translated": false,
            "position": 1,
            "has_suggestion": false,
            "has_comment": false,
            "has_failing_check": false,
            "num_words": 1,
            "priority": 100,
            "id": 31,
            "web_url": "http://example.com/translate/l10n-tests/qt-monolingual-ts-qtlinguist-example/es/?checksum=d53375be89c2a48b",
            "url": "https://weblate.example.com/api/units/31/"
        }
```

**Comment by nijel** [comment]
This looks like *bilingual* - you have source and target languages in single file.

**Comment by ilocit** [comment]
I actually had the same issue with QT files. I think that QT might not be clear about the definition of the file format. I could not find anything about a monolingual file template. My guess is that you can only create those "bilingual" files. Perhaps it was different with previous QT versions, but now I only find reference to the exact file format as in this issue.
It would not matter much if you could simply switch to bilingual. But then you have another issue that if you are also creating a "source language" QT file in  your development project, e.g. to manage plurals properly also in your English source. If this file is then also added to the project, because from a development point of view it is part of your locales, Weblate of course reports an issue with duplicate source locale EN. This is correct, since you now have an en.ts file in your project and e.g. an it.ts file which has the English as a source in that same file (bilingual). Hope it is clear what I am trying to describe here.

**Comment by loktionovam** [comment]
I still think there is a problem in ts files processing because:

-  I tried to remove `<translation type="unfinished"></translation>` like that:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
<context>
    <name></name>
    <message id="id-back-not-front">
        <source>Back</source>
        <extracomment>The back of the object, not the front</extracomment>
        <extra-Context>Not related to back-stepping</extra-Context>
    </message>
</context>
</TS>
```

the problem in source string detection still exists and translations have stopped being created:

```python
weblate_1   | uwsgi stderr | ERROR Internal Server Error: /new-lang/l10n-tests/qt-monolingual-ts-qtlinguist-example/
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
weblate_1   |     response = get_response(request)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 115, in _get_response
weblate_1   |     response = self.process_exception_by_middleware(e, request)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 113, in _get_response
weblate_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
weblate_1   |     response = view_func(request, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
weblate_1   |     return view_func(request, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/weblate/trans/views/basic.py", line 331, in new_language
weblate_1   |     translation = obj.add_new_language(language, request)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/component.py", line 2008, in add_new_language
weblate_1   |     file_format.add_language(fullname, language, base_filename)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/weblate/formats/base.py", line 416, in add_language
weblate_1   |     cls.create_new_file(filename, language, base)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/weblate/formats/ttkit.py", line 351, in create_new_file
weblate_1   |     cls.untranslate_store(store, language)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/weblate/formats/ttkit.py", line 808, in untranslate_store
weblate_1   |     super(TSFormat, cls).untranslate_store(store, language, True)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/weblate/formats/ttkit.py", line 332, in untranslate_store
weblate_1   |     unit.markfuzzy(fuzzy)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/translate/storage/ts2.py", line 255, in markfuzzy
weblate_1   |     self._settype("unfinished")
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/translate/storage/ts2.py", line 240, in _settype
weblate_1   |     self._gettargetnode().set("type", value)
weblate_1   | AttributeError: 'NoneType' object has no attribute 'set'
weblate_1   | Internal Server Error: /new-lang/l10n-tests/qt-monolingual-ts-qtlinguist-example/
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
weblate_1   |     response = get_response(request)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 115, in _get_response
weblate_1   |     response = self.process_exception_by_middleware(e, request)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 113, in _get_response
weblate_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
weblate_1   |     response = view_func(request, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
weblate_1   |     return view_func(request, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/weblate/trans/views/basic.py", line 331, in new_language
weblate_1   |     translation = obj.add_new_language(language, request)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/component.py", line 2008, in add_new_language
weblate_1   |     file_format.add_language(fullname, language, base_filename)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/weblate/formats/base.py", line 416, in add_language
weblate_1   |     cls.create_new_file(filename, language, base)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/weblate/formats/ttkit.py", line 351, in create_new_file
weblate_1   |     cls.untranslate_store(store, language)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/weblate/formats/ttkit.py", line 808, in untranslate_store
weblate_1   |     super(TSFormat, cls).untranslate_store(store, language, True)
weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/weblate/formats/ttkit.py", line 332, in untranslate_store
weblate_1   |     unit.markfuzzy(fuzzy)
```

- After that I tried to add target translation to base file (i.e. replace `<translation type="unfinished"></translation>` by `<translation>Back</translation>`):

```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1">
<context>
    <name></name>
    <message id="id-back-not-front">
        <source>Back</source>
       <translation>Back</translation>
        <extracomment>The back of the object, not the front</extracomment>
        <extra-Context>Not related to back-stepping</extra-Context>
    </message>
</context>
</TS>
```

and source string `Back` detected successfully and unit become:

```json
{
    "count": 2,
    "next": null,
    "previous": null,
    "results": [
        {
            "translation": "http://weblate.example.com:8080/api/translations/l10n-tests/qt-monolingual-ts-qtlinguist-example/templates/",
            "source": "Back",
            "previous_source": "",
            "target": "Back",
            "id_hash": -9209624781982387811,
            "content_hash": -1649052789351597514,
            "location": "",
            "context": "id-back-not-frontBack",
            "note": "The back of the object, not the front",
            "flags": "",
            "fuzzy": false,
            "translated": true,
            "position": 1,
            "has_suggestion": false,
            "has_comment": false,
            "has_failing_check": false,
            "num_words": 1,
            "priority": 100,
            "id": 17798,
            "web_url": "http://weblate.example.com/translate/l10n-tests/qt-monolingual-ts-qtlinguist-example/templates/?checksum=30d70e334e319d",
            "url": "http://weblate.example.com:8080/api/units/17798/"
        },
        {
            "translation": "http://weblate.example.com:8080/api/translations/l10n-tests/qt-monolingual-ts-qtlinguist-example/es/",
            "source": "Back",
            "previous_source": "",
            "target": "Volver",
            "id_hash": -9209624781982387811,
            "content_hash": -1649052789351597514,
            "location": "",
            "context": "id-back-not-frontBack",
            "note": "The back of the object, not the front",
            "flags": "",
            "fuzzy": false,
            "translated": true,
            "position": 1,
            "has_suggestion": false,
            "has_comment": false,
            "has_failing_check": false,
            "num_words": 1,
            "priority": 100,
            "id": 17799,
            "web_url": "http://weblate.example.com/translate/l10n-tests/qt-monolingual-ts-qtlinguist-example/es/?checksum=30d70e334e319d",
            "url": "http://weblate.example.com:8080/api/units/17799/"
        }
    ]
}
```

```json
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
            "name": "qt-monolingual-ts-qtlinguist-example",
            "slug": "qt-monolingual-ts-qtlinguist-example",
            "project": {
                "name": "l10n-tests",
                "slug": "l10n-tests",
                "web": "https://github.com/loktionovam/l10n-tests",
                "source_language": {
                    "code": "templates",
                    "name": "templates (generated)",
                    "direction": "ltr",
                    "web_url": "http://weblate.example.com/languages/templates/",
                    "url": "http://weblate.example.com:8080/api/languages/templates/"
                },
                "web_url": "http://weblate.example.com/projects/l10n-tests/",
                "url": "http://weblate.example.com:8080/api/projects/l10n-tests/",
                "components_list_url": "http://weblate.example.com:8080/api/projects/l10n-tests/components/",
                "repository_url": "http://weblate.example.com:8080/api/projects/l10n-tests/repository/",
                "statistics_url": "http://weblate.example.com:8080/api/projects/l10n-tests/statistics/",
                "changes_list_url": "http://weblate.example.com:8080/api/projects/l10n-tests/changes/",
                "languages_url": "http://weblate.example.com:8080/api/projects/l10n-tests/languages/"
            },
            "vcs": "git",
            "repo": "https://github.com/loktionovam/l10n-tests.git",
            "git_export": "http://weblate.example.com/git/l10n-tests/qt-monolingual-ts-qtlinguist-example/",
            "branch": "qtlingust-example-with-dst-translation",
            "filemask": "*/qt-monolingual.ts",
            "template": "templates/qt-monolingual.ts",
            "new_base": "templates/qt-monolingual.ts",
            "file_format": "ts",
            "license": "",
            "license_url": null,
            "web_url": "http://weblate.example.com/projects/l10n-tests/qt-monolingual-ts-qtlinguist-example/",
            "url": "http://weblate.example.com:8080/api/components/l10n-tests/qt-monolingual-ts-qtlinguist-example/",
            "repository_url": "http://weblate.example.com:8080/api/components/l10n-tests/qt-monolingual-ts-qtlinguist-example/repository/",
            "translations_url": "http://weblate.example.com:8080/api/components/l10n-tests/qt-monolingual-ts-qtlinguist-example/translations/",
            "statistics_url": "http://weblate.example.com:8080/api/components/l10n-tests/qt-monolingual-ts-qtlinguist-example/statistics/",
            "lock_url": "http://weblate.example.com:8080/api/components/l10n-tests/qt-monolingual-ts-qtlinguist-example/lock/",
            "changes_list_url": "http://weblate.example.com:8080/api/components/l10n-tests/qt-monolingual-ts-qtlinguist-example/changes/",
            "new_lang": "add",
            "push": "",
            "check_flags": "",
            "enforced_checks": ""
        }
    ]
}
```
```

**Comment by ilocit** [comment]
Honestly, I think QT .ts files are bilingual. Always. If you have a format with <source> and <target> ( in this case <translation>) what else would it be? Like XLIFF. So the problem only exists if you (a) try to setup a QT project in Weblate as monolingual, or (b) setup the project including the source language TS file.
Send me a PM if you want, and we can discuss this using a real example project with some real life TS files in our deployment of Weblate . Just a suggestion, if you want. And then we can get back to Michal with our findings. OK?

**Comment by nijel** [comment]
> the problem in source string detection still exists and translations have stopped being created:
> 
> ```python
> weblate_1   | uwsgi stderr | ERROR Internal Server Error: /new-lang/l10n-tests/qt-monolingual-ts-qtlinguist-example/
> weblate_1   | Traceback (most recent call last):
> weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
> weblate_1   |     response = get_response(request)
> weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 115, in _get_response
> weblate_1   |     response = self.process_exception_by_middleware(e, request)
> weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 113, in _get_response
> weblate_1   |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
> weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
> weblate_1   |     response = view_func(request, *args, **kwargs)
> weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
> weblate_1   |     return view_func(request, *args, **kwargs)
> weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/weblate/trans/views/basic.py", line 331, in new_language
> weblate_1   |     translation = obj.add_new_language(language, request)
> weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/component.py", line 2008, in add_new_language
> weblate_1   |     file_format.add_language(fullname, language, base_filename)
> weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/weblate/formats/base.py", line 416, in add_language
> weblate_1   |     cls.create_new_file(filename, language, base)
> weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/weblate/formats/ttkit.py", line 351, in create_new_file
> weblate_1   |     cls.untranslate_store(store, language)
> weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/weblate/formats/ttkit.py", line 808, in untranslate_store
> weblate_1   |     super(TSFormat, cls).untranslate_store(store, language, True)
> weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/weblate/formats/ttkit.py", line 332, in untranslate_store
> weblate_1   |     unit.markfuzzy(fuzzy)
> weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/translate/storage/ts2.py", line 255, in markfuzzy
> weblate_1   |     self._settype("unfinished")
> weblate_1   |   File "/usr/local/lib/python3.7/dist-packages/translate/storage/ts2.py", line 240, in _settype
> weblate_1   |     self._gettargetnode().set("type", value)
> weblate_1   | AttributeError: 'NoneType' object has no attribute 'set'
> ```

This bug should by addressed by following pull request: https://github.com/translate/translate/pull/3953
