### ISSUE TITLE
Weblate crashes when having unicode char in language name

### ISSUE THREAD

**Issue by Kilill** [WeblateOrg/weblate#3660]
Weblate crashes when "language" contains unicode characters ie "Norwegian Bokmål" 

create a new translation with language = Norwegian Bokmål

try to commit any translations changes

**Server configuration and status**

On pip installed Weblate:
weblate list_versions
 * Weblate: 3.11.3
 * Django: 3.0.5
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.0
 * lxml: 4.5.0
 * Pillow: 7.0.0
 * bleach: 3.1.4
 * six: 1.14.0
 * python-dateutil: 2.8.1
 * social-auth-core: 3.2.0
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.8.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 46.1.3
 * jellyfish: 0.7.2
 * openpyxl: 3.0.3
 * celery: 4.4.2
 * kombu: 4.6.8
 * celery-batches: 0.3
 * translation-finder: 1.8
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.36.0
 * diff-match-patch: 20181111
 * requests: 2.23.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.3
 * Cython: 0.29.16
 * misaka: 2.1.1
 * GitPython: 3.1.0
 * borgbackup: 1.1.11
 * Python: 3.6.9
 * Git: 2.17.1
 * psycopg2-binary: 2.8.4
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 5.3.13-1-pve (x86_64)

Error message:
Apr 02 19:19:01 indeed.maybe.cool weblate[29430]: ERROR Internal Server Error: /commit/test/tut/nb_NO/
                                                  Traceback (most recent call last):
                                                    File "/var/www/wb/weblate-env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
                                                      response = get_response(request)
                                                    File "/var/www/wb/weblate-env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
                                                      response = self.process_exception_by_middleware(e, request)
                                                    File "/var/www/wb/weblate-env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
                                                      response = wrapped_callback(request, *callback_args, **callback_kwargs)
                                                    File "/var/www/wb/weblate-env/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
                                                      return view_func(request, *args, **kwargs)
                                                    File "/var/www/wb/weblate-env/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
                                                      return func(request, *args, **kwargs)
                                                    File "/var/www/wb/weblate-env/lib/python3.6/site-packages/weblate/trans/views/git.py", line 129, in commit_translation
                                                      return perform_commit(request, obj)
                                                    File "/var/www/wb/weblate-env/lib/python3.6/site-packages/weblate/trans/views/git.py", line 58, in perform_commit
                                                      request.user,
                                                    File "/var/www/wb/weblate-env/lib/python3.6/site-packages/weblate/trans/views/git.py", line 36, in execute_locked
                                                      result = call(*args, **kwargs)
                                                    File "/var/www/wb/weblate-env/lib/python3.6/site-packages/weblate/trans/models/translation.py", line 456, in commit_pending
                                                      user, author_name, timestamp, skip_push=skip_push, signals=signals
                                                    File "/var/www/wb/weblate-env/lib/python3.6/site-packages/weblate/trans/models/translation.py", line 538, in git_commit
                                                      self.__git_commit(author, timestamp, signals=signals)
                                                    File "/var/www/wb/weblate-env/lib/python3.6/site-packages/weblate/trans/models/translation.py", line 491, in __git_commit
                                                      msg, author, timestamp, files + self.addon_commit_files
                                                    File "/var/www/wb/weblate-env/lib/python3.6/site-packages/weblate/vcs/git.py", line 246, in commit
                                                      self.execute(cmd)
                                                    File "/var/www/wb/weblate-env/lib/python3.6/site-packages/weblate/vcs/base.py", line 185, in execute
                                                      args, self.path, fullcmd=fullcmd, local=self.local, merge_err=merge_err
                                                    File "/var/www/wb/weblate-env/lib/python3.6/site-packages/weblate/vcs/base.py", line 162, in _popen
                                                      stdin=subprocess.PIPE,
                                                    File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
                                                      restore_signals, start_new_session)
                                                    File "/usr/lib/python3.6/subprocess.py", line 1295, in _execute_child
                                                      restore_signals, start_new_session, preexec_fn)
                                                  UnicodeEncodeError: 'ascii' codec can't encode character '\xe5' in position 40: ordinal not in range(128)

**Comment by nijel** [comment]
You need UTF-8 locales to be able to do this. It's default on most distributions for years, that's probably why nobody hit this so far. You can check what Python thinks of your locales by issuing: `python -c 'import sys; print(sys.getfilesystemencoding(), sys.getdefaultencoding())'` It should print twice utf-8.

**Comment by Kilill** [comment]
aha!, thanks. 
This is was on a virtual hosted server where it turns out, that for some reason default locale (/etc/default/locale) was set to LANG="C".
changing it to LANG="C.UTF-8" and reloging + restarting apache did the trick,

**Comment by nijel** [comment]
I've added system check for this in c9760a8ffe, so that it's more visible that system is not well configured for Weblate.

**Comment by Kilill** [comment]
just as a side note and for anyone having similar issues. I had to change the locale settings in two places: the /etc/default/locale , but also in apaches own environment settings , (this might be Ubuntu specific) /etc/apache2/envars. i guess that the later would probably suffice...

**Comment by Flohack74** [comment]
Hmm it seems I still have this issue, also on Apache, it was also set to C only in envars file. But after adding UTF8 there nothing really changed. So I cherrypicked the test that @nijel added onto 3.11, but it seems that the check passes and still the exception happens... any further ides?

**Comment by nijel** [comment]
@Flohack74 Please open separate issue for that and include more info, this way it's hard to guess whether it's related or not.
