### ISSUE TITLE
'AnonymousUser' object has no attribute 'check_access'

### ISSUE THREAD

**Issue by minusf** [WeblateOrg/weblate#3688]
**Describe the bug**
Received the following exception on a running instance, sorry not sure how to reproduce:

```
Traceback (most recent call last):
  File "/export/apps/weblate/venv/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/export/apps/weblate/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/export/apps/weblate/venv/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/export/apps/weblate/venv/lib64/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/export/apps/weblate/venv/lib64/python3.6/site-packages/weblate/trans/views/basic.py", line 180, in show_component
    obj = get_component(request, project, component)
  File "/export/apps/weblate/venv/lib64/python3.6/site-packages/weblate/utils/views.py", line 102, in get_component
    request.user.check_access(component.project)

Exception Type: AttributeError at /projects/widgets/project/
Exception Value: 'AnonymousUser' object has no attribute 'check_access'
Request information:
USER: AnonymousUser
```

**Server configuration and status**
Please paste the output of `list_versions` and `check --deploy` commands over
here. Depending on installation these can be executed in different way, please
consult https://docs.weblate.org/en/latest/admin/management.html for more
details.

On pip installed Weblate:

```
* Weblate: 3.11.3
* Django: 3.0.4
* siphashc: 1.3
* Whoosh: 2.7.4
* translate-toolkit: 2.5.0
* lxml: 4.5.0
* Pillow: 7.0.0
* bleach: 3.1.3
* six: 1.14.0
* python-dateutil: 2.8.1
* social-auth-core: 3.2.0
* social-auth-app-django: 3.1.0
* django-crispy-forms: 1.8.1
* oauthlib: 3.1.0
* django-compressor: 2.4
* djangorestframework: 3.11.0
* django-appconf: 1.0.3
* user-agents: 2.1
* filelock: 3.0.12
* setuptools: 39.2.0
* jellyfish: 0.7.2
* openpyxl: 3.0.3
* celery: 4.4.2
* kombu: 4.6.8
* celery-batches: 0.3
* translation-finder: 1.8
* html2text: 2020.1.16
* pycairo: 1.19.1
* pygobject: 3.36.0
* diff-match-patch: 20181111
* requests: 2.23.0
* django-redis: 4.11.0
* hiredis: 1.0.1
* sentry_sdk: 0.14.3
* Cython: 0.29.16
* misaka: 2.1.1
* GitPython: 3.1.0
* borgbackup: 1.1.11
* Python: 3.6.8
* Git: 2.22.2
* psycopg2-binary: 2.8.4
* chardet: 3.0.4
* ruamel.yaml: 0.16.10
* Database backends: django.db.backends.postgresql
* Cache backends: default:RedisCache, avatar:FileBasedCache
* Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
* Celery: redis://127.0.0.1:6380, redis://127.0.0.1:6380, regular
* Platform: Linux 3.10.0-1062.4.1.el7.x86_64 (x86_64)
```

**Comment by nijel** [comment]
Probably some misconfiguration on your side, the `AnonymousUser` should not appear at all in Weblate. Maybe `weblate.accounts.AuthenticationMiddleware` is missing from your `settings.py`?

**Comment by minusf** [comment]
both the middleware and the auth backend are there.  but so is our own backend for our custom SSO.  maybe the order is wrong?

**Comment by nijel** [comment]
Most likely, anything from Weblate needs to be called after `weblate.accounts.AuthenticationMiddleware` has processed the request.

**Comment by minusf** [comment]
```
MIDDLEWARE = [
    "weblate.middleware.ProxyMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "weblate.accounts.middleware.AuthenticationMiddleware",
    "custom_local.middleware.CustomLocalAuthenticationMiddleware", # <-- our SSO
    "weblate.accounts.middleware.RequireLoginMiddleware",
    "weblate.middleware.SecurityMiddleware",
]
```

**Comment by nijel** [comment]
Maybe the SSO can return `AnonymousUser` then? In that case you should include something like this there:

https://github.com/WeblateOrg/weblate/blob/18d29aeb2305668e51941c084d0c42a068de8c2d/weblate/accounts/middleware.py#L31-L47

**Comment by minusf** [comment]
the idea is to have read only access for non-logged-in anon users.  i will have a look how weblate does this.

**Comment by nijel** [comment]
There is anonymous user stored in the database and you can set permissions for it. Django does use AnonymousUser instead, which is not database backed.
