### ISSUE TITLE
Weblate 4.0 upgrade "No such file or directory: 'requirements-test.txt'"

### ISSUE THREAD

**Issue by Badiboy** [WeblateOrg/weblate#3736]
**Describe the bug**
Error during install (upgrade) the Weblate to 4.0 via PIP.
  FileNotFoundError: [Errno 2] No such file or directory: 'requirements-test.txt'

**To Reproduce**
cd /drive/weblate-env
. /drive/weblate-env/bin/activate
pip3 install --upgrade weblate

**Server configuration and status**
Ubuntu 18.04.4
Python 3.6.9

```
Collecting weblate
  Downloading Weblate-4.0.tar.gz (24.7 MB)
     |████████████████████████████████| 24.7 MB 1.4 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /drive/weblate-env/bin/python3 /drive/weblate-env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmppc423mze
       cwd: /tmp/pip-install-r3hxcago/weblate
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/drive/weblate-env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/drive/weblate-env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/drive/weblate-env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-jc9j70ap/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 148, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-jc9j70ap/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 128, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-jc9j70ap/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 250, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-jc9j70ap/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 143, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 34, in <module>
      with open("requirements-test.txt") as requirements:
  FileNotFoundError: [Errno 2] No such file or directory: 'requirements-test.txt'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /drive/weblate-env/bin/python3 /drive/weblate-env/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmppc423mze Check the logs for full command output.

```

**Comment by nijel** [comment]
I've noticed that as well, just after the release. The fix is in https://github.com/WeblateOrg/weblate/commit/d36e30c41f7b60cae896d64c6fbdd1969cfabf9a and there will be shortly a 4.0.1 release.
