### ISSUE TITLE
4.0.1 - Custom plugins are not loading

### ISSUE THREAD

**Issue by Badiboy** [WeblateOrg/weblate#3739]
**Describe the bug**
Custom plugins lead to a Weblate loading error.
_django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet._

**To Reproduce**
1. Create file: .../lib/python3.6/site-packages/weblate/addons/TestAddon.py
2. Put there code from documentation: https://docs.weblate.org/en/latest/admin/addons.html#writing-addon
3. Add plugin to settings.py:
```
# Django and Weblate apps
INSTALLED_APPS = [
...
#    "weblate.addons.TestAddon", 
]
```
4. Save settings or restart weblate server.

**Expected behavior**
Silent loading and plugin in the project component list.

**Error log**
```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/drive/weblate-env/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/drive/weblate-env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/drive/weblate-env/lib/python3.6/site-packages/django/utils/autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "/drive/weblate-env/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "/drive/weblate-env/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/drive/weblate-env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/drive/weblate-env/lib/python3.6/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/drive/weblate-env/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/drive/weblate-env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/drive/weblate-env/lib/python3.6/site-packages/weblate/addons/TestAddon.py", line 23, in <module>
    from weblate.addons.base import BaseAddon
  File "/drive/weblate-env/lib/python3.6/site-packages/weblate/addons/base.py", line 37, in <module>
    from weblate.addons.forms import BaseAddonForm
  File "/drive/weblate-env/lib/python3.6/site-packages/weblate/addons/forms.py", line 29, in <module>
    from weblate.trans.discovery import ComponentDiscovery
  File "/drive/weblate-env/lib/python3.6/site-packages/weblate/trans/discovery.py", line 31, in <module>
    from weblate.trans.models import Component
  File "/drive/weblate-env/lib/python3.6/site-packages/weblate/trans/models/__init__.py", line 28, in <module>
    from weblate.trans.models.agreement import ContributorAgreement
  File "/drive/weblate-env/lib/python3.6/site-packages/weblate/trans/models/agreement.py", line 42, in <module>
    class ContributorAgreement(models.Model):
  File "/drive/weblate-env/lib/python3.6/site-packages/django/db/models/base.py", line 107, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/drive/weblate-env/lib/python3.6/site-packages/django/apps/registry.py", line 252, in get_containing_app_config
    self.check_apps_ready()
  File "/drive/weblate-env/lib/python3.6/site-packages/django/apps/registry.py", line 135, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

```

**Comment by nijel** [comment]
Adding it to `INSTALLED_APPS` sounds wrong. It's not a standalone app in this case, it just additional module in existing one.

**Comment by Badiboy** [comment]
Oh, I'm sorry.

I'm trying to restore my _settings.py_ that was overriten by 4.0.0/4.0.1 update. Not everything that I did there is easy to remeber. :(

Of course it should be added here:
```
# List of enabled addons
WEBLATE_ADDONS = (
)
```

Thanks.
