### ISSUE TITLE
Error after upgrade Weblate v3.11 to v4.0.2

### ISSUE THREAD

**Issue by n-haddag** [WeblateOrg/weblate#3798]
**Describe the bug**
Error upgrade 

```
Traceback (most recent call last):
  File "./manage.py", line 30, in <module>
    from weblate.runner import main
  File "/home/nhaddag/weblate/weblate/__init__.py", line 39
    USER_AGENT = f"Weblate/{VERSION}"
                                    ^
SyntaxError: invalid syntax
```

**Comment by nijel** [comment]
You need Python 3.6 or newer to run Weblate 4.0, see https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-from-3-11-to-4-0
