### ISSUE TITLE
CI Tests Are Flaky

### ISSUE THREAD

**Issue by flosincapite** [WeblateOrg/weblate#3812]
**Describe the bug**
CI tests (mostly things like Test/py<version>,<db_config>) are flaky. I often need to re-run multiple times to get tests to pass. Failures surface as timeouts on CI servers and are not related to Weblate code.

**To Reproduce**
1. Create a new PR
2. Push some code
3. Watch CI tests

**Expected behavior**
CI tests should ideally not fail due to things like timeouts. If they do fail in this way, there should at least be a way to detect that and re-run the failing tests.

**Screenshots**

**Server configuration and status**

**Additional context**

**Comment by flosincapite** [comment]
![Screenshot from 2020-05-03 12-20-43](https://user-images.githubusercontent.com/4074974/80923428-9c687d80-8d38-11ea-9553-227accd3f8e3.png)

**Comment by nijel** [comment]
There is some issue with chromedriver in the CI environment:

```
 ======================================================================
ERROR: setUpClass (weblate.trans.tests.test_selenium.SeleniumTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/weblate/weblate/weblate/trans/tests/test_selenium.py", line 123, in setUpClass
    cls.driver = webdriver.Chrome(options=options)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81


----------------------------------------------------------------------
```

The versions installed however seem to be matching:

```
2020-05-03T23:30:59.0024204Z Selecting previously unselected package chromium-browser.
2020-05-03T23:30:59.0185361Z Preparing to unpack .../3-chromium-browser_81.0.4044.122-0ubuntu0.18.04.1_amd64.deb ...
2020-05-03T23:30:59.0197057Z Unpacking chromium-browser (81.0.4044.122-0ubuntu0.18.04.1) ...
2020-05-03T23:31:06.2097926Z Selecting previously unselected package chromium-browser-l10n.
2020-05-03T23:31:06.2292635Z Preparing to unpack .../4-chromium-browser-l10n_81.0.4044.122-0ubuntu0.18.04.1_all.deb ...
2020-05-03T23:31:06.2301341Z Unpacking chromium-browser-l10n (81.0.4044.122-0ubuntu0.18.04.1) ...
2020-05-03T23:31:06.5381292Z Selecting previously unselected package chromium-chromedriver.
2020-05-03T23:31:06.5526986Z Preparing to unpack .../5-chromium-chromedriver_81.0.4044.122-0ubuntu0.18.04.1_amd64.deb ...
2020-05-03T23:31:06.5536239Z Unpacking chromium-chromedriver (81.0.4044.122-0ubuntu0.18.04.1) ...
```

I didn't see the test passing in past few days, it consistently fails with this error...

**Comment by flosincapite** [comment]
Yep, I saw that after I made this bug (see comment on my CL).

I am happy to debug.

How can I run one of these failing tests locally?

**Comment by nijel** [comment]
The tests are not failing locally. The problem is in the CI environment that chromedriver complains about incompatible chrome, while they both seem to be installed of same version. It has started 5 days ago.

**Comment by nijel** [comment]
I started to debug this in https://github.com/nijel/ci-selenium-test

**Comment by nijel** [comment]
The problem was that we install Chrome using apt and there is also Chrome preinstalled in the CI environment since https://github.com/actions/virtual-environments/issues/9. So far these two versions matched and it caused no issues, but now they diverged and the chromedriver we install was used with Chrome included in the CI environment.
