### ISSUE TITLE
Server Error on myMemory setup

### ISSUE THREAD

**Issue by buck-E** [WeblateOrg/weblate#3814]
**Describe the bug**
After setting up mymemory, clicking "Translate" for a language brings me to a Server Error page

**To Reproduce**
1. 
```
495 MT_SERVICES = (
496 #     "weblate.machinery.apertium.ApertiumAPYTranslation",
497 #     "weblate.machinery.baidu.BaiduTranslation",
498 #     "weblate.machinery.deepl.DeepLTranslation",
499 #     "weblate.machinery.glosbe.GlosbeTranslation",
500 #     "weblate.machinery.google.GoogleTranslation",
501 #     "weblate.machinery.microsoft.MicrosoftCognitiveTranslation",
502 #     "weblate.machinery.microsoftterminology.MicrosoftTerminologyService",
503 "weblate.machinery.mymemory.MyMemoryTranslation"
504 #     "weblate.machinery.netease.NeteaseSightTranslation",
505 #     "weblate.machinery.tmserver.AmagamaTranslation",
506 #     "weblate.machinery.tmserver.TMServerTranslation",
507 #     "weblate.machinery.yandex.YandexTranslation",
508 #     "weblate.machinery.saptranslationhub.SAPTranslationHub",
509 #     "weblate.machinery.youdao.YoudaoTranslation",
510 #     "weblate.machinery.weblatetm.WeblateTranslation",
511 #     "weblate.memory.machine.WeblateMemory",
512 )
.
.
.
527 # MyMemory identification email, see
528 # https://mymemory.translated.net/doc/spec.php
529 MT_MYMEMORY_EMAIL = "my@email.com"
```

2. Click on 'Translate' next to "German" on "https://mysite.com/projects/weblatetest/component-1/"
3. Now I am at a page that says:

```
Server Error
The server had serious problems serving your request. Trained monkeys are en-route fixing the issue.
```

**Expected behavior**
I expect the translation page, with mymemory features.  Or at least a specific error message that tells me where to start looking for the problem.

**Server configuration and status**
Please paste the output of `list_versions` and `check --deploy` commands over
here. Depending on installation these can be executed in different way, please
consult https://docs.weblate.org/en/latest/admin/management.html for more
details.

On pip installed Weblate:

```
$ weblate list_versions
 * Weblate: 4.0.3
 * Django: 3.0.5
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.0
 * lxml: 4.5.0
 * Pillow: 7.1.1
 * bleach: 3.1.4
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.9.0
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 44.0.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.3
 * celery: 4.4.2
 * kombu: 4.6.8
 * translation-finder: 2.0
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.36.0
 * diff-match-patch: 20181111
 * requests: 2.23.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.3
 * Cython: 0.29.16
 * misaka: 2.1.1
 * GitPython: 3.1.1
 * borgbackup: 1.1.11
 * Python: 3.8.2
 * Git: 2.25.1
 * psycopg2-binary: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * aeidon: 1.7.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.9.0-8-amd64 (x86_64)
```

**weblate check --deploy**
```
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.0.3/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.0.3/admin/backup.html

System check identified 5 issues (1 silenced).

```

**Additional context**

1 - Just a note that when I uncomment `"weblate.machinery.mymemory.MyMemoryTranslation"` but do not delete the indentation I get a python IndentError.  It is probably not related to this error.

2 - `systemctl --user status uwsgi-weblate`:

```
May 04 08:04:17 xxx[28638]: ERROR Internal Server Error: /translate/weblatetest/component-1/de/
                                   Traceback (most recent call last):
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/utils/classloader.py", line 30, in load_class
                                       module, attr = name.rsplit(".", 1)
                                   ValueError: not enough values to unpack (expected 2, got 1)
                                   
                                   During handling of the above exception, another exception occurred:
                                   
                                   Traceback (most recent call last):
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
                                       response = get_response(request)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
                                       response = self.process_exception_by_middleware(e, request)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
                                       response = wrapped_callback(request, *callback_args, **callback_kwargs)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/trans/views/edit.py", line 490, in translate
                                       return render(
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/trans/util.py", line 259, in render
                                       return django_render(request, template, context, status=status)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
                                       content = loader.render_to_string(template_name, context, request, using=using)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
                                       return template.render(context, request)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
                                       return self.template.render(context)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/template/base.py", line 171, in render
                                       return self._render(context)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
                                       return self.nodelist.render(context)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/template/base.py", line 936, in render
                                       bit = node.render_annotated(context)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
                                       return self.render(context)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
                                       return compiled_parent._render(context)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
                                       return self.nodelist.render(context)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/template/base.py", line 936, in render
                                       bit = node.render_annotated(context)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
                                       return self.render(context)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
                                       result = block.nodelist.render(context)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/template/base.py", line 936, in render
File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
                                       return self.render(context)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
                                       result = block.nodelist.render(context)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/template/base.py", line 936, in render
                                       bit = node.render_annotated(context)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/template/base.py", line 903, in render_annotated
                                       return self.render(context)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/template/library.py", line 192, in render
                                       output = self.func(*resolved_args, **resolved_kwargs)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/auth/templatetags/permissions.py", line 26, in perm
                                       return context["user"].has_perm(permission, obj)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/auth/models.py", line 453, in has_perm
                                       return SPECIALS[perm](self, perm, obj)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/auth/permissions.py", line 239, in check_machinery
                                       if not MACHINE_TRANSLATION_SERVICES.exists():
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/utils/classloader.py", line 101, in exists
                                       return bool(self.data)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
                                       res = instance.__dict__[self.name] = self.func(instance)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/utils/classloader.py", line 71, in data
                                       return self.load_data()
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/utils/classloader.py", line 63, in load_data
                                       obj = load_class(path, self.name)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/utils/classloader.py", line 32, in load_class
                                       raise ImproperlyConfigured(
                                   django.core.exceptions.ImproperlyConfigured: Error importing class w in MT_SERVICES: "not enough values to unpack (expected 2, got 1)"
May 04 08:04:18 gv uwsgi[28638]: [pid: 28638|app: 0|req: 2/2] 89.39.107.202 () {54 vars in 1115 bytes} [Mon May  4 06:04:16 2020] GET /translate/weblatetest/component-1/de/?q=state:%3Ctranslated => generated 11>
May 04 08:04:18 gv uwsgi[28638]: [pid: 28638|app: 0|req: 3/3] 89.39.107.202 () {48 vars in 741 bytes} [Mon May  4 06:04:18 2020] GET /site.webmanifest => generated 433 bytes in 44 msecs (HTTP/1.1 200) 10 header>
May 04 08:04:19 gv uwsgi[28638]: [pid: 28638|app: 0|req: 4/4] 89.39.107.202 () {48 vars in 741 bytes} [Mon May  4 06:04:19 2020] GET /site.webmanifest => generated 433 bytes in 26 msecs (HTTP/1.1 200) 10 header>
May 04 08:05:59 gv uwsgi[28638]: [pid: 28638|app: 0|req: 5/5] 89.39.107.202 () {54 vars in 1064 bytes} [Mon May  4 06:05:58 2020] GET /projects/weblatetest/component-1/ => generated 66654 bytes in 318 msecs (HT>
May 04 08:06:01 gv uwsgi[28638]: [pid: 28638|app: 0|req: 6/6] 89.39.107.202 () {48 vars in 741 bytes} [Mon May  4 06:06:01 2020] GET /site.webmanifest => generated 433 bytes in 28 msecs (HTTP/1.1 200) 10 header>
May 04 08:06:43 gv weblate[28638]: ERROR Internal Server Error: /translate/weblatetest/component-1/de/
                                   Traceback (most recent call last):
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/utils/classloader.py", line 30, in load_class
                                       module, attr = name.rsplit(".", 1)
                                   ValueError: not enough values to unpack (expected 2, got 1)
                                   
                                   During handling of the above exception, another exception occurred:
                                   
                                   Traceback (most recent call last):
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
                                       response = get_response(request)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
                                       response = self.process_exception_by_middleware(e, request)
.
.
.
File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/utils/classloader.py", line 63, in load_data
                                       obj = load_class(path, self.name)
                                     File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/utils/classloader.py", line 32, in load_class
                                       raise ImproperlyConfigured(
                                   django.core.exceptions.ImproperlyConfigured: Error importing class w in MT_SERVICES: "not enough values to unpack (expected 2, got 1)"
May 04 08:06:44 gv uwsgi[28638]: [pid: 28638|app: 0|req: 7/7] 89.39.107.202 () {54 vars in 1115 bytes} [Mon May  4 06:06:41 2020] GET /translate/weblatetest/component-1/de/?q=state:%3Ctranslated => generated 11>
May 04 08:06:44 gv uwsgi[28638]: [pid: 28638|app: 0|req: 8/8] 89.39.107.202 () {48 vars in 741 bytes} [Mon May  4 06:06:44 2020] GET /site.webmanifest => generated 433 bytes in 27 msecs (HTTP/1.1 200) 10 header>
```

So these instructions may not be complete: https://docs.weblate.org/en/latest/admin/machine.html#mymemory

Or there may be a bug with weblate.

Or there may be a temporary error with mymemory.

I *think* it is a bug with weblate based on the lines:

```
File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/utils/classloader.py", line 30, in load_class
                                       module, attr = name.rsplit(".", 1)
                                   ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by nijel** [comment]
Or there is a bug in your configuration. `MT_SERVICES` is supposed to be list or tuple.

**Comment by buck-E** [comment]
Oh yes, of course.  I did not even realize I had removed the comma, and my eyes were scanning in json mode I guess.  Thank you.  Issue resolved.  (I'm not sure it's *working* but this error is gone.)

**Comment by buck-E** [comment]
P.S.  It is working very well.  Excellent feature.
