### ISSUE TITLE
Bug: Can not delete component due to some error checks

### ISSUE THREAD

**Issue by ionmincu** [WeblateOrg/weblate#3849]
**Describe the bug**
Can not delete component, error is thrown after clicking confirm button.

**To Reproduce**
1. Go to django admin 
2. Go to component page
3. Delete component
4. Confirm
5. Error is shown after a few seconds

**Expected behavior**
Component should be deleted successfully 

**Server configuration and status**

```

 * Weblate: 4.0.1
 * Django: 3.0.5
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.0
 * lxml: 4.3.2
 * Pillow: 7.1.1
 * bleach: 3.1.4
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.9.0
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.1
 * celery: 4.4.2
 * kombu: 4.6.8
 * translation-finder: 2.0
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.23.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.3
 * Cython: 0.29.16
 * misaka: 2.1.1
 * GitPython: 3.1.1
 * borgbackup: 1.1.11
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.7.7
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.12.39
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * Mercurial: 4.8.2
 * git-svn: 2.20.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.sendgrid.net
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.15.0-1082-azure (x86_64)

```

**Additional context**

```
 uwsgi stderr | ERROR Internal Server Error: /admin/trans/component/636/delete/
 Traceback (most recent call last):
   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 243, in _commit
     return self.connection.commit()
 psycopg2.IntegrityError: insert or update on table "checks_check" violates foreign key constraint "checks_check_unit_id_c312ecef_fk_trans_unit_id"
 DETAIL:  Key (unit_id)=(904510) is not present in table "trans_unit".


 The above exception was the direct cause of the following exception:

 Traceback (most recent call last):
   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
     response = get_response(request)
   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 115, in _get_response
     response = self.process_exception_by_middleware(e, request)
   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 113, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/usr/local/lib/python3.7/dist-packages/django/contrib/admin/options.py", line 607, in wrapper
     return self.admin_site.admin_view(view)(*args, **kwargs)
   File "/usr/local/lib/python3.7/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
     response = view_func(request, *args, **kwargs)
   File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
     response = view_func(request, *args, **kwargs)
   File "/usr/local/lib/python3.7/dist-packages/django/contrib/admin/sites.py", line 231, in inner
     return view(request, *args, **kwargs)
   File "/usr/local/lib/python3.7/dist-packages/django/utils/decorators.py", line 43, in _wrapper
     return bound_method(*args, **kwargs)
   File "/usr/local/lib/python3.7/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
     response = view_func(request, *args, **kwargs)
   File "/usr/local/lib/python3.7/dist-packages/django/contrib/admin/options.py", line 1831, in delete_view
     return self._delete_view(request, object_id, extra_context)
   File "/usr/local/lib/python3.7/dist-packages/django/db/transaction.py", line 232, in __exit__
     connection.commit()
   File "/usr/local/lib/python3.7/dist-packages/django/utils/asyncio.py", line 26, in inner
     return func(*args, **kwargs)
   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 267, in commit
     self._commit()
   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 243, in _commit
     return self.connection.commit()
   File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 90, in __exit__
     raise dj_exc_value.with_traceback(traceback) from exc_value
   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 243, in _commit
     return self.connection.commit()

```

**Comment by nijel** [comment]
Please upgrade, this has been fixed in 4.0.2 by 321abb0ce46de08ceeefdc4e47952f860844853b.
