### ISSUE TITLE
Expectations of `import_demo` command

### ISSUE THREAD

**Issue by julen** [WeblateOrg/weblate#3867]
Please treat this ticket as feedback rather than a specific bug report — I couldn't find a different channel to do so and I hope this is OK. Maybe some actionable items can be taken out of this, and I highlight some at the end.

I was setting up Weblate from source for the first time (I'm at d703d96, using almost verbatim settings from _settings_example.py_), and in order to have some data to play with, I tried the recently-added `import_demo` command. This created the Demo project and android + gettext components.

The expectations as to what should happen next have been confusing for me though: I was hoping the repos would be checked out and the strings imported (Celery was already running), but I came across _demo/android_ and _demo/gettext_ as empty.

At the same time, I could access the component progress page but it reported nothing — the contents of the page looked blank and broken. In the background an XHR request was being done at 1000ms intervals.

I ran a `updategit demo` but no feedback was reported (Django check warnings aside). Couldn't notice any errors in the celery logs. Then ran `updategit demo --foreground` and could finally see strings flowing in.

All in all:
* `updategit` could report some feedback to the user (e.g. _X is being handled in the background. To track progress do Y._)
* The [docs on bootstraping](https://docs.weblate.org/en/latest/contributing/start.html#bootstraping-your-devel-instance) could be more specific as to what to do after `import_demo` (in case something actually needs to be done).
* The component progress page could be a bit more robust to handle error cases like the one described above.
* To set the right expectations, I missed some concise documentation on how strings are meant to flow in Weblate.

**Comment by nijel** [comment]
This really seems like something was broken with your Celery setup. It's hard to tell what, though.

The import itself happens in Celery - the command just creates the components and triggers background update in Celery, which will parse the translations and import them into Weblate.

Did Celery receive the task? It would be visible in the main log, once it gets to processing it, it will appear in one of the worker logs.

**Comment by julen** [comment]
I can see Celery did receive the tasks (`Received task: weblate.trans.tasks.perform_update[...]`). I'll remove the projects and run `import_demo` again to better understand what could have gone wrong.

**Comment by julen** [comment]
Ok, I retried from a clean slate (removed _data/*_, dropped DB, and migrated), and now it did import everything without further actions. One thing I noticed though is the following traceback in the logs:
```py
[2020-05-14 09:46:21,111: ERROR/ForkPoolWorker-3] Failure while executing task: FileParseError: No such file or directory
[2020-05-14 09:46:21,112: ERROR/ForkPoolWorker-3] Failure while executing task: FileParseError: {'signal': <Signal: task_failure providing_args={'einfo', 'kwargs', 'exception', 'traceback', 'args', 'task_id'}>, 'sender': <@task: weblate.trans.tasks.component_after_save of weblate at 0x10cd47590>, 'task_id': '256c3e0e-7125-40c7-bc21-576b660bef31', 'args': [2, True, False, False, False], 'kwargs': {'skip_push': True}, 'traceback': <traceback object at 0x1144f3b40>, 'einfo': <ExceptionInfo: FileParseError('No such file or directory')>}
[2020-05-14 09:46:21,112: ERROR/ForkPoolWorker-3] Failure while executing task
Traceback (most recent call last):
  File "~/dev/weblate/weblate/trans/models/component.py", line 2201, in template_store
    return self.load_template_store()
  File "~/dev/weblate/weblate/trans/models/component.py", line 2191, in load_template_store
    return self.file_format_cls.parse(self.get_template_filename())
  File "~/dev/weblate/weblate/formats/base.py", line 190, in parse
    return cls(storefile, template_store, language_code, is_template)
  File "~/dev/weblate/weblate/formats/ttkit.py", line 219, in __init__
    super().__init__(storefile, template_store, language_code, is_template)
  File "~/dev/weblate/weblate/formats/base.py", line 202, in __init__
    self.store = self.load(storefile)
  File "~/dev/weblate/weblate/formats/ttkit.py", line 242, in load
    return cls.parse_store(storefile)
  File "~/dev/weblate/weblate/formats/ttkit.py", line 269, in parse_store
    with open(storefile, "rb") as handle:
FileNotFoundError: [Errno 2] No such file or directory: '~/dev/weblate/data/vcs/demo/gettext/app/src/main/res/values/strings.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.virtualenvs/weblate/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "~/.virtualenvs/weblate/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "~/.virtualenvs/weblate/lib/python3.7/site-packages/celery/app/base.py", line 487, in run
    return task._orig_run(*args, **kwargs)
  File "~/dev/weblate/weblate/trans/tasks.py", line 277, in component_after_save
    changed_git, changed_setup, changed_template, changed_shaping, skip_push
  File "~/dev/weblate/weblate/trans/models/component.py", line 2005, in after_save
    was_change = self.create_translations()
  File "~/dev/weblate/weblate/trans/models/component.py", line 1444, in create_translations
    force, langs, request, changed_template, from_link
  File "~/dev/weblate/weblate/trans/models/component.py", line 1484, in _create_translations
    self.template_store.check_valid()
  File "~/.virtualenvs/weblate/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "~/dev/weblate/weblate/trans/models/component.py", line 2204, in template_store
    self.handle_parse_error(error)
  File "~/dev/weblate/weblate/trans/models/component.py", line 1273, in handle_parse_error
    raise FileParseError(error_message)
weblate.trans.exceptions.FileParseError: No such file or directory
```

Is that expected? If so, maybe the exception should be caught and an explanation added to describe what's going on.

Also, I notice there are system and performance checks in the admin panel, but it won't complain at all if Celery is not running — it's probably good if admins know about it.

**Comment by nijel** [comment]
This is certainly not expected. There is a race condition in the code as the extra components might be created earlier than initial one is updated. I will fix that.

The performance page should complain about Celery not processing tasks.
