### ISSUE TITLE
Internal Server Error on download translation

### ISSUE THREAD

**Issue by SlavekB** [WeblateOrg/weblate#3897]
**Describe the bug**
I have no idea if a robot is trying to download it, but it causes a crash - in addition to the example given here, the same happens for other languages.
```
Internal Server Error: /weblate/download/tdevelop/tdevelop/eo/

TypeError at /weblate/download/tdevelop/tdevelop/eo/
expected string or bytes-like object

Request Method: GET
Request URL: https://mirror.git.trinitydesktop.org/weblate/download/tdevelop/tdevelop/eo/?format=xliff&q=state:%3Ctranslated
Django Version: 3.0.6
Python Executable: /usr/bin/python3
Python Version: 3.7.3
Python Path: ['/var/lib/weblate/lib/python3.7/site-packages/git/ext/gitdb', '/', '/var/lib/weblate/lib/python37.zip', '/var/lib/weblate/lib/python3.7', '/var/lib/weblate/lib/python3.7/lib-dynload', '/usr/lib/python3.7', '/var/lib/weblate/lib/python3.7/site-packages', '/var/lib/weblate/lib/python3.7/site-packages/gitdb/ext/smmap']
Server time: Mon, 18 May 2020 06:41:38 +0000
```

**To Reproduce**
```
Traceback (most recent call last):
  File "/var/lib/weblate/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/lib/weblate/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/lib/weblate/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/lib/weblate/lib/python3.7/site-packages/weblate/trans/views/files.py", line 99, in download_translation
    return download_translation_file(obj, **kwargs)
  File "/var/lib/weblate/lib/python3.7/site-packages/weblate/utils/views.py", line 197, in download_translation_file
    exporter.add_units(units)
  File "/var/lib/weblate/lib/python3.7/site-packages/weblate/formats/exporters.py", line 120, in add_units
    self.add_unit(unit)
  File "/var/lib/weblate/lib/python3.7/site-packages/weblate/formats/exporters.py", line 128, in add_unit
    output = self.build_unit(unit)
  File "/var/lib/weblate/lib/python3.7/site-packages/weblate/formats/exporters.py", line 262, in build_unit
    converted_source = xliff_string_to_rich(unit.source)
  File "/var/lib/weblate/lib/python3.7/site-packages/weblate/trans/util.py", line 303, in xliff_string_to_rich
    return [parse_xliff(string)]
  File "/var/lib/weblate/lib/python3.7/site-packages/translate/storage/placeables/lisa.py", line 218, in parse_xliff
    return xml_to_strelem(etree.fromstring('<source>%s</source>' % (pstr), parser))
  File "/var/lib/weblate/lib/python3.7/site-packages/translate/storage/placeables/lisa.py", line 112, in xml_to_strelem
    sub.append(make_placeable(child_dom_node, xml_space))
  File "/var/lib/weblate/lib/python3.7/site-packages/translate/storage/placeables/lisa.py", line 83, in make_placeable
    _namespace, tag = misc.parse_tag(node.tag)
  File "/var/lib/weblate/lib/python3.7/site-packages/translate/storage/xml_extract/misc.py", line 73, in parse_tag
    match = tag_pattern.match(full_tag)

Exception Type: TypeError at /weblate/download/tdevelop/tdevelop/eo/
Exception Value: expected string or bytes-like object
Request information:
USER: Anonymous

GET:
format = 'xliff'
q = 'state:<translated'

POST: No POST data

FILES: No FILES data

COOKIES: No cookie data
```

**Expected behavior**
It probably shouldn't crash.

**Server configuration and status**

```
 * Weblate: 4.0.4
 * Django: 3.0.6
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.1
 * lxml: 4.5.0
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.9.0
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 46.1.3
 * jellyfish: 0.7.2
 * openpyxl: 3.0.3
 * celery: 4.4.2
 * kombu: 4.6.8
 * translation-finder: 2.0
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.36.1
 * diff-match-patch: 20181111
 * requests: 2.23.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.3
 * Cython: 0.29.17
 * misaka: 2.1.1
 * GitPython: 3.1.2
 * borgbackup: 1.1.11
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2-binary: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * aeidon: 1.7.0
 * Mercurial: 4.8.2
 * git-svn: 2.20.1
 * git-review: 1.27.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django_sendmail_backend.backends.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 3.16.6-042stab141.42 (x86_64)
```
```
System check identified no issues (3 silenced).
```

**Comment by nijel** [comment]
Can you please try if 8b8f594b297f74cdec0667c3a35c15f6d68177cb fixes this? I'm not sure it's your issue...

Otherwise it would be great if you can look into the HTML error mail (you probably got one) and look at parameters passed to parse_xliff, that would make it easier to identify what went wrong.

**Comment by SlavekB** [comment]
Unfortunately, the patch didn't help. This seems to fail on a snippet of PHP code that is there as a string to translate:
```
parser
  <lxml.etree.XMLParser object at 0x7fb8f0114210>
pstr
  ('<?php\n'
 'if (!defined("FILENAME")){\n'
 'define("FILENAME",0);\n'
 '/*\n'
 '* @author AUTHOR\n'
 '*/\n'
 '\n'
 'class CLASSNAME extends BASECLASS {\n'
 '  //constructor\n'
 '  function CLASSNAME(){\n'
 '   BASECLASS::BASECLASS();\n'
 '  }\n'
 ' }\n'
 '}\n'
 '?>')
```
See [source string on TDE Weblate](https://mirror.git.trinitydesktop.org/weblate/translate/tdevelop/tdevelop/en/?checksum=f60f947fac859ff).
