### ISSUE TITLE
Bug: Cursor already closed

### ISSUE THREAD

**Issue by ionmincu** [WeblateOrg/weblate#3942]
**Describe the bug**
When downloading files over api random files can't be downloaded due to the following error (in console):
```
psycopg2.InterfaceError: cursor already closed
```

It also appears when getting `GET /api/translations/?page=162`

**To Reproduce**
1. Download resx files via API

**Expected behavior**
File should be downloaded.

**Server configuration and status**

```

 * Weblate: 4.0.4
 * Django: 3.0.6
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.1
 * lxml: 4.3.2
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.9.0
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.1
 * celery: 4.4.2
 * kombu: 4.6.8
 * translation-finder: 2.0
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.23.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.3
 * Cython: 0.29.17
 * misaka: 2.1.1
 * GitPython: 3.1.2
 * borgbackup: 1.1.11
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.7.7
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.13.4
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * Mercurial: 5.4
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.sendgrid.net
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.15.0-1082-azure (x86_64)

```

**Additional context**

```
ERROR Internal Server Error: /api/translations/<project>/<component>/pt-BR/file/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 97, in inner
    return func(*args, **kwargs)
psycopg2.InterfaceError: cursor already closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/weblate/api/views.py", line 816, in file
    obj = self.get_object()
  File "/usr/local/lib/python3.7/dist-packages/weblate/api/views.py", line 137, in get_object
    return get_object_or_404(queryset, **lookup)
  File "/usr/local/lib/python3.7/dist-packages/django/shortcuts.py", line 76, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 1263, in _fetch_all
    self._prefetch_related_objects()
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 782, in _prefetch_related_objects
    prefetch_related_objects(self._result_cache, *self._prefetch_related_lookups)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 1651, in prefetch_related_objects
    obj_list, additional_lookups = prefetch_one_level(obj_list, prefetcher, lookup, level)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 1781, in prefetch_one_level
    all_related_objects = list(rel_qs)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 276, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/compiler.py", line 1184, in execute_sql
    return list(result)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/compiler.py", line 1583, in cursor_iter
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/compiler.py", line 1583, in <lambda>
    for rows in iter((lambda: cursor.fetchmany(itersize)), sentinel):
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 97, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 97, in inner
    return func(*args, **kwargs)
django.db.utils.InterfaceError: cursor already closed
```

**Comment by nijel** [comment]
I didn't see this error yet, so it's quite likely that it's something in your environment. Anything special in your database configuration (for example using persistent connections)? Can you try upgrading psycopg2 to more recent version?

**Comment by ionmincu** [comment]
I'm actually using the docker versions of the weblate.  Using Weblate latest 4.04, but I came from a docker-compose version of weblate. Maybe the database is a bit out of date.

```
  database:
    image: postgres:9.6-alpine
  cache:
    image: redis:4-alpine
```

**Comment by nijel** [comment]
The older database server should not be causing this, and migrating it in Docker is a bit tricky, see https://github.com/docker-library/postgres/issues/37.

I've tried upgrading client library in https://github.com/WeblateOrg/docker/commit/cce0f59ccdebab954dcd43bb88a1ae13ad8ae349, that might make a difference. Can you please pull weblate:edge once that it built and try if that makes any difference?

**Comment by ionmincu** [comment]
I can't go with Edge I guess, I should wait for the full release.

**Comment by nijel** [comment]
The only difference compared to stable are few updated dependencies, there should be nothing risky in the update if you are worried about that (it's still stable release of Weblate, just having some additional changes in the Docker container).

**Comment by ionmincu** [comment]
Alright I'll give this a try then

**Comment by ionmincu** [comment]
@nijel Sorry for the delay, aparantly this did unlock some downloads, the source text could be downloaded without errors.

But some errors still appear:

<details><summary>See error details</summary>

```

 INFO <project>/<component>/ru: committing pending changes (download)

 INFO <project>/<component>/fr: committing ['/app/data/vcs/<project>/somerext.resx'] as NAME NAME <email@company.com>

 ERROR Internal Server Error: /api/translations/<project>/<component_2>/ru/file/
 Traceback (most recent call last):
   File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/component.py", line 637, in get_source
     return self._sources[id_hash]
 KeyError: 724035609943561601

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 238, in _cursor
     return self._prepare_cursor(self.create_cursor(name))
   File "/usr/local/lib/python3.7/dist-packages/django/utils/asyncio.py", line 26, in inner
     return func(*args, **kwargs)
   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/postgresql/base.py", line 231, in create_cursor
     cursor = self.connection.cursor()
 psycopg2.InterfaceError: connection already closed

 The above exception was the direct cause of the following exception:

 Traceback (most recent call last):
   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
     response = get_response(request)
   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 115, in _get_response
     response = self.process_exception_by_middleware(e, request)
   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 113, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
     return view_func(*args, **kwargs)
   File "/usr/local/lib/python3.7/dist-packages/rest_framework/viewsets.py", line 114, in view
     return self.dispatch(request, *args, **kwargs)
   File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 505, in dispatch
     response = self.handle_exception(exc)
   File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 465, in handle_exception
     self.raise_uncaught_exception(exc)
   File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
     raise exc
   File "/usr/local/lib/python3.7/dist-packages/rest_framework/views.py", line 502, in dispatch
     response = handler(request, *args, **kwargs)
   File "/usr/local/lib/python3.7/dist-packages/weblate/api/views.py", line 820, in file
     return download_translation_file(obj, fmt)
   File "/usr/local/lib/python3.7/dist-packages/weblate/utils/views.py", line 205, in download_translation_file
     translation.commit_pending("download", None)
   File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/translation.py", line 493, in commit_pending
     self.update_units(store, author_name, author.id)
   File "/usr/lib/python3.7/contextlib.py", line 74, in inner
     return func(*args, **kwds)
   File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/translation.py", line 639, in update_units
     state = unit.get_unit_state(pounit, "")
   File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/unit.py", line 262, in get_unit_state
     and self.source_info != self
   File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py", line 48, in __get__
     res = instance.__dict__[self.name] = self.func(instance)
   File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/unit.py", line 905, in source_info
     return self.translation.component.get_source(self.id_hash)
   File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/component.py", line 643, in get_source
     source = source_units.get(id_hash=id_hash)
   File "/usr/local/lib/python3.7/dist-packages/django/db/models/manager.py", line 82, in manager_method
     return getattr(self.get_queryset(), name)(*args, **kwargs)
   File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 411, in get
     num = len(clone)
   File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 258, in __len__
     self._fetch_all()
   File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 1261, in _fetch_all
     self._result_cache = list(self._iterable_class(self))
   File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 57, in __iter__
     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
   File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/compiler.py", line 1149, in execute_sql
     cursor = self.connection.cursor()
   File "/usr/local/lib/python3.7/dist-packages/django/utils/asyncio.py", line 26, in inner
     return func(*args, **kwargs)
   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 260, in cursor
     return self._cursor()
   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 238, in _cursor
     return self._prepare_cursor(self.create_cursor(name))
   File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 90, in __exit__
     raise dj_exc_value.with_traceback(traceback) from exc_value
   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 238, in _cursor
     return self._prepare_cursor(self.create_cursor(name))
   File "/usr/local/lib/python3.7/dist-packages/django/utils/asyncio.py", line 26, in inner
     return func(*args, **kwargs)
   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/postgresql/base.py", line 231, in create_cursor
     cursor = self.connection.cursor()
 django.db.utils.InterfaceError: connection already closed

 DEBUG <project>/<some_component>: skipped push: push on commit disabled
```

</details>

**Comment by humphrey** [comment]
I get the same issue, with a very similar stack trace in my own custom django project (not using weblate).  I do not yet have a solution, but the issue only occurs when I use `uwsgi`.  If I use `manage.py runserver` it does not occur.
