### ISSUE TITLE
Can not upgrade from 3.11.3 to 4.0 and later

### ISSUE THREAD

**Issue by zmartyz** [WeblateOrg/weblate#3947]
Hello Michal,

I am having trouble to upgrade Weblate from 3.11.3 to 4.0 and later versions.
When installing requirements ( pip install -r requirements.txt )  - after git fetch and git checkout weblate-4.0, i get these error messages during the installation: 

ERROR: weblate 3.9.1 has requirement bleach==3.1.0, but you'll have bleach 3.1.3 which is incompatible.
ERROR: weblate 3.9.1 has requirement Cython==0.29.13, but you'll have cython 0.29.15 which is incompatible.
ERROR: weblate 3.9.1 has requirement Django<2.3,>=2.2, but you'll have django 3.0.6 which is incompatible.
ERROR: weblate 3.9.1 has requirement django-compressor==2.3, but you'll have django-compressor 2.4 which is incompatible.
ERROR: weblate 3.9.1 has requirement django-crispy-forms==1.7.2, but you'll have django-crispy-forms 1.9.1 which is incompatible.
ERROR: weblate 3.9.1 has requirement djangorestframework<3.11,>=3.10, but you'll have djangorestframework 3.11.0 which is incompatible.
ERROR: weblate 3.9.1 has requirement hiredis==1.0.0, but you'll have hiredis 1.0.1 which is incompatible.
ERROR: weblate 3.9.1 has requirement python-dateutil==2.8.0, but you'll have python-dateutil 2.8.1 which is incompatible.
ERROR: weblate 3.9.1 has requirement sentry_sdk==0.12.3, but you'll have sentry-sdk 0.14.3 which is incompatible.
ERROR: weblate 3.9.1 has requirement six==1.12.0, but you'll have six 1.14.0 which is incompatible.
ERROR: weblate 3.9.1 has requirement social-auth-core==3.2.0, but you'll have social-auth-core 3.3.3 which is incompatible.
ERROR: weblate 3.9.1 has requirement translation-finder==1.7, but you'll have translation-finder 2.0 which is incompatible.

When i try to ignore these errors and try to do manage.py migrate --noinput, i get the following output: 

Traceback (most recent call last):
  File "/opt/weblate/lib/python3.6/site-packages/django/core/cache/__init__.py", line 50, in _create_cache
    backend_cls = import_string(backend)
  File "/opt/weblate/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/opt/weblate/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/weblate/lib/python3.6/site-packages/django_redis/cache.py", line 8, in <module>
    from .util import load_class
  File "/opt/weblate/lib/python3.6/site-packages/django_redis/util.py", line 8, in <module>
    from django.utils import six
ImportError: cannot import name 'six'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/weblate/weblate-src/weblate/vcs/base.py", line 338, in is_supported
    delete_configuration_error(cls.name.lower())
  File "/opt/weblate/weblate-src/weblate/trans/util.py", line 160, in delete_configuration_error
    errors = cache.get("configuration-errors", [])
  File "/opt/weblate/lib/python3.6/site-packages/django/core/cache/__init__.py", line 98, in __getattr__
    return getattr(caches[DEFAULT_CACHE_ALIAS], name)
  File "/opt/weblate/lib/python3.6/site-packages/django/core/cache/__init__.py", line 79, in __getitem__
    cache = _create_cache(alias)
  File "/opt/weblate/lib/python3.6/site-packages/django/core/cache/__init__.py", line 53, in _create_cache
    "Could not find backend '%s': %s" % (backend, e))
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'django_redis.cache.RedisCache': cannot import name 'six'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/weblate/lib/python3.6/site-packages/django/core/cache/__init__.py", line 50, in _create_cache
    backend_cls = import_string(backend)
  File "/opt/weblate/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/opt/weblate/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/weblate/lib/python3.6/site-packages/django_redis/cache.py", line 8, in <module>
    from .util import load_class
  File "/opt/weblate/lib/python3.6/site-packages/django_redis/util.py", line 8, in <module>
    from django.utils import six
ImportError: cannot import name 'six'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./manage.py", line 32, in <module>
    main()
  File "/opt/weblate/weblate-src/weblate/runner.py", line 32, in main
    execute_from_command_line(argv)
  File "/opt/weblate/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/weblate/lib/python3.6/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/opt/weblate/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/weblate/lib/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/opt/weblate/lib/python3.6/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/weblate/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/weblate/weblate-src/weblate/addons/models.py", line 45, in <module>
    from weblate.trans.models import Component, Unit
  File "/opt/weblate/weblate-src/weblate/trans/models/__init__.py", line 33, in <module>
    from weblate.trans.models.component import Component
  File "/opt/weblate/weblate-src/weblate/trans/models/component.py", line 164, in <module>
    class Component(models.Model, URLMixin, PathMixin):
  File "/opt/weblate/weblate-src/weblate/trans/models/component.py", line 189, in Component
    choices=VCS_REGISTRY.get_choices(),
  File "/opt/weblate/weblate-src/weblate/utils/classloader.py", line 106, in get_choices
    for x in sorted(self)
  File "/opt/weblate/weblate-src/weblate/utils/classloader.py", line 92, in __iter__
    return self.data.__iter__()
  File "/opt/weblate/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/weblate/weblate-src/weblate/utils/classloader.py", line 71, in data
    return self.load_data()
  File "/opt/weblate/weblate-src/weblate/vcs/models.py", line 34, in load_data
    if not vcs.is_supported():
  File "/opt/weblate/weblate-src/weblate/vcs/base.py", line 344, in is_supported
    cls.name, version, cls.req_version, error
  File "/opt/weblate/weblate-src/weblate/trans/util.py", line 140, in add_configuration_error
    errors = cache.get("configuration-errors", [])
  File "/opt/weblate/lib/python3.6/site-packages/django/core/cache/__init__.py", line 98, in __getattr__
    return getattr(caches[DEFAULT_CACHE_ALIAS], name)
  File "/opt/weblate/lib/python3.6/site-packages/django/core/cache/__init__.py", line 79, in __getitem__
    cache = _create_cache(alias)
  File "/opt/weblate/lib/python3.6/site-packages/django/core/cache/__init__.py", line 53, in _create_cache
    "Could not find backend '%s': %s" % (backend, e))
django.core.cache.backends.base.InvalidCacheBackendError: Could not find backend 'django_redis.cache.RedisCache': cannot import name 'six'

I also tried to upgrade to newer versions, but the problems with package requirments are same, output from manage.py migrate is little bit different.
 

./manage.py list_versions      same output as manage.py migrate --noinput
./manage.py check --deploy  same output as manage.py migrate --noinput

System is CenOS 8.1

Please, can you suggest some solution ?
Thank you

**Comment by nijel** [comment]
You need to update depdendencies. Not sure how you did install in the first place, but `pip install -e .` or `pip install -r requirements.txt` might be thing to do. I will clarify the ugprade instructions to cover this.

**Comment by zmartyz** [comment]
pip install -r requirements.txt shows errors that i have newer packages and that they are incompatible.

**Comment by nijel** [comment]
Try adding -U to the command line

**Comment by zmartyz** [comment]
I tried it with parametr -U but unfortunatly, still have these errors: 
ERROR: weblate 3.9.1 has requirement bleach==3.1.0, but you'll have bleach 3.1.5 which is incompatible.
ERROR: weblate 3.9.1 has requirement borgbackup==1.1.10, but you'll have borgbackup 1.1.11 which is incompatible.
ERROR: weblate 3.9.1 has requirement celery==4.3.0, but you'll have celery 4.4.2 which is incompatible.
ERROR: weblate 3.9.1 has requirement Cython==0.29.13, but you'll have cython 0.29.19 which is incompatible.
ERROR: weblate 3.9.1 has requirement Django<2.3,>=2.2, but you'll have django 3.0.6 which is incompatible.
ERROR: weblate 3.9.1 has requirement django-appconf==1.0.3, but you'll have django-appconf 1.0.4 which is incompatible.
ERROR: weblate 3.9.1 has requirement django-compressor==2.3, but you'll have django-compressor 2.4 which is incompatible.
ERROR: weblate 3.9.1 has requirement django-crispy-forms==1.7.2, but you'll have django-crispy-forms 1.9.1 which is incompatible.
ERROR: weblate 3.9.1 has requirement django-redis==4.10.0, but you'll have django-redis 4.11.0 which is incompatible.
ERROR: weblate 3.9.1 has requirement djangorestframework<3.11,>=3.10, but you'll have djangorestframework 3.11.0 which is incompatible.
.
.
.

**Comment by nijel** [comment]
It still reports weblate 3.9.1 installed. You should probably do `pip install -e .`

**Comment by zmartyz** [comment]
Hello, so the problem with package dependencies was solved with "pip install -e ." command, but when i try to perform "manage.py migrate --noinput" it ends up with this error:

Running migrations:
  Applying trans.0064_fulltext_index...Traceback (most recent call last):
  File "/opt/weblate/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedFile: could not open extension control file "/usr/share/pgsql/extension/pg_trgm.control": No such file or directory


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 32, in <module>
    main()
  File "/opt/weblate/weblate-src/weblate/runner.py", line 32, in main
    execute_from_command_line(argv)
  File "/opt/weblate/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/weblate/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/weblate/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/weblate/lib/python3.6/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/opt/weblate/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/weblate/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 233, in handle
    fake_initial=fake_initial,
  File "/opt/weblate/lib/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/weblate/lib/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/weblate/lib/python3.6/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/weblate/lib/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/weblate/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/opt/weblate/weblate-src/weblate/trans/migrations/0064_fulltext_index.py", line 27, in create_index
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
  File "/opt/weblate/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "/opt/weblate/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/weblate/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/weblate/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/weblate/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/weblate/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: could not open extension control file "/usr/share/pgsql/extension/pg_trgm.control": No such file or directory

Please, do you have any suggestion for this? Thank you

**Comment by nijel** [comment]
That one seems to be in -contrib package on some distros, see https://dba.stackexchange.com/a/165301/138847

**Comment by zmartyz** [comment]
Thank you
