### ISSUE TITLE
auto_translate method failed if runned after translation re-creation

### ISSUE THREAD

**Issue by loktionovam** [WeblateOrg/weblate#3990]
**Describe the bug**

I try to write addon which removes an existing translation,  creates new translation and applies `weblate.trans.tasks.auto_translate` using weblate translation memory. After that `auto_translate` method fails for each translation in a component. Is this a bug in `weblate.trans.tasks.auto_translate` (maybe some race condition)?

* Traceback:

```python
celery-synchronize stderr | 2020-06-03 09:53:51,496 ERROR Failure while executing task
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/weblate/machinery/base.py", line 289, in translate
    result = self.download_translations(source, language, text, unit, user)
  File "/usr/local/lib/python3.7/dist-packages/weblate/memory/machine.py", line 55, in download_translations
    memory.refresh()
  File "/usr/local/lib/python3.7/dist-packages/weblate/memory/storage.py", line 118, in refresh
    self.__dict__['searcher'] = self.searcher.refresh()
  File "/usr/local/lib/python3.7/dist-packages/whoosh/searching.py", line 251, in refresh
    newreader = self._ix.reader(reuse=self.ixreader)
  File "/usr/local/lib/python3.7/dist-packages/whoosh/index.py", line 548, in reader
    info.generation, reuse=reuse)
  File "/usr/local/lib/python3.7/dist-packages/whoosh/index.py", line 539, in _reader
    r.close()
  File "/usr/local/lib/python3.7/dist-packages/whoosh/reading.py", line 670, in close
    raise ReaderClosed("Reader already closed")
whoosh.reading.ReaderClosed: Reader already closed

During handling of the above exception, another exception occurred:
```

* Addon code:

```python
from weblate.trans.tasks import auto_translate
....
....
....
    for translation in component.translation_set.iterator():
        with transaction.atomic():
            logger.info("Processing '%s'", translation)
            if translation.language_code in TEMPLATES:
                logger.info(
                    "Translation '%s' is template translation, so skipping",
                    translation
                )
                continue

            logger.info("Deletion user is: '%s'", user)
            logger.info("Remove '%s'", translation)
            translation.remove(user)

            language = translation.language
            logger.info("Create new translation for '%s' language", language)
            new_translation = component.add_new_language(
                language=language,
                request=request,
                send_signal=False)

        if translation.is_source:
            logger.info(
                "Skipping auto translation for source translation '%s'",
                translation
            )
            continue
        # if sleep, then auto_translate will works. Race condition here?
        # sleep(10)
        run_auto_translate(user.pk, new_translation, configuration)

    logger.info(
        "Translation recreate for '%s' component completed", component.name
    )


def run_auto_translate(user_id, translation, configuration):
    logger.info(
        "Apply auto translation to '%s'", translation
    )
    transaction.on_commit(
        lambda: auto_translate.apply(
            args=(user_id, translation.pk), kwargs=configuration,
        )
    )
```

* Addon configuration:

```python
{
    'auto_source': 'mt',
    'component': '',
    'engines': ['weblate-translation-memory'],
    'filter_type': 'all',
    'mode': 'translate',
    'threshold': 80
}
```

**Expected behavior**

`weblate.trans.tasks.auto_translate` will works without errors.

**Screenshots**

**Server configuration and status**
Please paste the output of `list_versions` and `check --deploy` commands over
here. Depending on installation these can be executed in different way, please
consult https://docs.weblate.org/en/latest/admin/management.html for more
details.

On pip installed Weblate:

```
weblate list_versions
weblate check --deploy
```

On Git checkout:

```
./manage.py list_versions
./manage.py check --deploy
```

Using docker-compose:

```
docker-compose exec weblate weblate list_versions
Start 'settings-override.py'
Start defining custom active directory authentication
'WEBLATE_TRANSLATION_SYNCHRONIZATION_ENABLE': 'True'
System check identified some issues:

INFOS:
?: (weblate.I031) New Weblate version is available, please upgrade to 4.0.4.
	HINT: https://docs.weblate.org/en/weblate-3.11/admin/upgrade.html
 * Weblate: 3.11
 * Django: 3.0.3
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.0
 * lxml: 4.3.2
 * Pillow: 7.0.0
 * bleach: 3.1.0
 * six: 1.14.0
 * python-dateutil: 2.8.1
 * social-auth-core: 3.2.0
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.8.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.3
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.1
 * celery: 4.4.0
 * kombu: 4.6.7
 * celery-batches: 0.3
 * translation-finder: 1.7
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.22.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.1
 * Cython: 0.29.15
 * misaka: 2.1.1
 * GitPython: 3.0.8
 * borgbackup: 1.1.10
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.7.7
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.0
 * akismet: 1.1
 * boto3: 1.12.0
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * Mercurial: 4.8.2
 * git-svn: 2.20.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.lancloud.ru
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.15.0-20-generic (x86_64)


docker-compose exec weblate weblate list_versions
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
        
root@translate:~# cd /opt/weblate/
root@translate:/opt/weblate# docker-compose exec weblate weblate list_versions
Start 'settings-override.py'
Start defining custom active directory authentication
'WEBLATE_TRANSLATION_SYNCHRONIZATION_ENABLE': 'True'
System check identified some issues:

INFOS:
?: (weblate.I031) New Weblate version is available, please upgrade to 4.0.4.
	HINT: https://docs.weblate.org/en/weblate-3.11/admin/upgrade.html
 * Weblate: 3.11
 * Django: 3.0.3
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.0
 * lxml: 4.3.2
 * Pillow: 7.0.0
 * bleach: 3.1.0
 * six: 1.14.0
 * python-dateutil: 2.8.1
 * social-auth-core: 3.2.0
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.8.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-appconf: 1.0.3
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.7.2
 * openpyxl: 3.0.1
 * celery: 4.4.0
 * kombu: 4.6.7
 * celery-batches: 0.3
 * translation-finder: 1.7
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.22.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.1
 * Cython: 0.29.15
 * misaka: 2.1.1
 * GitPython: 3.0.8
 * borgbackup: 1.1.10
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.7.7
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.0
 * akismet: 1.1
 * boto3: 1.12.0
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * Mercurial: 4.8.2
 * git-svn: 2.20.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.lancloud.ru
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.15.0-20-generic (x86_64)
root@translate:/opt/weblate# 
root@translate:/opt/weblate# docker-compose exec --user weblate weblate weblate check --deploy
Start 'settings-override.py'
Start defining custom active directory authentication
'WEBLATE_TRANSLATION_SYNCHRONIZATION_ENABLE': 'True'
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Can not send email ((535, b'5.7.3 Authentication unsuccessful')), please check EMAIL_* settings.
	HINT: https://docs.weblate.org/en/weblate-3.11/admin/install.html#out-mail
?: (weblate.E027) Path /app/data/memory/MAIN_at6nprrwjkhkdft8.seg is owned by different user, check your DATA_DIR settings.
	HINT: https://docs.weblate.org/en/weblate-3.11/admin/install.html#file-permissions
?: (weblate.E027) Path /app/data/settings-override.py is owned by different user, check your DATA_DIR settings.
	HINT: https://docs.weblate.org/en/weblate-3.11/admin/install.html#file-permissions
?: (weblate.E027) Path /app/data/ssl is owned by different user, check your DATA_DIR settings.
	HINT: https://docs.weblate.org/en/weblate-3.11/admin/install.html#file-permissions

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-3.11/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-3.11/admin/backup.html
?: (weblate.I031) New Weblate version is available, please upgrade to 4.0.4.
	HINT: https://docs.weblate.org/en/weblate-3.11/admin/upgrade.html

System check identified 10 issues (1 silenced).

```

**Additional context**

**Comment by nijel** [comment]
Please upgrade, we're no longer using Whoosh for this since 4.0.
