### ISSUE TITLE
"About" page not available after upgrade to 4.1

### ISSUE THREAD

**Issue by buck-E** [WeblateOrg/weblate#4039]
**Describe the bug**
After upgrading to 4.1 from 4.0.4, "About" page is not visible at https://thesite.com/about
(Note errors under `weblate list_versions` below)

**To Reproduce**
1. Go to https://docs.weblate.org/en/weblate-4.1/admin/upgrade.html?highlight=port#upgrade-from-4-0-to-4-1
2. Upgrade pip install from 4.0.4 to 4.1
3. Definitely change settings.py for upgrade
4. Restart celery and uwsgi
5. See upgraded weblate working
6. Except see 502 error for /about page coming from nginx (reverse proxy setup)

**Expected behavior**
I would expect that the about page is visible (or no pages are).

**Server configuration and status**
Please paste the output of `list_versions` and `check --deploy` commands over
here. Depending on installation these can be executed in different way, please
consult https://docs.weblate.org/en/latest/admin/management.html for more
details.

On pip installed Weblate:

weblate list_versions
```
$ weblate list_versions
WARNING Handled exception: FileNotFoundError: [Errno 2] No such file or directory: 'hg'
Traceback (most recent call last):
  File "/home/weblate/weblate-env/bin/weblate", line 8, in <module>
    sys.exit(main())
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/runner.py", line 32, in main
    execute_from_command_line(argv)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/utils/management/base.py", line 42, in execute
    return super().execute(*args, **options)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/trans/management/commands/list_versions.py", line 38, in handle
    for version in get_versions_list():
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/utils/requirements.py", line 238, in get_versions_list
    + get_optional_versions()
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/utils/requirements.py", line 127, in get_optional_versions
    if HgRepository.is_supported():
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/vcs/base.py", line 322, in is_supported
    version = cls.get_version()
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/vcs/base.py", line 331, in get_version
    cls._version = cls._get_version()
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/vcs/mercurial.py", line 237, in _get_version
    output = cls._popen(["version", "-q"], merge_err=False)
  File "/home/weblate/weblate-env/lib/python3.8/site-packages/weblate/vcs/base.py", line 158, in _popen
    process = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hg'
```

weblate check --deploy
```
WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (weblate.W025.ini) Failure in loading handler for ini file format: Missing iniparse library.
        HINT: https://docs.weblate.org/en/weblate-4.1/admin/install.html#optional-deps
?: (weblate.W025.islu) Failure in loading handler for islu file format: Missing iniparse library.
        HINT: https://docs.weblate.org/en/weblate-4.1/admin/install.html#optional-deps
?: (weblate.W033.Gerrit) Failure in loading VCS module for Gerritt: git: 'review' is not a git command. See 'git --help'.
 (1)
        HINT: https://docs.weblate.org/en/weblate-4.1/vcs.html
?: (weblate.W033.Mercurial) Failure in loading VCS module for Mercurialt: [Errno 2] No such file or directory: 'hg'
        HINT: https://docs.weblate.org/en/weblate-4.1/vcs.html
?: (weblate.W033.Subversion) Failure in loading VCS module for Subversiont: git: 'svn' is not a git command. See 'git --help'.

The most similar commands are
        fsck
        mv
        show
 (1)
        HINT: https://docs.weblate.org/en/weblate-4.1/vcs.html

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.1/admin/backup.html

```
**Additional context**

I tried stopping celery and uwsgi, and running `weblate collectstatic --noinput` and then restarting celery and uwsgi again.  It did not change.

**Comment by buck-E** [comment]
Upgrading to 4.1.1 confirmed fied.
