### ISSUE TITLE
test_create weblate.trans.tests.test_commands.CreateDemoTestCase fails

### ISSUE THREAD

**Issue by scarabeusiv** [WeblateOrg/weblate#4046]
When creating the update to 4.1 the test_create fails in openSUSE:

```
[ 1813s] ERROR: test_create (weblate.trans.tests.test_commands.CreateDemoTestCase)
[ 1813s] ----------------------------------------------------------------------
[ 1813s] Traceback (most recent call last):
[ 1813s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.1/weblate/trans/tests/test_commands.py", line 399, in test_create
[ 1813s]     call_command("import_demo", stdout=output)
[ 1813s]   File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 168, in call_command
[ 1813s]     return command.execute(*args, **defaults)
[ 1813s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.1/weblate/utils/management/base.py", line 42, in execute
[ 1813s]     return super().execute(*args, **options)
[ 1813s]   File "/usr/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
[ 1813s]     output = self.handle(*args, **options)
[ 1813s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.1/weblate/trans/management/commands/import_demo.py", line 39, in handle
[ 1813s]     component = Component.objects.create(
[ 1813s]   File "/usr/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
[ 1813s]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[ 1813s]   File "/usr/lib/python3.8/site-packages/django/db/models/query.py", line 433, in create
[ 1813s]     obj.save(force_insert=True, using=self.db)
[ 1813s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.1/weblate/trans/models/component.py", line 641, in save
[ 1813s]     task = component_after_save.delay(
[ 1813s]   File "/usr/lib/python3.8/site-packages/celery/app/task.py", line 425, in delay
[ 1813s]     return self.apply_async(args, kwargs)
[ 1813s]   File "/usr/lib/python3.8/site-packages/celery/app/task.py", line 561, in apply_async
[ 1813s]     return self.apply(args, kwargs, task_id=task_id or uuid(),
[ 1813s]   File "/usr/lib/python3.8/site-packages/celery/app/task.py", line 775, in apply
[ 1813s]     ret = tracer(task_id, args, kwargs, request)
[ 1813s]   File "/usr/lib/python3.8/site-packages/celery/app/trace.py", line 399, in trace_task
[ 1813s]     I, R, state, retval = on_error(task_request, exc, uuid)
[ 1813s]   File "/usr/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
[ 1813s]     R = retval = fun(*args, **kwargs)
[ 1813s]   File "/usr/lib/python3.8/site-packages/celery/app/base.py", line 487, in run
[ 1813s]     return task._orig_run(*args, **kwargs)
[ 1813s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.1/weblate/trans/tasks.py", line 277, in component_after_save
[ 1813s]     component.after_save(
[ 1813s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.1/weblate/trans/models/component.py", line 2075, in after_save
[ 1813s]     self.sync_git_repo(skip_push=skip_push)
[ 1813s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.1/weblate/trans/models/component.py", line 1731, in sync_git_repo
[ 1813s]     self.configure_branch()
[ 1813s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.1/weblate/trans/models/component.py", line 1061, in configure_branch
[ 1813s]     self.repository.configure_branch(self.branch)
[ 1813s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.1/weblate/vcs/git.py", line 288, in configure_branch
[ 1813s]     self.execute(["checkout", "-b", branch, "origin/{0}".format(branch)])
[ 1813s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.1/weblate/vcs/base.py", line 189, in execute
[ 1813s]     self.last_output = self._popen(
[ 1813s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.1/weblate/vcs/base.py", line 177, in _popen
[ 1813s]     raise RepositoryException(retcode, output)
[ 1813s] weblate.vcs.base.RepositoryException: fatal: 'origin/master' is not a commit and a branch 'master' cannot be created from it
[ 1813s]  (128)
```
Rest of the stuff went fine:
```
[ 1813s] Ran 3551 tests in 1772.553s
[ 1813s] 
[ 1813s] FAILED (errors=1, skipped=73, expected failures=7)
[ 1813s] Destroying test database for alias 'default' ('test_weblate')...
```

Well the git message is kinda obvious that this is not allowed, but I dunno why it didn't read out a specific commit...

**Comment by nijel** [comment]
The test requires network access, I guess that it's disabled in your build system...
