### ISSUE TITLE
weblate cannot install on postgresql with user not owner of DB 

### ISSUE THREAD

**Issue by gioppoluca** [WeblateOrg/weblate#4182]
I'm installing weblate using docker.
I have a PostgreSQL db where the weblate user is not the owner of the DB, but has grants on a specific weblate schema, since in the DB there are also other projects and we are using the schema to isolate content.
I'm getting the error:
Traceback (most recent call last):
weblate_1           |   File "/usr/local/bin/weblate", line 10, in <module>
weblate_1           |     sys.exit(main())
weblate_1           |   File "/usr/local/lib/python3.7/dist-packages/weblate/runner.py", line 32, in main
weblate_1           |     execute_from_command_line(argv)
weblate_1           |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
weblate_1           |     utility.execute()
weblate_1           |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 395, in execute
weblate_1           |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate_1           |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 328, in run_from_argv
weblate_1           |     self.execute(*args, **cmd_options)
weblate_1           |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 369, in execute
weblate_1           |     output = self.handle(*args, **options)
weblate_1           |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 83, in wrapped
weblate_1           |     res = handle_func(*args, **kwargs)
weblate_1           |   File "/usr/local/lib/python3.7/dist-packages/django/core/management/commands/migrate.py", line 233, in handle
weblate_1           |     fake_initial=fake_initial,
weblate_1           |   File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/executor.py", line 117, in migrate
weblate_1           |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
weblate_1           |   File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
weblate_1           |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
weblate_1           |   File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/executor.py", line 245, in apply_migration
weblate_1           |     state = migration.apply(state, schema_editor)
weblate_1           |   File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/migration.py", line 124, in apply
weblate_1           |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
weblate_1           |   File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
weblate_1           |     self.code(from_state.apps, schema_editor)
weblate_1           |   File "/usr/local/lib/python3.7/dist-packages/weblate/memory/migrations/0007_use_trigram.py", line 18, in create_index
weblate_1           |     schema_editor.connection.settings_dict["NAME"]
weblate_1           |   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/schema.py", line 142, in execute
weblate_1           |     cursor.execute(sql, params)
weblate_1           |   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 100, in execute
weblate_1           |     return super().execute(sql, params)
weblate_1           |   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 68, in execute
weblate_1           |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
weblate_1           |   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
weblate_1           |     return executor(sql, params, many, context)
weblate_1           |   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 86, in _execute
weblate_1           |     return self.cursor.execute(sql, params)
weblate_1           |   File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 90, in __exit__
weblate_1           |     raise dj_exc_value.with_traceback(traceback) from exc_value
weblate_1           |   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 86, in _execute
weblate_1           |     return self.cursor.execute(sql, params)
weblate_1           | django.db.utils.ProgrammingError: must be owner of database micado

Are there any permissions on the DB I can set to solve this.
I think that it should be able to install on a schema different than public

**Comment by gioppoluca** [comment]
ths is a duplicate of this: https://github.com/WeblateOrg/weblate/issues/3940
