### ISSUE TITLE
ImportError: cannot import name 'etree' from 'lxml'

### ISSUE THREAD

**Issue by maicol07** [WeblateOrg/weblate#4183]
**Describe the bug**
Upgraded to Ubuntu 20.04. Now wsgi.py gives the error below

**To Reproduce**

1. Upgrade to Ubuntu 20.04
2. See error

**Expected behavior**

Weblate should work

**Server configuration and status**
```
(weblate) maicol07@maicol07:/var/www/html/weblate$ weblate list_versions
 * Weblate: 4.1.1
 * Django: 3.0.5
 * siphashc: 1.2
 * Whoosh: 2.7.4
 * translate-toolkit: 3.0.0
 * lxml: 4.5.2
 * Pillow: 6.2.1
 * bleach: 3.1.1
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.4.0
 * django-crispy-forms: 1.9.0
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-filter: 2.3.0
 * django-appconf: 1.0.3
 * user-agents: 2.0
 * filelock: 3.0.12
 * setuptools: 41.2.0
 * jellyfish: 0.7.2
 * openpyxl: 2.6.3
 * celery: 4.4.2
 * kombu: 4.6.8
 * translation-finder: 2.1
 * html2text: 2019.9.26
 * pycairo: 1.18.1
 * pygobject: 3.34.0
 * diff-match-patch: 20181111
 * requests: 2.22.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.1
 * Cython: 0.29.14
 * misaka: 2.1.1
 * GitPython: 3.0.5
 * borgbackup: 1.1.10
 * pyparsing: 2.4.7
 * Python: 3.6.8
 * Git: 2.25.1
 * psycopg2-binary: 2.8.3
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.5
 * zeep: 3.4.0
 * aeidon: 1.6.0
 * hub: 2.14.2
 * Redis server: 6.0.5
 * PostgreSQL server: 10.12
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: mail.maicol07.it
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 5.7.1-050701-generic (x86_64)
```

**Exception traceback**
```
[Wed Jul 15 10:47:00.280803 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636] mod_wsgi (pid=393651): Failed to exec Python script file '/var/www/html/weblate/lib/python3.6/site-packages/weblate/wsgi.py'.
[Wed Jul 15 10:47:00.280911 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636] mod_wsgi (pid=393651): Exception occurred processing WSGI script '/var/www/html/weblate/lib/python3.6/site-packages/weblate/wsgi.py'.
[Wed Jul 15 10:47:00.281775 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636] Traceback (most recent call last):
[Wed Jul 15 10:47:00.281988 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]   File "/var/www/html/weblate/lib/python3.6/site-packages/weblate/wsgi.py", line 42, in <module>
[Wed Jul 15 10:47:00.282007 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]     application = get_wsgi_application()
[Wed Jul 15 10:47:00.282043 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]   File "/var/www/html/weblate/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
[Wed Jul 15 10:47:00.282061 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]     django.setup(set_prefix=False)
[Wed Jul 15 10:47:00.282097 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]   File "/var/www/html/weblate/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
[Wed Jul 15 10:47:00.282115 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Wed Jul 15 10:47:00.282152 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]   File "/var/www/html/weblate/lib/python3.6/site-packages/django/conf/__init__.py", line 76, in __getattr__
[Wed Jul 15 10:47:00.282169 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]     self._setup(name)
[Wed Jul 15 10:47:00.282204 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]   File "/var/www/html/weblate/lib/python3.6/site-packages/django/conf/__init__.py", line 63, in _setup
[Wed Jul 15 10:47:00.282222 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]     self._wrapped = Settings(settings_module)
[Wed Jul 15 10:47:00.282258 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]   File "/var/www/html/weblate/lib/python3.6/site-packages/django/conf/__init__.py", line 142, in __init__
[Wed Jul 15 10:47:00.282276 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Wed Jul 15 10:47:00.282311 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
[Wed Jul 15 10:47:00.282353 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]     return _bootstrap._gcd_import(name[level:], package, level)
[Wed Jul 15 10:47:00.282389 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[Wed Jul 15 10:47:00.282426 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[Wed Jul 15 10:47:00.282462 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]   File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
[Wed Jul 15 10:47:00.282498 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Wed Jul 15 10:47:00.282535 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
[Wed Jul 15 10:47:00.282571 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
[Wed Jul 15 10:47:00.282608 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
[Wed Jul 15 10:47:00.282645 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
[Wed Jul 15 10:47:00.282681 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
[Wed Jul 15 10:47:00.282718 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
[Wed Jul 15 10:47:00.282755 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]   File "/var/www/html/weblate/lib/python3.6/site-packages/weblate/__init__.py", line 22, in <module>
[Wed Jul 15 10:47:00.282773 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]     from weblate.vcs.base import RepositoryException
[Wed Jul 15 10:47:00.282808 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]   File "/var/www/html/weblate/lib/python3.6/site-packages/weblate/vcs/base.py", line 37, in <module>
[Wed Jul 15 10:47:00.282826 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]     from weblate.trans.util import get_clean_env, path_separator
[Wed Jul 15 10:47:00.282862 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]   File "/var/www/html/weblate/lib/python3.6/site-packages/weblate/trans/util.py", line 38, in <module>
[Wed Jul 15 10:47:00.282879 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636]     from lxml import etree
[Wed Jul 15 10:47:00.282934 2020] [wsgi:error] [pid 393651:tid 140461297325824] [remote 151.36.80.223:49636] ImportError: cannot import name 'etree' from 'lxml' (/var/www/html/weblate/lib/python3.6/site-packages/lxml/__init__.py)
```

**Comment by nijel** [comment]
Probably Python was upgraded and you need to reinstall pip installed packages.

**Comment by maicol07** [comment]
Reinstalled all the packages with pip but I've got the same error

**Comment by nijel** [comment]
Some people say uninstalling lxmi and installing it did help in this situation: https://stackoverflow.com/a/53898728/225718

**Comment by maicol07** [comment]
Same error

**Comment by nijel** [comment]
Try deleting the pip cache (~/.cache/pip) before reinstalling.

**Comment by maicol07** [comment]
Nothing changed

**Comment by nijel** [comment]
What is content of `/var/www/html/weblate/lib/python3.6/site-packages/lxml/`? Is the etree module built during the installation or did you install wheel?

Maybe the system misses some dependencies, try running `ldd /var/www/html/weblate/lib/python3.6/site-packages/lxml/*.so`.

**Comment by maicol07** [comment]
This is the content of that `lxml` 

```shellsession
maicol07@maicol07:/var/www/html/weblate/lib/python3.6/site-packages/lxml$ ls
builder.cpython-36m-x86_64-linux-gnu.so       etree.cpython-36m-x86_64-linux-gnu.so  objectify.cpython-36m-x86_64-linux-gnu.so
builder.py                                    etree.h                                __pycache__
cssselect.py                                  html                                   pyclasslookup.py
doctestcompare.py                             includes                               sax.cpython-36m-x86_64-linux-gnu.so
ElementInclude.py                             __init__.py                            sax.py
_elementpath.cpython-36m-x86_64-linux-gnu.so  isoschematron                          usedoctest.py
_elementpath.py                               lxml.etree_api.h
etree_api.h                                   lxml.etree.h
```

Output of the ldd command:

```shellsession
maicol07@maicol07:/var/www/html/weblate/lib/python3.6/site-packages/lxml$ ldd /var/www/html/weblate/lib/python3.6/site-packages/lxml/*.so
/var/www/html/weblate/lib/python3.6/site-packages/lxml/builder.cpython-36m-x86_64-linux-gnu.so:
       linux-vdso.so.1 (0x00007ffce80e2000)
       libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2b0c70a000)
       libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2b0c518000)
       /lib64/ld-linux-x86-64.so.2 (0x00007f2b0c963000)
/var/www/html/weblate/lib/python3.6/site-packages/lxml/_elementpath.cpython-36m-x86_64-linux-gnu.so:
       linux-vdso.so.1 (0x00007ffd08ed4000)
       libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2e582d9000)
       libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2e580e7000)
       /lib64/ld-linux-x86-64.so.2 (0x00007f2e5854d000)
/var/www/html/weblate/lib/python3.6/site-packages/lxml/etree.cpython-36m-x86_64-linux-gnu.so:
       linux-vdso.so.1 (0x00007ffe44d71000)
       librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3f314de000)
       libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f3f3138f000)
       libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3f3136c000)
       libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3f3117a000)
       /lib64/ld-linux-x86-64.so.2 (0x00007f3f31c28000)
/var/www/html/weblate/lib/python3.6/site-packages/lxml/objectify.cpython-36m-x86_64-linux-gnu.so:
       linux-vdso.so.1 (0x00007ffec6799000)
       librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa6e752a000)
       libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa6e73db000)
       libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa6e73b8000)
       libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa6e71c6000)
       /lib64/ld-linux-x86-64.so.2 (0x00007fa6e7a50000)
/var/www/html/weblate/lib/python3.6/site-packages/lxml/sax.cpython-36m-x86_64-linux-gnu.so:
       linux-vdso.so.1 (0x00007ffe5db56000)
       libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc1eb564000)
       libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc1eb372000)
       /lib64/ld-linux-x86-64.so.2 (0x00007fc1eb7d1000)
```

**Comment by nijel** [comment]
Maybe that so is not compatible with your Python version. Try building it instead of using provided wheel. `pip uinstall lxml; pip install --no-binary lxml` should do that.

**Comment by maicol07** [comment]
Doesn't work

**Comment by maicol07** [comment]
It seems that Python itself find etree... while Weblate files no...

```shellsession
(weblate) maicol07@maicol07:/var/www/html/weblate$ python
Python 3.6.8 (default, Aug 20 2019, 17:12:48)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from lxml import etree
>>> etree
<module 'lxml.etree' from '/var/www/html/weblate/lib/python3.6/site-packages/lxml/etree.cpython-36m-x86_64-linux-gnu.so'>
>>>
```

**Comment by nijel** [comment]
Does that work in Weblate shell as well? (`weblate shell` executed in the virtualenv)

**Comment by maicol07** [comment]
Didn't know Weblate has its own shell!!

Tested with this: can't enter but there is a more detailed error:

```shellsession
(weblate) maicol07@maicol07:/var/www/html/weblate$ weblate shell
Traceback (most recent call last):
 File "/var/www/html/weblate/bin/weblate", line 5, in <module>
   from weblate.runner import main
 File "/var/www/html/weblate/lib/python3.6/site-packages/weblate/__init__.py", line 22, in <module>
   from weblate.vcs.base import RepositoryException
 File "/var/www/html/weblate/lib/python3.6/site-packages/weblate/vcs/base.py", line 37, in <module>
   from weblate.trans.util import get_clean_env, path_separator
 File "/var/www/html/weblate/lib/python3.6/site-packages/weblate/trans/util.py", line 38, in <module>
   from lxml import etree
ImportError: /var/www/html/weblate/lib/python3.6/site-packages/lxml/etree.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf
```

Maybe this last line can help solving the issue?

**Comment by nijel** [comment]
That indicates that the module was built for different CPython than you're using. Still that's weird, both is supposed to be same Python interpreter. Can you try recreating the Weblate virtualenv?

```
virtualenv /var/www/html/weblate/  --python python3.6
```

**Comment by maicol07** [comment]
It seems that you're right:

```shellsession
maicol07@maicol07:/var/www/html/weblate$ virtualenv /var/www/html/weblate/ --python python3.6
-bash: /usr/local/bin/virtualenv: /usr/bin/python: bad interpreter: No such file or directory
```

How to fix it, then?

**Comment by nijel** [comment]
Maybe Ubuntu 20.04 dropped Python 2 and you have some leftovers from this on the system? Looks like /usr/bin/python is dangling link, but there might be other things broken as well. Try looking for Ubuntu advice, this is not really related to Weblate...

**Comment by maicol07** [comment]
Ok, got it working with `sudo python3.6 -m venv /var/www/html/weblate/`

Now I'm installing all the deps again...

**Comment by maicol07** [comment]
So this is the resume of what I've done:

1.  Create a Venv with Python 3.8 (`sudo python3.6 -m venv /var/www/html/weblate/`)
2.  Installed Weblate in the new venv (`pip install Weblate`)
3.  Copied `settings.py` from `python3.6` folder to `python3.8`
4.  Got again this issue: #3117 (solved by restarting apache (`sudo service apache2 restart`))
5.  Getting this error: `ModuleNotFoundError: No module named 'weblate.legal.templatetags'`  
    Solved by commenting the line where `weblate.legal.templatetags` was added to `INSTALLED_APPS`.copying the folder `/var/www/html/weblate/lib/python3.6/site-packages/weblate/legal` to `/var/www/html/weblate/lib/python3.6/site-packages/weblate/legal`.
6.  Another error: `ModuleNotFoundError: No module named 'psycopg2'`  
    Solved with `sudo apt install python3-psycopg2` (Installs the psycopg2 deps), then `pip install psycopg2-binary` (Installs the psycopg2 lib) and finally an apache2 restart (same command as step 4)

At this point, I tried the command weblate shell and enters correctly into the shell. Though, the web interface doesn't work...

**Comment by nijel** [comment]
Do you get some error in the Apache logs?

**Comment by maicol07** [comment]
No

**Comment by nijel** [comment]
And what happens? It has to fail somehow :-)

**Comment by maicol07** [comment]
Too long request browser error

**Comment by nijel** [comment]
Maybe it needs to recalculate the stats. You can do this from the command line as well: `weblate ensure_stats`

**Comment by maicol07** [comment]
Not working and no error in the logs
