### ISSUE TITLE
Cannot export Rails YML format

### ISSUE THREAD

**Issue by TruffeCendree** [WeblateOrg/weblate#4316]
**Describe the bug**

I am trying to export the locale 'English' for a component. Translation has been imported from an original .yml file, then updated in the editor. An internal error occures.

Exporting to other format works fine.

**To Reproduce**

Go to Projet > Component > English > Download file (Ruby YAML)

**Screenshots**
![image](https://user-images.githubusercontent.com/4479304/90237889-4c17b600-de25-11ea-9f46-50cea7c570d9.png)

![image](https://user-images.githubusercontent.com/4479304/90237856-3dc99a00-de25-11ea-9abd-b2cb1342509c.png)

**Server configuration and status**

 * Weblate: 4.1.1
 * Django: 3.0.8
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 3.0.0
 * lxml: 4.5.2
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 3.4.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.0
 * django-filter: 2.3.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.1
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.1
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20181111
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.15.1
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.7
 * borgbackup: 1.1.13
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.5
 * psycopg2-binary: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.14.33
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 2.0.1
 * Mercurial: 5.4.2
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * hub: 2.13.0
 * lab: 0.16
 * Redis server: 4.0.14
 * PostgreSQL server: 11.8
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: 127.0.0.1
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.3.0-1032-aws (x86_64)

**Weblate deploy checks**

```
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Cannot send e-mail ([Errno 111] Connection refused), please check EMAIL_* settings.
	HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/install.html#out-mail
?: (weblate.E017) Correct the site domain
	HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/install.html#production-site

WARNINGS:
?: (security.W005) You have not set the SECURE_HSTS_INCLUDE_SUBDOMAINS setting to True. Without this, your site is potentially vulnerable to attack via an insecure connection to a subdomain. Only set this to True if you are certain that all subdomains of your domain should be served exclusively via SSL.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.1.1/admin/backup.html
```

**Exception traceback**

```
weblate_1       | celery-main stderr | [2020-08-14 09:48:47,040: INFO/MainProcess] Received task: weblate.utils.tasks.heartbeat[dc5aa609-345e-4a06-8e17-cceb9599cbf8]  
weblate_1       | uwsgi stderr | ERROR Internal Server Error: /download/ogustine/rails/en/
weblate_1       | uwsgi stderr | Traceback (most recent call last):
weblate_1       | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 34, in inner
weblate_1       | uwsgi stderr |     response = get_response(request)
weblate_1       | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 115, in _get_response
weblate_1       | uwsgi stderr |     response = self.process_exception_by_middleware(e, request)
weblate_1       | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 113, in _get_response
weblate_1       | uwsgi stderr |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
weblate_1       | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/weblate/trans/views/files.py", line 117, in download_translation
weblate_1       | uwsgi stderr |     return download_translation_file(obj, **kwargs)
weblate_1       | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/weblate/utils/views.py", line 228, in download_translation_file
weblate_1       | uwsgi stderr |     translation.commit_pending("download", None)
weblate_1       | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/translation.py", line 505, in commit_pending
weblate_1       | uwsgi stderr |     self.update_units(store, author_name, author.id)
weblate_1       | uwsgi stderr |   File "/usr/lib/python3.7/contextlib.py", line 74, in inner
weblate_1       | uwsgi stderr |     return func(*args, **kwds)
weblate_1       | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/translation.py", line 697, in update_units
weblate_1       | uwsgi stderr |     store.save()
weblate_1       | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/weblate/formats/ttkit.py", line 297, in save
weblate_1       | uwsgi stderr |     self.save_atomic(self.storefile, self.save_content)
weblate_1       | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/weblate/formats/base.py", line 307, in save_atomic
weblate_1       | uwsgi stderr |     callback(temp)
weblate_1       | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/weblate/formats/ttkit.py", line 293, in save_content
weblate_1       | uwsgi stderr |     self.store.serialize(handle)
weblate_1       | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/translate/storage/yaml.py", line 124, in serialize
weblate_1       | uwsgi stderr |     nested_set(units, unit.getid().split('->'), unit.target)
weblate_1       | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/translate/storage/yaml.py", line 113, in nested_set
weblate_1       | uwsgi stderr |     nested_set(target[path[0]], path[1:], value)
weblate_1       | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/translate/storage/yaml.py", line 107, in nested_set
weblate_1       | uwsgi stderr |     target[path[0]][pos] = value
weblate_1       | uwsgi stderr | TypeError: 'SingleQuotedScalarString' object does not support item assignment
```

**Comment by TruffeCendree** [comment]
After investigation, I found the date producing the issue :

The file imported contains :

``` yml
en:
  days_on: '["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]'
```

The original file looks like :

```yml
fr:
    - dimanches
    - lundis
    - mardis
    - mercredis
    - jeudis
    - vendredis
    - samedis
```

And the script is trying to assign an array to a string.
The invalid format for generated by LocaleApp.

**Comment by nijel** [comment]
I think this should be addressed by https://github.com/translate/translate/pull/4090, but it should be verified.
