### ISSUE TITLE
Cannot upgrade from 3.10.3 to 3.11.3 (even 3.11)

### ISSUE THREAD

**Issue by Antiarchitect** [WeblateOrg/weblate#4352]
**Describe the bug**

Migration in trans module is failing with PostgreSQL 10

**To Reproduce**

Run a weblate container with 3.11.3 or 3.11 version with the old database connected

**Expected behavior**

Migrations are run smoothly.

**Actual behavior**

```
Starting...
weblate
Postgres is up
System check identified some issues:

INFOS:
?: (weblate.I031) New Weblate version is available, please upgrade to 4.2.
	HINT: https://docs.weblate.org/en/weblate-3.11.3/admin/upgrade.html
Starting database migration...
System check identified some issues:

INFOS:
?: (weblate.I031) New Weblate version is available, please upgrade to 4.2.
	HINT: https://docs.weblate.org/en/weblate-3.11.3/admin/upgrade.html
ERROR Handled exception: ProgrammingError: there is no unique constraint matching given keys for referenced table "trans_unit"

Operations to perform:
  Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, fonts, gitexport, lang, memory, screenshots, sessions, sites, social_django, trans, weblate_auth, wladmin
Running migrations:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: there is no unique constraint matching given keys for referenced table "trans_unit"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 11, in <module>
    load_entry_point('Weblate==3.11.3', 'console_scripts', 'weblate')()
  File "/usr/local/lib/python3.7/dist-packages/weblate/runner.py", line 33, in main
    execute_from_command_line(argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/commands/migrate.py", line 233, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/executor.py", line 247, in apply_migration
    migration_recorded = True
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/schema.py", line 115, in __exit__
    self.execute(sql)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/sentry_sdk/integrations/django/__init__.py", line 467, in execute
    return real_execute(self, sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: there is no unique constraint matching given keys for referenced table "trans_unit"

Sentry is attempting to send 1 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
  Applying trans.0059_auto_20200206_0937...
```

Frankly, I do not understand Django migrations and model to table mapping as well so I couldn't deduce what actual field must have UNIQUE constraint.

**Comment by nijel** [comment]
Did you do any manual changes to the database? It seems that the `trans_unit` table has lost it's primary key. Can you dump structure for it?

**Comment by Antiarchitect** [comment]
```
      Column       |           Type           | Collation | Nullable |                Default                 | Storage  | Stats target | Description
-------------------+--------------------------+-----------+----------+----------------------------------------+----------+--------------+-------------
 id                | integer                  |           | not null | nextval('trans_unit_id_seq'::regclass) | plain    |              |
 location          | text                     |           | not null |                                        | extended |              |
 context           | text                     |           | not null |                                        | extended |              |
 note              | text                     |           | not null |                                        | extended |              |
 flags             | text                     |           | not null |                                        | extended |              |
 source            | text                     |           | not null |                                        | extended |              |
 previous_source   | text                     |           | not null |                                        | extended |              |
 target            | text                     |           | not null |                                        | extended |              |
 position          | integer                  |           | not null |                                        | plain    |              |
 has_suggestion    | boolean                  |           | not null |                                        | plain    |              |
 has_comment       | boolean                  |           | not null |                                        | plain    |              |
 has_failing_check | boolean                  |           | not null |                                        | plain    |              |
 num_words         | integer                  |           | not null |                                        | plain    |              |
 priority          | integer                  |           | not null |                                        | plain    |              |
 translation_id    | integer                  |           | not null |                                        | plain    |              |
 content_hash      | bigint                   |           | not null |                                        | plain    |              |
 id_hash           | bigint                   |           | not null |                                        | plain    |              |
 pending           | boolean                  |           | not null |                                        | plain    |              |
 state             | integer                  |           | not null |                                        | plain    |              |
 original_state    | integer                  |           | not null |                                        | plain    |              |
 extra_context     | text                     |           | not null |                                        | extended |              |
 extra_flags       | text                     |           | not null |                                        | extended |              |
 timestamp         | timestamp with time zone |           | not null |                                        | plain    |              |
 shaping_id        | integer                  |           |          |                                        | plain    |              |
Indexes:
    "trans_unit_content_hash_2fea59d3" btree (content_hash)
    "trans_unit_has_comment_8af043c5" btree (has_comment)
    "trans_unit_has_failing_check_2f1475f3" btree (has_failing_check)
    "trans_unit_has_suggestion_9d2d3f72" btree (has_suggestion)
    "trans_unit_priority_position_c0f26d59_idx" btree (priority, "position")
    "trans_unit_shaping_id_b90861a2" btree (shaping_id)
    "trans_unit_state_e08f099e" btree (state)
    "trans_unit_translation_id_513bb910" btree (translation_id)
    "trans_unit_translation_id_pending_90547d66_idx" btree (translation_id, pending)
Foreign-key constraints:
    "trans_unit_shaping_id_b90861a2_fk_trans_shaping_id" FOREIGN KEY (shaping_id) REFERENCES trans_shaping(id) DEFERRABLE INITIALLY DEFERRED
    "trans_unit_translation_id_513bb910_fk_trans_translation_id" FOREIGN KEY (translation_id) REFERENCES trans_translation(id) DEFERRABLE INITIALLY DEFERRED
```
