### ISSUE TITLE
import_demo management command doesn't work in dockerized dev environment

### ISSUE THREAD

**Issue by vladox** [WeblateOrg/weblate#4414]
**Describe the bug**

When running  `docker-compose exec --user weblate weblate weblate import_demo` the following error is produced:

`WARNING File parse error: FileNotFoundError: [Errno 2] No such file or directory: '/app/data/vcs/demo/gettext/weblate/langdata/locale/django.pot'`

**To Reproduce**

1. Go to folder 'dev-docker': `cd dev-docker` from project root
2. Run `docker-compose exec --user weblate weblate weblate import_demo`
4. See error in docker-compose logs: 

```
WARNING File parse error: FileNotFoundError: [Errno 2] No such file or directory: '/app/data/vcs/demo/gettext/weblate/langdata/locale/django.pot'
WARNING Handled exception: ValidationError: {'new_base': ['Base file for new translations not found.'], 'new_lang': ['Base file for new translations not found.']}
```

**Expected behavior**

As described in the documentation [here](https://docs.weblate.org/en/latest/admin/management.html#import-demo) a demo translation is loaded in the DB

**Comment by vladox** [comment]
@nijel I'm guessing cloning the following repo needs to be done somehow: [https://github.com/WeblateOrg/demo](https://github.com/WeblateOrg/demo) 
But the structure doesn't seems to match the path where the management command is looking for it.
Do you have a more detailed instructions about how to proceed?

**Comment by nijel** [comment]
Maybe networking doesn't work in your Docker? There is often issue with DNS resolving.

**Comment by vladox** [comment]
To me looks like something else, but I need to debug it, until now I couldn't find an easy way with Docker, here the stacktrace in case it helps:

```
Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/weblate/runner.py", line 32, in main
    execute_from_command_line(argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/dist-packages/weblate/utils/management/base.py", line 42, in execute
    return super().execute(*args, **options)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/management/commands/import_demo.py", line 54, in handle
    component.clean()
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/component.py", line 2128, in clean
    self.clean_new_lang()
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/component.py", line 2010, in clean_new_lang
    raise ValidationError({"new_base": message, "new_lang": message})
django.core.exceptions.ValidationError: {'new_base': ['Base file for new translations not found.'], 'new_lang': ['Base file for new translations not found.']}
```

**Comment by nijel** [comment]
The repository access error should raise a validation error as well. 

The file path seems correct:

https://github.com/WeblateOrg/weblate/blob/6121b543d9ca936002a41d642d0587f5c36596cb/weblate/trans/management/commands/import_demo.py#L50

The file is there:

https://github.com/WeblateOrg/demo/blob/master/weblate/langdata/locale/django.pot

Most importantly it runs fine for me and it runs fine during the CI tests.

What is content of the /app/data/vcs/demo/gettext? Is there valid checkout of the demo repository?
