### ISSUE TITLE
Borgbackup Permission Error

### ISSUE THREAD

**Issue by bilalcorbacioglu** [WeblateOrg/weblate#4434]
**Describe the bug**

I'm using Weblate on Docker Container. I'm trying to use borg for backup, but it can not work. 

**To Reproduce**

Steps:

1- I have opened this URL ".../manage/backup/" and added backup service "weblate_borgbackup".
2- I've clicked "Perform Backup" button.
3- It has thrown these errors.

``` bash
celery-backup stderr | [2020-09-04 08:12:22,414: ERROR/ForkPoolWorker-1] Failure while executing task: BackupError: {'signal': <Signal: task_failure providing_args={'task_id', 'kwargs', 'einfo', 'args', 'exception', 'traceback'}>, 'sender': <@task: weblate.wladmin.tasks.backup_service of weblate at 0x7ff5380736d8>, 'task_id': '96974677-a401-41dc-8b8f-783c8f556781', 'args': [], 'kwargs': {'pk': '4'}, 'traceback': <traceback object at 0x7ff52efa5448>, 'einfo': <ExceptionInfo: BackupError('Local Exception\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.7/dist-packages/borg/archiver.py", line 4565, in main\n    exit_code = archiver.run(args)\n  File "/usr/local/lib/python3.7/dist-packages/borg/archiver.py", line 4497, in run\n    return set_ec(func(args))\n  File "/usr/local/lib/python3.7/dist-packages/borg/archiver.py", line 161, in wrapper\n    with repository:\n  File "/usr/local/lib/python3.7/dist-packages/borg/repository.py", line 188, in __enter__\n    self.create(self.path)\n  File "/usr/local/lib/python3.7/dist-packages/borg/repository.py", line 269, in create\n    os.mkdir(path)\nPermissionError: [Errno 13] Permission denied: \'/weblate_borgbackup\'\n\nPlatform: Linux 9ea5afd24e3b 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64\nLinux: debian 10.5 \nBorg: 1.1.13  Python: CPython 3.7.3 msgpack: 0.5.6\nPID: 4908  CWD: /\nsys.argv: [\'/usr/local/bin/borg\', \'--rsh\', \'/app/data/ssh/ssh-weblate-wrapper-db5c5ca9e000131e\', \'init\', \'--encryption\', \'repokey-blake2\', \'weblate_borgbackup\']\nSSH_ORIGINAL_COMMAND: None\n\n')>}
celery-backup stderr | ERROR Failure while executing task
celery-backup stderr | Traceback (most recent call last):
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/weblate/utils/backup.py", line 79, in borg
celery-backup stderr |     universal_newlines=True,
celery-backup stderr |   File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
celery-backup stderr |     **kwargs).stdout
celery-backup stderr |   File "/usr/lib/python3.7/subprocess.py", line 487, in run
celery-backup stderr |     output=stdout, stderr=stderr)
celery-backup stderr | subprocess.CalledProcessError: Command '['borg', '--rsh', '/app/data/ssh/ssh-weblate-wrapper-db5c5ca9e000131e', 'init', '--encryption', 'repokey-blake2', 'weblate_borgbackup']' returned non-zero exit status 2.
celery-backup stderr | 
celery-backup stderr | During handling of the above exception, another exception occurred:
celery-backup stderr | 
celery-backup stderr | Traceback (most recent call last):
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/celery/app/trace.py", line 412, in trace_task
celery-backup stderr |     R = retval = fun(*args, **kwargs)
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/celery/app/trace.py", line 704, in __protected_call__
celery-backup stderr |     return self.run(*args, **kwargs)
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/weblate/wladmin/tasks.py", line 92, in backup_service
celery-backup stderr |     service.ensure_init()
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/weblate/wladmin/models.py", line 141, in ensure_init
celery-backup stderr |     log = initialize(self.repository, self.passphrase)
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/weblate/utils/backup.py", line 96, in initialize
celery-backup stderr |     {"BORG_NEW_PASSPHRASE": passphrase},
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/weblate/utils/backup.py", line 86, in borg
celery-backup stderr |     raise BackupError(error.stdout)
celery-backup stderr | weblate.utils.backup.BackupError: Local Exception
celery-backup stderr | Traceback (most recent call last):
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/borg/archiver.py", line 4565, in main
celery-backup stderr |     exit_code = archiver.run(args)
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/borg/archiver.py", line 4497, in run
celery-backup stderr |     return set_ec(func(args))
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/borg/archiver.py", line 161, in wrapper
celery-backup stderr |     with repository:
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/borg/repository.py", line 188, in __enter__
celery-backup stderr |     self.create(self.path)
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/borg/repository.py", line 269, in create
celery-backup stderr |     os.mkdir(path)
celery-backup stderr | PermissionError: [Errno 13] Permission denied: '/weblate_borgbackup'
celery-backup stderr | 
celery-backup stderr | Platform: Linux 9ea5afd24e3b 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64
celery-backup stderr | Linux: debian 10.5 
celery-backup stderr | Borg: 1.1.13  Python: CPython 3.7.3 msgpack: 0.5.6
celery-backup stderr | PID: 4908  CWD: /
celery-backup stderr | sys.argv: ['/usr/local/bin/borg', '--rsh', '/app/data/ssh/ssh-weblate-wrapper-db5c5ca9e000131e', 'init', '--encryption', 'repokey-blake2', 'weblate_borgbackup']
celery-backup stderr | SSH_ORIGINAL_COMMAND: None
celery-backup stderr | 
celery-backup stderr | 
celery-backup stderr | [2020-09-04 08:12:22,414: ERROR/ForkPoolWorker-1] Failure while executing task
celery-backup stderr | Traceback (most recent call last):
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/weblate/utils/backup.py", line 79, in borg
celery-backup stderr |     universal_newlines=True,
celery-backup stderr |   File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
celery-backup stderr |     **kwargs).stdout
celery-backup stderr |   File "/usr/lib/python3.7/subprocess.py", line 487, in run
celery-backup stderr |     output=stdout, stderr=stderr)
celery-backup stderr | subprocess.CalledProcessError: Command '['borg', '--rsh', '/app/data/ssh/ssh-weblate-wrapper-db5c5ca9e000131e', 'init', '--encryption', 'repokey-blake2', 'weblate_borgbackup']' returned non-zero exit status 2.
celery-backup stderr | 
celery-backup stderr | During handling of the above exception, another exception occurred:
celery-backup stderr | 
celery-backup stderr | Traceback (most recent call last):
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/celery/app/trace.py", line 412, in trace_task
celery-backup stderr |     R = retval = fun(*args, **kwargs)
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/celery/app/trace.py", line 704, in __protected_call__
celery-backup stderr |     return self.run(*args, **kwargs)
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/weblate/wladmin/tasks.py", line 92, in backup_service
celery-backup stderr |     service.ensure_init()
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/weblate/wladmin/models.py", line 141, in ensure_init
celery-backup stderr |     log = initialize(self.repository, self.passphrase)
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/weblate/utils/backup.py", line 96, in initialize
celery-backup stderr |     {"BORG_NEW_PASSPHRASE": passphrase},
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/weblate/utils/backup.py", line 86, in borg
celery-backup stderr |     raise BackupError(error.stdout)
celery-backup stderr | weblate.utils.backup.BackupError: Local Exception
celery-backup stderr | Traceback (most recent call last):
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/borg/archiver.py", line 4565, in main
celery-backup stderr |     exit_code = archiver.run(args)
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/borg/archiver.py", line 4497, in run
celery-backup stderr |     return set_ec(func(args))
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/borg/archiver.py", line 161, in wrapper
celery-backup stderr |     with repository:
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/borg/repository.py", line 188, in __enter__
celery-backup stderr |     self.create(self.path)
celery-backup stderr |   File "/usr/local/lib/python3.7/dist-packages/borg/repository.py", line 269, in create
celery-backup stderr |     os.mkdir(path)
celery-backup stderr | PermissionError: [Errno 13] Permission denied: '/weblate_borgbackup'
celery-backup stderr | 
celery-backup stderr | Platform: Linux 9ea5afd24e3b 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64
celery-backup stderr | Linux: debian 10.5 
celery-backup stderr | Borg: 1.1.13  Python: CPython 3.7.3 msgpack: 0.5.6
celery-backup stderr | PID: 4908  CWD: /
celery-backup stderr | sys.argv: ['/usr/local/bin/borg', '--rsh', '/app/data/ssh/ssh-weblate-wrapper-db5c5ca9e000131e', 'init', '--encryption', 'repokey-blake2', 'weblate_borgbackup']
celery-backup stderr | SSH_ORIGINAL_COMMAND: None
```

**Expected behavior**

Successful completion of the backup.

**Server configuration and status**
```bash
 * Weblate: 4.2.1
 * Django: 3.1
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 3.0.0
 * lxml: 4.5.2
 * Pillow: 7.2.0
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 3.3.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.1
 * django-filter: 2.3.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.4
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.1
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.16.5
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.7
 * borgbackup: 1.1.13
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.5
 * psycopg2-binary: 2.8.5
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.14.47
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * iniparse: 0.5
 * mysqlclient: 2.0.1
 * Mercurial: 5.5
 * git-svn: 2.20.1
 * git-review: 1.28.0
 * hub: 2.13.0
 * lab: 0.16
 * Redis server: 5.0.9
 * PostgreSQL server: 11.7
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.gmail.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.15.0-112-generic (x86_64
```

**Weblate deploy checks**

``` bash
DEBUG git: exec git config --global user.name Weblate [retcode=0]
DEBUG git: exec git config --global user.name Weblate [retcode=0]
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.C029) There was error while performing backups: missing
        HINT: https://docs.weblate.org/en/weblate-4.2.1/admin/backup.html
```

**Comment by nijel** [comment]
The `weblate_borgbackup` does not seem to exist in the container and borg fails to create it because it is running as weblate user which cannot write to the root filesystem. 

Anyway backing up to non-existing location in the container makes little sense as that will disappear on container restart. You should add a volume for storing the backups. Alternatively, you can backup to existing data volume and use `/app/data/weblate_borgbackup` as path for backups.

**Comment by bilalcorbacioglu** [comment]
@nijel One more question: As you know it's possible to backup to another server with borg. How can I do this with Weblate on Docker Container?

**Comment by nijel** [comment]
Just for the reference (as the question was removed meanwhile here), this is covered by the documentation: https://docs.weblate.org/en/latest/admin/backup.html#using-custom-backup-storage

**Comment by dmpanch** [comment]
Faced with same issue, adding weblate user to the root group of the host system doesn't solve the it.

Unfortunately, using borgbackup as docker volume instead of host directory also lead to the same error.

```
celery-backup stderr | ERROR Failure while executing task: BackupError: {'signal': <Signal: task_failure providing_args={'task_id', 'kwargs', 'traceback', 'exception', 'einfo', 'args'}>, 'sender': <@task: weblate.wladmin.tasks.backup_service of weblate at 0x7efc9808e550>, 'task_id': '17906037-fa03-4171-ae6a-c5a930e4d609', 'args': [], 'kwargs': {'pk': '7'}, 'traceback': <traceback object at 0x7efc8f672448>, 'einfo': <ExceptionInfo: BackupError('Local Exception\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.7/dist-packages/borg/archiver.py", line 4565, in main\n    exit_code = archiver.run(args)\n  File "/usr/local/lib/python3.7/dist-packages/borg/archiver.py", line 4497, in run\n    return set_ec(func(args))\n  File "/usr/local/lib/python3.7/dist-packages/borg/archiver.py", line 161, in wrapper\n    with repository:\n  File "/usr/local/lib/python3.7/dist-packages/borg/repository.py", line 188, in __enter__\n    self.create(self.path)\n  File "/usr/local/lib/python3.7/dist-packages/borg/repository.py", line 272, in create\n    with open(os.path.join(path, \'README\'), \'w\') as fd:\nPermissionError: [Errno 13] Permission denied: \'/app/data/borgbackup/README\'\n\nPlatform: Linux d57494082071 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64\nLinux: debian 10.4 \nBorg: 1.1.13  Python: CPython 3.7.3 msgpack: 0.5.6\nPID: 661  CWD: /\nsys.argv: [\'/usr/local/bin/borg\', \'--rsh\', \'/app/data/ssh/ssh-weblate-wrapper-605e2eb8033ee0bb155e6ab512c148d1\', \'init\', \'--encryption\', \'repokey-blake2\', \'/app/data/borgbackup\']\nSSH_ORIGINAL_COMMAND: None\n\n')>}
```

Part of my docker-compose:

```
  weblate:
    image: weblate/weblate:4.1.1-3
    volumes:
      - weblate-data:/app/data
      - borgbackup:/app/data/borgbackup
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
    environment:
      WEBLATE_ENABLE_HTTPS: 1
      WEBLATE_IP_PROXY_HEADER: HTTP_X_FORWARDED_FOR
  database:
    image: postgres:11-alpine
    env_file:
      - ./environment
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
```
