### ISSUE TITLE
Migration failure when used with an Azure Database for PostgreSQL server

### ISSUE THREAD

**Issue by SimonGolms** [WeblateOrg/weblate#4708]
**Describe the bug**

We want to use the latest docker image `weblate/weblate:4.3-1` in our Azure instance and an Azure Database for PostgreSQL server. However, the initial migration  already fails during the build because it can't resolve the `POSTGRES_USER` correctly. Due to the fact that Azure PostgreSQL requires all usernames to be in the format `<username@hostname>`, apparently django/psycopg code that reads the `POSTGRES_USER` env doesn't interpret the `@` symbol properly and thus doesn't authenticate and perform the install, here is the full error stack:

```txt
Starting...
Creating /app/data/python/customize
Postgres is up
Starting database migration...
Operations to perform:
  Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, fonts, gitexport, glossary, lang, memory, screenshots, sessions, social_django, trans, weblate_auth, wladmin
Running migrations:
  Applying weblate_auth.0001_initial... OK
  Applying lang.0001_squashed_0008_auto_20200408_0436... OK
  Applying trans.0001_squashed_0074_fix_broken_browser_alert... OK
  Applying trans.0075_auto_20200501_1428... OK
  Applying trans.0076_comment_userdetails... OK
  Applying trans.0077_auto_20200513_1512... OK
  Applying trans.0078_auto_20200515_0729... OK
  Applying trans.0079_auto_20200519_1436... OK
  Applying trans.0080_auto_20200522_0909... OK
  Applying trans.0081_announcement_notify... OK
  Applying trans.0082_component_push_branch... OK
  Applying trans.0083_component_restricted... OK
  Applying trans.0084_auto_20200605_0648... OK
  Applying lang.0009_auto_20200521_0753... OK
  Applying glossary.0001_initial... OK
  Applying trans.0085_change_glossary_term... OK
  Applying glossary.0002_migrate_dictionary... OK
  Applying trans.0086_auto_20200609_1134... OK
  Applying trans.0087_auto_20200615_0747... OK
  Applying trans.0088_component_auto_lock_error... OK
  Applying trans.0089_auto_20200630_1321... OK
  Applying trans.0090_alert_updated... OK
  Applying trans.0091_json_key... OK
  Applying trans.0092_alert_dismissed... OK
  Applying trans.0093_auto_20200730_1432... OK
  Applying trans.0094_project_language_aliases... OK
  Applying trans.0095_fix_json_units... OK
  Applying trans.0096_fix_enforced_checks... OK
  Applying lang.0010_auto_20200627_0508... OK
  Applying glossary.0003_fulltext... OK
  Applying glossary.0004_glossary_source_language... OK
  Applying glossary.0005_set_source_language... OK
  Applying trans.0097_component_source_language... OK
  Applying trans.0098_move_source_language... OK
  Applying trans.0099_remove_project_source_language... OK
  Applying trans.0100_auto_20200912_1131... OK
  Applying trans.0101_fix_rename_changes... OK
  Applying trans.0102_unit_source_unit... OK
  Applying trans.0103_update_source_unit... OK
  Applying trans.0104_update_source_unit_source... OK
  Applying social_django.0001_initial... OK
  Applying accounts.0001_squashed_0019_auto_20200403_2004... OK
  Applying accounts.0002_profile_nearby_strings... OK
  Applying accounts.0003_auto_20200630_1321... OK
  Applying accounts.0004_profile_commented... OK
  Applying accounts.0005_update_comment_count... OK
  Applying accounts.0006_auto_20200903_0817... OK
  Applying accounts.0007_auto_20200904_0840... OK
  Applying accounts.0008_auto_20200923_1216... OK
  Applying accounts.0009_auto_20200923_2023... OK
  Applying addons.0001_squashed_0021_linguas_daily... OK
  Applying contenttypes.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747... OK
  Applying authtoken.0003_tokenproxy... OK
  Applying checks.0001_squashed_0003_auto_20191212_1441... OK
  Applying checks.0004_auto_20200516_1821... OK
  Applying fonts.0001_squashed_0007_auto_20190517_1907... OK
  Applying gitexport.0001_squashed_0002_fill_in_url... OK
  Applying weblate_auth.0002_auto_20180507_1540_squashed_0011_auto_20180509_0739_squashed_0007_group_components... OK
  Applying memory.0001_squashed_0006_memory_update... OK
  Applying memory.0007_use_trigram... OK
WARNING Handled exception: ProgrammingError: role "weblate@hostname" does not exist

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedObject: role "weblate@hostname" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/weblate/runner.py", line 32, in main
    execute_from_command_line(argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/commands/migrate.py", line 245, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/executor.py", line 227, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/usr/local/lib/python3.7/dist-packages/weblate/memory/migrations/0008_adjust_similarity.py", line 18, in update_index
    schema_editor.quote_name(schema_editor.connection.settings_dict["USER"])
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/schema.py", line 142, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: role "weblate@hostname" does not exist

  Applying memory.0008_adjust_similarity...
```

**To Reproduce**

1. Start with a fresh Azure PostgreSQL DB and fresh weblate instance.
2. Edit your env variables as shown in the example above to match your AzurePostgreSQL settings.
3. Run the `weblate:4:3-1` image to setup and configure your Weblate instance, and you will get the shown results.

**Expected behavior**

I expect to be able to configure the docker image to use an external PostgreSQL database as outlined in Weblate documentation like so:

```env
POSTGRES_PASSWORD=***** # PostgreSQL password.
POSTGRES_USER=weblate@hostname # PostgreSQL username.
POSTGRES_DATABASE=weblate # PostgreSQL database name.
POSTGRES_HOST=hostname.postgres.database.azure.com # PostgreSQL server hostname or IP address. Defaults to database.
POSTGRES_PORT=5432 # PostgreSQL server port. Defaults to none (uses the default value).
POSTGRES_SSL_MODE=require
```

And then be able to run the docker image build which should result in a successful Weblate configuration/deployment.

**Server configuration and status**

Unfortunately, can not be delivered

**Weblate deploy checks**

Unfortunately, can not be delivered

**Exception traceback**

See above

**Additional context**

```sql
$ psql "host=hostname.postgres.database.azure.com port=5432 dbname=postgres user=weblate@hostname password=****** sslmode=require"
postgres=> \l
                                                               List of databases
       Name        |      Owner      | Encoding |          Collate           |           Ctype            |          Access privileges
-------------------+-----------------+----------+----------------------------+----------------------------+-------------------------------------
 azure_maintenance | azure_superuser | UTF8     | English_United States.1252 | English_United States.1252 | azure_superuser=CTc/azure_superuser
 azure_sys         | azure_superuser | UTF8     | English_United States.1252 | English_United States.1252 |
 postgres          | azure_superuser | UTF8     | English_United States.1252 | English_United States.1252 |
 template0         | azure_superuser | UTF8     | English_United States.1252 | English_United States.1252 | =c/azure_superuser                 +
                   |                 |          |                            |                            | azure_superuser=CTc/azure_superuser
 template1         | azure_superuser | UTF8     | English_United States.1252 | English_United States.1252 | =c/azure_superuser                 +
                   |                 |          |                            |                            | azure_superuser=CTc/azure_superuser
 weblate           | weblate         | UTF8     | English_United States.1252 | English_United States.1252 |
postgres=> \du+
                                                 List of roles
    Role name    |                         Attributes                         |    Member of     | Description
-----------------+------------------------------------------------------------+------------------+-------------
 azure_pg_admin  | Cannot login, Replication                                  | {}               |
 azure_superuser | Superuser, Create role, Create DB, Replication, Bypass RLS | {}               |
 weblate         | Create role, Create DB, Replication                        | {azure_pg_admin} |
```

**Comment by nijel** [comment]
Can't you use just ```POSTGRES_USER=weblate```? 

Anyway there used to be setting on database level, but that didn't work well in some cases as well (see #3940) and was changed to per role adjustments in bbf6f11e21dabfee760725b2ebb32fe84e8180f6.

**Comment by SimonGolms** [comment]
Hi @nijel, unfortunately a database connection cannot be established with `POSTGRES_USER=weblate`

Thanks for the note about the mention ticket, which I have already seen, but I'd like to use the Docker Image unchanged.
I am not a Python expert, but would such a workaround be possible?
```python
    schema_editor.execute(
        "ALTER ROLE {} SET pg_trgm.similarity_threshold = 0.5".format(
#            schema_editor.connection.settings_dict["USER"]
            schema_editor.connection.settings_dict["USER"][:schema_editor.connection.settings_dict["USER"].find("@")]
        )
```

**Comment by nijel** [comment]
Something like that would work in your case, but I'm not sure it's generally safe thing to do - nothing prevents you from creating role containing `@`.

**Comment by nijel** [comment]
There will be a `POSTGRES_ALTER_ROLE` setting in 4.3.1 allowing you to set name of role to alter to deal with such setups.

**Comment by woeterman94** [comment]
I'm using POSTGRES_ALTER_ROLE and I'm getting a similar error
`django.db.utils.ProgrammingError: role "postgres@xxx-postgresql-dev-we-001" does not exist  `
