### ISSUE TITLE
Can't confirm or login with new user after upgrade to 3.11.3 -- IntegrityError: null value in column "social_id" violates not-null constraint

### ISSUE THREAD

**Issue by zen-fu** [WeblateOrg/weblate#4832]
**Describe the bug**

After upgrading from 3.8 to 3.11.3, when I register a user and try to confirm it or ask for a new password with URLs sent over e-mail, I get an error in the Weblate web interface:

```
The server had serious problems serving your request. Trained monkeys are
en-route fixing the issue.
```

The full traceback in the server log is further below, and boils down to:

```
IntegrityError: null value in column "social_id" violates not-null constraint
```

**To Reproduce the bug**

We have upgraded Weblate from 3.8 to 3.9.1, then to 3.10.3, and then to 3.11.3, so I'm not sure how to reproduce this one. We're using Debian Stretch with Python 3.5.3 and Weblate dependencies installed from upstream repositories.

**Expected behavior**

Successful e-mail confirmation and login, no error in web interface, no traceback in logs.

**Server configuration and status**

```
System check identified some issues:

INFOS:
?: (weblate.I031) New Weblate version is available, please upgrade to 4.3.2.
        HINT: https://docs.weblate.org/en/weblate-3.11.3/admin/upgrade.html
 * Weblate: weblate-3.11.3
 * Django: 2.2.17
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 2.5.1
 * lxml: 4.6.1
 * Pillow: 4.0.0
 * bleach: 3.1.5
 * six: 1.14.0
 * python-dateutil: 2.8.1
 * social-auth-core: 3.2.0
 * social-auth-app-django: 3.1.0
 * django-crispy-forms: 1.8.1
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.2
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 50.3.2.post20201105
 * jellyfish: 0.7.2
 * openpyxl: 2.6.4
 * celery: 4.4.7
 * kombu: 4.6.11
 * celery-batches: 0.2
 * translation-finder: 1.8
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.38.0
 * diff-match-patch: 20181111
 * requests: 2.23.0
 * django-redis: 4.11.0
 * hiredis: 1.0.1
 * sentry_sdk: 0.14.4
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.11
 * borgbackup: 1.1.14
 * Python: 3.5.3
 * Git: 2.11.0
 * psycopg2: 2.6.2
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.12
 * Mercurial: 4.0
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:MemcachedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * Celery: redis://:3I0eY3Bx5Cv8FrmIpyfKED4X4S0t8fMH@localhost:6379, redis://:3I0eY3Bx5Cv8FrmIpyfKED4X4S0t8fMH@localhost:6379, regular
 * Platform: Linux 4.9.0-14-amd64 (x86_64)
```

**Weblate deploy checks**

```
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.

INFOS:
?: (weblate.I021) Error collection is not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-3.11.3/admin/install.html#collecting-errors
?: (weblate.I031) New Weblate version is available, please upgrade to 4.3.2.
        HINT: https://docs.weblate.org/en/weblate-3.11.3/admin/upgrade.html

System check identified 3 issues (8 silenced).
```

The silenced checks are:

- weblate.I028
- security.W008
- weblate.W025.srt
- weblate.W025.ass
- weblate.W025.sub
- weblate.W025.php
- weblate.W025.ssa
- admin.E408

**Exception traceback**

```
        2020-11-06 20:57:46,906 INFO Correct CAPTCHA for me@example.org (13 - 8 = 5)
        2020-11-06 20:57:46,942 INFO sending notification activation on /accounts/complete/email/?verification_code=[REMOVED]&partial_token=[REMOVED] to me@example.org
        2020-11-06 20:59:08,028 ERROR Internal Server Error: /accounts/complete/email/
        Traceback (most recent call last):
          File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 538, in get_or_create
            return self.get(**kwargs), False
          File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 408, in get
            self.model._meta.object_name
        weblate.accounts.models.VerifiedEmail.DoesNotExist: VerifiedEmail matching query does not exist.
        ​
        During handling of the above exception, another exception occurred:
        ​
        Traceback (most recent call last):
          File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 84, in _execute
            return self.cursor.execute(sql, params)
        psycopg2.IntegrityError: null value in column "social_id" violates not-null constraint
        DETAIL:  Failing row contains (223, me@example.org, null).
    ​
    ​
    The above exception was the direct cause of the following exception:
    ​
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 34, ininner
        response = get_response(request)
      File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 115, in _get_response
        response = self.process_exception_by_middleware(e, request)
      File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 113, in _get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
        return view_func(*args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
        response = view_func(request, *args, **kwargs)
      File "/usr/local/share/weblate/weblate/accounts/views.py", line 1042, in social_complete
        return complete(request, backend)
      File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
        response = view_func(request, *args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
        return view_func(*args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/social_django/utils.py", line 49, in wrapper
        return func(request, backend, *args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/social_django/views.py", line 33, in complete
        *args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/social_core/actions.py", line 39, in do_complete
        user = backend.continue_pipeline(partial)
      File "/usr/local/lib/python3.5/dist-packages/social_core/backends/base.py", line 201, in continue_pipeline
        **partial.kwargs)
      File "/usr/local/lib/python3.5/dist-packages/social_django/strategy.py", line 107, in authenticate
        return authenticate(*args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/django/contrib/auth/__init__.py", line 73, in authenticate
        user = backend.authenticate(request, **credentials)
      File "/usr/local/lib/python3.5/dist-packages/social_core/backends/base.py", line 80, in authenticate
        return self.pipeline(pipeline, *args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/social_core/backends/base.py", line 83, in pipeline
        out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/social_core/backends/base.py", line 113, in run_pipeline
        result = func(*args, **out) or {}
      File "/usr/local/share/weblate/weblate/accounts/pipeline.py", line 341, in store_email
        social=social, defaults={'email': details['email']}
      File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 541, in get_or_create
        return self._create_object_from_params(kwargs, params)
      File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 583, in _create_object_from_params
        raise e
      File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 575, in _create_object_from_params
        obj = self.create(**params)
      File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 422, in create
        obj.save(force_insert=True, using=self.db)
      File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 744, in save
        force_update=force_update, update_fields=update_fields)
      File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 782, in save_base
        force_update, using, update_fields,
      File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 873, in _save_table
        result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
      File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 911, in _do_insert
        using=using, raw=raw)
      File "/usr/local/lib/python3.5/dist-packages/django/db/models/manager.py", line 82, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
      File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 1186, in _insert
        return query.get_compiler(using=using).execute_sql(return_id)
      File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1377, in execute_sql
        cursor.execute(sql, params)
      File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 67, in execute
        return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
      File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
        return executor(sql, params, many, context)
      File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 84, in _execute
        return self.cursor.execute(sql, params)
      File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 89, in __exit__
        raise dj_exc_value.with_traceback(traceback) from exc_value
      File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 84, in _execute
        return self.cursor.execute(sql, params)
    django.db.utils.IntegrityError: null value in column "social_id" violates not-null constraint
    DETAIL:  Failing row contains (223, me@example.org, null).
```

**Additional context**

We don't deviate much from upstream's `settings_default.py`, and certainly not in `social_django`-related configuration, middlewares, authentication backends, etc.

**Comment by nijel** [comment]
It might some incompatibility between python-social-auth and Weblate. Please check if SOCIAL_AUTH_PIPELINE matches example settings.

**Comment by zen-fu** [comment]
Hi, @nijel! Thanks for your quick response.

> It might some incompatibility between python-social-auth and Weblate. Please check if SOCIAL_AUTH_PIPELINE matches example settings.

Yes, we're using the same settings in `SOCIAL_AUTH_PIPELINE` and `SOCIAL_AUTH_PIPELINE_DISCONNECT`:

```
SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    "weblate.accounts.pipeline.store_params",
    "weblate.accounts.pipeline.verify_open",
    "social_core.pipeline.user.get_username",
    "weblate.accounts.pipeline.require_email",
    "social_core.pipeline.mail.mail_validation",
    "weblate.accounts.pipeline.revoke_mail_code",
    "weblate.accounts.pipeline.ensure_valid",
    "weblate.accounts.pipeline.remove_account",
    "social_core.pipeline.social_auth.associate_by_email",
    "weblate.accounts.pipeline.reauthenticate",
    "weblate.accounts.pipeline.verify_username",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "weblate.accounts.pipeline.cleanup_next",
    "weblate.accounts.pipeline.user_full_name",
    "weblate.accounts.pipeline.store_email",
    "weblate.accounts.pipeline.notify_connect",
    "weblate.accounts.pipeline.password_reset",
)
SOCIAL_AUTH_DISCONNECT_PIPELINE = (
    "social_core.pipeline.disconnect.allowed_to_disconnect",
    "social_core.pipeline.disconnect.get_entries",
    "social_core.pipeline.disconnect.revoke_tokens",
    "weblate.accounts.pipeline.cycle_session",
    "weblate.accounts.pipeline.adjust_primary_mail",
    "weblate.accounts.pipeline.notify_disconnect",
    "social_core.pipeline.disconnect.disconnect",
    "weblate.accounts.pipeline.cleanup_next",
)
```

Versions of related deps also match the ones in `requirements.txt`:

```
social-auth-app-django (3.1.0)
social-auth-core (3.2.0)
```

**Comment by zen-fu** [comment]
> This issue looks more like a support question than an issue. We strive to answer these reasonably fast, but [purchasing the support subscription](https://weblate.org/support/) is not only more responsible and faster for your business but also makes Weblate stronger. In case your question is already answered, [making a donation](https://weblate.org/donate/) is the right way to say thank you!

I agree and will consult about the possibility of purchasing support and/or making a donation. Thanks a lot for not blocking on this, though. :-)

**Comment by nijel** [comment]
That looks correct `social_core.pipeline.user.create_user` creates user (if not set before) and `social_core.pipeline.social_auth.associate_user` creates social auth object. So, it is supposed to be set in further steps...

Do you see something suspicious in the log with debug enabled?

**Comment by zen-fu** [comment]
Thanks for the idea of enabling debug and looking through the log. It helped me go deep and find the problem, even though I still don't know how to fix it.

I found that the schema of our `social_auth_usersocialauth` table is different from the one in a fresh installation of Weblate (I looked at the DB created by the Docker image) The difference in the schema causes `social_core.pipeline.social_auth.associate_user` to [fail creating the object in the database](https://github.com/python-social-auth/social-core/blob/3.2.0/social_core/pipeline/social_auth.py#L35):

```
null value in column "created" violates not-null constraint
DETAIL:  Failing row contains (260, email, me@example.org, {}, 254, null, null).
```

That is an `IntegrityError` and is purposefully not raised. I don't really understand why the exception is treated the way it is in `associate_user()`, but it seems that the `except` clause should not be reached in the current circumstance.

This is the schema of our `social_auth_usersocialauth` table:

```sql
CREATE TABLE public.social_auth_usersocialauth (
    id integer NOT NULL,
    provider character varying(32) NOT NULL,
    uid character varying(255) NOT NULL,
    extra_data text NOT NULL,
    user_id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    modified timestamp with time zone NOT NULL
);
```

This is the schema of the `social_auth_usersocialauth` table from a fresh install using the Docker image:

```sql
CREATE TABLE public.social_auth_usersocialauth (
    id integer NOT NULL,
    provider character varying(32) NOT NULL,
    uid character varying(255) NOT NULL,
    extra_data text NOT NULL,
    user_id integer NOT NULL
);
```

I currently don't know:
- why our schema is different from what it should be, and
- how to fix it "the proper way"

Next, I'll try to find migrations touching this table and see if that brings some light into how to fix. I vaguely remember a split in the a package involving the social modules, maybe this is also related.

**Comment by zen-fu** [comment]
Hi, I found what was wrong, and it had nothing to do with the package split:

- We were running Weblate 3.5.1, which required `social-auth-app-django>=3.1.0`.
- `social-auth-app-django` version 4.0.0 was released on June 21st 2020.
- Shortly after that, we upgraded some of Weblate dependencies, including `social-auth-app-django` to 4.0.0. Migrations were applied.
- We updated Weblate to 3.11.3 which has a more restrictive requirement for that package: `social-auth-app-django==3.1.0` (introduced in Weblate 3.9.1). At that point, we downgraded `social-auth-app-django` to 3.1.0, but didn't revert the migrations introduced previously.

What had to be done to fix:

- Manually copy the [newer missing migrations](https://github.com/python-social-auth/social-app-django/tree/4.0.0/social_django/migrations) to the migrations folder of `social-auth-app-django` (that is `/usr/local/lib/python3.5/dist-packages/social_django/migrations` in our Debian box).
- Apply the last migration for `social-auth-app-django` 3.1.0, which unapplies the newer ones:
```
# ./manage.py migrate social_django 0008_partial_timestamp
Operations to perform:
  Target specific migration: 0008_partial_timestamp, from social_django
Running migrations:
  Rendering model states... DONE
  Unapplying social_django.0010_uid_db_index... OK
  Unapplying social_django.0009_auto_20191118_0520... OK
```

After that our registration is working again.

My understanding is that this problem was thus caused by some misfortunes plus bad dependency management on our side.

Thanks for maintaining Weblate, it's super useful for us.

**Comment by nijel** [comment]
> That is an `IntegrityError` and is purposefully not raised. I don't really understand why the exception is treated the way it is in `associate_user()`, but it seems that the `except` clause should not be reached in the current circumstance.

The idea seems to be that `IntegrityError` is raised only in case the matching row already exists and it can be safely ignored in that case and return existing object. This pull request should address it: https://github.com/python-social-auth/social-core/pull/521
