### ISSUE TITLE
Can't commit json files

### ISSUE THREAD

**Issue by ilkarataev** [WeblateOrg/weblate#4854]
Hi , i am using weblate in docker-compose last version.
I am import simple component with json.I had error on commit 
Server Error
The server had serious problems serving your request. Trained monkeys are en-route fixing the issue.

I am attach json file and log from container

[de.json.txt](https://github.com/WeblateOrg/weblate/files/5542664/de.json.txt)

[logs.txt](https://github.com/WeblateOrg/weblate/files/5542665/logs.txt)

I catch the problem with my json files.But i am convert it from mysql and php functions json_encode.Maybe you have some best practice for convertations?

**Comment by nijel** [comment]
Including the traceback from the log so that it can be searched by others:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/views/git.py", line 128, in commit_translation
    return perform_commit(request, obj)
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/views/git.py", line 57, in perform_commit
    request.user,
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/views/git.py", line 35, in execute_locked
    result = call(*args, **kwargs)
  File "/usr/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/translation.py", line 516, in commit_pending
    self.update_units(units, store, author_name, author.id)
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/translation.py", line 692, in update_units
    store.save()
  File "/usr/local/lib/python3.7/dist-packages/weblate/formats/ttkit.py", line 299, in save
    self.save_atomic(self.storefile, self.save_content)
  File "/usr/local/lib/python3.7/dist-packages/weblate/formats/base.py", line 301, in save_atomic
    callback(temp)
  File "/usr/local/lib/python3.7/dist-packages/weblate/formats/ttkit.py", line 295, in save_content
    self.store.serialize(handle)
  File "/usr/local/lib/python3.7/dist-packages/translate/storage/jsonl10n.py", line 170, in serialize
    self.serialize_units(units)
  File "/usr/local/lib/python3.7/dist-packages/translate/storage/base.py", line 997, in serialize_units
    unit.storevalues(output)
  File "/usr/local/lib/python3.7/dist-packages/translate/storage/jsonl10n.py", line 132, in storevalues
    self.storevalue(output, self.converttarget())
  File "/usr/local/lib/python3.7/dist-packages/translate/storage/base.py", line 951, in storevalue
    target.append(default)
AttributeError: 'collections.OrderedDict' object has no attribute 'append'
```

**Comment by nijel** [comment]
The issue should be fixed by https://github.com/translate/translate/pull/4168
