### ISSUE TITLE
Need document for changes of BaseAddon.post_update method

### ISSUE THREAD

**Issue by exzhawk** [WeblateOrg/weblate#4896]
**Describe the issue**

`BaseAddon.post_update` method signature was changed by adding a `skip_push` param, but this change is not revealed in the documents.
Related commit: 11652c17

Could you please add a notice in version specific instructions to avoid addon outage? Thank you!

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce**

1. Write an addon and enable it in weblate 4.3.1
```python
class MyAddon(BaseAddon):
    def post_update(self, main_component, previous_head):
        pass
```
2. Upgrade site to weblate 4.3.2

**Expected behavior**

The addon works as expected

**Screenshots**

**Server configuration and status**
```
docker-compose exec weblate weblate list_versions
 * Weblate: 4.3.2                 
```

**Weblate deploy checks**

**Exception traceback**

```
weblate_1   | uwsgi stderr | [2020-11-22 21:54:47,855: ERROR/19733] Internal Server Error: /addons/project/component/                                                                                           
weblate_1   | uwsgi stderr | Traceback (most recent call last):                                                                                                                                                                         
weblate_1   | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner                                                                                                       
weblate_1   | uwsgi stderr |     response = get_response(request)                                                                                                                                                                       
weblate_1   | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 179, in _get_response                                                                                                   
weblate_1   | uwsgi stderr |     response = wrapped_callback(request, *callback_args, **callback_kwargs)                                                                                                                                
weblate_1   | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback                                                                              
weblate_1   | uwsgi stderr |     return callback(request, *args, **kwargs)                                                                                                                                                              
weblate_1   | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/django/views/generic/base.py", line 70, in view                                                                                                             
weblate_1   | uwsgi stderr |     return self.dispatch(request, *args, **kwargs)                                                                                                                                                         
weblate_1   | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/django/views/generic/base.py", line 98, in dispatch                                                                                                         
weblate_1   | uwsgi stderr |     return handler(request, *args, **kwargs)                                                                                                                                                               
weblate_1   | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/weblate/addons/views.py", line 88, in post                                                                                                                  
weblate_1   | uwsgi stderr |     addon.create(component)                                                                                                                                                                                
weblate_1   | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/weblate/addons/base.py", line 108, in create                                                                                                                
weblate_1   | uwsgi stderr |     result.post_configure()                                                                                                                                                                                
weblate_1   | uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/weblate/addons/base.py", line 157, in post_configure                                                                                                        
weblate_1   | uwsgi stderr |     self.post_update(component, "", False)                                                                                                                                                                 
weblate_1   | uwsgi stderr | TypeError: post_update() takes 3 positional arguments but 4 were given                                                                                                                                     
```

**Additional context**

**Comment by nijel** [comment]
Sorry, as there is currently no documentation on addons API, I didn't realize this needs to be documented...
