### ISSUE TITLE
Wrong path to download after changing Files paths in component

### ISSUE THREAD

**Issue by surli** [WeblateOrg/weblate#5265]
**Describe the issue**

We changed recently the file paths of some of our components (both the Mask path and the base language file path) because of the change of formats (to be a bit specific, we were using a virtual path manipulated by some addons before the introduction of the XWiki formats in Weblate). So now the files do not exist anymore on the old paths. 
However I'm receiving some error mails about file not found to the old paths when using the /download/ API. 
To be more specific, I reproduce the error quite easily when going in that kind of URL: `/download/project/component/language`.
Also note that I've restarted Weblate several times since the file path change.

**I already tried**

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.
- [x] I've checked again the component settings and the component repository, all is fine there.

**To Reproduce the issue**

I'm not sure about those steps.

1. Setup weblate with some components and languages
2. Change the paths of some  translations files and edit the component settings
3. Go to an existing language translation and click on "Files" > "Download original translation file"

**Expected behavior**

The new path should be immediately used.

**Exception traceback**

```
Internal Server Error: /download/xwiki-contrib/tour-application/fr/

FileNotFoundError at /download/xwiki-contrib/tour-application/fr/
[Errno 2] No such file or directory: '/var/weblate/data/vcs/xwiki-contrib/tour-application/.translation/application-tour-ui/src/main/resources/TourCode/TourTranslations_fr.properties'

Request Method: GET
Request URL: https://l10n.xwiki.org/download/xwiki-contrib/tour-application/fr/
Django Version: 3.1.5
Python Executable: /usr/bin/uwsgi-core
Python Version: 3.7.3
Python Path: ['/home/weblate/weblate-env/lib/python3.7/site-packages/git/ext/gitdb', '/', '.', '', '/home/weblate/weblate-env/lib/python37.zip', '/home/weblate/weblate-env/lib/python3.7', '/home/weblate/weblate-env/lib/python3.7/lib-dynload', '/usr/lib/python3.7', '/home/weblate/weblate-env/lib/python3.7/site-packages', '/home/weblate/weblate-env/lib/python3.7/site-packages/gitdb/ext/smmap']
Server time: Mon, 25 Jan 2021 09:04:04 +0000
Installed Applications:
['weblate.addons',
 'weblate.auth',
 'weblate.checks',
 'weblate.configuration',
 'weblate.formats',
 'weblate.glossary',
 'weblate.machinery',
 'weblate.trans',
 'weblate.lang',
 'weblate_language_data',
 'weblate.memory',
 'weblate.screenshots',
 'weblate.fonts',
 'weblate.accounts',
 'weblate.utils',
 'weblate.vcs',
 'weblate.wladmin',
 'weblate',
 'weblate.gitexport',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin.apps.SimpleAdminConfig',
 'django.contrib.admindocs',
 'django.contrib.sitemaps',
 'django.contrib.humanize',
 'social_django',
 'crispy_forms',
 'compressor',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters']
Installed Middleware:
['weblate.middleware.RedirectMiddleware',
 'weblate.middleware.ProxyMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'weblate.accounts.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'weblate.accounts.middleware.RequireLoginMiddleware',
 'weblate.api.middleware.ThrottlingMiddleware',
 'weblate.middleware.SecurityMiddleware']


Traceback (most recent call last):
  File "/home/weblate/weblate-env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/weblate/weblate-env/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/weblate/weblate-env/lib/python3.7/site-packages/weblate/trans/views/files.py", line 134, in download_translation
    return download_translation_file(request, obj, **kwargs)
  File "/home/weblate/weblate-env/lib/python3.7/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/weblate/weblate-env/lib/python3.7/site-packages/weblate/utils/views.py", line 285, in download_translation_file
    open(filenames[0], "rb"),

Exception Type: FileNotFoundError at /download/xwiki-contrib/tour-application/fr/
Exception Value: [Errno 2] No such file or directory: '/var/weblate/data/vcs/xwiki-contrib/tour-application/.translation/application-tour-ui/src/main/resources/TourCode/TourTranslations_fr.properties'
```

**Server configuration and status**

Weblate installation: pip

```
 * Weblate: 4.4.2
 * Django: 3.1.5
 * siphashc: 1.3
 * Whoosh: 2.7.4
 * translate-toolkit: 3.3.0
 * lxml: 4.5.2
 * Pillow: 7.1.2
 * bleach: 3.1.5
 * python-dateutil: 2.8.1
 * social-auth-core: 4.0.3
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.11.1
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 50.3.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 4.4.7
 * kombu: 4.6.11
 * translation-finder: 2.7
 * weblate-language-data: 2020.13
 * html2text: 2020.1.16
 * pycairo: 1.19.1
 * pygobject: 3.38.0
 * diff-match-patch: 20200713
 * requests: 2.24.0
 * django-redis: 4.12.1
 * hiredis: 1.0.1
 * sentry_sdk: 0.15.1
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.8
 * borgbackup: 1.1.13
 * pyparsing: 2.4.7
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2-binary: 2.8.6
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.12
 * Redis server: 5.0.3
 * PostgreSQL server: 11.9
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.19.0-12-amd64 (x86_64)
```

**Weblate deploy checks**

```
WARNINGS:
?: (weblate.W025.ass) Failure in loading handler for ass file format: aeidon or gaupol package required for Subtitle support
	HINT: https://docs.weblate.org/en/weblate-4.4.2/admin/install.html#optional-deps
?: (weblate.W025.ini) Failure in loading handler for ini file format: Missing iniparse library.
	HINT: https://docs.weblate.org/en/weblate-4.4.2/admin/install.html#optional-deps
?: (weblate.W025.islu) Failure in loading handler for islu file format: Missing iniparse library.
	HINT: https://docs.weblate.org/en/weblate-4.4.2/admin/install.html#optional-deps
?: (weblate.W025.laravel) Failure in loading handler for laravel file format: No module named 'phply'
	HINT: https://docs.weblate.org/en/weblate-4.4.2/admin/install.html#optional-deps
?: (weblate.W025.php) Failure in loading handler for php file format: No module named 'phply'
	HINT: https://docs.weblate.org/en/weblate-4.4.2/admin/install.html#optional-deps
?: (weblate.W025.srt) Failure in loading handler for srt file format: aeidon or gaupol package required for Subtitle support
	HINT: https://docs.weblate.org/en/weblate-4.4.2/admin/install.html#optional-deps
?: (weblate.W025.ssa) Failure in loading handler for ssa file format: aeidon or gaupol package required for Subtitle support
	HINT: https://docs.weblate.org/en/weblate-4.4.2/admin/install.html#optional-deps
?: (weblate.W025.sub) Failure in loading handler for sub file format: aeidon or gaupol package required for Subtitle support
	HINT: https://docs.weblate.org/en/weblate-4.4.2/admin/install.html#optional-deps
?: (weblate.W033.Gerrit) Failure in loading VCS module for Gerrit: git: 'review' is not a git command. See 'git --help'.
 (1)
	HINT: https://docs.weblate.org/en/weblate-4.4.2/vcs.html
?: (weblate.W033.Mercurial) Failure in loading VCS module for Mercurial: [Errno 2] No such file or directory: 'hg': 'hg'
	HINT: https://docs.weblate.org/en/weblate-4.4.2/vcs.html
?: (weblate.W033.Subversion) Failure in loading VCS module for Subversion: git: 'svn' is not a git command. See 'git --help'.

The most similar command is
	serve
 (1)
	HINT: https://docs.weblate.org/en/weblate-4.4.2/vcs.html

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.4.2/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.4.2/admin/backup.html

System check identified 13 issues (1 silenced).
```

**Comment by surli** [comment]
> Are there any component alerts?

I don't have any component alert. Now it's possible that I got errors when changing the setup back then but I thought I had them fixed since I don't have any alert.

> in case the component update didn't complete after changing the paths, these will be still pointing to the old locations.

So is there a way to trigger a component update with the current settings then, to ensure all paths stored in DB are correct?

**Comment by nijel** [comment]
You can do it from the command line using `weblate loadpo --force --foreground xwiki-contrib/tour-application` (foreground option is not required, but helps in debugging), see https://docs.weblate.org/en/latest/admin/management.html#loadpo

**Comment by surli** [comment]
Thanks I'll check that command  tomorrow and see if it fixes my issue.

**Comment by surli** [comment]
Thanks again for the pointer, apparently it did fix the problem.
