### ISSUE TITLE
weblate-dev docker container not accessible on 127.0.0.1:8080

### ISSUE THREAD

**Issue by bl00mber** [WeblateOrg/weblate#5348]
$ ./rundev.sh
```
...
Successfully built 67657739c88a
Successfully tagged weblate-dev:latest
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Recreating dev-docker_cache_1    ... done
Recreating dev-docker_database_1 ... done
Recreating dev-docker_weblate_1  ... done

Running development version of Weblate on http://127.0.0.1:8080/
```
$ docker ps
```
CONTAINER ID   IMAGE                COMMAND                  CREATED         STATUS                             PORTS                      NAMES
66b386f25c62   weblate-dev:latest   "/app/bin/start runs…"   9 minutes ago   Up 19 seconds (health: starting)   127.0.0.1:8080->8080/tcp   dev-docker_weblate_1
d3e7fc6146a0   postgres:12-alpine   "docker-entrypoint.s…"   9 minutes ago   Up 9 minutes                       5432/tcp                   dev-docker_database_1
0fee69659cdf   redis:6-alpine       "docker-entrypoint.s…"   9 minutes ago   Up 9 minutes                       6379/tcp                   dev-docker_cache_1
```
$ curl 127.0.0.1:8080
```
curl: (56) Recv failure: Connection reset by peer
```

**Comment by nijel** [comment]
> (health: starting)

The container has not yet fully started. Check the logs.

**Comment by bl00mber** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 5, in <module>
    from weblate.runner import main
  File "/usr/local/lib/python3.7/dist-packages/weblate/__init__.py", line 23, in <module>
    from weblate.vcs.git import GitRepository
  File "/usr/local/lib/python3.7/dist-packages/weblate/vcs/git.py", line 42, in <module>
    from weblate.vcs.gpg import get_gpg_sign_key
  File "/usr/local/lib/python3.7/dist-packages/weblate/vcs/gpg.py", line 29, in <module>
    from weblate.utils.checks import weblate_check
  File "/usr/local/lib/python3.7/dist-packages/weblate/utils/checks.py", line 36, in <module>
    from weblate.utils.docs import get_doc_url
  File "/usr/local/lib/python3.7/dist-packages/weblate/utils/docs.py", line 22, in <module>
    from weblate_language_data.docs import DOCUMENTATION_LANGUAGES
ModuleNotFoundError: No module named 'weblate_language_data.docs'
redis is unavailable - waiting 30
```

**Comment by nijel** [comment]
Seems like something went wrong with installing dependencies. Did you get any error during the container build? Do you have a log from the build to see what version of weblate_language_data is being installed?

**Comment by bl00mber** [comment]
commands are executed under `sudo su`
```
+ pip3 install -r /tmp/requirements.txt
WARNING: The directory '/home/weblate/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
```
may be `RUN chmod...` should be executed before `RUN pip3 install...`?

**Comment by nijel** [comment]
That should be harmless, pip can work just fine without a cache.

Sorry, the package name is `weblate-language-data`. 

The commit which introduced this code changed the dependency as well, so either it is not correctly passed to pip or something wrong is going on in the docker container. See 3abd8642e14

**Comment by bl00mber** [comment]
The Dockerfile uses `./requirements.txt` file in which weblate_language_data is not present, not `../../requirements.txt`. Maybe this is the cause of dependencies not being installed?

**Comment by nijel** [comment]
Yes, there was a bug in the requirements.txt build...

**Comment by bl00mber** [comment]
Thanks!
