### ISSUE TITLE
Update 4.6 fail, redit timeout cannot be higher as expire

### ISSUE THREAD

**Issue by reloxx13** [WeblateOrg/weblate#5918]
Heya, 

i tried to update but the huge glossary migration fails with:

> 
> Running migrations:
>   Applying trans.0116_migrate_glossaries...Migrating glossaries 0% [0/23]...PROJECTNAME
> Traceback (most recent call last):
>   File "./manage.py", line 32, in <module>
>     main(developer_mode=True)
>   File "/home/weblate/weblate/runner.py", line 34, in main
>     utility.execute()
>   File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 395, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 330, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 371, in execute
>     output = self.handle(*args, **options)
>   File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 85, in wrapped
>     res = handle_func(*args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/django/core/management/commands/migrate.py", line 245, in handle
>     fake_initial=fake_initial,
>   File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/executor.py", line 117, in migrate
>     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
>   File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
>     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
>   File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/executor.py", line 227, in apply_migration
>     state = migration.apply(state, schema_editor)
>   File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/migration.py", line 124, in apply
>     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
>   File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
>     self.code(from_state.apps, schema_editor)
>   File "/home/weblate/weblate/trans/migrations/0116_migrate_glossaries.py", line 83, in migrate_glossaries
>     repo = LocalRepository.from_files(repo_path, {})
>   File "/home/weblate/weblate/vcs/git.py", line 927, in from_files
>     with repo.lock:
>   File "/home/weblate/weblate/utils/lock.py", line 81, in __enter__
>     if not self._lock.acquire(timeout=self._timeout):
>   File "/usr/local/lib/python3.7/dist-packages/redis_lock/__init__.py", line 233, in acquire
>     raise TimeoutTooLarge("Timeout (%d) cannot be greater than expire (%d)" % (timeout, self._expire))
> redis_lock.TimeoutTooLarge: Timeout (120) cannot be greater than expire (5)
>

**Comment by reloxx13** [comment]
i have set it to 120 tempoary to get it running.
in

https://github.com/WeblateOrg/weblate/blob/ca6afc412bf7a72665068a0678808ace407211a1/weblate/utils/lock.py#L58

**Comment by nijel** [comment]
That should work because there is auto-renewal enabled:

https://github.com/ionelmc/python-redis-lock/blob/1842f8a6780613e8c89938218121e0ee464d2a50/src/redis_lock/__init__.py#L237-L238

Seems like we need to tighten the dependency because this behavior was introduced in https://github.com/ionelmc/python-redis-lock/commit/a01785d848003b7aa9fb2d32cf9dd8450cc9a58a which was released in 3.6.0.

Can you please confirm you are using an older version of python-redis-lock? (That's why the template has asked for versions...)

**Comment by reloxx13** [comment]
> That should work because there is auto-renewal enabled:
> 
> https://github.com/ionelmc/python-redis-lock/blob/1842f8a6780613e8c89938218121e0ee464d2a50/src/redis_lock/__init__.py#L237-L238
> 
> Seems like we need to tighten the dependency because this behavior was introduced in [ionelmc/python-redis-lock@a01785d](https://github.com/ionelmc/python-redis-lock/commit/a01785d848003b7aa9fb2d32cf9dd8450cc9a58a) which was released in 3.6.0.
> 
> Can you please confirm you are using an older version of python-redis-lock? (That's why the template has asked for versions...)


im sorry, i had to rush to get it online again :p

**Server configuration and status**

Weblate installation:  other (git)

On Git checkout:

./manage.py list_versions
```
sudo -u weblate ./manage.py list_versions
 * Weblate: weblate-4.6
 * Django: 3.1.4
 * siphashc: 1.3
 * translate-toolkit: 3.3.4
 * lxml: 4.6.2
 * Pillow: 8.0.1
 * bleach: 3.2.1
 * python-dateutil: 2.8.1
 * social-auth-core: 4.1.0
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.9.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4
 * djangorestframework: 3.12.2
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.1
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.5
 * celery: 5.0.5
 * kombu: 5.0.2
 * translation-finder: 2.7
 * weblate-language-data: 2021.4
 * html2text: 2020.1.16
 * pycairo: 1.20.0
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.21.0
 * django-redis: 4.12.1
 * hiredis: 1.1.0
 * sentry_sdk: 0.14.1
 * Cython: 0.29.21
 * misaka: 2.1.1
 * GitPython: 3.1.11
 * borgbackup: 1.1.14
 * pyparsing: 2.4.7
 * pyahocorasick: 1.4.2
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.4
 * psycopg2-binary: 2.8.4
 * phply: 1.2.5
 * chardet: 3.0.4
 * ruamel.yaml: 0.16.10
 * tesserocr: 2.5.0
 * akismet: 1.1
 * boto3: 1.12.5
 * zeep: 3.4.0
 * aeidon: 1.7.0
 * Mercurial: 5.3
 * git-review: 1.28.0
 * Redis server: 5.0.3
 * PostgreSQL server: 11.9
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: smtp.office365.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 4.19.0-13-amd64 (x86_64)
```


**Weblate deploy checks**

On Git checkout:

./manage.py check --deploy
```
sudo -u weblate ./manage.py check --deploy
System check identified some issues:

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (weblate.W025.ini) Failure in loading handler for ini file format: Missing iniparse library.
	HINT: https://docs.weblate.org/en/weblate-4.6/admin/install.html#optional-deps
?: (weblate.W025.islu) Failure in loading handler for islu file format: Missing iniparse library.
	HINT: https://docs.weblate.org/en/weblate-4.6/admin/install.html#optional-deps
?: (weblate.W033.Subversion) Failure in loading VCS module for Subversion: git: 'svn' is not a git command. See 'git --help'.

The most similar command is
	serve
 (1)
	HINT: https://docs.weblate.org/en/weblate-4.6/vcs.html

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.6/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
	HINT: https://docs.weblate.org/en/weblate-4.6/admin/backup.html

System check identified 6 issues (1 silenced).
```

**Comment by reloxx13** [comment]
the python-redis-lock is not listed there...

i dont know why.

```
pip3 list
Package                Version      
---------------------- -------------
aeidon                 1.7.0        
akismet                1.1          
amqp                   5.0.2        
appdirs                1.4.3        
argon2-cffi            20.1.0       
asgiref                3.3.1        
asn1crypto             0.24.0       
attrs                  19.3.0       
billiard               3.6.3.0      
bleach                 3.2.1        
borgbackup             1.1.14       
boto3                  1.12.5       
botocore               1.15.5       
cached-property        1.5.1        
celery                 5.0.5        
celery-batches         0.3          
certifi                2018.8.24    
cffi                   1.14.0       
chardet                3.0.4        
click                  7.1.2        
click-didyoumean       0.0.3        
click-plugins          1.1.1        
click-repl             0.1.6        
cryptography           2.6.1        
cssselect              1.1.0        
Cython                 0.29.21      
defusedxml             0.6.0        
diff-match-patch       20200713     
Django                 3.1.4        
django-appconf         1.0.4        
django-compressor      2.4          
django-crispy-forms    1.9.2        
django-filter          2.4.0        
django-redis           4.12.1       
djangorestframework    3.12.2       
docutils               0.15.2       
entrypoints            0.3          
et-xmlfile             1.0.1        
fail2ban               0.10.2       
filelock               3.0.12       
future                 0.18.2       
git-review             1.28.0       
gitdb                  4.0.1        
gitdb2                 4.0.2        
GitPython              3.1.11       
hiredis                1.1.0        
html2text              2020.1.16    
httplib2               0.11.3       
idna                   2.6          
importlib-metadata     1.5.0        
isc                    2.0          
isodate                0.6.0        
jdcal                  1.4.1        
jellyfish              0.8.2        
jmespath               0.9.4        
jsonschema             3.2.0        
keyring                17.1.1       
keyrings.alt           3.1.1        
kombu                  5.0.2        
lxml                   4.6.2        
mercurial              5.3          
methodtools            0.4.2        
misaka                 2.1.1        
oauthlib               3.1.0        
openpyxl               3.0.5        
packaging              20.8         
phply                  1.2.5        
Pillow                 8.0.1        
pip                    18.1         
ply                    3.11         
prompt-toolkit         3.0.8        
psycopg2               2.8.4        
psycopg2-binary        2.8.4        
pyahocorasick          1.4.2        
pycairo                1.20.0       
pycparser              2.19         
pycrypto               2.6.1        
pycurl                 7.43.0.2     
PyGObject              3.30.4       
pyinotify              0.9.6        
PyJWT                  2.0.0        
pyparsing              2.4.7        
pyrsistent             0.16.0       
PySimpleSOAP           1.16.2       
python-apt             1.8.4.3      
python-dateutil        2.8.1        
python-debian          0.1.35       
python-debianbts       2.8.2        
python-redis-lock      3.5.0        
python3-openid         3.1.0        
pytz                   2019.3       
pyxdg                  0.25         
rcssmin                1.0.6        
redis                  3.4.1        
reportbug              7.5.3-deb10u1
requests               2.21.0       
requests-oauthlib      1.3.0        
requests-toolbelt      0.9.1        
rjsmin                 1.1.0        
ruamel.yaml            0.16.10      
ruamel.yaml.clib       0.2.0        
s3transfer             0.3.3        
SecretStorage          2.3.1        
sentry-sdk             0.14.1       
setuptools             40.8.0       
siphashc               1.3          
six                    1.14.0       
smmap                  3.0.1        
social-auth-app-django 4.0.0        
social-auth-core       4.1.0        
sqlparse               0.3.0        
systemd-python         234          
tesserocr              2.5.0        
translate-toolkit      3.3.4        
translation-finder     2.7          
ua-parser              0.9.0        
ufw                    0.36         
urllib3                1.24.1       
user-agents            2.1          
uWSGI                  2.0.18       
vine                   5.0.0        
virtualenv             15.1.0       
wcwidth                0.2.5        
webencodings           0.5.1        
weblate-language-data  2021.4       
weblate-schemas        0.6          
wheel                  0.32.3       
Whoosh                 2.7.4        
wirerope               0.4.2        
zeep                   3.4.0        
zipp                   3.0.0 
```

**Comment by reloxx13** [comment]
did some upgrading:

```
pip3 list
Package                Version      
---------------------- -------------
aeidon                 1.7.0        
akismet                1.1          
amqp                   5.0.6        
appdirs                1.4.3        
argon2-cffi            20.1.0       
asgiref                3.3.4        
asn1crypto             0.24.0       
attrs                  20.3.0       
billiard               3.6.4.0      
bleach                 3.3.0        
borgbackup             1.1.16       
boto3                  1.12.5       
botocore               1.15.5       
cached-property        1.5.1        
celery                 5.0.5        
celery-batches         0.3          
certifi                2018.8.24    
cffi                   1.14.5       
chardet                3.0.4        
click                  7.1.2        
click-didyoumean       0.0.3        
click-plugins          1.1.1        
click-repl             0.1.6        
colorclass             2.2.0        
cryptography           2.6.1        
cssselect              1.1.0        
Cython                 0.29.23      
defusedxml             0.6.0        
diff-match-patch       20200713     
Django                 3.2          
django-appconf         1.0.4        
django-compressor      2.4.1        
django-crispy-forms    1.11.2       
django-filter          2.4.0        
django-redis           4.12.1       
djangorestframework    3.12.4       
docopt                 0.6.2        
docutils               0.15.2       
entrypoints            0.3          
et-xmlfile             1.0.1        
fail2ban               0.10.2       
filelock               3.0.12       
future                 0.18.2       
git-review             1.28.0       
gitdb                  4.0.7        
gitdb2                 4.0.2        
GitPython              3.1.15       
hiredis                2.0.0        
html2text              2020.1.16    
httplib2               0.11.3       
idna                   2.6          
importlib-metadata     4.0.1        
isc                    2.0          
isodate                0.6.0        
jdcal                  1.4.1        
jellyfish              0.8.2        
jmespath               0.9.4        
jsonschema             3.2.0        
keyring                17.1.1       
keyrings.alt           3.1.1        
kombu                  5.0.2        
lxml                   4.6.3        
Mako                   1.0.7        
Markdown               3.0.1        
MarkupSafe             1.1.0        
mercurial              5.3          
methodtools            0.4.2        
misaka                 2.1.1        
oauthlib               3.1.0        
openpyxl               3.0.7        
packaging              20.9         
phply                  1.2.5        
Pillow                 8.2.0        
pip                    18.1         
pip-review             1.1.0        
pip-upgrader           1.4.15       
ply                    3.11         
prompt-toolkit         3.0.18       
psycopg2               2.8.4        
psycopg2-binary        2.8.4        
pyahocorasick          1.4.2        
pycairo                1.20.0       
pycparser              2.20         
pycrypto               2.6.1        
pycurl                 7.43.0.2     
Pygments               2.3.1        
PyGObject              3.40.1       
pyinotify              0.9.6        
PyJWT                  2.0.0        
pyparsing              2.4.7        
pyrsistent             0.17.3       
PySimpleSOAP           1.16.2       
python-apt             1.8.4.3      
python-dateutil        2.8.1        
python-debian          0.1.35       
python-debianbts       2.8.2        
python-redis-lock      3.7.0    <<<<    
python3-openid         3.1.0        
pytz                   2021.1       
pyxdg                  0.25         
PyYAML                 3.13         
rcssmin                1.0.6        
redis                  3.5.3        
reportbug              7.5.3-deb10u1
requests               2.25.1       
requests-oauthlib      1.3.0        
requests-toolbelt      0.9.1        
rjsmin                 1.1.0        
ruamel.yaml            0.16.10      
ruamel.yaml.clib       0.2.0        
s3transfer             0.3.3        
SecretStorage          2.3.1        
sentry-sdk             1.0.0        
setuptools             56.0.0       
siphashc               2.1          
six                    1.15.0       
smmap                  4.0.0        
social-auth-app-django 4.0.0        
social-auth-core       4.1.0        
sqlparse               0.4.1        
systemd-python         234          
terminaltables         3.1.0        
tesserocr              2.5.0        
translate-toolkit      3.3.4        
translation-finder     2.9          
typing-extensions      3.7.4.3      
ua-parser              0.10.0       
ufw                    0.36         
urllib3                1.24.1       
user-agents            2.2.0        
uWSGI                  2.0.18       
vine                   5.0.0        
virtualenv             15.1.0       
wcwidth                0.2.5        
webencodings           0.5.1        
weblate-language-data  2021.4       
weblate-schemas        0.6          
wheel                  0.32.3       
Whoosh                 2.7.4        
wirerope               0.4.2        
zeep                   3.4.0        
zipp                   3.4.1 
```

**Comment by reloxx13** [comment]
i changed it back to 5s and restarted and it does not fail on the UI/Website anymore.   
cannot test for the migration again.
