### ISSUE TITLE
4.6: TypeError: 'MetricsWrapper' object is not subscriptable

### ISSUE THREAD

**Issue by hostalp** [WeblateOrg/weblate#5927]
**Describe the issue**
After updating from 4.4.2 to 4.6 we started occassionally getting exceptions such as the one shown below. They're accompanied by an e-mail notification for it.
Is this an issuw with the Weblate application itself?

**Exception traceback**
```
uwsgi stderr | [2021-04-26 16:14:01,465: ERROR/467] Internal Server Error: /projects/retail-implementation/
uwsgi stderr | Traceback (most recent call last):
uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/django/template/base.py", line 829, in _resolve_lookup
uwsgi stderr |     current = current[bit]
uwsgi stderr | TypeError: 'MetricsWrapper' object is not subscriptable
uwsgi stderr |
uwsgi stderr | During handling of the above exception, another exception occurred:
uwsgi stderr |
uwsgi stderr | Traceback (most recent call last):
uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
uwsgi stderr |     response = get_response(request)
...
uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 78, in _execute
uwsgi stderr |     self.db.validate_no_broken_transaction()
uwsgi stderr |   File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/base.py", line 448, in validate_no_broken_transaction
uwsgi stderr |     "An error occurred in the current transaction. You can't "
uwsgi stderr | django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.
```
See https://pastebin.com/B2vvJgBU for complete output

**Server configuration and status**
Weblate installation: Docker
docker-compose exec --user weblate weblate weblate list_versions
```
 * Weblate: 4.6
 * Django: 3.2
 * siphashc: 2.1
 * translate-toolkit: 3.3.4
 * lxml: 4.6.3
 * Pillow: 8.2.0
 * bleach: 3.3.0
 * python-dateutil: 2.8.1
 * social-auth-core: 4.1.0
 * social-auth-app-django: 4.0.0
 * django-crispy-forms: 1.11.2
 * oauthlib: 3.1.0
 * django-compressor: 2.4.1
 * djangorestframework: 3.12.4
 * django-filter: 2.4.0
 * django-appconf: 1.0.4
 * user-agents: 2.2.0
 * filelock: 3.0.12
 * setuptools: 40.8.0
 * jellyfish: 0.8.2
 * openpyxl: 3.0.7
 * celery: 5.0.5
 * kombu: 5.0.2
 * translation-finder: 2.9
 * weblate-language-data: 2021.4
 * html2text: 2020.1.16
 * pycairo: 1.16.2
 * pygobject: 3.30.4
 * diff-match-patch: 20200713
 * requests: 2.25.1
 * django-redis: 4.12.1
 * hiredis: 2.0.0
 * sentry_sdk: 1.0.0
 * Cython: 0.29.23
 * misaka: 2.1.1
 * GitPython: 3.1.14
 * borgbackup: 1.1.16
 * pyparsing: 2.4.7
 * pyahocorasick: 1.4.2
 * Python: 3.7.3
 * Git: 2.20.1
 * psycopg2: 2.8.6
 * psycopg2-binary: 2.8.6
 * phply: 1.2.5
 * chardet: 4.0.0
 * ruamel.yaml: 0.17.4
 * tesserocr: 2.5.1
 * akismet: 1.1
 * boto3: 1.17.53
 * zeep: 4.0.0
 * aeidon: 1.9
 * iniparse: 0.5
 * mysqlclient: 2.0.3
 * Mercurial: 5.7.1
 * git-svn: 2.20.1
 * git-review: 2.0.0
 * Redis server: 6.2.2
 * PostgreSQL server: 11.11
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: (removed)
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.18.0-240.22.1.el8_3.x86_64 (x86_64)
```

**Weblate deploy checks**
docker-compose exec --user weblate weblate weblate check --deploy
```
System check identified some issues:

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.6/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.6/admin/backup.html

System check identified 2 issues (1 silenced).
```

**Comment by nijel** [comment]
Does the e-mail notification contain more information? The TypeError is expected to happen (it's way how Django resolves variables in templates), but the TransactionManagementError is not. The root cause of that is however somewhere before and not visible in the log you've shared.

**Comment by hostalp** [comment]
I attached the e-mail notification (with some internal information removed) as PDF. 
[TransactionManagementError at _projects_retail-implementation_.pdf](https://github.com/WeblateOrg/weblate/files/6383770/TransactionManagementError.at._projects_retail-implementation_.pdf)

**Comment by hostalp** [comment]
Unfortunately not, nothing else in logs.

**Comment by nijel** [comment]
Do you know when this error happens? Is it upon creating a new project?

Maybe it is also a similar issue as https://github.com/WeblateOrg/weblate/issues/5926 (because that is the code where we get the crash).

**Comment by hostalp** [comment]
I'm not sure. but it doesn't appear to be related to a new project creation. I don't see any such activity around the same time and the affected request is simple `GET` on `/projects/project-name/`

**Comment by nijel** [comment]
Can you please try adding the following snippet to `/app/data/settings-override.py` (see https://docs.weblate.org/en/latest/admin/install/docker.html#further-configuration-customization):

```python
LOGGING["loggers"]["django.db.backends"] = {
    "handlers": ["console"],
    "level": "DEBUG",
}
```

It will add logging of all SQL queries to the console and that should make it clear what did fail.

**Comment by hostalp** [comment]
Will do, but please keep in mind that ot occurs rather irregularly so it may take some unknown amount of time to occur again.
