### ISSUE TITLE
Internal Server Error with a fresh installation 

### ISSUE THREAD

**Issue by IceeMC** [WeblateOrg/weblate#5943]
**Describe the issue**

When going to `/accounts/profile/` an error occurrs.

**To Reproduce the issue**
1. Login with the admin user
2. Click Settings
3. An Internal Server Error will occur

**Expected behavior**

The account settings to open

**Exception traceback**

```
uwsgi stderr \| [2021-04-29 22:04:36,852: ERROR/404] Internal Server Error: /accounts/profile/
--
Thu, Apr 29 2021 15:04:36 | uwsgi stderr \| Traceback (most recent call last):
Thu, Apr 29 2021 15:04:36 | uwsgi stderr \| File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
Thu, Apr 29 2021 15:04:36 | uwsgi stderr \| response = get_response(request)
Thu, Apr 29 2021 15:04:36 | uwsgi stderr \| File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 181, in _get_response
Thu, Apr 29 2021 15:04:36 | uwsgi stderr \| response = wrapped_callback(request, *callback_args, **callback_kwargs)
Thu, Apr 29 2021 15:04:36 | uwsgi stderr \| File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
Thu, Apr 29 2021 15:04:36 | uwsgi stderr \| response = view_func(request, *args, **kwargs)
Thu, Apr 29 2021 15:04:36 | uwsgi stderr \| File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
Thu, Apr 29 2021 15:04:36 | uwsgi stderr \| return view_func(request, *args, **kwargs)
Thu, Apr 29 2021 15:04:36 | uwsgi stderr \| File "/usr/local/lib/python3.7/dist-packages/weblate/accounts/views.py", line 367, in user_profile
Thu, Apr 29 2021 15:04:36 | uwsgi stderr \| forms = [form.from_request(request) for form in form_classes]
Thu, Apr 29 2021 15:04:36 | uwsgi stderr \| File "/usr/local/lib/python3.7/dist-packages/weblate/accounts/views.py", line 367, in <listcomp>
Thu, Apr 29 2021 15:04:36 | uwsgi stderr \| forms = [form.from_request(request) for form in form_classes]
Thu, Apr 29 2021 15:04:36 | uwsgi stderr \| File "/usr/local/lib/python3.7/dist-packages/weblate/accounts/forms.py", line 139, in from_request
Thu, Apr 29 2021 15:04:36 | uwsgi stderr \| return cls(instance=request.user.profile)
Thu, Apr 29 2021 15:04:36 | uwsgi stderr \| File "/usr/local/lib/python3.7/dist-packages/weblate/accounts/forms.py", line 205, in __init__
Thu, Apr 29 2021 15:04:36 | uwsgi stderr \| self.fields["public_email"].choices = [(x, x) for x in sorted(emails)]
Thu, Apr 29 2021 15:04:36 | uwsgi stderr \| TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

**Server configuration and status**

Weblate installation: 4.6

**Weblate deploy checks**
```
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Cannot send e-mail (please run connect() first), please check EMAIL_* settings.
        HINT: https://docs.weblate.org/en/weblate-4.6/admin/install.html#out-mail

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.6/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.6/admin/backup.html
```

**Additional context**

This is a fresh Kubernetes-based install of weblate.

**Comment by nijel** [comment]
There seems to be NULL stored as user email somewhere... How do you authenticate users? Did you import users?

**Comment by IceeMC** [comment]
Oh, it appears there is no admin user email set.
