### ISSUE TITLE
Okta/SAML: key error for `attr_user_permanent_id`

### ISSUE THREAD

**Issue by M0Rf30** [WeblateOrg/weblate#6013]
If I try to trigger the SAML login this stacktrace pops out (with DEBUG enabled)
```
Environment:


Request Method: POST
Request URL: https://mydomain.com/accounts/complete/saml/

Django Version: 3.2.3
Python Version: 3.7.3
Installed Applications:
['customize',
 'weblate.addons',
 'weblate.auth',
 'weblate.checks',
 'weblate.formats',
 'weblate.glossary',
 'weblate.machinery',
 'weblate.trans',
 'weblate.lang',
 'weblate_language_data',
 'weblate.memory',
 'weblate.screenshots',
 'weblate.fonts',
 'weblate.accounts',
 'weblate.configuration',
 'weblate.utils',
 'weblate.vcs',
 'weblate.wladmin',
 'weblate.metrics',
 'weblate',
 'weblate.gitexport',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin.apps.SimpleAdminConfig',
 'django.contrib.admindocs',
 'django.contrib.sitemaps',
 'django.contrib.humanize',
 'social_django',
 'crispy_forms',
 'compressor',
 'rest_framework',
 'rest_framework.authtoken',
 'django_filters']
Installed Middleware:
['weblate.middleware.RedirectMiddleware',
 'weblate.middleware.ProxyMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'weblate.accounts.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'weblate.accounts.middleware.RequireLoginMiddleware',
 'weblate.api.middleware.ThrottlingMiddleware',
 'weblate.middleware.SecurityMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/weblate/accounts/views.py", line 1233, in social_complete
    return complete(request, backend)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/social_django/utils.py", line 49, in wrapper
    return func(request, backend, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/social_django/views.py", line 33, in complete
    *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/social_core/actions.py", line 45, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/social_core/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/social_core/backends/saml.py", line 333, in auth_complete
    return self.strategy.authenticate(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/social_django/strategy.py", line 107, in authenticate
    return authenticate(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/views/decorators/debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/contrib/auth/__init__.py", line 76, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/usr/local/lib/python3.7/dist-packages/social_core/backends/base.py", line 80, in authenticate
    return self.pipeline(pipeline, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/social_core/backends/base.py", line 83, in pipeline
    out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/social_core/backends/base.py", line 113, in run_pipeline
    result = func(*args, **out) or {}
  File "/usr/local/lib/python3.7/dist-packages/social_core/pipeline/social_auth.py", line 9, in social_uid
    return {'uid': backend.get_user_id(details, response)}
  File "/usr/local/lib/python3.7/dist-packages/social_core/backends/saml.py", line 305, in get_user_id
    uid = idp.get_user_permanent_id(response['attributes'])
  File "/usr/local/lib/python3.7/dist-packages/social_core/backends/saml.py", line 45, in get_user_permanent_id
    uid = attributes[self.conf.get('attr_user_permanent_id', OID_USERID)]

Exception Type: KeyError at /accounts/complete/saml/
Exception Value: 'urn:oid:0.9.2342.19200300.100.1.1'
```
This is solved using an Attribute Statement of this type on Okta
Attr | Name Format | Value(IdP side) |
----- | ------------------ | -------------------- |
urn:oid:0.9.2342.19200300.100.1.1 | URI Type |user.email |

Below I report an image from Okta configuration page:
![image](https://user-images.githubusercontent.com/491117/118287753-0da64900-b4d4-11eb-9211-baaa8dbf44b2.png)

My doubt is: should this attrbute be included in Weblate statements as `uid` attribute field or how to simplify this?

**Comment by nijel** [comment]
These attributes are configurable, but most IDPs export these standard attributes. But it should be documented.

**Comment by M0Rf30** [comment]
Thank you so much. This is very appreciated and enlights my thoughts. Will test ASAP.
