### ISSUE TITLE
Test installation instructions (Ubuntu/Debian) don't work

### ISSUE THREAD

**Issue by gunchleoc** [WeblateOrg/weblate#6296]
**Describe the issue**

Trying to set up a test installation following the instructions on https://docs.weblate.org/en/latest/admin/install/venv-debian.html and failing. The step that fails is `weblate migrate`, and the error messages change slightly on each run. Examples (full stack below):

```
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
django.db.utils.OperationalError: FATAL:  password authentication failed for user "weblate"
```

**I already tried**

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.

**To Reproduce the issue**

1. Set up a Linux Mint Mate 20.02 VM
2. Follow the instructions
3. 1 slight change for updated Python version: `cp ~/weblate-env/lib/python3.8/site-packages/weblate/settings_example.py ~/weblate-env/lib/python3.8/site-packages/weblate/settings.py`
4. `weblate migrate` step fails

**Exception traceback**

```
(weblate-env) somebody@somebody-VirtualBox:~$ weblate migrate
[2021-07-15 18:33:02,484: WARNING/2176] Handled exception: OperationalError: FATAL:  password authentication failed for user "weblate"
FATAL:  password authentication failed for user "weblate"

Traceback (most recent call last):
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "weblate"
FATAL:  password authentication failed for user "weblate"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/somebody/weblate-env/bin/weblate", line 8, in <module>
    sys.exit(main())
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/weblate/runner.py", line 34, in main
    utility.execute()
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/core/checks/model_checks.py", line 34, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/db/models/base.py", line 1290, in check
    *cls._check_indexes(databases),
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/db/models/base.py", line 1682, in _check_indexes
    connection.features.supports_covering_indexes or
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/db/backends/postgresql/features.py", line 93, in is_postgresql_11
    return self.connection.pg_version >= 110000
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 329, in pg_version
    with self.temporary_connection():
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/db/backends/base/base.py", line 603, in temporary_connection
    with self.cursor() as cursor:
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "weblate"
FATAL:  password authentication failed for user "weblate"

(weblate-env) somebody@somebody-VirtualBox:~$ weblate migrate
[2021-07-15 18:33:06,985: WARNING/2199] Handled exception: ImproperlyConfigured: The SECRET_KEY setting must not be empty.
Traceback (most recent call last):
  File "/home/somebody/weblate-env/bin/weblate", line 8, in <module>
    sys.exit(main())
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/weblate/runner.py", line 34, in main
    utility.execute()
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/urls/resolvers.py", line 412, in check
    for pattern in self.url_patterns:
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/weblate/urls.py", line 29, in <module>
    import weblate.accounts.urls
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/weblate/accounts/urls.py", line 23, in <module>
    import weblate.accounts.views
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/weblate/accounts/views.py", line 31, in <module>
    from django.contrib.auth.views import LoginView, LogoutView
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/contrib/auth/views.py", line 10, in <module>
    from django.contrib.auth.forms import (
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/contrib/auth/forms.py", line 11, in <module>
    from django.contrib.auth.tokens import default_token_generator
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/contrib/auth/tokens.py", line 117, in <module>
    default_token_generator = PasswordResetTokenGenerator()
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/contrib/auth/tokens.py", line 18, in __init__
    self.secret = self.secret or settings.SECRET_KEY
  File "/home/somebody/weblate-env/lib/python3.8/site-packages/django/conf/__init__.py", line 90, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.

```

**Server configuration and status**

I got exceptions about `SECRET_KEY` and about an empty database password, so I added those to the default settings. I also tried with `ADMINS` empty or with the default admin

```
import os
import platform
from logging.handlers import SysLogHandler

# Title of site to use
SITE_TITLE = "Weblate"

# Site domain
SITE_DOMAIN = ""

# Whether site uses https
ENABLE_HTTPS = False

#
# Django settings for Weblate project.
#

SECRET_KEY = "foobar"

DEBUG = True

ADMINS = (
    ("Your Name", "your_email@example.com"),
)

MANAGERS = ADMINS

DATABASES = {
    "default": {
        # Use "postgresql" or "mysql".
        "ENGINE": "django.db.backends.postgresql",
        # Database name.
        "NAME": "weblate",
        # Database user.
        "USER": "weblate",
        # Name of role to alter to set parameters in PostgreSQL,
        # use in case role name is different than user used for authentication.
        # "ALTER_ROLE": "weblate",
        # Database password.
        "PASSWORD": "foobar",
        # Set to empty string for localhost.
        "HOST": "127.0.0.1",
        # Set to empty string for default.
        "PORT": "",
        # Customizations for databases.
        "OPTIONS": {
            # In case of using an older MySQL server,
            # which has MyISAM as a default storage
            # "init_command": "SET storage_engine=INNODB",
            # Uncomment for MySQL older than 5.7:
            # "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
            # Set emoji capable charset for MySQL:
            # "charset": "utf8mb4",
            # Change connection timeout in case you get MySQL gone away error:
            # "connect_timeout": 28800,
        },
    }
}

...

<unchanged below>
```

**Comment by nijel** [comment]
I've clarified the docs in cad7a640f69d81f8d7a436894d9dceabc8af2c56.

**Comment by gunchleoc** [comment]
Thank you for your help! I got it running now :)
