### ISSUE TITLE
KeyError on disabled check

### ISSUE THREAD

**Issue by nijel** [WeblateOrg/weblate#6576]
Hi,

After upgrading to version 4.8 I noticed that occasionally  see

KeyError at /translate/test/ja/ 'ellipsis'

```
Traceback (most recent call last):
  File "/home/weblate/weblate-env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/weblate/weblate-env/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/weblate/weblate-env/lib/python3.7/site-packages/sentry_sdk/integrations/django/views.py", line 67, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/weblate/weblate-env/lib/python3.7/site-packages/weblate/trans/views/edit.py", line 589, in translate
    response = handle_translate(request, unit, this_unit_url, next_unit_url)
  File "/home/weblate/weblate-env/lib/python3.7/site-packages/weblate/utils/ratelimit.py", line 118, in rate_wrap
    return function(request, *args, **kwargs)
  File "/home/weblate/weblate-env/lib/python3.7/site-packages/weblate/trans/views/edit.py", line 403, in handle_translate
    go_next = perform_translation(unit, form, request)
  File "/home/weblate/weblate-env/lib/python3.7/site-packages/weblate/trans/views/edit.py", line 318, in perform_translation
    user, form.cleaned_data["target"], form.cleaned_data["state"]
  File "/usr/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/weblate/weblate-env/lib/python3.7/site-packages/weblate/trans/models/unit.py", line 1263, in translate
    user, change_action=change_action, propagate=propagate, author=author
  File "/home/weblate/weblate-env/lib/python3.7/site-packages/weblate/trans/models/unit.py", line 941, in save_backend
    propagate_checks=was_propagated or changed,
  File "/home/weblate/weblate-env/lib/python3.7/site-packages/weblate/trans/models/unit.py", line 393, in save
    self.run_checks(propagate_checks)
  File "/home/weblate/weblate-env/lib/python3.7/site-packages/weblate/trans/models/unit.py", line 1173, in run_checks
    self.source_unit.run_checks()
  File "/home/weblate/weblate-env/lib/python3.7/site-packages/weblate/trans/models/unit.py", line 1156, in run_checks
    name for name in old_checks if CHECKS[name].propagates
  File "/home/weblate/weblate-env/lib/python3.7/site-packages/weblate/trans/models/unit.py", line 1156, in <listcomp>
    name for name in old_checks if CHECKS[name].propagates
  File "/home/weblate/weblate-env/lib/python3.7/site-packages/weblate/utils/classloader.py", line 80, in __getitem__
    return self.data.__getitem__(key)

Exception Type: KeyError at /translate/test/ja/
Exception Value: 'ellipsis'
Request information:
USER: ******
```

_Originally posted by @ghubz in https://github.com/WeblateOrg/weblate/discussions/6544_

**Comment by matzeeable** [comment]
Hey @nijel !

I have added this to my `docker-compose.yml`:

```yml
WEBLATE_RMEOVE_CHECK: weblate.checks.same.SameCheck
```

And after I try to [`updatechecks`](https://docs.weblate.org/en/latest/admin/management.html#updatechecks) all components I get the following error:

![image](https://user-images.githubusercontent.com/1008534/134642204-ec732c8c-af1c-4893-b95d-91b6fe502445.png)

Does your fix cover this, too? 😊

**Comment by nijel** [comment]
Yes, it should
