### ISSUE TITLE
Two tests () fail because of different command line API of the recent git

### ISSUE THREAD

**Issue by mcepl** [WeblateOrg/weblate#6915]
### Describe the issue

While packaging update of weblate 4.9.1 for openSUSE (git 2.34, git-review 1.28) I got this errors in the test suite:

```
[ 7594s] ======================================================================
[ 7594s] ERROR: test_push_branch (weblate.vcs.tests.test_vcs.VCSGerritTest)
[ 7594s] ----------------------------------------------------------------------
[ 7594s] Traceback (most recent call last):
[ 7594s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.9.1/weblate/vcs/tests/test_vcs.py", line 212, in test_push_branch
[ 7594s]     self.test_push("push-branch")
[ 7594s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.9.1/weblate/vcs/tests/test_vcs.py", line 204, in test_push
[ 7594s]     self.repo.push(branch)
[ 7594s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.9.1/weblate/vcs/git.py", line 514, in push
[ 7594s]     self.execute(["review", "--yes", self.branch])
[ 7594s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.9.1/weblate/vcs/base.py", line 232, in execute
[ 7594s]     self.last_output = self._popen(
[ 7594s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.9.1/weblate/vcs/base.py", line 211, in _popen
[ 7594s]     raise RepositoryException(
[ 7594s] weblate.vcs.base.RepositoryException: Errors running git rebase -p -i remotes/origin/main
[ 7594s] fatal: --preserve-merges was replaced by --rebase-merges
[ 7594s] It is likely that your change has a merge conflict. You may resolve it
[ 7594s] in the working tree now as described above and then run 'git review'
[ 7594s] again, or if you do not want to resolve it yet (note that the change
[ 7594s] can not merge until the conflict is resolved) you may run 'git rebase
[ 7594s] --abort' then 'git review -R' to upload the change without rebasing.
[ 7594s]  (1)
[ 7594s] 
[ 7594s] ======================================================================
[ 7594s] ERROR: test_push_commit (weblate.vcs.tests.test_vcs.VCSGerritTest)
[ 7594s] ----------------------------------------------------------------------
[ 7594s] Traceback (most recent call last):
[ 7594s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.9.1/weblate/vcs/tests/test_vcs.py", line 208, in test_push_commit
[ 7594s]     self.test_push()
[ 7594s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.9.1/weblate/vcs/tests/test_vcs.py", line 204, in test_push
[ 7594s]     self.repo.push(branch)
[ 7594s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.9.1/weblate/vcs/git.py", line 514, in push
[ 7594s]     self.execute(["review", "--yes", self.branch])
[ 7594s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.9.1/weblate/vcs/base.py", line 232, in execute
[ 7594s]     self.last_output = self._popen(
[ 7594s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.9.1/weblate/vcs/base.py", line 211, in _popen
[ 7594s]     raise RepositoryException(
[ 7594s] weblate.vcs.base.RepositoryException: Errors running git rebase -p -i remotes/origin/main
[ 7594s] fatal: --preserve-merges was replaced by --rebase-merges
[ 7594s] It is likely that your change has a merge conflict. You may resolve it
[ 7594s] in the working tree now as described above and then run 'git review'
[ 7594s] again, or if you do not want to resolve it yet (note that the change
[ 7594s] can not merge until the conflict is resolved) you may run 'git rebase
[ 7594s] --abort' then 'git review -R' to upload the change without rebasing.
[ 7594s]  (1)
[ 7594s] 
[ 7594s] ----------------------------------------------------------------------
[ 7594s] Ran 4306 tests in 7473.665s
[ 7594s] 
[ 7594s] FAILED (errors=2, skipped=92)
```

[Complete build log](https://github.com/WeblateOrg/weblate/files/7670924/_log.txt) with all details of packages used and steps taken to achieve this.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Run the test suite

### Expected behavior

Test suite passes

### Exception traceback

```pytb
See above
```

### How do you run Weblate?

Other

**Comment by mcepl** [comment]
Actually, there should be probably `git-review >= 2.2.0` in `requirements-optional.txt`.

**Comment by nijel** [comment]
Indeed `git-review >= 2.2.0` seems needed with Git 2.34.0 or newer. I'm not sure it's a good idea to enforce this as most users will be on older Git....
