### ISSUE TITLE
Error in database migration after upgrade from 4.9 to 4.10

### ISSUE THREAD

**Issue by rwrx** [WeblateOrg/weblate#6978]
### Describe the issue

I have deployed Weblate with docker-compose. I have upgraded from 4.9 to 4.10 and I am getting this error:

```
weblate_1   | Postgres is up
database_1  | ERROR:  column c.relispartition does not exist at character 54
database_1  | STATEMENT:  
database_1  |               SELECT c.relname,
database_1  |               CASE WHEN c.relispartition THEN 'p' WHEN c.relkind IN ('m', 'v') THEN 'v' ELSE 't' END
database_1  |               FROM pg_catalog.pg_class c
database_1  |               LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
database_1  |               WHERE c.relkind IN ('f', 'm', 'p', 'r', 'v')
database_1  |                   AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
database_1  |                   AND pg_catalog.pg_table_is_visible(c.oid)
database_1  |          
weblate_1   | [2021-12-20 18:26:06,211: WARNING/26] Handled exception: ProgrammingError: column c.relispartition does not exist
weblate_1   | LINE 3:             CASE WHEN c.relispartition THEN 'p' WHEN c.relki...
weblate_1   |                               ^
weblate_1   |
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 83, in _execute
weblate_1   |     return self.cursor.execute(sql)
weblate_1   | psycopg2.errors.UndefinedColumn: column c.relispartition does not exist
weblate_1   | LINE 3:             CASE WHEN c.relispartition THEN 'p' WHEN c.relki...
weblate_1   |                               ^
weblate_1   |
weblate_1   |
weblate_1   | The above exception was the direct cause of the following exception:
weblate_1   |
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/bin/weblate", line 8, in <module>
weblate_1   |     sys.exit(main())
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/weblate/runner.py", line 34, in main
weblate_1   |     utility.execute()
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 419, in execute
weblate_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 373, in run_from_argv
weblate_1   |     self.execute(*args, **cmd_options)
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 417, in execute
weblate_1   |     output = self.handle(*args, **options)
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/core/management/commands/showmigrations.py", line 54, in handle
weblate_1   |     return self.show_plan(connection, options['app_label'])
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/core/management/commands/showmigrations.py", line 121, in show_plan
weblate_1   |     loader = MigrationLoader(connection)
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/migrations/loader.py", line 53, in __init__
weblate_1   |     self.build_graph()
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/migrations/loader.py", line 223, in build_graph
weblate_1   |     self.applied_migrations = recorder.applied_migrations()
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
weblate_1   |     if self.has_table():
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/migrations/recorder.py", line 56, in has_table
weblate_1   |     tables = self.connection.introspection.table_names(cursor)
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/base/introspection.py", line 52, in table_names
weblate_1   |     return get_names(cursor)
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/base/introspection.py", line 47, in get_names
weblate_1   |     return sorted(ti.name for ti in self.get_table_list(cursor)
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/postgresql/introspection.py", line 49, in get_table_list
weblate_1   |     cursor.execute("""
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 67, in execute
weblate_1   |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
weblate_1   |     return executor(sql, params, many, context)
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 85, in _execute
weblate_1   |     return self.cursor.execute(sql, params)
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/utils.py", line 90, in __exit__
weblate_1   |     raise dj_exc_value.with_traceback(traceback) from exc_value
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 83, in _execute
weblate_1   |     return self.cursor.execute(sql)
weblate_1   | django.db.utils.ProgrammingError: column c.relispartition does not exist
weblate_1   | LINE 3:             CASE WHEN c.relispartition THEN 'p' WHEN c.relki...
weblate_1   |                               ^
weblate_1   |
weblate_1   |
weblate_1   | Database migration has failed. Please check the error message above.
weblate_1   | In case you are upgrading from an 3.x version, please upgrade to 4.1.1-3 first.
weblate-docker_weblate_1 exited with code 1
```

This is my docker-compose.yml:

```
version: '3'
services:
  weblate:
    image: weblate/weblate
    links:
      - database
      - cache
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
  database:
    image: postgres:9.6-alpine
    env_file:
      - ./environment
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  cache:  
    image: redis:4-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
volumes:  
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### How do you run Weblate?

Docker container

**Comment by nijel** [comment]
Most likely you need to upgrade the PostgreSQL server, see https://docs.weblate.org/en/latest/admin/upgrade.html#upgrade-4-10
