### ISSUE TITLE
ERROR 500 When Updating from Weblate.

### ISSUE THREAD

**Issue by a-zAz-Z0-9** [WeblateOrg/weblate#7414]
### Describe the issue

See error (screenshot )

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to menu >> PROJECT >> choose a project >> MANAGE 
2. 
3. Click on REPOSITORY MAINTENANCE
4. See error (screenshot )

### Expected behavior

to not crash

### Screenshots

![weblate_crash](https://user-images.githubusercontent.com/102165928/159683645-f0018aac-60af-46ad-8e65-3963a5d0f5a8.PNG)

### Exception traceback

```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/weblate/trans/views/js.py", line 181, in git_status_project
    return git_status_shared(request, obj, obj.all_repo_components)
  File "/usr/local/lib/python3.10/site-packages/weblate/trans/views/js.py", line 163, in git_status_shared
    return render(
  File "/usr/local/lib/python3.10/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.10/site-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 542, in render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/loader_tags.py", line 208, in render
    return template.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 540, in render
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/usr/local/lib/python3.10/site-packages/django/template/defaulttags.py", line 540, in <dictcomp>
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 712, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 842, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.10/site-packages/django/template/base.py", line 909, in _resolve_lookup
    current = current()
  File "/usr/local/lib/python3.10/site-packages/weblate/trans/models/component.py", line 161, in on_link_wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/weblate/trans/models/component.py", line 1103, in get_last_remote_commit
    return self.repository.get_revision_info(self.remote_revision)
  File "/usr/local/lib/python3.10/site-packages/weblate/vcs/base.py", line 352, in get_revision_info
    result = self._get_revision_info(revision)
  File "/usr/local/lib/python3.10/site-packages/weblate/vcs/git.py", line 299, in _get_revision_info
    result["summary"] = message[0]

Exception Type: IndexError at /js/git/proj/
Exception Value: list index out of range
```

**Comment by a-zAz-Z0-9** [comment]
This issue is in the docker image. I pulled it several times and it is still there.
Could you please update the docker image as well?

**Comment by nijel** [comment]
This issue was fixed for Weblate 4.12 which is not yet released and thus not in the default image. If you want use development version, choose `bleeding` tag, see https://docs.weblate.org/en/latest/admin/install/docker.html#choosing-docker-hub-tag.

**Comment by a-zAz-Z0-9** [comment]
OK I'l give it a try.But ...
can you give me a hint what is best way to upgrade to bleeding?

**Comment by nijel** [comment]
Just change the tag name in the compose file

**Comment by a-zAz-Z0-9** [comment]
for your information, I installed bleeding and the failure is exactly the same.

**Comment by a-zAz-Z0-9** [comment]
thanks. it is working now better
