### ISSUE TITLE
How to solve this: ValueError: invalid literal for int() with base 10: 'default' ?

### ISSUE THREAD

**Issue by anebi** [WeblateOrg/weblate#7737]
### Describe the issue

I am deploying Weblate on our Kubernetes cluster using the helm chart. We have already an external postgresql and redis so I configure the Weblate helm to use those instead of creating new deployments for PG and Redis.

Configuration seems to be fine because I can see that database tables are created and Redis connection seems to be fine too. The values i set for helm:

`
postgresql:
  enabled: false
redis:
  enabled: false
  cluster:
    enabled: false
externalSecretName: weblate-credentials
`

Credentials secret defined following data:

`
            POSTGRES_HOST: "pg-host"
            POSTGRES_PORT: "5432"
            POSTGRES_DATABASE: "transapp_weblate"
            POSTGRES_USER: "transapp_weblate"
            POSTGRES_PASSWORD: "pass1234"
            REDIS_HOST: "redis-master"
            REDIS_DB: "default"
            REDIS_PASSWORD: "pass3456"
            WEBLATE_EMAIL_HOST: ""
            WEBLATE_EMAIL_PORT: "25"
            WEBLATE_EMAIL_HOST_USER: ""
            WEBLATE_EMAIL_HOST_PASSWORD: ""
            WEBLATE_EMAIL_USE_TLS: "1"
            WEBLATE_ENABLE_HTTPS: "1"
            WEBLATE_REQUIRE_LOGIN: "1"
`
Once container starts I get following error that causes constant restart of the container:

`Blank e-mail for admin, using admin@example.com instead!
CommandError: User exists, specify --update to update existing
Refreshing stats...
Removing corrupted schedule file: ValueError("invalid literal for int() with base 10: 'default'")
[2022-06-03 19:28:34,511: WARNING/99] Handled exception: ValueError: invalid literal for int() with base 10: 'default'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/celery/app/base.py", line 1250, in backend
    return self._local.backend
AttributeError: '_thread._local' object has no attribute 'backend'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/weblate/utils/management/commands/cleanup_celery.py", line 45, in handle
    self.setup_schedule()
  File "/usr/local/lib/python3.10/site-packages/weblate/utils/management/commands/cleanup_celery.py", line 40, in setup_schedule
    scheduler = service.get_scheduler()
  File "/usr/local/lib/python3.10/site-packages/celery/beat.py", line 670, in get_scheduler
    return symbol_by_name(self.scheduler_cls, aliases=aliases)(
  File "/usr/local/lib/python3.10/site-packages/celery/beat.py", line 515, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/beat.py", line 271, in __init__
    self.setup_schedule()
  File "/usr/local/lib/python3.10/site-packages/celery/beat.py", line 559, in setup_schedule
    self.install_default_entries(self.schedule)
  File "/usr/local/lib/python3.10/site-packages/celery/beat.py", line 276, in install_default_entries
    not self.app.backend.supports_autoexpire:
  File "/usr/local/lib/python3.10/site-packages/celery/app/base.py", line 1252, in backend
    self._local.backend = new_backend = self._get_backend()
  File "/usr/local/lib/python3.10/site-packages/celery/app/base.py", line 958, in _get_backend
    return backend(app=self, url=url)
  File "/usr/local/lib/python3.10/site-packages/celery/backends/redis.py", line 264, in __init__
    self.connparams = self._params_from_url(url, self.connparams)
  File "/usr/local/lib/python3.10/site-packages/celery/backends/redis.py", line 342, in _params_from_url
    connparams['db'] = int(db)
ValueError: invalid literal for int() with base 10: 'default'`

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Setup kubernetes cluster
2. Use helm to deploy postgresql
3. Use helm to deploy redis
4. Use helm to deploy weblate and configure it to use external postgres and redis using a secret for passing env vars
5. Monitor container work

### Expected behavior

Container starts without errors and stop restarting

### Screenshots

<img width="1684" alt="Screenshot 2022-06-03 at 22 39 20" src="https://user-images.githubusercontent.com/225278/171938296-f8b3bfe3-a71d-4892-b09f-3c3f50762db3.png">

### How do you run Weblate?

Docker container

### Weblate versions

4.12.1-1

**Comment by anebi** [comment]
I did some extra debugging and it looks like the problem was caused by my REDIS_DB var in the secret. I commented it out and the container is running fine now.

**Comment by nijel** [comment]
The error should be more clear in the future with c438791dd640b6ce7639c5f74e79b46b49ced47d
