### ISSUE TITLE
Upgrade 4.1.1 to 4.2

### ISSUE THREAD

**Issue by jkoorts** [WeblateOrg/weblate#7934]
### Describe the issue

1. I read Upgrade from 4.1 to 4.2 (https://docs.weblate.org/en/latest/admin/upgrade.html#version-specific-instructions)
2. That says I must read Generic upgrade instructions (https://docs.weblate.org/en/latest/admin/upgrade.html#generic-upgrade-instructions)
3. Thats says to run pip install -U Weblate

Which does this:
Collecting Weblate
  Using cached Weblate-4.13.1-py3-none-any.whl (27.0 MB)

But I thought I was upgrading to 4.2? What is this 4.13?

In anycase that fails with:

Collecting borgbackup!=1.2.0,<1.3,>=1.1.11
  Using cached borgbackup-1.1.18.tar.gz (3.9 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-ofb05qse/borgbackup_e53536cce204473eb9c83ae22b991ce8/setup.py", line 183, in <module>
          raise Exception('Unable to find OpenSSL >= 1.0 headers. (Looked here: {})'.format(', '.join(possible_openssl_prefixes)))
      Exception: Unable to find OpenSSL >= 1.0 headers. (Looked here: /usr, /usr/local, /usr/local/opt/openssl, /usr/local/ssl, /usr/local/openssl, /usr/local/borg, /opt/local, /opt/pkg, /opt/homebrew/opt/openssl@1.1)
      [end of output]
  

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### Expected behavior

To work

### How do you run Weblate?

Other

### Weblate versions

```
bitnami@ip-172-31-6-243:/opt/bitnami/apps/weblate/weblate$ sudo /usr/bin/python3 manage.py list_versions
Traceback (most recent call last):
  File "manage.py", line 34, in <module>
    from weblate.runner import main
  File "/opt/bitnami/apps/weblate/weblate/weblate/__init__.py", line 22, in <module>
    from weblate.vcs.base import RepositoryException
  File "/opt/bitnami/apps/weblate/weblate/weblate/vcs/base.py", line 38, in <module>
    from weblate.vcs.ssh import SSH_WRAPPER
  File "/opt/bitnami/apps/weblate/weblate/weblate/vcs/ssh.py", line 25, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils.spawn'
```

### Weblate deploy checks

```
bitnami@ip-172-31-6-243:/opt/bitnami/apps/weblate/weblate$ sudo /usr/bin/python3 manage.py check --deploy
Traceback (most recent call last):
  File "manage.py", line 34, in <module>
    from weblate.runner import main
  File "/opt/bitnami/apps/weblate/weblate/weblate/__init__.py", line 22, in <module>
    from weblate.vcs.base import RepositoryException
  File "/opt/bitnami/apps/weblate/weblate/weblate/vcs/base.py", line 38, in <module>
    from weblate.vcs.ssh import SSH_WRAPPER
  File "/opt/bitnami/apps/weblate/weblate/weblate/vcs/ssh.py", line 25, in <module>
    from distutils.spawn import find_executable
ModuleNotFoundError: No module named 'distutils.spawn'
```

### Additional context

pip 22.2 from /opt/bitnami/python/lib/python3.7/site-packages/pip (python 3.7)

**Comment by nijel** [comment]
You need to have OpenSSL 1.0 or newer headers, see system requirements in our [installation guides](https://docs.weblate.org/en/latest/admin/install.html#installing-weblate).
