### ISSUE TITLE
handle_unit_translation_change seems to crash everytime after container upgrade

### ISSUE THREAD

**Issue by arbaes** [WeblateOrg/weblate#8060]
### Describe the issue

I upgraded the Weblate container according to the [documentation](https://docs.weblate.org/en/latest/admin/install/docker.html#upgrading-the-docker-container), but now after restart, my logs are spammed with the same traceback over and over again. ( see below)

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Have a weblate container in version 4.12
2. docker-compose down
3. docker-compose pull
4. docker-compose up -d

### Expected behavior

No task failing

### Exception traceback

```pytb
[2022-08-26 14:11:02,184: ERROR/ForkPoolWorker-1] Failure while executing task
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 204, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 199, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/weblate/memory/tasks.py", line 60, in handle_unit_translation_change
    unit = Unit.objects.select_related(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
    raise self.model.DoesNotExist(
weblate.trans.models.unit.Unit.DoesNotExist: Unit matching query does not exist.
```

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.14
 * Django: 4.1
 * siphashc: 2.1
 * translate-toolkit: 3.7.2
 * lxml: 4.9.1
 * Pillow: 9.2.0
 * bleach: 5.0.1
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.2.0
 * django-compressor: 4.1
 * djangorestframework: 3.13.1
 * django-filter: 22.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.8.0
 * rapidfuzz: 2.6.0
 * openpyxl: 3.0.10
 * celery: 5.2.7
 * kombu: 5.2.4
 * translation-finder: 2.14
 * weblate-language-data: 2022.7
 * html2text: 2020.1.16
 * pycairo: 1.21.0
 * pygobject: 3.42.2
 * diff-match-patch: 20200713
 * requests: 2.28.1
 * django-redis: 5.2.0
 * hiredis: 2.0.0

### Weblate deploy checks

```shell
$ docker-compose exec --user weblate weblate weblate check --deploy
System check identified some issues:

INFOS:
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.14/admin/backup.html

System check identified 1 issue (1 silenced).
```

### Additional context

Basically, my logs are spammed like this

```shell
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,026: ERROR/397] Failure while executing task: DoesNotExist: Unit matching query does not exist.
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,026: ERROR/ForkPoolWorker-1] Failure while executing task: DoesNotExist: Unit matching query does not exist.
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,026: ERROR/397] Failure while executing task: DoesNotExist: {'signal': <Signal: task_failure providing_args={'traceback', 'args', 'kwargs', 'einfo', 'exception', 'task_id'}>, 'sender': <@task: weblate.memory.tasks.handle_unit_translation_change of weblate at 0x7f8663d385b0>, 'task_id': '6184def1-7d14-4f22-a7de-b7aabd61c2a2', 'args': [1294881], 'kwargs': {}, 'traceback': <traceback object at 0x7f86561e24c0>, 'einfo': <ExceptionInfo: DoesNotExist('Unit matching query does not exist.')>}
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,026: ERROR/ForkPoolWorker-1] Failure while executing task: DoesNotExist: {'signal': <Signal: task_failure providing_args={'traceback', 'args', 'kwargs', 'einfo', 'exception', 'task_id'}>, 'sender': <@task: weblate.memory.tasks.handle_unit_translation_change of weblate at 0x7f8663d385b0>, 'task_id': '6184def1-7d14-4f22-a7de-b7aabd61c2a2', 'args': [1294881], 'kwargs': {}, 'traceback': <traceback object at 0x7f86561e24c0>, 'einfo': <ExceptionInfo: DoesNotExist('Unit matching query does not exist.')>}
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,026: ERROR/397] Failure while executing task
weblate_1   | celery-memory stderr | Traceback (most recent call last):
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
weblate_1   | celery-memory stderr |     R = retval = fun(*args, **kwargs)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 204, in _inner
weblate_1   | celery-memory stderr |     reraise(*exc_info)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 54, in reraise
weblate_1   | celery-memory stderr |     raise value
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 199, in _inner
weblate_1   | celery-memory stderr |     return f(*args, **kwargs)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
weblate_1   | celery-memory stderr |     return self.run(*args, **kwargs)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/weblate/memory/tasks.py", line 60, in handle_unit_translation_change
weblate_1   | celery-memory stderr |     unit = Unit.objects.select_related(
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
weblate_1   | celery-memory stderr |     raise self.model.DoesNotExist(
weblate_1   | celery-memory stderr | weblate.trans.models.unit.Unit.DoesNotExist: Unit matching query does not exist.
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,026: ERROR/ForkPoolWorker-1] Failure while executing task
weblate_1   | celery-memory stderr | Traceback (most recent call last):
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
weblate_1   | celery-memory stderr |     R = retval = fun(*args, **kwargs)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 204, in _inner
weblate_1   | celery-memory stderr |     reraise(*exc_info)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 54, in reraise
weblate_1   | celery-memory stderr |     raise value
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 199, in _inner
weblate_1   | celery-memory stderr |     return f(*args, **kwargs)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
weblate_1   | celery-memory stderr |     return self.run(*args, **kwargs)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/weblate/memory/tasks.py", line 60, in handle_unit_translation_change
weblate_1   | celery-memory stderr |     unit = Unit.objects.select_related(
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
weblate_1   | celery-memory stderr |     raise self.model.DoesNotExist(
weblate_1   | celery-memory stderr | weblate.trans.models.unit.Unit.DoesNotExist: Unit matching query does not exist.
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,036: INFO/MainProcess] Task weblate.memory.tasks.handle_unit_translation_change[af60a575-a691-4146-b33f-7c9ac8a78e63] received
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,102: ERROR/397] Failure while executing task: DoesNotExist: Unit matching query does not exist.
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,102: ERROR/ForkPoolWorker-1] Failure while executing task: DoesNotExist: Unit matching query does not exist.
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,104: ERROR/397] Failure while executing task: DoesNotExist: {'signal': <Signal: task_failure providing_args={'traceback', 'args', 'kwargs', 'einfo', 'exception', 'task_id'}>, 'sender': <@task: weblate.memory.tasks.handle_unit_translation_change of weblate at 0x7f8663d385b0>, 'task_id': '54e2c82d-c403-41df-85a0-1ea99fbd1cb5', 'args': [1294882], 'kwargs': {}, 'traceback': <traceback object at 0x7f8656c7e9c0>, 'einfo': <ExceptionInfo: DoesNotExist('Unit matching query does not exist.')>}
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,104: ERROR/ForkPoolWorker-1] Failure while executing task: DoesNotExist: {'signal': <Signal: task_failure providing_args={'traceback', 'args', 'kwargs', 'einfo', 'exception', 'task_id'}>, 'sender': <@task: weblate.memory.tasks.handle_unit_translation_change of weblate at 0x7f8663d385b0>, 'task_id': '54e2c82d-c403-41df-85a0-1ea99fbd1cb5', 'args': [1294882], 'kwargs': {}, 'traceback': <traceback object at 0x7f8656c7e9c0>, 'einfo': <ExceptionInfo: DoesNotExist('Unit matching query does not exist.')>}
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,107: ERROR/397] Failure while executing task
weblate_1   | celery-memory stderr | Traceback (most recent call last):
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
weblate_1   | celery-memory stderr |     R = retval = fun(*args, **kwargs)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 204, in _inner
weblate_1   | celery-memory stderr |     reraise(*exc_info)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 54, in reraise
weblate_1   | celery-memory stderr |     raise value
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 199, in _inner
weblate_1   | celery-memory stderr |     return f(*args, **kwargs)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
weblate_1   | celery-memory stderr |     return self.run(*args, **kwargs)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/weblate/memory/tasks.py", line 60, in handle_unit_translation_change
weblate_1   | celery-memory stderr |     unit = Unit.objects.select_related(
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
weblate_1   | celery-memory stderr |     raise self.model.DoesNotExist(
weblate_1   | celery-memory stderr | weblate.trans.models.unit.Unit.DoesNotExist: Unit matching query does not exist.
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,107: ERROR/ForkPoolWorker-1] Failure while executing task
weblate_1   | celery-memory stderr | Traceback (most recent call last):
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
weblate_1   | celery-memory stderr |     R = retval = fun(*args, **kwargs)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 204, in _inner
weblate_1   | celery-memory stderr |     reraise(*exc_info)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 54, in reraise
weblate_1   | celery-memory stderr |     raise value
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 199, in _inner
weblate_1   | celery-memory stderr |     return f(*args, **kwargs)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
weblate_1   | celery-memory stderr |     return self.run(*args, **kwargs)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/weblate/memory/tasks.py", line 60, in handle_unit_translation_change
weblate_1   | celery-memory stderr |     unit = Unit.objects.select_related(
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
weblate_1   | celery-memory stderr |     raise self.model.DoesNotExist(
weblate_1   | celery-memory stderr | weblate.trans.models.unit.Unit.DoesNotExist: Unit matching query does not exist.
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,117: INFO/MainProcess] Task weblate.memory.tasks.handle_unit_translation_change[527ff5e6-8dc7-4a1e-aeb8-500d8a5d46a9] received
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,181: ERROR/397] Failure while executing task: DoesNotExist: Unit matching query does not exist.
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,181: ERROR/ForkPoolWorker-1] Failure while executing task: DoesNotExist: Unit matching query does not exist.
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,183: ERROR/397] Failure while executing task: DoesNotExist: {'signal': <Signal: task_failure providing_args={'traceback', 'args', 'kwargs', 'einfo', 'exception', 'task_id'}>, 'sender': <@task: weblate.memory.tasks.handle_unit_translation_change of weblate at 0x7f8663d385b0>, 'task_id': '87bd9798-b95c-4ee8-9029-93d6c167b157', 'args': [1294883], 'kwargs': {}, 'traceback': <traceback object at 0x7f8656200540>, 'einfo': <ExceptionInfo: DoesNotExist('Unit matching query does not exist.')>}
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,183: ERROR/ForkPoolWorker-1] Failure while executing task: DoesNotExist: {'signal': <Signal: task_failure providing_args={'traceback', 'args', 'kwargs', 'einfo', 'exception', 'task_id'}>, 'sender': <@task: weblate.memory.tasks.handle_unit_translation_change of weblate at 0x7f8663d385b0>, 'task_id': '87bd9798-b95c-4ee8-9029-93d6c167b157', 'args': [1294883], 'kwargs': {}, 'traceback': <traceback object at 0x7f8656200540>, 'einfo': <ExceptionInfo: DoesNotExist('Unit matching query does not exist.')>}
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,184: ERROR/397] Failure while executing task
weblate_1   | celery-memory stderr | Traceback (most recent call last):
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
weblate_1   | celery-memory stderr |     R = retval = fun(*args, **kwargs)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 204, in _inner
weblate_1   | celery-memory stderr |     reraise(*exc_info)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 54, in reraise
weblate_1   | celery-memory stderr |     raise value
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 199, in _inner
weblate_1   | celery-memory stderr |     return f(*args, **kwargs)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
weblate_1   | celery-memory stderr |     return self.run(*args, **kwargs)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/weblate/memory/tasks.py", line 60, in handle_unit_translation_change
weblate_1   | celery-memory stderr |     unit = Unit.objects.select_related(
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
weblate_1   | celery-memory stderr |     raise self.model.DoesNotExist(
weblate_1   | celery-memory stderr | weblate.trans.models.unit.Unit.DoesNotExist: Unit matching query does not exist.
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,184: ERROR/ForkPoolWorker-1] Failure while executing task
weblate_1   | celery-memory stderr | Traceback (most recent call last):
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
weblate_1   | celery-memory stderr |     R = retval = fun(*args, **kwargs)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 204, in _inner
weblate_1   | celery-memory stderr |     reraise(*exc_info)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/_compat.py", line 54, in reraise
weblate_1   | celery-memory stderr |     raise value
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/sentry_sdk/integrations/celery.py", line 199, in _inner
weblate_1   | celery-memory stderr |     return f(*args, **kwargs)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
weblate_1   | celery-memory stderr |     return self.run(*args, **kwargs)
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/weblate/memory/tasks.py", line 60, in handle_unit_translation_change
weblate_1   | celery-memory stderr |     unit = Unit.objects.select_related(
weblate_1   | celery-memory stderr |   File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 650, in get
weblate_1   | celery-memory stderr |     raise self.model.DoesNotExist(
weblate_1   | celery-memory stderr | weblate.trans.models.unit.Unit.DoesNotExist: Unit matching query does not exist.
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,208: INFO/MainProcess] Task weblate.memory.tasks.handle_unit_translation_change[27d74cd6-4b53-4456-8e77-b2109a11d4ce] received
weblate_1   | celery-memory stderr | [2022-08-26 14:11:02,256: ERROR/397] Failure while executing task: DoesNotExist: Unit matching query does not exist.
                                                                                                                       
```

**Comment by arbaes** [comment]
No sure what happened, but I noticed I had 300K+ items in the memory celery queue, now that they all failed, it seems to have come back to normal. Closing...
