### ISSUE TITLE
Weblate does not start after reboot

### ISSUE THREAD

**Issue by tomkolp** [WeblateOrg/weblate#8540]
### Describe the issue

I restarted the server and unfortunately weblate does not start. I tried to load the oldest backup (12/19/2022), still the same error. Nothing was changed in the configuration. Weblate is run by docker, pull the latest test version doesn't help either.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

2. Scroll down to '...'
3. Click on '...'

### How do you run Weblate?

Docker container

### Additional context

```

Starting weblate-docker_database_1     ... done
Starting weblate-docker_https-portal_1 ... done
Starting weblate-docker_cache_1        ... done
Starting weblate-docker_weblate_1      ... done
Attaching to weblate-docker_database_1, weblate-docker_cache_1, weblate-docker_https-portal_1, weblate-docker_weblate_1
database_1      |
database_1      | PostgreSQL Database directory appears to contain a database; Skipping initialization
database_1      |
cache_1         | 1:C 28 Dec 2022 18:24:25.453 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
cache_1         | 1:C 28 Dec 2022 18:24:25.454 # Redis version=6.2.8, bits=64, commit=00000000, modified=0, pid=1, just started
cache_1         | 1:C 28 Dec 2022 18:24:25.454 # Configuration loaded
cache_1         | 1:M 28 Dec 2022 18:24:25.455 * monotonic clock: POSIX clock_gettime
cache_1         | 1:M 28 Dec 2022 18:24:25.457 * Running mode=standalone, port=6379.
cache_1         | 1:M 28 Dec 2022 18:24:25.457 # Server initialized
database_1      | 2022-12-28 18:24:25.704 UTC [1] LOG:  starting PostgreSQL 13.9 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
database_1      | 2022-12-28 18:24:25.704 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
database_1      | 2022-12-28 18:24:25.704 UTC [1] LOG:  listening on IPv6 address "::", port 5432
database_1      | 2022-12-28 18:24:25.891 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
weblate_1       | Starting...
cache_1         | 1:M 28 Dec 2022 18:24:25.459 * Reading RDB preamble from AOF file...
cache_1         | 1:M 28 Dec 2022 18:24:25.459 * Loading RDB produced by version 6.2.8
cache_1         | 1:M 28 Dec 2022 18:24:25.459 * RDB age 60570 seconds
cache_1         | 1:M 28 Dec 2022 18:24:25.459 * RDB memory usage when created 43.20 Mb
cache_1         | 1:M 28 Dec 2022 18:24:25.459 * RDB has an AOF tail
https-portal_1  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
database_1      | 2022-12-28 18:24:25.981 UTC [22] LOG:  database system was shut down at 2022-12-28 18:22:15 UTC
database_1      | 2022-12-28 18:24:25.995 UTC [1] LOG:  database system is ready to accept connections
cache_1         | 1:M 28 Dec 2022 18:24:25.844 # Done loading RDB, keys loaded: 264050, keys expired: 0.
cache_1         | 1:M 28 Dec 2022 18:24:25.845 * Reading the remaining AOF tail...
cache_1         | 1:M 28 Dec 2022 18:24:26.106 * DB loaded from append only file: 0.648 seconds
cache_1         | 1:M 28 Dec 2022 18:24:26.106 * Ready to accept connections
https-portal_1  | [s6-init] ensuring user provided files have correct perms...exited 0.
https-portal_1  | [fix-attrs.d] applying ownership & permissions fixes...
https-portal_1  | [fix-attrs.d] done.
https-portal_1  | [cont-init.d] executing container initialization scripts...
https-portal_1  | [cont-init.d] 00-welcome: executing...
https-portal_1  |
https-portal_1  | ========================================
https-portal_1  | HTTPS-PORTAL v1.14.0
https-portal_1  | ========================================
https-portal_1  |
https-portal_1  | [cont-init.d] 00-welcome: exited 0.
https-portal_1  | [cont-init.d] 10-persist-env: executing...
https-portal_1  | [cont-init.d] 10-persist-env: exited 0.
https-portal_1  | [cont-init.d] 20-setup: executing...
https-portal_1  | /opt/certs_manager/models/domain.rb:185: warning: regular expression has redundant nested repeat operator '?'
https-portal_1  | DH parameters appear to be ok.
https-portal_1  | -----BEGIN DH PARAMETERS-----
https-portal_1  | hide
https-portal_1  | hide
https-portal_1  | hide
https-portal_1  | hide
https-portal_1  | hide
https-portal_1  | hide
https-portal_1  | -----END DH PARAMETERS-----
https-portal_1  | RSA key ok
https-portal_1  | Signing skipped for weblate.eso-spolszczenie.eu, it expires at 64 days from now.
https-portal_1  | [cont-init.d] 20-setup: exited 0.
https-portal_1  | [cont-init.d] 30-set-docker-gen-status: executing...
https-portal_1  | [cont-init.d] 30-set-docker-gen-status: exited 0.
https-portal_1  | [cont-init.d] done.
https-portal_1  | [services.d] starting services
https-portal_1  | [services.d] done.
cache_1         | 1:M 28 Dec 2022 18:25:26.046 * 10000 changes in 60 seconds. Saving...
cache_1         | 1:M 28 Dec 2022 18:25:26.047 * Background saving started by pid 16
cache_1         | 16:C 28 Dec 2022 18:25:26.603 * DB saved on disk
cache_1         | 16:C 28 Dec 2022 18:25:26.605 * RDB: 6 MB of memory used by copy-on-write
cache_1         | 1:M 28 Dec 2022 18:25:26.650 * Background saving terminated with success
weblate_1       | [2022-12-28 19:26:41,412: WARNING/10] Handled exception: TimeoutError: Timeout connecting to server
weblate_1       | Traceback (most recent call last):
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 31, in _decorator
weblate_1       |     return method(self, *args, **kwargs)
weblate_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 137, in has_key
weblate_1       |     return self.client.has_key(*args, **kwargs)
weblate_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django_redis/client/default.py", line 666, in has_key
weblate_1       |     raise ConnectionInterrupted(connection=client) from e
weblate_1       | django_redis.exceptions.ConnectionInterrupted: Redis TimeoutError: Timeout connecting to server
weblate_1       |
weblate_1       | During handling of the above exception, another exception occurred:
weblate_1       |
weblate_1       | Traceback (most recent call last):
weblate_1       |   File "/usr/local/bin/weblate", line 8, in <module>
weblate_1       |     sys.exit(main())
weblate_1       |              ^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/weblate/runner.py", line 34, in main
weblate_1       |     utility.execute()
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
weblate_1       |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
weblate_1       |     self.execute(*args, **cmd_options)
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
weblate_1       |     output = self.handle(*args, **options)
weblate_1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/shell.py", line 117, in handle
weblate_1       |     exec(options["command"], globals())
weblate_1       |   File "<string>", line 1, in <module>
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 38, in _decorator
weblate_1       |     raise e.__cause__
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django_redis/client/default.py", line 664, in has_key
weblate_1       |     return client.exists(key) == 1
weblate_1       |            ^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/redis/commands/core.py", line 1635, in exists
weblate_1       |     return self.execute_command("EXISTS", *names)
weblate_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/redis.py", line 170, in sentry_patched_execute_command
weblate_1       |     return old_execute_command(self, name, *args, **kwargs)
weblate_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1255, in execute_command
weblate_1       |     conn = self.connection or pool.get_connection(command_name, **options)
weblate_1       |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 1389, in get_connection
weblate_1       |     connection.connect()
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 602, in connect
weblate_1       |     raise TimeoutError("Timeout connecting to server")
weblate_1       | redis.exceptions.TimeoutError: Timeout connecting to server
weblate_1       | Sentry is attempting to send 2 pending error messages
weblate_1       | Waiting up to 2 seconds
weblate_1       | Press Ctrl-C to quit
weblate_1       | redis is unavailable - waiting 30
weblate_1       | [2022-12-28 19:28:58,643: WARNING/64] Handled exception: TimeoutError: Timeout connecting to server
weblate_1       | Traceback (most recent call last):
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 31, in _decorator
weblate_1       |     return method(self, *args, **kwargs)
weblate_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 137, in has_key
weblate_1       |     return self.client.has_key(*args, **kwargs)
weblate_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django_redis/client/default.py", line 666, in has_key
weblate_1       |     raise ConnectionInterrupted(connection=client) from e
weblate_1       | django_redis.exceptions.ConnectionInterrupted: Redis TimeoutError: Timeout connecting to server
weblate_1       |
weblate_1       | During handling of the above exception, another exception occurred:
weblate_1       |
weblate_1       | Traceback (most recent call last):
weblate_1       |   File "/usr/local/bin/weblate", line 8, in <module>
weblate_1       |     sys.exit(main())
weblate_1       |              ^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/weblate/runner.py", line 34, in main
weblate_1       |     utility.execute()
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
weblate_1       |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
weblate_1       |     self.execute(*args, **cmd_options)
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
weblate_1       |     output = self.handle(*args, **options)
weblate_1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/shell.py", line 117, in handle
weblate_1       |     exec(options["command"], globals())
weblate_1       |   File "<string>", line 1, in <module>
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 38, in _decorator
weblate_1       |     raise e.__cause__
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django_redis/client/default.py", line 664, in has_key
weblate_1       |     return client.exists(key) == 1
weblate_1       |            ^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/redis/commands/core.py", line 1635, in exists
weblate_1       |     return self.execute_command("EXISTS", *names)
weblate_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/redis.py", line 170, in sentry_patched_execute_command
weblate_1       |     return old_execute_command(self, name, *args, **kwargs)
weblate_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1255, in execute_command
weblate_1       |     conn = self.connection or pool.get_connection(command_name, **options)
weblate_1       |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 1389, in get_connection
weblate_1       |     connection.connect()
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 602, in connect
weblate_1       |     raise TimeoutError("Timeout connecting to server")
weblate_1       | redis.exceptions.TimeoutError: Timeout connecting to server
weblate_1       | Sentry is attempting to send 2 pending error messages
weblate_1       | Waiting up to 2 seconds
weblate_1       | Press Ctrl-C to quit
weblate_1       | redis is unavailable - waiting 29
weblate_1       | [2022-12-28 19:31:15,844: WARNING/128] Handled exception: TimeoutError: Timeout connecting to server
weblate_1       | Traceback (most recent call last):
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 31, in _decorator
weblate_1       |     return method(self, *args, **kwargs)
weblate_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 137, in has_key
weblate_1       |     return self.client.has_key(*args, **kwargs)
weblate_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django_redis/client/default.py", line 666, in has_key
weblate_1       |     raise ConnectionInterrupted(connection=client) from e
weblate_1       | django_redis.exceptions.ConnectionInterrupted: Redis TimeoutError: Timeout connecting to server
weblate_1       |
weblate_1       | During handling of the above exception, another exception occurred:
weblate_1       |
weblate_1       | Traceback (most recent call last):
weblate_1       |   File "/usr/local/bin/weblate", line 8, in <module>
weblate_1       |     sys.exit(main())
weblate_1       |              ^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/weblate/runner.py", line 34, in main
weblate_1       |     utility.execute()
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
weblate_1       |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 402, in run_from_argv
weblate_1       |     self.execute(*args, **cmd_options)
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 448, in execute
weblate_1       |     output = self.handle(*args, **options)
weblate_1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/shell.py", line 117, in handle
weblate_1       |     exec(options["command"], globals())
weblate_1       |   File "<string>", line 1, in <module>
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django_redis/cache.py", line 38, in _decorator
weblate_1       |     raise e.__cause__
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/django_redis/client/default.py", line 664, in has_key
weblate_1       |     return client.exists(key) == 1
weblate_1       |            ^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/redis/commands/core.py", line 1635, in exists
weblate_1       |     return self.execute_command("EXISTS", *names)
weblate_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/sentry_sdk/integrations/redis.py", line 170, in sentry_patched_execute_command
weblate_1       |     return old_execute_command(self, name, *args, **kwargs)
weblate_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1255, in execute_command
weblate_1       |     conn = self.connection or pool.get_connection(command_name, **options)
weblate_1       |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 1389, in get_connection
weblate_1       |     connection.connect()
weblate_1       |   File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 602, in connect
weblate_1       |     raise TimeoutError("Timeout connecting to server")
weblate_1       | redis.exceptions.TimeoutError: Timeout connecting to server
weblate_1       | Sentry is attempting to send 2 pending error messages
weblate_1       | Waiting up to 2 seconds
weblate_1       | Press Ctrl-C to quit
weblate_1       | redis is unavailable - waiting 28


```

**Comment by tomkolp** [comment]
The problem was with the redis-overcommit-on-host I was using.

**Comment by tomkolp** [comment]
Unfortunately, the problem returns after every server restart. Deleting and re-downloading the containers allows weblate to start until the next server restart.
Same error as here: https://github.com/WeblateOrg/docker/issues/1691

**Comment by tomkolp** [comment]
> Maybe there is some issue with the Docker networking – recreating the containers will recreate the network as well. Does `docker-compose down; docker-compose up` fix it as well?

No new bleeding version for 3 days. I'm afraid to disable the container because downloading the bleeding version allowed me to run weblate like everything else failed.

**Comment by nijel** [comment]
The above command will not download a new image, it will just recreate the container and network. Just try that once you hit the issue with redis.

PS: The `bleeding` will not be updated until 4.15.1 is released due to incompatible deps.

**Comment by tomkolp** [comment]
```
sudo docker-compose -f docker-compose-https.yml -f docker-compose-https.override.yml up
Creating network "weblate-docker_default" with the default driver
Creating weblate-docker_database_1     ... done
Creating weblate-docker_https-portal_1 ...
Creating weblate-docker_https-portal_1 ... error
Creating weblate-docker_weblate_1      ...
WARNING: Host is already in use by another container

ERROR: for weblate-docker_https-portal_1  Cannot start service https-portal: driver failed programming external connectivity on endpoint weblate-docker_https-poCreating weblate-docker_weblate_1      ... done

ERROR: for https-portal  Cannot start service https-portal: driver failed programming external connectivity on endpoint weblate-docker_https-portal_1 (2e74d32f3ab5f6d744e68f652ee6d69f28159b0ecd0c96239f240936d95271ee): Error starting userland proxy: listen tcp4 0.0.0.0:465: bind: address already in use
ERROR: Encountered errors while bringing up the project.

```
```
sudo netstat -nlp | grep 465
tcp        0      0 0.0.0.0:465             0.0.0.0:*               LISTEN      32730/docker-proxy
tcp6       0      0 :::465                  :::*                    LISTEN      32753/docker-proxy
```

**Comment by nijel** [comment]
Is there some other Docker container running? What is output of `docker ps` and `docker ps -a`?

**Comment by tomkolp** [comment]
> Is there some other Docker container running? What is output of `docker ps` and `docker ps -a`?

```
docker ps
CONTAINER ID   IMAGE                           COMMAND                  CREATED          STATUS                   PORTS                                                                                            NAMES
79d4207b5a03   weblate/weblate:bleeding        "/app/bin/start runs…"   4 minutes ago    Up 4 minutes (healthy)   8080/tcp                                                                                         weblate-docker_weblate_1
464d33f830a7   redis:6-alpine                  "docker-entrypoint.s…"   4 minutes ago    Up 4 minutes             6379/tcp                                                                                         weblate-docker_cache_1
40dc4bba2741   postgres:13-alpine              "docker-entrypoint.s…"   4 minutes ago    Up 4 minutes             5432/tcp                                                                                         weblate-docker_database_1
71124c00e325   portainer/portainer-ee:latest   "/portainer"             30 minutes ago   Up 6 minutes             0.0.0.0:8000->8000/tcp, :::8000->8000/tcp, 0.0.0.0:9443->9443/tcp, :::9443->9443/tcp, 9000/tcp   portainer

```
Now it works and now I can't restart the server and throw the error.
I only have the output from the command console history: docker ps
I'm using docker-compose down, only portainer was working then, but weblate still wouldn't start. I also tried without a working portainer, it also does not work. Weblate is not implemented by portainer, I only use it to clean up old images and containers.

**Comment by tomkolp** [comment]
Please let me know how docker-compose.yml, docker-compose-https.yml, docker-compose-https.yml, docker-compose-https.override.yml configuration files should look like. I am using the Lets encrypt certificate.
Maybe my configuration is wrong from the start and updating weblate exposed this bug.

**Comment by nijel** [comment]
I don't think there is something wrong with the configuration, but there might be something wrong in a way you manage the Docker containers. It appears to me that some of them might stay running, or at least their proxies, when you start the containers again.

**Comment by tomkolp** [comment]
I reinstalled ubuntu server and uploaded weblate from backup.  So far everything works fine.
