### ISSUE TITLE
weblate.machinery.base.MachineTranslationError: ReadTimeout

### ISSUE THREAD

**Issue by SVronskiy** [WeblateOrg/weblate#8788]
### Describe the issue

On running Service > Automated translation I get an error:
```
celery-translate stderr | weblate.machinery.base.MachineTranslationError: ReadTimeout: HTTPSConnectionPool(host='translate.argosopentech.com', port=443): Read timed out. (read timeout=5.0)
```

It looks like when running LibreTranslate timeout is exceeded, how can I adjust timeout from 5 secs?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Go to Project
2. Go to Component 
3. Go to language
4. Click Service menu
5. Click Automated translation

### Expected behavior

Weblate uses LibreTranslate to auto translate texts.

### Exception traceback

```pytb
celery-translate stderr | weblate.machinery.base.MachineTranslationError: ReadTimeout: HTTPSConnectionPool(host='translate.argosopentech.com', port=443): Read timed out. (read timeout=5.0)
celery-translate stderr | [2023-02-11 12:37:02,157: ERROR/ForkPoolWorker-1] Failure while executing task
celery-translate stderr | Traceback (most recent call last):
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 449, in _make_request
celery-translate stderr |     six.raise_from(e, None)
celery-translate stderr |   File "<string>", line 3, in raise_from
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 444, in _make_request
celery-translate stderr |     httplib_response = conn.getresponse()
celery-translate stderr |                        ^^^^^^^^^^^^^^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/http/client.py", line 1374, in getresponse
celery-translate stderr |     response.begin()
celery-translate stderr |   File "/usr/local/lib/python3.11/http/client.py", line 318, in begin
celery-translate stderr |     version, status, reason = self._read_status()
celery-translate stderr |                               ^^^^^^^^^^^^^^^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/http/client.py", line 279, in _read_status
celery-translate stderr |     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
celery-translate stderr |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/socket.py", line 706, in readinto
celery-translate stderr |     return self._sock.recv_into(b)
celery-translate stderr |            ^^^^^^^^^^^^^^^^^^^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/ssl.py", line 1278, in recv_into
celery-translate stderr |     return self.read(nbytes, buffer)
celery-translate stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/ssl.py", line 1134, in read
celery-translate stderr |     return self._sslobj.read(len, buffer)
celery-translate stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-translate stderr | TimeoutError: The read operation timed out
celery-translate stderr | 
celery-translate stderr | During handling of the above exception, another exception occurred:
celery-translate stderr | 
celery-translate stderr | Traceback (most recent call last):
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
celery-translate stderr |     resp = conn.urlopen(
celery-translate stderr |            ^^^^^^^^^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
celery-translate stderr |     retries = retries.increment(
celery-translate stderr |               ^^^^^^^^^^^^^^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 550, in increment
celery-translate stderr |     raise six.reraise(type(error), error, _stacktrace)
celery-translate stderr |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/urllib3/packages/six.py", line 770, in reraise
celery-translate stderr |     raise value
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
celery-translate stderr |     httplib_response = self._make_request(
celery-translate stderr |                        ^^^^^^^^^^^^^^^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 451, in _make_request
celery-translate stderr |     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
celery-translate stderr |     raise ReadTimeoutError(
celery-translate stderr | urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='translate.argosopentech.com', port=443): Read timed out. (read timeout=5.0)
celery-translate stderr | 
celery-translate stderr | During handling of the above exception, another exception occurred:
celery-translate stderr | 
celery-translate stderr | Traceback (most recent call last):
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/machinery/base.py", line 393, in _translate
celery-translate stderr |     result = list(
celery-translate stderr |              ^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/machinery/libretranslate.py", line 48, in download_translations
celery-translate stderr |     response = self.request(
celery-translate stderr |                ^^^^^^^^^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/machinery/base.py", line 145, in request
celery-translate stderr |     response = request(method, url, headers=headers, timeout=5.0, **kwargs)
celery-translate stderr |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/utils/requests.py", line 19, in request
celery-translate stderr |     response = requests.request(method, url, headers=headers, **kwargs)
celery-translate stderr |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
celery-translate stderr |     return session.request(method=method, url=url, **kwargs)
celery-translate stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
celery-translate stderr |     resp = self.send(prep, **send_kwargs)
celery-translate stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
celery-translate stderr |     r = adapter.send(request, **kwargs)
celery-translate stderr |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 578, in send
celery-translate stderr |     raise ReadTimeout(e, request=request)
celery-translate stderr | requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='translate.argosopentech.com', port=443): Read timed out. (read timeout=5.0)
celery-translate stderr | 
celery-translate stderr | During handling of the above exception, another exception occurred:
celery-translate stderr | 
celery-translate stderr | Traceback (most recent call last):
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 451, in trace_task
celery-translate stderr |     R = retval = fun(*args, **kwargs)
celery-translate stderr |                  ^^^^^^^^^^^^^^^^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/celery/app/trace.py", line 734, in __protected_call__
celery-translate stderr |     return self.run(*args, **kwargs)
celery-translate stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/celery/app/autoretry.py", line 34, in run
celery-translate stderr |     return task._orig_run(*args, **kwargs)
celery-translate stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/trans/tasks.py", line 395, in auto_translate
celery-translate stderr |     auto.process_mt(engines, threshold)
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/trans/autotranslate.py", line 184, in process_mt
celery-translate stderr |     translations = self.fetch_mt(engines, int(threshold))
celery-translate stderr |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/trans/autotranslate.py", line 169, in fetch_mt
celery-translate stderr |     translation_service.batch_translate(
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/machinery/base.py", line 443, in batch_translate
celery-translate stderr |     self._batch_translate(source, language, units, user=user, threshold=threshold)
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/machinery/base.py", line 450, in _batch_translate
celery-translate stderr |     for item in self._translate(
celery-translate stderr |                 ^^^^^^^^^^^^^^^^
celery-translate stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/machinery/base.py", line 416, in _translate
celery-translate stderr |     raise MachineTranslationError(self.get_error_message(exc))
celery-translate stderr | weblate.machinery.base.MachineTranslationError: ReadTimeout: HTTPSConnectionPool(host='translate.argosopentech.com', port=443): Read timed out. (read timeout=5.0)
nginx stdout | 10.38.0.3 - - [11/Feb/2023:12:37:02 +0000] "GET /api/tasks/b4295c84-1c2b-44e7-9532-06a3be6bfae1/ HTTP/1.1" 200 283 "https://weblate.vronsky.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/109.0"
celery-celery stderr | [2023-02-11 12:37:07,759: INFO/MainProcess] Task weblate.utils.tasks.heartbeat[518a8adc-3bac-4c80-8894-2e18b318ecdf] received
```

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.15.2
 * Django: 4.1.5
 * siphashc: 2.1
 * translate-toolkit: 3.8.3
 * lxml: 4.9.2
 * Pillow: 9.4.0
 * bleach: 5.0.1
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 1.14.0
 * oauthlib: 3.2.2
 * django-compressor: 4.3.1
 * djangorestframework: 3.14.0
 * django-filter: 22.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.9.0
 * rapidfuzz: 2.13.7
 * openpyxl: 3.0.10
 * celery: 5.2.7
 * kombu: 5.2.4
 * translation-finder: 2.15
 * weblate-language-data: 2023.1
 * html2text: 2020.1.16
 * pycairo: 1.23.0
 * pygobject: 3.42.2
 * diff-match-patch: 20200713
 * requests: 2.28.2
 * django-redis: 5.2.0
 * hiredis: 2.1.1
 * sentry_sdk: 1.14.0
 * Cython: 0.29.33
 * misaka: 2.1.1
 * GitPython: 3.1.30
 * borgbackup: 1.2.3
 * pyparsing: 3.0.9
 * pyahocorasick: 2.0.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.0.1
 * Python: 3.11.1
 * Git: 2.30.2
 * psycopg2: 2.9.5
 * psycopg2-binary: 2.9.5
 * phply: 1.2.6
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * boto3: 1.26.59
 * zeep: 4.2.1
 * aeidon: 1.12
 * iniparse: 0.5
 * mysqlclient: 2.1.1
 * Mercurial: 6.3.2
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 7.0.8
 * PostgreSQL server: 15.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: 
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://:weblate@my-weblate-redis-master:6379/1, redis://:weblate@my-weblate-redis-master:6379/1, regular
 * Platform: Linux 5.15.0-58-generic (x86_64)

### Weblate deploy checks

```shell
ystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Cannot send e-mail (EMAIL_USE_TLS/EMAIL_USE_SSL are mutually exclusive, so only set one of those settings to True.), please check EMAIL_* settings.
        HINT: https://docs.weblate.org/en/weblate-4.15.2/admin/install.html#out-mail

WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.15.2/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.15.2/admin/backup.html
```

**Comment by nijel** [comment]
As you've already figured out, the timeout is currently hard-coded at 5 seconds. We might discuss what is an acceptable time for waiting for external service, but definitely not 120 seconds you propose at https://github.com/WeblateOrg/weblate/pull/8796

**Comment by SVronskiy** [comment]
I've tested different timeouts, minimum timeout than it stop failing is 20-30 sec.
