### ISSUE TITLE
VCS kex_exchange_identification

### ISSUE THREAD

**Issue by Angeschossen** [WeblateOrg/weblate#8890]
### Describe the issue

* Since two weeks, I'm getting this issue below. Weblate can't fetch upstream changes from GitHub. It happened out of nowhere without me changing anything on the server it's running on for months. The host has already been rebooted.
* The host is located in a data center. I doubt this is some ISP issue.

````
kex_exchange_identification: read: Connection reset by peer
Connection reset by supersecretgithubserver port 22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 (128)
 ````
 
 Image of the error in weblate: https://imgur.com/RIuuSE3
 
Also, when going to https://yourdomain.com/manage/ssh/ and try to add a host key. In this example github.com. I get an error saying this: `Failed to get host key:`. A host key for github.com already exists from when it worked. Not sure if this is related.

This issue is also present if I create a new project and component. 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

I'm not sure how to reproduce this. I'm just hoping somebody else knows more.

### Expected behavior

Weblate being able to fetch upstream changes.

### Screenshots

https://imgur.com/RIuuSE3

### Exception traceback

```pytb
When creating a new component. I'm not sure if this is related.

weblate-docker-weblate-1   | gunicorn stderr | [2023-03-06 13:23:06,733: ERROR/383] Internal Server Error: /create/component/vcs/
weblate-docker-weblate-1   | gunicorn stderr | Traceback (most recent call last):
weblate-docker-weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
weblate-docker-weblate-1   | gunicorn stderr |     response = get_response(request)
weblate-docker-weblate-1   | gunicorn stderr |                ^^^^^^^^^^^^^^^^^^^^^
weblate-docker-weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
weblate-docker-weblate-1   | gunicorn stderr |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
weblate-docker-weblate-1   | gunicorn stderr |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-docker-weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
weblate-docker-weblate-1   | gunicorn stderr |     return self.dispatch(request, *args, **kwargs)
weblate-docker-weblate-1   | gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-docker-weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
weblate-docker-weblate-1   | gunicorn stderr |     return bound_method(*args, **kwargs)
weblate-docker-weblate-1   | gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-docker-weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
weblate-docker-weblate-1   | gunicorn stderr |     return view_func(request, *args, **kwargs)
weblate-docker-weblate-1   | gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-docker-weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/trans/views/create.py", line 354, in dispatch
weblate-docker-weblate-1   | gunicorn stderr |     return super().dispatch(request, *args, **kwargs)
weblate-docker-weblate-1   | gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-docker-weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 142, in dispatch
weblate-docker-weblate-1   | gunicorn stderr |     return handler(request, *args, **kwargs)
weblate-docker-weblate-1   | gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-docker-weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/views/generic/edit.py", line 184, in post
weblate-docker-weblate-1   | gunicorn stderr |     return super().post(request, *args, **kwargs)
weblate-docker-weblate-1   | gunicorn stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate-docker-weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/views/generic/edit.py", line 152, in post
weblate-docker-weblate-1   | gunicorn stderr |     if form.is_valid():
weblate-docker-weblate-1   | gunicorn stderr |        ^^^^^^^^^^^^^^^
weblate-docker-weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/forms/forms.py", line 205, in is_valid
weblate-docker-weblate-1   | gunicorn stderr |     return self.is_bound and not self.errors
weblate-docker-weblate-1   | gunicorn stderr |                                  ^^^^^^^^^^^
weblate-docker-weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/forms/forms.py", line 200, in errors
weblate-docker-weblate-1   | gunicorn stderr |     self.full_clean()
weblate-docker-weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/forms/forms.py", line 438, in full_clean
weblate-docker-weblate-1   | gunicorn stderr |     self._clean_form()
weblate-docker-weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/django/forms/forms.py", line 459, in _clean_form
weblate-docker-weblate-1   | gunicorn stderr |     cleaned_data = self.clean()
weblate-docker-weblate-1   | gunicorn stderr |                    ^^^^^^^^^^^^
weblate-docker-weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/trans/forms.py", line 1818, in clean
weblate-docker-weblate-1   | gunicorn stderr |     self.clean_instance(self.cleaned_data)
weblate-docker-weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/trans/forms.py", line 1807, in clean_instance
weblate-docker-weblate-1   | gunicorn stderr |     instance.clean_repo()
weblate-docker-weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/trans/models/component.py", line 2634, in clean_repo
weblate-docker-weblate-1   | gunicorn stderr |     self.sync_git_repo(validate=True, skip_push=True)
weblate-docker-weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/trans/models/component.py", line 2387, in sync_git_repo
weblate-docker-weblate-1   | gunicorn stderr |     self.configure_repo(validate)
weblate-docker-weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/trans/models/component.py", line 1441, in configure_repo
weblate-docker-weblate-1   | gunicorn stderr |     with self.repository.lock:
weblate-docker-weblate-1   | gunicorn stderr |   File "/usr/local/lib/python3.11/site-packages/weblate/utils/lock.py", line 68, in __enter__
weblate-docker-weblate-1   | gunicorn stderr |     raise WeblateLockTimeout(
weblate-docker-weblate-1   | gunicorn stderr | weblate.utils.lock.WeblateLockTimeout: Lock could not be acquired in 120s
```

### How do you run Weblate?

Docker container

### Weblate versions

 * Weblate: 4.16.1
 * Django: 4.1.7
 * siphashc: 2.1
 * translate-toolkit: 3.8.4
 * lxml: 4.9.2
 * Pillow: 9.4.0
 * nh3: 0.2.8
 * python-dateutil: 2.8.2
 * social-auth-core: 4.3.0
 * social-auth-app-django: 5.0.0
 * django-crispy-forms: 2.0
 * oauthlib: 3.2.2
 * django-compressor: 4.3.1
 * djangorestframework: 3.14.0
 * django-filter: 22.1
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.9.0
 * rapidfuzz: 2.13.7
 * openpyxl: 3.1.1
 * celery: 5.2.7
 * django-celery-beat: 2.4.0
 * kombu: 5.2.4
 * translation-finder: 2.15
 * weblate-language-data: 2023.3
 * html2text: 2020.1.16
 * pycairo: 1.23.0
 * pygobject: 3.42.2
 * diff-match-patch: 20200713
 * requests: 2.28.2
 * django-redis: 5.2.0
 * hiredis: 2.2.2
 * sentry_sdk: 1.16.0
 * Cython: 0.29.33
 * misaka: 2.1.1
 * GitPython: 3.1.31
 * borgbackup: 1.2.3
 * pyparsing: 3.0.9
 * pyahocorasick: 2.0.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.0.1
 * Python: 3.11.2
 * Git: 2.30.2
 * psycopg2: 2.9.5
 * psycopg2-binary: 2.9.5
 * phply: 1.2.6
 * ruamel.yaml: 0.17.21
 * tesserocr: 2.5.2
 * boto3: 1.26.81
 * zeep: 4.2.1
 * aeidon: 1.12
 * iniparse: 0.5
 * mysqlclient: 2.1.1
 * Mercurial: 6.3.2
 * git-svn: 2.30.2
 * git-review: 2.3.1
 * Redis server: 6.2.11
 * PostgreSQL server: 14.7
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: in-v3.mailjet.com
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 5.10.0-12-amd64 (x86_64)

### Weblate deploy checks

```shell
System check identified some issues:

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.16.1/admin/install.html#collecting-errors

System check identified 1 issue (1 silenced).
```

**Comment by nijel** [comment]
Most likely firewall or networking issue, see https://stackoverflow.com/a/69398009/225718

**Comment by Angeschossen** [comment]
I thought the same and temporarily disabled the firewall with no positive results. I couldn't find any similar issues in the issue section of the weblate repo. So I thought I would open a new one. As you said, the issue is more likely to arise from outside of weblate. But I didn't know for sure. I'll post an update here if I find any solution.

**Comment by Angeschossen** [comment]
Is it possible to let weblate use port 443 instead of 22 for ssh to github? Adding this section to the config file of ssh on my debian host solves the issue for system users, but for weblate the issue still exists:
````
Host github.com
    Hostname ssh.github.com
    Port 443
````

**Comment by Angeschossen** [comment]
Thank you very much! That worked like a charm. I still don't know why this is happening. But the issue is resolved. :)
