### ISSUE TITLE
test_ocr tests fails

### ISSUE THREAD

**Issue by mcepl** [WeblateOrg/weblate#8931]
### Describe the issue

When packaging weblate 4.14.2 for openSUSE test `test_ocr` fails almost always (more in the build server than on my workstation, but it is in both close to 100%):

```
[ 9019s] ======================================================================
[ 9019s] FAIL: test_ocr (weblate.screenshots.tests.ViewTest)
[ 9019s] ----------------------------------------------------------------------
[ 9019s] Traceback (most recent call last):
[ 9019s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.14.2/weblate/screenshots/tests.py", line 170, in test_ocr
[ 9019s]     self.assertIn('<a class="add-string', data["results"])
[ 9019s] AssertionError: '<a class="add-string' not found in '\n\n\n\n\n\n\n\n\n\n\n\n<table class="table table-condensed">\n  <thead>\n    <tr>\n      <th class="unit-state-cell"></th>\n      \n      \n      \n      \n      \n        \n          <th>\n        \n          English\n        \n        </th>\n      \n      \n        <th>Location</th>\n      \n      \n        <th>Assigned screenshots</th>\n      \n      \n        <th>Actions</th>\n      \n    </tr>\n  </thead>\n  \n    <tbody id="loading-screenshots" style="display:none;">\n      <tr><td colspan="5"><span class="icon-spin"  ><svg width="24" height="24" version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12,4V2A10,10 0 0,0 2,12H4A8,8 0 0,1 12,4Z"/></svg></span> Loading results…</td></tr>\n    </tbody>\n  \n  <tbody class="unit-listing-body">\n\n    \n      <tr class="warning">\n        <td colspan="5"><em>No matching strings found.</em></td>\n      </tr>\n    \n\n  </tbody>\n</table>\n\n'
[ 9019s] 
```

[Complete build log](https://github.com/WeblateOrg/weblate/files/10977793/_log.txt) with the list of all packages used and all steps taken to reproduce.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Run the test suite (see the attached log)

### Expected behavior

All test passing

### Screenshots

`test_ocr` fails almost always

### Exception traceback

```pytb
[ 9019s] ======================================================================
[ 9019s] FAIL: test_ocr (weblate.screenshots.tests.ViewTest)
[ 9019s] ----------------------------------------------------------------------
[ 9019s] Traceback (most recent call last):
[ 9019s]   File "/home/abuild/rpmbuild/BUILD/Weblate-4.14.2/weblate/screenshots/tests.py", line 170, in test_ocr
[ 9019s]     self.assertIn('<a class="add-string', data["results"])
[ 9019s] AssertionError: '<a class="add-string' not found in '\n\n\n\n\n\n\n\n\n\n\n\n<table class="table table-condensed">\n  <thead>\n    <tr>\n      <th class="unit-state-cell"></th>\n      \n      \n      \n      \n      \n        \n          <th>\n        \n          English\n        \n        </th>\n      \n      \n        <th>Location</th>\n      \n      \n        <th>Assigned screenshots</th>\n      \n      \n        <th>Actions</th>\n      \n    </tr>\n  </thead>\n  \n    <tbody id="loading-screenshots" style="display:none;">\n      <tr><td colspan="5"><span class="icon-spin"  ><svg width="24" height="24" version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12,4V2A10,10 0 0,0 2,12H4A8,8 0 0,1 12,4Z"/></svg></span> Loading results…</td></tr>\n    </tbody>\n  \n  <tbody class="unit-listing-body">\n\n    \n      <tr class="warning">\n        <td colspan="5"><em>No matching strings found.</em></td>\n      </tr>\n    \n\n  </tbody>\n</table>\n\n'
[ 9019s]
```

### How do you run Weblate?

Other

**Comment by nijel** [comment]
Do you have tesseract data installed on the test system? Maybe https://forums.opensuse.org/t/tesseract-ocr-wrong-data-directory/164659/9 is related?

**Comment by mcepl** [comment]
> Do you have tesseract data installed on the test system? Maybe https://forums.opensuse.org/t/tesseract-ocr-wrong-data-directory/164659/9 is related?

Hmm, it is in `/usr/share/tessdata/eng.traineddata`, that should be correct, shouldn’t it?

**Comment by mcepl** [comment]
This is not a support question! Does failure of your test suite not matter at all?

**Comment by nijel** [comment]
It's not recognizing the text. It can be caused by wrongly installed data files, missing dependency on the tesseract data, or something else.

This test has been there for years (introduced in df4a52af1aa), it worked before on SUSE, it works anywhere else so far. All that makes me think the issue is in your environment, and not in Weblate.

**Comment by mcepl** [comment]
Is there some command line command or something which could show me more what tesseract thinks is wrong with the setup?

**Comment by nijel** [comment]
`tesseract weblate/trans/tests/data/screenshot.png  -` in Weblate sources should produce something like:

```console
$ tesseract weblate/trans/tests/data/screenshot.png  -
Warning: Invalid resolution 0 dpi. Using 70 instead.
Estimating resolution as 133
Source string

Hello, world!+

One
Orangutan has %d banana.«!

Other
Orangutan has %d bananas.

Try Weblate at <http://demo.weblate.org/>!«!

Thank you for using Weblate.

Screenshot is shown to add visual context for all listed source strings.

 

```

**Comment by mcepl** [comment]
That’s exactly (I believe) what I’ve got:
```
[   63s] + tesseract weblate/trans/tests/data/screenshot.png -
[   63s] Estimating resolution as 133
[   63s] Source string
[   63s] 
[   63s] Hello, world!+
[   63s] 
[   63s] One
[   63s] Orangutan has %d banana.<!
[   63s] 
[   63s] Other
[   63s] Orangutan has %d bananas.
[   63s] 
[   63s] Try Weblate at <http://demo.weblate.org/>!«!
[   63s] 
[   63s] Thank you for using Weblate.
[   63s] 
[   63s] Screenshot is shown to add visual context for all listed source strings.
[   63s] 
```

[Complete build log](https://github.com/WeblateOrg/weblate/files/11207526/_log.txt)
