### ISSUE TITLE
Error in migrate on new setup

### ISSUE THREAD

**Issue by yupix** [WeblateOrg/weblate#9774]
### Describe the issue

I get the following error when installing using pip

```
ImportError: Module "redis.connection" does not define a "HiredisParser" attribute/class
```

This problem seems to occur in redis-py 5.0.0 environment. The following Issue is related

https://github.com/redis/redis-py/issues/2895

We have confirmed normal operation by changing the code as follows.

```diff
-redis.connection.HiredisParser
+redis.connection._HiredisParser
```

I think you need to add the information to the document

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Fulfill the system requirements with reference to the [official documentation](https://docs.weblate.org/en/latest/admin/install/venv-debian.html) for using Ubuntu
2. `virtualenv ~/weblate-env`
3. `. ~/weblate-env/bin/activate`
4. `pip install "Weblate[all]"`
5. Set minimum required config.
6. `weblate migrate`

### Expected behavior

Migration must work properly

### Exception traceback

```pytb
(weblate-env) root@CT115:~# weblate migrate
[2023-08-19 02:21:46,605: WARNING/4287] Handled exception: ImportError: Module "redis.connection" does not define a "HiredisParser" attribute/class
Traceback (most recent call last):
  File "/root/weblate-env/lib/python3.10/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "/root/weblate-env/lib/python3.10/site-packages/django/utils/module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
AttributeError: module 'redis.connection' has no attribute 'HiredisParser'. Did you mean: '_HiredisParser'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/weblate-env/bin/weblate", line 8, in <module>
    sys.exit(main())
  File "/root/weblate-env/lib/python3.10/site-packages/weblate/runner.py", line 19, in main
    utility.execute()
  File "/root/weblate-env/lib/python3.10/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/root/weblate-env/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/weblate-env/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/root/weblate-env/lib/python3.10/site-packages/django/apps/config.py", line 123, in create
    mod = import_module(mod_path)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/weblate-env/lib/python3.10/site-packages/weblate/formats/apps.py", line 8, in <module>
    from weblate.utils.checks import weblate_check
  File "/root/weblate-env/lib/python3.10/site-packages/weblate/utils/checks.py", line 26, in <module>
    from weblate.utils.docs import get_doc_url
  File "/root/weblate-env/lib/python3.10/site-packages/weblate/utils/docs.py", line 9, in <module>
    import weblate.utils.version
  File "/root/weblate-env/lib/python3.10/site-packages/weblate/utils/version.py", line 37, in <module>
    GIT_REPO = GitRepository(get_root_dir(), local=True)
  File "/root/weblate-env/lib/python3.10/site-packages/weblate/vcs/base.py", line 84, in __init__
    self.lock = WeblateLock(
  File "/root/weblate-env/lib/python3.10/site-packages/weblate/utils/lock.py", line 45, in __init__
    cache.client.get_client(),
  File "/root/weblate-env/lib/python3.10/site-packages/django_redis/client/default.py", line 105, in get_client
    self._clients[index] = self.connect(index)
  File "/root/weblate-env/lib/python3.10/site-packages/django_redis/client/default.py", line 118, in connect
    return self.connection_factory.connect(self._server[index])
  File "/root/weblate-env/lib/python3.10/site-packages/django_redis/pool.py", line 70, in connect
    params = self.make_connection_params(url)
  File "/root/weblate-env/lib/python3.10/site-packages/django_redis/pool.py", line 42, in make_connection_params
    "parser_class": self.get_parser_cls(),
  File "/root/weblate-env/lib/python3.10/site-packages/django_redis/pool.py", line 99, in get_parser_cls
    return import_string(cls)
  File "/root/weblate-env/lib/python3.10/site-packages/django/utils/module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "redis.connection" does not define a "HiredisParser" attribute/class
```
```


### How do you run Weblate?

PyPI module

### Weblate versions

* Weblate: 4.18.2
 * Django: 4.2.4
 * siphashc: 2.1
 * translate-toolkit: 3.9.2
 * lxml: 4.9.3
 * Pillow: 9.5.0
 * nh3: 0.2.14
 * python-dateutil: 2.8.2
 * social-auth-core: 4.4.2
 * social-auth-app-django: 5.2.0
 * django-crispy-forms: 2.0
 * oauthlib: 3.2.2
 * django-compressor: 4.4
 * djangorestframework: 3.14.0
 * django-filter: 23.2
 * django-appconf: 1.0.5
 * user-agents: 2.2.0
 * filelock: 3.12.2
 * rapidfuzz: 3.1.2
 * openpyxl: 3.1.2
 * celery: 5.3.1
 * django-celery-beat: 2.5.0
 * kombu: 5.3.1
 * translation-finder: 2.15
 * weblate-language-data: 2023.5
 * html2text: 2020.1.16
 * pycairo: 1.24.0
 * PyGObject: 3.44.1
 * diff-match-patch: 20230430
 * requests: 2.31.0
 * django-redis: 5.3.0
 * hiredis: 2.2.3
 * sentry-sdk: 1.29.2
 * Cython: 0.29.36
 * misaka: 2.1.1
 * GitPython: 3.1.32
 * borgbackup: 1.2.4
 * pyparsing: 3.0.9
 * pyahocorasick: 2.0.0
 * python-redis-lock: 4.0.0
 * charset-normalizer: 3.2.0
 * Python: 3.10.12
 * Git: 2.34.1
 * phply: 1.2.6
 * ruamel.yaml: 0.17.32
 * tesserocr: 2.6.1
 * boto3: 1.26.165
 * zeep: 4.2.1
 * aeidon: 1.12
 * iniparse: 0.5
 * Mercurial: 6.5.1
 * git-svn: 2.34.1
 * git-review: 2.3.1
 * Redis server: 7.2.0
 * PostgreSQL server: 15.4
 * Database backends: django.db.backends.postgresql
 * Cache backends: default:RedisCache, avatar:FileBasedCache
 * Email setup: django.core.mail.backends.smtp.EmailBackend: localhost
 * OS encoding: filesystem=utf-8, default=utf-8
 * Celery: redis://localhost:6379, redis://localhost:6379, regular
 * Platform: Linux 5.15.108-1-pve (x86_64)

### Weblate deploy checks

_No response_

### Additional context

_No response_

**Comment by nijel** [comment]
You can remove the problematic line from settings, it is no longer needed and was removed in f990e0a5e0087b905b4d96e6bd926cff2a3c8de8.
