### ISSUE TITLE
Database error: "MultiXactId 10655 has not been created yet -- apparent wraparound"

### ISSUE THREAD

**Issue by ScionOfDesign** [WeblateOrg/weblate#9788]
### Describe the issue

This error seems to occur every several seconds, but does not seem to affect general site function.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

The error just started appearing one day.

### Expected behavior

There should be no database exception.

### Exception traceback

```pytb
celery-beat stderr | django.db.utils.InternalError: MultiXactId 10655 has not been created yet -- apparent wraparound
celery-beat stderr | [2023-08-21 15:30:28,623: ERROR/MainProcess] Database gave error: InternalError('MultiXactId 10655 has not been created yet -- apparent wraparound')
celery-beat stderr | Traceback (most recent call last):
celery-beat stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
celery-beat stderr |     return self.cursor.execute(sql, params)
celery-beat stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-beat stderr |   File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute
celery-beat stderr |     raise ex.with_traceback(None)
celery-beat stderr | psycopg.errors.InternalError_: MultiXactId 10655 has not been created yet -- apparent wraparound
celery-beat stderr | 
celery-beat stderr | The above exception was the direct cause of the following exception:
celery-beat stderr | 
celery-beat stderr | Traceback (most recent call last):
celery-beat stderr |   File "/usr/local/lib/python3.11/site-packages/django_celery_beat/schedulers.py", line 267, in schedule_changed
celery-beat stderr |     last, ts = self._last_timestamp, self.Changes.last_change()
celery-beat stderr |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-beat stderr |   File "/usr/local/lib/python3.11/site-packages/django_celery_beat/models.py", line 394, in last_change
celery-beat stderr |     return cls.objects.get(ident=1).last_update
celery-beat stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^
celery-beat stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
celery-beat stderr |     return getattr(self.get_queryset(), name)(*args, **kwargs)
celery-beat stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-beat stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 633, in get
celery-beat stderr |     num = len(clone)
celery-beat stderr |           ^^^^^^^^^^
celery-beat stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 380, in __len__
celery-beat stderr |     self._fetch_all()
celery-beat stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
celery-beat stderr |     self._result_cache = list(self._iterable_class(self))
celery-beat stderr |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-beat stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
celery-beat stderr |     results = compiler.execute_sql(
celery-beat stderr |               ^^^^^^^^^^^^^^^^^^^^^
celery-beat stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
celery-beat stderr |     cursor.execute(sql, params)
celery-beat stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 67, in execute
celery-beat stderr |     return self._execute_with_wrappers(
celery-beat stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-beat stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
celery-beat stderr |     return executor(sql, params, many, context)
celery-beat stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-beat stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
celery-beat stderr |     with self.db.wrap_database_errors:
celery-beat stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
celery-beat stderr |     raise dj_exc_value.with_traceback(traceback) from exc_value
celery-beat stderr |   File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
celery-beat stderr |     return self.cursor.execute(sql, params)
celery-beat stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery-beat stderr |   File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute
celery-beat stderr |     raise ex.with_traceback(None)
celery-beat stderr | django.db.utils.InternalError: MultiXactId 10655 has not been created yet -- apparent wraparound
```

### How do you run Weblate?

Docker container

### Weblate versions

4.18.2

### Weblate deploy checks

```shell
SystemCheckError: System check identified some issues:

CRITICALS:
?: (weblate.E003) Cannot send e-mail ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1002)), please check EMAIL_* settings.
        HINT: https://docs.weblate.org/en/weblate-4.18.2/admin/install.html#out-mail

INFOS:
?: (weblate.I021) Error collection is not set up, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.18.2/admin/install.html#collecting-errors
?: (weblate.I028) Backups are not configured, it is highly recommended for production use
        HINT: https://docs.weblate.org/en/weblate-4.18.2/admin/backup.html

System check identified 3 issues (1 silenced).
```

### Additional context

Note: The email issue is unrelated and I have not looked into solving it yet. However we do have a slef-signed certificate and would like it to be accepted.
We also DO have backups, but not through Weblate.

**Comment by ScionOfDesign** [comment]
Figures.
If there's no simple query I can run to fix it, my options then are to restore from a significantly older backup (I'd lose the metadata, but not the translations) or create a backup through the Weblate UI and restore from that.

Do you think restoring from a Weblate backup is likely to fix the issue? Or will it just restore the Postgres database to a corrupted state again?

**Comment by nijel** [comment]
If the SQL backup works, it should restore correctly. But you can do the same using pg_dump/pg_restore directly without involving Weblate backups.

**Comment by ScionOfDesign** [comment]
Well ,`pg_dump` fails so I think my best option is just to make Weblate backups of the projects, remake the server and restore from the weblate backups. Until then,  the only issue it seems to be causing is that error mentioned above.
