### ISSUE TITLE
Docker: WEBLATE_SOCIAL_AUTH_GITHUB_ORG_NAME does not work

### ISSUE THREAD

**Issue by UncleSamSwiss** [WeblateOrg/weblate#9844]
### Describe the issue

When `WEBLATE_SOCIAL_AUTH_GITHUB_ORG_NAME` is set, the application fails to start because of the exception shown below.

The solution to this is either not to use the fallback value in:
https://github.com/WeblateOrg/weblate/blob/5e05e62957d62f30ffb07d34abf904604691316d/weblate/settings_docker.py#L262
Or to parse it in an optional way beforehand:
```python
    SOCIAL_AUTH_GITHUB_SECRET = get_env_str(
        "WEBLATE_SOCIAL_AUTH_GITHUB_SECRET"
    )
```

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

1. Set `WEBLATE_SOCIAL_AUTH_GITHUB_ORG_NAME` in docker (or in our case Kubernetes)
2. Start the application

### Expected behavior

Social Auth with GitHub for Organizations works as documented

### Exception traceback

```pytb
Starting...
Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/weblate/runner.py", line 19, in main
    utility.execute()
  File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
    self._wrapped = Settings(settings_module)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/site-packages/weblate/settings_docker.py", line 262, in <module>
    SOCIAL_AUTH_GITHUB_SECRET,
    ^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'SOCIAL_AUTH_GITHUB_SECRET' is not defined. Did you mean: 'SOCIAL_AUTH_GITHUB_KEY'?
Failed to load configuration, please see errors above.
```

### How do you run Weblate?

Docker container

### Weblate versions

Docker image tag 5.0.0.1

**Comment by UncleSamSwiss** [comment]
@nijel I was able to verify this fix, it works. Thanks for your quick response!
